-- BootyBay.lua: Booty Bay in the Dungeon Journal, generated by Tools/build_factions.py.
local ns = _G.NaowhForever

ns.Journal.AddFaction("BootyBay", {
    id = 21, name = "Booty Bay", tab = "reputation",
    group = "Steamwheedle Cartel",
    zone = "Stranglethorn Vale",
    quartermaster = { name = "Gezzy Gunkgear", map = 1434, x = 28.2, y = 74.8 },
    maps = { 1434 },
    tiers = {
        { standing = 5, items = { 274745, 274746, 274747 } },
        { standing = 6, items = { 274748, 274749 } },
        { standing = 7, items = { 274022 } },
    },
    prices = {
        [274022] = 50000,
        [274745] = 11042,
        [274746] = 14775,
        [274747] = 10322,
        [274748] = 31088,
        [274749] = 16643,
    },
})
