-- DarkspearTrolls.lua: Darkspear Trolls in the Dungeon Journal, generated by Tools/build/factions.py.
local ns = _G.NaowhForever

ns.Journal.AddFaction("DarkspearTrolls", {
    id = 530, name = "Darkspear Trolls", tab = "reputation",
    group = "Cities",
    zone = "Orgrimmar",
    side = "Horde",
    maps = { 1411, 1454 },
    turnins = {
        { name = "Additional Runecloth", rep = 50, level = 60, takes = { 14047, 20 },
            quests = {
                { 7837, "H", "Orgrimmar - Vehena (37.8, 87.6)", 1454, 37.8, 87.6 },
            },
        },
    },
    tiers = {
    },
})
