-- EarthenRing.lua: Earthen Ring in the Dungeon Journal, generated by Tools/build_factions.py.
local ns = _G.NaowhForever

ns.Journal.AddFaction("EarthenRing", {
    id = 2787, name = "Earthen Ring", tab = "reputation",
    zone = "Mulgore",
    new = true,
    quartermaster = { name = "Sutara Plainstalker", map = 1412, x = 34.4, y = 22.8 },
    maps = { 1412 },
    tiers = {
        { standing = 5, items = { 276976, 276977, 276978, 276979, 276980, 276981, 276982, 276983 } },
    },
    prices = {
        [276976] = 100000,
        [276977] = 100000,
        [276978] = 100000,
        [276979] = 100000,
        [276980] = 100000,
        [276981] = 100000,
        [276982] = 100000,
        [276983] = 100000,
    },
})
