-- GuardiansOfHyjal.lua: Guardians of Hyjal in the Dungeon Journal, generated by Tools/build_factions.py.
local ns = _G.NaowhForever

ns.Journal.AddFaction("GuardiansOfHyjal", {
    id = 2765, name = "Guardians of Hyjal", tab = "reputation",
    zone = "Mount Hyjal",
    new = true,
    quartermaster = { name = "Rhylin Stonethorn", map = 2482, x = 70.6, y = 51.2 },
    maps = { 2482 },
    tiers = {
        { standing = 7, items = { 274379 } },
        { standing = 8, items = { 274025 } },
    },
    prices = {
        [274025] = 250000,
        [274379] = 100000,
    },
})
