-- HydraxianWaterlords.lua: Hydraxian Waterlords in the Dungeon Journal, generated by Tools/build_factions.py.
local ns = _G.NaowhForever

ns.Journal.AddFaction("HydraxianWaterlords", {
    id = 749, name = "Hydraxian Waterlords", tab = "reputation",
    zone = "Azshara",
    unreleased = true,
    maps = { 1447 },
    tiers = {
        { standing = 7, items = { 228979, 22705 } },
    },
    prices = {
        [22705] = 150000,
        [228979] = 100000,
    },
})
