-- Ironforge.lua: Ironforge in the Dungeon Journal, generated by Tools/build_factions.py.
local ns = _G.NaowhForever

ns.Journal.AddFaction("Ironforge", {
    id = 47, name = "Ironforge", tab = "reputation",
    group = "Cities",
    zone = "Ironforge",
    side = "Alliance",
    maps = { 1455 },
    turnins = {
        { name = "Additional Runecloth", rep = 50, level = 60, takes = { 14047, 20 },
            quests = {
                { 7806, "A", "Ironforge - Mistina Steelshield (43.2, 32)", 1455, 43.2, 32 },
            },
        },
    },
    tiers = {
    },
})
