-- Stormwind.lua: Stormwind in the Dungeon Journal, generated by Tools/build_factions.py.
local ns = _G.NaowhForever

ns.Journal.AddFaction("Stormwind", {
    id = 72, name = "Stormwind", tab = "reputation",
    group = "Cities",
    zone = "Stormwind City",
    side = "Alliance",
    maps = { 1453 },
    turnins = {
        { name = "Additional Runecloth", rep = 50, level = 60, takes = { 14047, 20 },
            quests = {
                { 7796, "A", "Stormwind City - Clavicus Knavingham (44.2, 73.6)", 1453, 44.2, 73.6 },
            },
            from = {
                { "Stormwind City", 1, "Stormwind Royal Guard" },
            },
        },
    },
    tiers = {
    },
})
