-- ThunderBluff.lua: Thunder Bluff in the Dungeon Journal, generated by Tools/build_factions.py.
local ns = _G.NaowhForever

ns.Journal.AddFaction("ThunderBluff", {
    id = 81, name = "Thunder Bluff", tab = "reputation",
    group = "Cities",
    zone = "Thunder Bluff",
    side = "Horde",
    maps = { 1412, 1456 },
    turnins = {
        { name = "Additional Runecloth", rep = 50, level = 60, takes = { 14047, 20 },
            quests = {
                { 7825, "H", "Thunder Bluff - Rumstag Proudstrider (43.2, 42.8)", 1456, 43.2, 42.8 },
            },
        },
        { name = "Morrowgrain to Thunder Bluff", rep = 50, level = 55, takes = { 11040, 10 },
            quests = {
                { 3804, "H", "Thunder Bluff - Bashana Runetotem (70.8, 33.8)", 1456, 70.8, 33.8 },
            },
        },
    },
    tiers = {
    },
})
