-- Undercity.lua: Undercity in the Dungeon Journal, generated by Tools/build_factions.py.
local ns = _G.NaowhForever

ns.Journal.AddFaction("Undercity", {
    id = 68, name = "Undercity", tab = "reputation",
    group = "Cities",
    zone = "Undercity",
    side = "Horde",
    maps = { 1458 },
    turnins = {
        { name = "Additional Runecloth", rep = 50, level = 60, takes = { 14047, 20 },
            quests = {
                { 7819, "H", "Undercity - Ralston Farnsley (71.6, 28.8)", 1458, 71.6, 28.8 },
            },
        },
    },
    tiers = {
    },
})
