-------------------------------------------------------------------------------
--  Data/Dungeons/AlcazPrison.lua -- Alcaz Prison in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("AlcazPrison", {
    name = "Alcaz Prison",
    new = true,
    closed = true,
    zone = "Dustwallow Marsh", territory = "Contested",
    wings = {
        { bosses = {
            { npc = nil, name = "Blazeroar" },
        } },
    },
})
