-- AlcazPrison.lua: Alcaz Prison in the Dungeon Journal, generated by Tools/build_journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("AlcazPrison", {
    name = "Alcaz Prison",
    new = true,
    closed = true,
    zone = "Dustwallow Marsh", territory = "Contested",
    wings = {
        { bosses = {
            { npc = nil, name = "Blazeroar" },
        } },
    },
})
