-- BarrowDeeps.lua: The Barrow Deeps in the Dungeon Journal, generated by Tools/build_journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("BarrowDeeps", {
    name = "The Barrow Deeps",
    new = true,
    raid = 10,
    note = "Opens on Forever on 9 December 2026. The boss order is the achievement's, not yet confirmed, and the loot shows in a later version of the addon, once it is known.",
    zone = "Mount Hyjal", territory = "Contested",
    entrance = { map = 2482, x = 70.1, y = 62.0 },
    wings = {
        { bosses = {
            { npc = 259867, name = "Deepscar Matriarch" },
            { npc = 259904, name = "Elder Tangleclaw" },
            { npc = 259902, name = "Khalith the Dreadspinner" },
            { npc = 259866, name = "Well of Sorrow" },
            { npc = 259907, name = "Amethrax" },
            { npc = 259911, name = "Del'lynar Songwood" },
            { npc = 259905, name = "Ravus and Darlissa" },
            { npc = 259912, name = "Sonya Darkhallow" },
        } },
    },
})
