-- BlackrockDepths.lua: Blackrock Depths in the Dungeon Journal, generated by Tools/build_journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("BlackrockDepths", {
    name = "Blackrock Depths",
    closed = true,
    zone = "Blackrock Mountain", territory = "Contested",
    entrance = { map = 1427, x = 27.6, y = 72.4 },
    wings = {
        { name = "Detention Block", bosses = {
            { npc = 9018, name = "High Interrogator Gerstahn", model = 8761, encounters = { 227 }, loot = { 11624, 11625, 22240, 11626 }, chance = { 22, 19, 18, 17 } },
            { npc = 9025, name = "Lord Roccor", model = 5781, encounters = { 228 }, loot = { 11632, 11631, 22397, 22234 }, chance = { 23, 23, 22, 22 } },
            { npc = 9319, name = "Houndmaster Grebmar", model = 9212, encounters = { 229 }, loot = { 11627, 11623, 11629, 11628 }, chance = { 34, 30, 13, 13 } },
        } },
        { name = "Ring of Law", bosses = {
            { npc = 9031, name = "Anub'shiah", model = 3004, loot = { 11675, 11677, 11678, 11731 }, chance = { 33, 31, 19, 12 } },
            { npc = 9029, name = "Eviscerator", model = 523, loot = { 11679, 11685, 11686, 11730 }, chance = { 30, 29, 20, 18 } },
            { npc = 9027, name = "Gorosh the Dervish", model = 8760, loot = { 22257, 22271, 22266, 11726 }, chance = { 23, 21, 17, 16 } },
            { npc = 9028, name = "Grizzle", model = 7873, loot = { 11703, 11702, 11722, 22270 }, chance = { 30, 30, 20, 16 } },
            { npc = 9032, name = "Hedrum the Creeper", model = 8271, loot = { 11633, 11634, 11635, 11729 }, chance = { 31, 28, 21, 14 } },
            { npc = 9030, name = "Ok'thor the Breaker", model = 11538, loot = { 11662, 11665, 11824, 11728 }, chance = { 31, 29, 20, 17 } },
        } },
        { name = "Shadowforge City", bosses = {
            { npc = 9024, name = "Pyromancer Loregrain", model = 8762, encounters = { 231 }, loot = { 11748, 11747, 11749, 11750 }, chance = { 29, 24, 24, 20 } },
            { npc = 9017, name = "Lord Incendius", model = 1204, encounters = { 232 }, loot = { 11768, 11764, 11766, 11767, 11765 }, chance = { 41, 14, 14, 14, 14 } },
            { npc = 9041, name = "Warder Stilgiss", model = 9089, encounters = { 233 }, loot = { 11783, 11782, 11784, 22241 }, chance = { 25, 23, 23, 22 } },
            { npc = 9042, name = "Verek", model = 9019, loot = { 11755, 22242 }, chance = { 14, 12 } },
            { npc = 9056, name = "Fineous Darkvire", model = 8704, encounters = { 234 }, loot = { 11841, 11842, 11839, 22223 }, chance = { 24, 23, 21, 19 } },
            { npc = 9016, name = "Bael'Gar", model = 12162, encounters = { 235 }, loot = { 11802, 11803, 11807, 11805 }, chance = { 34, 33, 19, 7 } },
            { npc = 9033, name = "General Angerforge", model = 8756, encounters = { 236 }, loot = { 11820, 11816, 11821, 11817, 11810 }, chance = { 23, 23, 15, 13, 11 } },
            { npc = 8983, name = "Golem Lord Argelmach", model = 8759, encounters = { 237 }, loot = { 11823, 11822, 11669, 11819 }, chance = { 36, 36, 11, 9 } },
            { npc = 9537, name = "Hurley Blackbreath", model = 8658, encounters = { 238 }, loot = { 18044, 18043, 22275, 11735 }, chance = { 26, 24, 23, 9 } },
            { npc = 9502, name = "Phalanx", model = 8177, encounters = { 239 }, loot = { 11744, 11745, 227947, 11743 }, chance = { 31, 30, 29, 3 } },
            { npc = 9543, name = "Ribbly Screwspigot", model = 8667, encounters = { 240 } },
            { npc = 9499, name = "Plugger Spazzring", model = 8652, encounters = { 241 }, loot = { 12793, 12791 }, chance = { 30, 10 } },
            { npc = 9156, name = "Ambassador Flamelash", model = 8329, encounters = { 242 }, loot = { 11812, 11814, 11809, 11832, 11808 }, chance = { 38, 37, 11, 10, 1 } },
            { npc = 9938, name = "Magmus", model = 12162, encounters = { 244 }, loot = { 22208, 11935, 22400, 22395 }, chance = { 22, 21, 15, 12 } },
            { npc = 9019, name = "Emperor Dagran Thaurissan", model = 8807, encounters = { 2790 }, loot = { 11930, 11924, 22204, 11928, 11934, 11932, 11931, 22207, 11933, 11815, 11684 }, chance = { 19, 19, 18, 18, 18, 18, 18, 18, 17, 15, 1 } },
            { npc = 8923, name = "Panzor the Invincible", model = 8270, rare = true, loot = { 11787, 11786, 11785, 22245 }, chance = { 29, 24, 23, 20 } },
            { npc = 8929, name = "Princess Moira Bronzebeard", model = 8705, optional = true, encounters = { 2789 }, loot = { 12554, 12553, 12557, 12556 }, chance = { 23, 23, 23, 22 } },
            { npc = nil, name = "Secret Safe", chest = 161495, loot = { 22205, 22254, 22256, 22255, 11920, 11929, 11926 }, chance = { 19, 18, 16, 13, 7, 7, 6 } },
            { npc = nil, name = "Chest of The Seven", chest = 169243, loot = { 11929, 11927, 11926, 11925 }, chance = { 50, 47, 27, 25 } },
            { npc = nil, name = "Trash", trash = true, loot = { 22305, 11920, 11921, 11922, 11746, 12527, 12528, 12531, 12532, 12535, 12542, 12546, 12547, 12549, 12550, 12551, 12552, 12555 }, chance = { 100, 28, 26, 22, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
        } },
    },
})
