-- BlackmawHold.lua: Blackmaw Hold in the Dungeon Journal, generated by Tools/build_journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("BlackmawHold", {
    name = "Blackmaw Hold",
    new = true,
    closed = true,
    zone = "Azshara", territory = "Contested",
    wings = {
    },
})
