-------------------------------------------------------------------------------
--  Data/Dungeons/BlackmawHold.lua -- Blackmaw Hold in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("BlackmawHold", {
    name = "Blackmaw Hold",
    new = true,
    closed = true,
    zone = "Azshara", territory = "Contested",
    wings = {
    },
})
