-- Deadmines.lua: The Deadmines in the Dungeon Journal, generated by Tools/build/journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Deadmines", {
    name = "The Deadmines",
    zone = "Westfall", territory = "Alliance",
    entrance = { map = 1436, x = 43.2, y = 72.4 },
    wings = {
        { bosses = {
            { npc = 644, name = "Rhahk'Zor", model = 14403, encounters = { 2741 }, loot = { 5187, 872, 273289 }, chance = { 76, 4, 0 } },
            { npc = 642, name = "Sneed's Shredder", model = 1269, encounters = { 2742 }, with = "Sneed", loot = { 2169, 1937, 285292 }, chance = { 57, 10, 0 } },
            { npc = 643, name = "Sneed", model = 7125, encounters = { 2742 }, loot = { 5195, 5194, 273293 }, chance = { 68, 28, 0 } },
            { npc = 1763, name = "Gilnid", model = 7124, encounters = { 2743 }, loot = { 5199, 1156, 273297 }, chance = { 57, 37, 0 } },
            { npc = 646, name = "Mr. Smite", model = 2026, encounters = { 2745 }, loot = { 5192, 5196, 7230, 284715 }, chance = { 38, 38, 19, 0 } },
            { npc = 647, name = "Captain Greenskin", model = 7113, encounters = { 2744 }, loot = { 5201, 5200, 10403 }, chance = { 38, 28, 26 } },
            { npc = 639, name = "Edwin VanCleef", model = 2029, encounters = { 2747 }, loot = { 5202, 5193, 5191, 10399 }, chance = { 24, 23, 16, 16 } },
            { npc = 645, name = "Cookie", model = 1305, encounters = { 2746 }, loot = { 5197, 5198, 273298 }, chance = { 55, 34, 0 } },
            { npc = 3586, name = "Miner Johnson", model = 556, rare = true, encounters = { 3676 }, loot = { 5444, 5443 }, chance = { 55, 41 } },
            { npc = nil, name = "Trash", trash = true, loot = { 1925, 1945, 1943, 1951, 1929, 1936, 1934, 1944, 10400, 10401, 10402, 1930 }, chance = { 7, 6, 6, 6, 6, 6, 6, 5, 3, 3, 3, 2 } },
        } },
    },
})
