-- DireMaul.lua: Dire Maul in the Dungeon Journal, generated by Tools/build_journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("DireMaul", {
    name = "Dire Maul",
    closed = true,
    zone = "Feralas", territory = "Contested",
    entrance = { map = 1444, x = 61.9, y = 31.6 },
    wings = {
        { name = "East", bosses = {
            { npc = 14354, name = "Pusillin", model = 7552, encounters = { 2792 } },
            { npc = 11490, name = "Zevrim Thornhoof", model = 11335, encounters = { 343 }, loot = { 18306, 18308, 18313, 18323, 18319 }, chance = { 25, 24, 19, 19, 10 } },
            { npc = 13280, name = "Hydrospawn", model = 5489, encounters = { 344 }, loot = { 18305, 18307, 18322, 18317, 18324 }, chance = { 24, 24, 20, 19, 10 } },
            { npc = 14327, name = "Lethtendris", model = 14378, encounters = { 345 }, loot = { 18302, 18325, 18301, 18311 }, chance = { 29, 29, 28, 9 } },
            { npc = 11492, name = "Alzzin the Wildshaper", model = 14416, encounters = { 346 }, loot = { 18310, 18314, 18321, 18315, 18328, 18312, 18309, 18326, 18327, 18318 }, chance = { 19, 19, 19, 19, 19, 19, 19, 19, 19, 19 } },
            { npc = 16097, name = "Isalien", model = 16000, optional = true, loot = { 22314, 22304, 22472, 22315, 22401, 22345 }, chance = { 22, 20, 19, 14, 12, 10 } },
            { npc = nil, name = "Trash", trash = true, loot = { 18354, 18450, 18459, 18460, 18464, 18462, 18451, 18463, 18458, 18494, 18498, 18496, 18493, 18497, 18289, 18295, 18340, 18343, 18339, 18338, 18344, 18337, 18298, 18296 }, chance = { 24, 10, 10, 9, 9, 9, 9, 9, 9, 7, 7, 6, 6, 6, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1 } },
        } },
        { name = "West", bosses = {
            { npc = 11489, name = "Tendris Warpwood", model = 14383, encounters = { 350 }, loot = { 18390, 18352, 18353, 18393 }, chance = { 24, 24, 24, 24 } },
            { npc = 11488, name = "Illyanna Ravenoak", model = 11270, encounters = { 347 }, loot = { 18347, 18349, 18383, 18386 }, chance = { 24, 24, 24, 22 } },
            { npc = 11487, name = "Magister Kalendris", model = 14384, encounters = { 348 }, loot = { 18350, 18351, 18374, 18397, 18371 }, chance = { 25, 23, 20, 19, 9 } },
            { npc = 11496, name = "Immol'thar", model = 14173, encounters = { 349 }, loot = { 18377, 18379, 18381, 18391, 18385, 18384, 18389, 18394, 18372, 18370 }, chance = { 26, 25, 24, 24, 21, 19, 19, 19, 10, 9 } },
            { npc = 11486, name = "Prince Tortheldrin", model = 11256, encounters = { 361 }, loot = { 18395, 18382, 18380, 18378, 18396, 18392, 18376, 18375, 18388, 18373 }, chance = { 24, 24, 23, 21, 20, 19, 18, 17, 10, 9 } },
            { npc = 11467, name = "Tsu'zee", model = 11250, rare = true, encounters = { 2794 }, loot = { 18345, 18387, 18346 }, chance = { 33, 30, 29 } },
            { npc = 14506, name = "Lord Hel'nurath", model = 14556, optional = true, encounters = { 2793 }, loot = { 18755, 18756, 18757, 18754 }, chance = { 25, 25, 24, 22 } },
            { npc = 14690, name = "Revanchion", model = 14695, optional = true, loot = { 23128, 23127, 23129 }, chance = { 56, 33, 11 } },
            { npc = nil, name = "Trash", trash = true, loot = { 18354, 18450, 18459, 18460, 18464, 18462, 18451, 18463, 18458, 18494, 18498, 18496, 18493, 18497, 18289, 18295, 18340, 18343, 18339, 18338, 18344, 18337, 18298, 18296 }, chance = { 24, 10, 10, 9, 9, 9, 9, 9, 9, 7, 7, 6, 6, 6, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1 } },
        } },
        { name = "North", bosses = {
            { npc = 14326, name = "Guard Mol'dar", model = 11561, encounters = { 362 } },
            { npc = 14322, name = "Stomper Kreeg", model = 11545, encounters = { 363 }, loot = { 18425 }, chance = { 56 } },
            { npc = 14321, name = "Guard Fengus", model = 11561, encounters = { 364 } },
            { npc = 14323, name = "Guard Slip'kik", model = 11561, encounters = { 365 } },
            { npc = 14325, name = "Captain Kromcrush", model = 11564, encounters = { 366 }, loot = { 18503, 18507, 18505, 18502 }, chance = { 23, 23, 22, 22 } },
            { npc = 11501, name = "King Gordok", model = 11583, encounters = { 368 }, loot = { 18521, 18524, 18523, 18527, 18525, 18520, 18522, 18526 }, chance = { 25, 24, 24, 24, 24, 24, 24, 24 } },
            { npc = 14324, name = "Cho'Rush the Observer", model = 11537, optional = true, encounters = { 367 }, loot = { 18484, 18483, 18485, 18490 }, chance = { 44, 42, 42, 42 } },
            { npc = nil, name = "Gordok Tribute", chest = 179564, loot = { 18475, 18528, 18478, 18500, 18481, 18477, 18479, 18499, 18529, 18480, 18533, 18532, 18531, 18482, 18534, 18476, 18530, 18495, 18537 }, chance = { 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1 } },
            { npc = nil, name = "Trash", trash = true, loot = { 18354, 18450, 18459, 18460, 18464, 18462, 18451, 18463, 18458, 18494, 18498, 18496, 18493, 18497, 18289, 18295, 18340, 18343, 18339, 18338, 18344, 18337, 18298, 18296 }, chance = { 24, 10, 10, 9, 9, 9, 9, 9, 9, 7, 7, 6, 6, 6, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1 } },
        } },
    },
})
