-- DrownedCity.lua: The Drowned City in the Dungeon Journal, generated by Tools/build_journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("DrownedCity", {
    name = "The Drowned City",
    new = true,
    closed = true,
    zone = "Stranglethorn Vale", territory = "Contested",
    entrance = { map = 1434, x = 21.4, y = 27.9 },
    wings = {
        { bosses = {
            { npc = 270882, name = "Zul'Alai", model = 144475 },
            { npc = 270883, name = "Var'Taka", model = 144487 },
            { npc = 270884, name = "Captain Dreadrise", model = 142144 },
            { npc = 270885, name = "Deathless Marrow", model = 142245 },
            { npc = 270886, name = "Min'loth the Serpent", model = 142286 },
        } },
    },
})
