-- HallOfThanes.lua: The Hall of Thanes in the Dungeon Journal, generated by Tools/build_journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("HallOfThanes", {
    name = "The Hall of Thanes",
    new = true,
    zone = "Ironforge", territory = "Alliance",
    entrance = { map = 1455, x = 43.0, y = 51.0 },
    wings = {
        { bosses = {
            { npc = 261306, name = "Faldrim Anvilmar", model = 142826, encounters = { 3493 }, loot = { 271097, 270227, 271096 }, chance = { 38, 31, 31 } },
            { npc = 261316, name = "Magmatus", model = 1070, encounters = { 3495 }, loot = { 270230, 271095, 270231 }, chance = { 37, 32, 31 } },
            { npc = 261311, name = "Plunder", model = 142840, encounters = { 3494 }, loot = { 270228, 270229, 271098 }, chance = { 37, 34, 29 } },
            { npc = 261319, name = "Durgen Dirgehammer", model = 142837, encounters = { 3496 }, loot = { 270256, 270260, 270261 }, chance = { 28, 25, 22 } },
        } },
    },
})
