-- HyjalSummit.lua: Hyjal Summit in the Dungeon Journal, generated by Tools/build/journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("HyjalSummit", {
    name = "Hyjal Summit",
    new = true,
    raid = 20,
    note = "Opens on Forever on 9 December 2026. The boss order is the achievement's, not yet confirmed, and the loot shows in a later version of the addon, once it is known.",
    zone = "Mount Hyjal", territory = "Contested",
    entrance = { map = 2482, x = 85.3, y = 33.0 },
    wings = {
        { bosses = {
            { npc = 249790, name = "Bandalar" },
            { npc = 250076, name = "Ancient of Decay" },
            { npc = nil, name = "Time-Lost Battalion" },
            { npc = 257638, name = "Sylvestris Dusksong" },
            { npc = 250070, name = "Old Gloomlurker" },
            { npc = 250075, name = "Gharalis the Abyssal" },
            { npc = 250077, name = "Kathris the Haunted" },
            { npc = 249787, name = "Anara Chillwind" },
            { npc = 253861, name = "Elder Minderel" },
            { npc = 250074, name = "Tracker Stillwind" },
            { npc = 250082, name = "Council of Thorns" },
            { npc = 250078, name = "Nythus the Dreambound" },
            { npc = 250079, name = "The Wild King" },
        } },
    },
})
