-------------------------------------------------------------------------------
--  Data/Dungeons/Kroldok.lua -- Krol'dok Stronghold in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Kroldok", {
    name = "Krol'dok Stronghold",
    new = true,
    closed = true,
    zone = "Riverglades", territory = "Contested",
    wings = {
    },
})
