-- Kroldok.lua: Krol'dok Stronghold in the Dungeon Journal, generated by Tools/build_journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Kroldok", {
    name = "Krol'dok Stronghold",
    new = true,
    closed = true,
    zone = "Riverglades", territory = "Contested",
    wings = {
    },
})
