-- LowerBlackrockSpire.lua: Lower Blackrock Spire in the Dungeon Journal, generated by Tools/build/journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("LowerBlackrockSpire", {
    name = "Lower Blackrock Spire",
    closed = true,
    zone = "Blackrock Mountain", territory = "Contested",
    entrance = { map = 1427, x = 41.1, y = 95.3 },
    wings = {
        { bosses = {
            { npc = 9196, name = "Highlord Omokk", model = 11565, encounters = { 267 }, loot = { 16670, 13167, 13169, 13170, 13168, 13166 }, chance = { 16, 13, 13, 13, 13, 13 } },
            { npc = 9236, name = "Shadow Hunter Vosh'gajin", model = 9732, encounters = { 268 }, loot = { 13255, 12626, 16712, 13257, 12651, 12653 }, chance = { 34, 18, 17, 8, 7, 7 } },
            { npc = 9237, name = "War Master Voone", model = 9733, encounters = { 269 }, loot = { 13173, 13179, 13177, 16676, 22231, 12582, 13175 }, chance = { 75, 20, 19, 19, 17, 14, 1 } },
            { npc = 10596, name = "Mother Smolderweb", model = 9929, encounters = { 270 }, loot = { 13244, 16715, 13213, 13183 }, chance = { 27, 16, 14, 4 } },
            { npc = 10584, name = "Urok Doomhowl", model = 11583, encounters = { 271 }, loot = { 13259, 13258, 22232, 13178 }, chance = { 23, 20, 20, 19 } },
            { npc = 9736, name = "Quartermaster Zigris", model = 9738, encounters = { 272 }, loot = { 13252, 13253 }, chance = { 19, 18 } },
            { npc = 10268, name = "Gizrul the Slavener", model = 9564, encounters = { 273 }, loot = { 13206, 13205, 13208, 16718 }, chance = { 26, 25, 24, 18 } },
            { npc = 10220, name = "Halycon", model = 9567, encounters = { 274 }, loot = { 13211, 13212, 22313, 13210 }, chance = { 26, 26, 21, 17 } },
            { npc = 9568, name = "Overlord Wyrmthalak", model = 8711, encounters = { 275 }, loot = { 16679, 22321, 13163, 13162, 13161, 13143, 13148, 13164 }, chance = { 16, 16, 15, 15, 15, 4, 1, 1 } },
            { npc = 9219, name = "Spirestone Butcher", model = 11574, rare = true, loot = { 12608, 13286 }, chance = { 58, 38 } },
            { npc = 9218, name = "Spirestone Battle Lord", model = 11576, rare = true, loot = { 13284, 13285 }, chance = { 57, 38 } },
            { npc = 9217, name = "Spirestone Lord Magus", model = 11578, rare = true, loot = { 13283, 13282, 13261 }, chance = { 47, 25, 22 } },
            { npc = 9596, name = "Bannok Grimaxe", model = 9668, rare = true, loot = { 12634, 12637, 12621 }, chance = { 32, 32, 29 } },
            { npc = 10376, name = "Crystal Fang", model = 9755, rare = true, loot = { 13185, 13184, 13218 }, chance = { 33, 33, 15 } },
            { npc = 9718, name = "Ghok Bashguud", model = 11809, rare = true, loot = { 13203, 13204, 13198 }, chance = { 38, 34, 23 } },
            { npc = 10263, name = "Burning Felguard", model = 5047, rare = true, loot = { 13181, 13182 }, chance = { 29, 29 } },
            { npc = 16080, name = "Mor Grayhoof", model = 15997, optional = true, loot = { 22306, 22322, 22319, 22325, 22398 }, chance = { 22, 22, 20, 18, 17 } },
            { npc = nil, name = "Trash", trash = true, loot = { 16683, 16680, 16696, 16703, 16673, 16735, 16713, 13260 }, chance = { 3, 3, 3, 3, 3, 3, 3, 0 } },
        } },
    },
})
