-- OnyxiasLair.lua: Onyxia's Lair in the Dungeon Journal, generated by Tools/build_journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("OnyxiasLair", {
    name = "Onyxia's Lair",
    raid = 40,
    note = "Opens on Forever on 9 December 2026. Its loot shows in a later version of the addon, once it is known.",
    zone = "Dustwallow Marsh", territory = "Contested",
    entrance = { map = 1445, x = 52.9, y = 78.2 },
    wings = {
        { bosses = {
            { npc = 10184, name = "Onyxia", model = 8570, encounters = { 1084 } },
        } },
    },
})
