-- Scholomance.lua: Scholomance in the Dungeon Journal, generated by Tools/build/journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Scholomance", {
    name = "Scholomance",
    closed = true,
    zone = "Western Plaguelands", territory = "Contested",
    entrance = { map = 1422, x = 70.7, y = 71.0 },
    wings = {
        { bosses = {
            { npc = 10506, name = "Kirtonos the Herald", model = 143673, encounters = { 2805 }, loot = { 13957, 13967, 13960, 13969, 16734, 13956, 14024, 13955, 13983 }, chance = { 19, 19, 19, 19, 19, 18, 18, 18, 14 } },
            { npc = 10503, name = "Jandice Barov", model = 11073, encounters = { 2804 }, loot = { 16701, 14545, 14548, 18690, 22394, 14541, 18689, 14543 }, chance = { 16, 13, 12, 12, 11, 10, 10, 1 } },
            { npc = 11622, name = "Rattlegore", model = 12073, encounters = { 2811 }, loot = { 16711, 14539, 14531, 14537, 14528, 14538, 18686 }, chance = { 18, 12, 12, 12, 12, 12, 12 } },
            { npc = 10433, name = "Marduk Blackpool", model = 10248, encounters = { 2809 }, loot = { 18692, 14576 }, chance = { 7, 7 } },
            { npc = 10432, name = "Vectus", model = 2606, encounters = { 2813 }, loot = { 14577, 18691 }, chance = { 8, 7 } },
            { npc = 10508, name = "Ras Frostwhisper", model = 7919, encounters = { 2810 }, loot = { 16689, 14487, 18694, 14502, 18696, 18693, 18695, 13952, 14522, 14525, 14340, 14503, 13314 }, chance = { 19, 16, 16, 16, 16, 15, 15, 15, 15, 15, 14, 14, 1 } },
            { npc = 10505, name = "Instructor Malicia", model = 11069, encounters = { 2803 }, loot = { 16710, 14623, 14621, 14620, 14622, 14624 }, chance = { 4, 4, 4, 4, 3, 1 } },
            { npc = 11261, name = "Doctor Theolen Krastinov", model = 10901, encounters = { 2802 }, loot = { 16684, 14622, 14620, 14621, 14623, 14624 }, chance = { 8, 4, 4, 4, 4, 1 } },
            { npc = 10901, name = "Lorekeeper Polkelt", model = 11492, encounters = { 2808 }, loot = { 16705, 14620, 14622, 14623, 14621, 14624 }, chance = { 8, 4, 4, 3, 3, 1 } },
            { npc = 10507, name = "The Ravenian", model = 10433, encounters = { 2812 }, loot = { 16716, 14622, 14620, 14623, 14621, 14624 }, chance = { 5, 4, 4, 4, 4, 1 } },
            { npc = 10504, name = "Lord Alexei Barov", model = 11072, encounters = { 2807 }, loot = { 14624, 16722 }, chance = { 7, 4 } },
            { npc = 10502, name = "Lady Illucia Barov", model = 11835, encounters = { 2806 }, loot = { 14620, 14621, 14622, 14623, 14624 }, chance = { 4, 4, 4, 4, 1 } },
            { npc = 1853, name = "Darkmaster Gandling", model = 11070, encounters = { 2801 }, loot = { 13951, 22433, 13944, 13953, 13398, 13964, 16686, 13938, 16677, 16731, 16693, 16698, 16720, 16707, 16727, 16667, 13937, 13950 }, chance = { 14, 14, 13, 13, 13, 13, 13, 13, 12, 12, 12, 11, 11, 11, 7, 6, 2, 1 } },
            { npc = 14695, name = "Lord Blackwood", model = 14699, optional = true, loot = { 23132, 23139, 23156 }, chance = { 30, 29, 26 } },
            { npc = 16118, name = "Kormok", model = 16020, optional = true, encounters = { 3055 }, loot = { 22333, 22303, 22331, 22332, 22326 }, chance = { 32, 15, 15, 14, 11 } },
            { npc = 14516, name = "Death Knight Darkreaver", model = 14591, optional = true, loot = { 18760, 18758, 18761, 18759 }, chance = { 24, 24, 24, 22 } },
            { npc = nil, name = "Trash", trash = true, loot = { 16684, 16705, 14631, 14636, 14638, 14629, 14632, 14633, 14640, 14641, 14615, 14620, 16722, 14612, 14614, 14616, 14621, 14622, 14623, 14626, 18680, 18681, 18683, 14637, 18682, 18684, 14624, 14611, 23200, 14536, 18697, 18698, 18699, 18700, 18701, 18702 }, chance = { 5, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0 } },
        } },
    },
})
