-- ShadowfangKeep.lua: Shadowfang Keep in the Dungeon Journal, generated by Tools/build_journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("ShadowfangKeep", {
    name = "Shadowfang Keep",
    zone = "Silverpine Forest", territory = "Horde",
    entrance = { map = 1421, x = 45.5, y = 67.7 },
    wings = {
        { bosses = {
            { npc = 3914, name = "Rethilgore", model = 524, encounters = { 2748 }, loot = { 5254, 273456, 273457 }, chance = { 86, 0, 0 } },
            { npc = 3886, name = "Razorclaw the Butcher", model = 524, encounters = { 2749 }, loot = { 6226, 6633, 1292 }, chance = { 42, 40, 9 } },
            { npc = 3887, name = "Baron Silverlaine", model = 3222, encounters = { 2750 }, loot = { 6323, 6321, 273637 }, chance = { 38, 19, 0 } },
            { npc = 4278, name = "Commander Springvale", model = 3223, encounters = { 2751 }, loot = { 3191, 6320, 273643 }, chance = { 36, 30, 0 } },
            { npc = 4279, name = "Odo the Blindwatcher", model = 522, encounters = { 2752 }, loot = { 6319, 6318, 273645 }, chance = { 58, 33, 0 } },
            { npc = 4274, name = "Fenrus the Devourer", model = 2352, encounters = { 2753 }, loot = { 6340, 3230, 273646 }, chance = { 73, 17, 0 } },
            { npc = 3927, name = "Wolf Master Nandos", model = 11179, encounters = { 2754 }, loot = { 3748, 6314, 273647 }, chance = { 57, 38, 0 } },
            { npc = 4275, name = "Archmage Arugal", model = 2353, encounters = { 2755 }, loot = { 6324, 6392, 6220 }, chance = { 35, 35, 18 } },
            { npc = 3872, name = "Deathsworn Captain", model = 3224, rare = true, loot = { 6641, 6642, 2205 }, chance = { 57, 34, 2 } },
            { npc = 3864, name = "Fel Steed", model = 1951, rare = true, loot = { 6341 }, chance = { 7 } },
            { npc = 14682, name = "Sever", model = 1061, optional = true, loot = { 23173, 23171 }, chance = { 51, 44 } },
            { npc = 4627, name = "Arugal's Voidwalker", model = 1131, optional = true, loot = { 5943 } },
            { npc = nil, name = "Trash", trash = true, loot = { 6341, 5943, 1318, 1482, 1483, 1484, 1489, 1935, 1974, 2205, 2292, 2807, 3194 }, chance = { 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
        } },
    },
})
