-- ShapersTerrace.lua: Shaper's Terrace in the Dungeon Journal, generated by Tools/build_journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("ShapersTerrace", {
    name = "Shaper's Terrace",
    new = true,
    closed = true,
    zone = "Un'Goro Crater", territory = "Contested",
    entrance = { map = 1441, x = 12.2, y = 66.7 },
    wings = {
        { bosses = {
            { npc = nil, name = "Nanaya" },
            { npc = nil, name = "Snowtalon" },
            { npc = nil, name = "Cinder" },
            { npc = nil, name = "Bolt" },
        } },
    },
})
