-------------------------------------------------------------------------------
--  Data/Dungeons/ShapersTerrace.lua -- Shaper's Terrace in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("ShapersTerrace", {
    name = "Shaper's Terrace",
    new = true,
    closed = true,
    zone = "Un'Goro Crater", territory = "Contested",
    entrance = { map = 1441, x = 12.2, y = 66.7 },
    wings = {
        { bosses = {
            { npc = nil, name = "Nanaya" },
            { npc = nil, name = "Snowtalon" },
            { npc = nil, name = "Cinder" },
            { npc = nil, name = "Bolt" },
        } },
    },
})
