-- SunkenTemple.lua: Sunken Temple in the Dungeon Journal, generated by Tools/build_journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("SunkenTemple", {
    name = "Sunken Temple",
    closed = true,
    zone = "Swamp of Sorrows", territory = "Contested",
    entrance = { map = 1435, x = 69.6, y = 53.7 },
    wings = {
        { bosses = {
            { npc = 8580, name = "Atal'alarion", model = 7873, encounters = { 3582, 2814 }, loot = { 10800, 10798, 10799 }, chance = { 38, 37, 18 } },
            { npc = 5721, name = "Dreamscythe", model = 7553, encounters = { 3588, 486 }, loot = { 12465, 12466, 12243 }, chance = { 10, 10, 9 } },
            { npc = 5720, name = "Weaver", model = 6375, encounters = { 3587, 487 }, loot = { 12243, 12466, 12465 }, chance = { 10, 9, 9 } },
            { npc = 5710, name = "Jammal'an the Prophet", model = 6708, encounters = { 3589, 488 }, loot = { 10808, 10806, 10807 }, chance = { 30, 27, 27 } },
            { npc = 5711, name = "Ogom the Wretched", model = 6709, loot = { 10804, 10803, 10805 }, chance = { 31, 30, 30 } },
            { npc = 5719, name = "Morphaz", model = 7975, encounters = { 3586, 490 }, loot = { 12466, 12243, 12465 }, chance = { 8, 8, 8 } },
            { npc = 5722, name = "Hazzas", model = 9584, encounters = { 3585, 491 }, loot = { 12466, 12243, 12465 }, chance = { 9, 8, 8 } },
            { npc = 5709, name = "Shade of Eranikus", model = 7806, encounters = { 3584, 493 }, loot = { 10829, 10833, 10835, 10836, 10828, 10837, 10847 }, chance = { 32, 32, 29, 27, 17, 14, 1 } },
            { npc = 8443, name = "Avatar of Hakkar", model = 8053, encounters = { 3583, 492 }, loot = { 12462 }, chance = { 1 } },
            { npc = 5708, name = "Spawn of Hakkar", model = 4065, optional = true, loot = { 10801, 10802 }, chance = { 47, 24 } },
            { npc = nil, name = "Trash", trash = true, loot = { 10846, 10842, 10843, 10845, 10838, 10844, 10788, 10795, 10797, 12463, 10796, 12466, 12465, 12243, 10786, 12464, 10787, 10785, 10783, 10784, 10624, 10625, 10626, 10629, 10630, 10631, 10632, 10633 }, chance = { 33, 33, 32, 31, 16, 16, 10, 9, 9, 9, 9, 9, 9, 9, 8, 8, 7, 6, 4, 3, 0, 0, 0, 0, 0, 0, 0, 0 } },
        } },
    },
})
