-- ZulFarrak.lua: Zul'Farrak in the Dungeon Journal, generated by Tools/build_journal.py.
local ns = _G.NaowhForever

ns.Journal.AddDungeon("ZulFarrak", {
    name = "Zul'Farrak",
    closed = true,
    zone = "Tanaris", territory = "Contested",
    entrance = { map = 1446, x = 39.6, y = 21.7 },
    wings = {
        { bosses = {
            { npc = 8127, name = "Antu'sul", model = 7353, encounters = { 595 }, loot = { 9641, 9640, 9639, 9379 }, chance = { 34, 32, 18, 3 } },
            { npc = 7272, name = "Theka the Martyr", model = 6696, encounters = { 596 } },
            { npc = 7271, name = "Witch Doctor Zum'rah", model = 6434, encounters = { 597 }, loot = { 18083, 18082 }, chance = { 35, 15 } },
            { npc = 7796, name = "Nekrum Gutchewer", model = 6690, encounters = { 598 } },
            { npc = 7275, name = "Shadowpriest Sezz'ziz", model = 6441, encounters = { 599 }, loot = { 9470, 9473, 9475, 9474 }, chance = { 23, 22, 22, 22 } },
            { npc = 7604, name = "Sergeant Bly", model = 6433, loot = { 5616 } },
            { npc = 7795, name = "Hydromancer Velratha", model = 6685, encounters = { 593 } },
            { npc = 7273, name = "Gahz'rilla", model = 7271, encounters = { 594 }, loot = { 9467, 9469 }, chance = { 46, 45 } },
            { npc = 7267, name = "Chief Ukorz Sandscalp", model = 6439, encounters = { 600 }, loot = { 9476, 9477, 9478, 9479, 11086 }, chance = { 32, 23, 23, 11, 2 } },
            { npc = 10082, name = "Zerillis", model = 9293, rare = true, loot = { 12470 }, chance = { 18 } },
            { npc = 10081, name = "Dustwraith", model = 9292, rare = true, loot = { 12471 }, chance = { 21 } },
            { npc = nil, name = "Trash", trash = true, loot = { 9243 }, chance = { 1 } },
        } },
    },
})
