-------------------------------------------------------------------------------
--  NaowhForever_PvPSpells.lua -- generated by Tools/build_pvp_auras.py from the game's spell
--  tables (build 1.60.1.70205); do not edit by hand. PvP Auras' spell lists by spell ID: crowd
--  control by ability, every other crowd control spell, and common PvP debuffs.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.PvPSpells = {
    crowdControl = {
        { key = "chargeStun", group = "Warrior", label = "Charge Stun", icon = 135860, spell = 7922, ids = {
            [7922] = true, [411688] = true,
        } },
        { key = "interceptStun", group = "Warrior", label = "Intercept Stun", icon = 135860, spell = 20253, ids = {
            [20253] = true, [20614] = true, [20615] = true, [427746] = true,
        } },
        { key = "intimidatingShout", group = "Warrior", label = "Intimidating Shout", icon = 132154, spell = 5246, ids = {
            [5246] = true, [19134] = true, [20511] = true, [29544] = true, [1213465] = true, [1270811] = true,
        } },
        { key = "concussionBlow", group = "Warrior", label = "Concussion Blow", icon = 132325, spell = 12809, ids = {
            [12809] = true, [22427] = true,
        } },
        { key = "disarm", group = "Warrior", label = "Disarm", icon = 132343, spell = 676, ids = {
            [676] = true, [6713] = true, [8379] = true, [11879] = true, [13534] = true, [15752] = true, [22691] = true, [27581] = true, [445282] = true, [458880] = true, [1225428] = true, [1236176] = true,
        } },
        { key = "improvedHamstring", group = "Warrior", label = "Improved Hamstring", icon = 132316, spell = 23694, ids = {
            [23694] = true,
        } },
        { key = "shieldBashSilence", group = "Warrior", label = "Shield Bash Silence", icon = 132357, spell = 18498, ids = {
            [18498] = true,
        } },
        { key = "hammerOfJustice", group = "Paladin", label = "Hammer of Justice", icon = 135963, spell = 853, ids = {
            [853] = true, [5588] = true, [5589] = true, [10308] = true, [13005] = true, [1213301] = true,
        } },
        { key = "repentance", group = "Paladin", label = "Repentance", icon = 135942, spell = 20066, ids = {
            [20066] = true,
        } },
        { key = "freezingTrap", group = "Hunter", label = "Freezing Trap", icon = 135834, spell = 3355, ids = {
            [3355] = true, [14308] = true, [14309] = true,
        } },
        { key = "scatterShot", group = "Hunter", label = "Scatter Shot", icon = 132153, spell = 19503, ids = {
            [19503] = true, [23601] = true, [462666] = true,
        } },
        { key = "wyvernSting", group = "Hunter", label = "Wyvern Sting", icon = 135125, spell = 24335, ids = {
            [24335] = true, [26180] = true, [1215753] = true,
        } },
        { key = "intimidation", group = "Hunter", label = "Intimidation", icon = 136122, spell = 7093, ids = {
            [7093] = true, [24394] = true,
        } },
        { key = "improvedConcussiveShot", group = "Hunter", label = "Improved Concussive Shot", icon = 135860, spell = 19410, ids = {
            [19410] = true, [22915] = true, [28445] = true,
        } },
        { key = "entrapment", group = "Hunter", label = "Entrapment", icon = 136100, spell = 19185, ids = {
            [19185] = true, [465230] = true,
        } },
        { key = "counterattack", group = "Hunter", label = "Counterattack", icon = 132336, spell = 19306, ids = {
            [19306] = true, [20909] = true, [20910] = true, [1242634] = true,
        } },
        { key = "scareBeast", group = "Hunter", label = "Scare Beast", icon = 132118, spell = 1513, ids = {
            [1513] = true, [14326] = true, [14327] = true,
        } },
        { key = "sap", group = "Rogue", label = "Sap", icon = 132310, spell = 2070, ids = {
            [2070] = true, [6770] = true, [11297] = true,
        } },
        { key = "gouge", group = "Rogue", label = "Gouge", icon = 132155, spell = 1776, ids = {
            [1776] = true, [1777] = true, [8629] = true, [11285] = true, [11286] = true, [12540] = true, [13579] = true, [24698] = true, [28456] = true,
        } },
        { key = "blind", group = "Rogue", label = "Blind", icon = 136175, spell = 2094, ids = {
            [2094] = true, [21060] = true,
        } },
        { key = "kidneyShot", group = "Rogue", label = "Kidney Shot", icon = 132298, spell = 408, ids = {
            [408] = true, [8643] = true, [27615] = true,
        } },
        { key = "cheapShot", group = "Rogue", label = "Cheap Shot", icon = 132092, spell = 1833, ids = {
            [1833] = true, [6409] = true, [14902] = true,
        } },
        { key = "kickSilence", group = "Rogue", label = "Kick Silence", icon = 132219, spell = 18425, ids = {
            [18425] = true,
        } },
        { key = "riposte", group = "Rogue", label = "Riposte", icon = 132336, spell = 14251, ids = {
            [14251] = true,
        } },
        { key = "psychicScream", group = "Priest", label = "Psychic Scream", icon = 136184, spell = 8122, ids = {
            [8122] = true, [8124] = true, [10888] = true, [10890] = true, [13704] = true, [15398] = true, [22884] = true, [26042] = true, [27610] = true,
        } },
        { key = "mindControl", group = "Priest", label = "Mind Control", icon = 136206, spell = 605, ids = {
            [605] = true, [10911] = true, [10912] = true, [11446] = true, [1213332] = true,
        } },
        { key = "silence", group = "Priest", label = "Silence", icon = 135975, spell = 6726, ids = {
            [6726] = true, [8988] = true, [12528] = true, [15487] = true, [18278] = true, [18327] = true, [22666] = true, [23207] = true, [26069] = true, [27559] = true, [29943] = true, [30225] = true,
            [1214273] = true, [1224125] = true, [1293654] = true, [1304401] = true,
        } },
        { key = "blackout", group = "Priest", label = "Blackout", icon = 136160, spell = 15269, ids = {
            [15269] = true,
        } },
        { key = "polymorph", group = "Mage", label = "Polymorph", icon = 136071, spell = 118, ids = {
            [118] = true, [12824] = true, [12825] = true, [12826] = true, [13323] = true, [14621] = true, [15534] = true, [27760] = true, [28270] = true, [28271] = true, [28272] = true, [29124] = true,
            [29848] = true, [434754] = true, [1236174] = true, [1236290] = true,
        } },
        { key = "frostNova", group = "Mage", label = "Frost Nova", icon = 135848, spell = 122, ids = {
            [122] = true, [865] = true, [6131] = true, [9915] = true, [10230] = true, [11831] = true, [12674] = true, [12748] = true, [14907] = true, [15063] = true, [15531] = true, [15532] = true,
            [22645] = true, [29849] = true, [30094] = true, [463448] = true, [1220855] = true, [1289447] = true,
        } },
        { key = "counterspellSilence", group = "Mage", label = "Counterspell Silence", icon = 135856, spell = 18469, ids = {
            [18469] = true,
        } },
        { key = "impact", group = "Mage", label = "Impact", icon = 135821, spell = 12355, ids = {
            [12355] = true,
        } },
        { key = "frostbite", group = "Mage", label = "Frostbite", icon = 135842, spell = 12494, ids = {
            [12494] = true,
        } },
        { key = "fear", group = "Warlock", label = "Fear", icon = 136183, spell = 5782, ids = {
            [5782] = true, [6213] = true, [6215] = true, [12096] = true, [12542] = true, [22678] = true, [26070] = true, [26580] = true, [27641] = true, [27990] = true, [29168] = true, [30002] = true,
            [411959] = true, [469521] = true, [469793] = true, [469879] = true, [1213452] = true, [1222563] = true, [1247087] = true, [1271593] = true,
        } },
        { key = "howlOfTerror", group = "Warlock", label = "Howl of Terror", icon = 136147, spell = 5484, ids = {
            [5484] = true, [17928] = true,
        } },
        { key = "deathCoil", group = "Warlock", label = "Death Coil", icon = 136145, spell = 6789, ids = {
            [6789] = true, [17925] = true, [17926] = true, [28412] = true,
        } },
        { key = "seduction", group = "Warlock", label = "Seduction", icon = 136175, spell = 6358, ids = {
            [6358] = true,
        } },
        { key = "spellLock", group = "Warlock", label = "Spell Lock", icon = 136174, spell = 24259, ids = {
            [24259] = true,
        } },
        { key = "entanglingRoots", group = "Druid", label = "Entangling Roots", icon = 136100, spell = 339, ids = {
            [339] = true, [1062] = true, [5195] = true, [5196] = true, [9852] = true, [9853] = true, [11922] = true, [12747] = true, [19970] = true, [19971] = true, [19972] = true, [19973] = true,
            [19974] = true, [19975] = true, [20654] = true, [20699] = true, [21331] = true, [22127] = true, [22415] = true, [22800] = true, [24648] = true, [26071] = true, [28858] = true, [435991] = true,
            [460690] = true, [1213253] = true, [1263640] = true, [1281781] = true, [1294112] = true, [1303308] = true, [1316480] = true, [1320095] = true,
        } },
        { key = "hibernate", group = "Druid", label = "Hibernate", icon = 136090, spell = 2637, ids = {
            [2637] = true, [18657] = true, [18658] = true,
        } },
        { key = "bash", group = "Druid", label = "Bash", icon = 132114, spell = 5211, ids = {
            [5211] = true, [6798] = true, [8983] = true, [25515] = true, [440586] = true, [447891] = true, [1260650] = true,
        } },
        { key = "pounce", group = "Druid", label = "Pounce", icon = 132142, spell = 9005, ids = {
            [9005] = true, [9823] = true, [9827] = true, [1229228] = true, [1258520] = true, [1264548] = true,
        } },
        { key = "feralCharge", group = "Druid", label = "Feral Charge", icon = 132183, spell = 19675, ids = {
            [19675] = true,
        } },
        { key = "starfireStun", group = "Druid", label = "Starfire Stun", icon = 135753, spell = 16922, ids = {
            [16922] = true,
        } },
        { key = "warStomp", group = "Racials & Items", label = "War Stomp", icon = 132091, spell = 11876, ids = {
            [11876] = true, [15593] = true, [16727] = true, [19482] = true, [20549] = true, [24375] = true, [27758] = true, [28725] = true, [470031] = true, [1222567] = true, [1223459] = true,
        } },
        { key = "tidalCharm", group = "Racials & Items", label = "Tidal Charm", icon = 135861, spell = 835, ids = {
            [835] = true, [1317288] = true,
        } },
        { key = "netOMatic", group = "Racials & Items", label = "Net-o-Matic", icon = 132149, spell = 13099, ids = {
            [13099] = true, [13119] = true, [13138] = true, [16566] = true,
        } },
        { key = "recklessCharge", group = "Racials & Items", label = "Reckless Charge", icon = 136010, spell = 13327, ids = {
            [13327] = true,
        } },
        { key = "grenades", group = "Racials & Items", label = "Grenades & Bombs", icon = 135826, spell = 4068, ids = {
            [4068] = true, [4069] = true, [12421] = true, [12543] = true, [12562] = true, [19769] = true, [19784] = true,
        } },
        { key = "flashBomb", group = "Racials & Items", label = "Flash Bomb", icon = 136142, spell = 5134, ids = {
            [5134] = true, [29419] = true,
        } },
        { key = "arcaneBomb", group = "Racials & Items", label = "Arcane Bomb", icon = 135975, spell = 19821, ids = {
            [19821] = true, [462664] = true,
        } },
        { key = "mindControlCap", group = "Racials & Items", label = "Gnomish Mind Control Cap", icon = 135995, spell = 13181, ids = {
            [13181] = true,
        } },
    },
    otherCrowdControl = {
        [16] = true, [25] = true, [56] = true, [101] = true, [113] = true, [228] = true, [260] = true, [512] = true, [530] = true, [692] = true, [700] = true, [710] = true,
        [720] = true, [731] = true, [745] = true, [775] = true, [785] = true, [800] = true, [804] = true, [851] = true, [1090] = true, [1098] = true, [1121] = true, [2647] = true,
        [2878] = true, [2880] = true, [3109] = true, [3143] = true, [3242] = true, [3260] = true, [3263] = true, [3271] = true, [3442] = true, [3446] = true, [3542] = true, [3551] = true,
        [3589] = true, [3609] = true, [3618] = true, [3635] = true, [3636] = true, [3651] = true, [4064] = true, [4065] = true, [4066] = true, [4067] = true, [4159] = true, [4167] = true,
        [4168] = true, [4169] = true, [4243] = true, [4246] = true, [4320] = true, [4538] = true, [4962] = true, [5101] = true, [5106] = true, [5164] = true, [5165] = true, [5205] = true,
        [5219] = true, [5254] = true, [5259] = true, [5260] = true, [5276] = true, [5376] = true, [5403] = true, [5424] = true, [5543] = true, [5567] = true, [5627] = true, [5648] = true,
        [5649] = true, [5703] = true, [5708] = true, [5726] = true, [5727] = true, [5918] = true, [5951] = true, [6145] = true, [6243] = true, [6253] = true, [6266] = true, [6271] = true,
        [6304] = true, [6432] = true, [6435] = true, [6466] = true, [6524] = true, [6533] = true, [6537] = true, [6538] = true, [6576] = true, [6580] = true, [6605] = true, [6607] = true,
        [6608] = true, [6664] = true, [6669] = true, [6714] = true, [6716] = true, [6728] = true, [6730] = true, [6749] = true, [6754] = true, [6772] = true, [6869] = true, [6894] = true,
        [6927] = true, [6942] = true, [6945] = true, [6982] = true, [7033] = true, [7074] = true, [7082] = true, [7136] = true, [7139] = true, [7144] = true, [7184] = true, [7267] = true,
        [7295] = true, [7399] = true, [7586] = true, [7587] = true, [7621] = true, [7645] = true, [7670] = true, [7761] = true, [7803] = true, [7950] = true, [7961] = true, [7964] = true,
        [7967] = true, [8040] = true, [8041] = true, [8064] = true, [8142] = true, [8150] = true, [8151] = true, [8208] = true, [8225] = true, [8242] = true, [8281] = true, [8285] = true,
        [8312] = true, [8338] = true, [8345] = true, [8346] = true, [8359] = true, [8377] = true, [8391] = true, [8399] = true, [8510] = true, [8511] = true, [8611] = true, [8646] = true,
        [8672] = true, [8715] = true, [8817] = true, [8893] = true, [8901] = true, [8902] = true, [8994] = true, [9032] = true, [9159] = true, [9179] = true, [9256] = true, [9454] = true,
        [9458] = true, [9484] = true, [9485] = true, [9552] = true, [9576] = true, [9992] = true, [10017] = true, [10093] = true, [10134] = true, [10326] = true, [10451] = true, [10576] = true,
        [10737] = true, [10794] = true, [10805] = true, [10834] = true, [10835] = true, [10836] = true, [10851] = true, [10852] = true, [10856] = true, [10955] = true, [11020] = true, [11264] = true,
        [11428] = true, [11430] = true, [11444] = true, [11481] = true, [11641] = true, [11650] = true, [11725] = true, [11726] = true, [11820] = true, [11836] = true, [11958] = true, [12023] = true,
        [12024] = true, [12098] = true, [12134] = true, [12241] = true, [12242] = true, [12252] = true, [12461] = true, [12483] = true, [12509] = true, [12520] = true, [12521] = true, [12613] = true,
        [12734] = true, [12888] = true, [12890] = true, [12943] = true, [12946] = true, [13158] = true, [13235] = true, [13237] = true, [13238] = true, [13360] = true, [13466] = true, [13488] = true,
        [13608] = true, [13808] = true, [13902] = true, [13907] = true, [14030] = true, [14100] = true, [14102] = true, [14180] = true, [14515] = true, [14821] = true, [14823] = true, [14870] = true,
        [14871] = true, [15056] = true, [15252] = true, [15283] = true, [15471] = true, [15474] = true, [15535] = true, [15609] = true, [15618] = true, [15621] = true, [15652] = true, [15655] = true,
        [15660] = true, [15753] = true, [15822] = true, [15859] = true, [15878] = true, [15970] = true, [16045] = true, [16053] = true, [16075] = true, [16096] = true, [16097] = true, [16104] = true,
        [16310] = true, [16350] = true, [16420] = true, [16451] = true, [16452] = true, [16469] = true, [16470] = true, [16497] = true, [16508] = true, [16600] = true, [16707] = true, [16708] = true,
        [16709] = true, [16790] = true, [16798] = true, [16803] = true, [16805] = true, [16838] = true, [16869] = true, [17011] = true, [17172] = true, [17244] = true, [17250] = true, [17272] = true,
        [17276] = true, [17286] = true, [17293] = true, [17307] = true, [17308] = true, [17333] = true, [17398] = true, [17405] = true, [17446] = true, [17492] = true, [17500] = true, [17507] = true,
        [17624] = true, [17651] = true, [17691] = true, [17738] = true, [17743] = true, [17772] = true, [17774] = true, [18093] = true, [18103] = true, [18144] = true, [18373] = true, [18395] = true,
        [18430] = true, [18503] = true, [18546] = true, [18647] = true, [18763] = true, [18795] = true, [18798] = true, [18812] = true, [18953] = true, [19128] = true, [19136] = true, [19229] = true,
        [19364] = true, [19369] = true, [19393] = true, [19408] = true, [19469] = true, [19597] = true, [19636] = true, [19641] = true, [19676] = true, [19677] = true, [19678] = true, [19679] = true,
        [19680] = true, [19681] = true, [19682] = true, [19683] = true, [19684] = true, [19685] = true, [19686] = true, [19695] = true, [19725] = true, [19753] = true, [19780] = true, [19832] = true,
        [19872] = true, [20019] = true, [20170] = true, [20276] = true, [20277] = true, [20310] = true, [20478] = true, [20507] = true, [20548] = true, [20604] = true, [20663] = true, [20668] = true,
        [20669] = true, [20672] = true, [20683] = true, [20685] = true, [20740] = true, [20861] = true, [20882] = true, [20989] = true, [21099] = true, [21152] = true, [21167] = true, [21173] = true,
        [21188] = true, [21330] = true, [21556] = true, [21566] = true, [21748] = true, [21749] = true, [21808] = true, [21835] = true, [21847] = true, [21848] = true, [21869] = true, [21898] = true,
        [21909] = true, [21916] = true, [21936] = true, [21980] = true, [21990] = true, [22274] = true, [22289] = true, [22291] = true, [22357] = true, [22419] = true, [22519] = true, [22561] = true,
        [22566] = true, [22592] = true, [22651] = true, [22667] = true, [22686] = true, [22692] = true, [22703] = true, [22707] = true, [22744] = true, [22787] = true, [22856] = true, [22901] = true,
        [22911] = true, [22924] = true, [22935] = true, [22994] = true, [23010] = true, [23023] = true, [23055] = true, [23103] = true, [23171] = true, [23174] = true, [23186] = true, [23269] = true,
        [23275] = true, [23279] = true, [23310] = true, [23312] = true, [23364] = true, [23365] = true, [23414] = true, [23417] = true, [23444] = true, [23447] = true, [23454] = true, [23456] = true,
        [23457] = true, [23603] = true, [23775] = true, [23918] = true, [23919] = true, [23973] = true, [24004] = true, [24020] = true, [24048] = true, [24053] = true, [24057] = true, [24110] = true,
        [24152] = true, [24170] = true, [24178] = true, [24193] = true, [24213] = true, [24261] = true, [24324] = true, [24327] = true, [24333] = true, [24346] = true, [24360] = true, [24408] = true,
        [24594] = true, [24600] = true, [24619] = true, [24647] = true, [24664] = true, [24671] = true, [24686] = true, [24687] = true, [24690] = true, [24700] = true, [24732] = true, [24740] = true,
        [24743] = true, [24753] = true, [24754] = true, [24778] = true, [24811] = true, [24832] = true, [24883] = true, [24919] = true, [24935] = true, [24937] = true, [25006] = true, [25043] = true,
        [25056] = true, [25057] = true, [25161] = true, [25189] = true, [25260] = true, [25371] = true, [25374] = true, [25425] = true, [25495] = true, [25654] = true, [25655] = true, [25656] = true,
        [25685] = true, [25698] = true, [25725] = true, [25756] = true, [25772] = true, [25774] = true, [25806] = true, [25815] = true, [25821] = true, [25852] = true, [25900] = true, [25937] = true,
        [25999] = true, [26044] = true, [26049] = true, [26053] = true, [26061] = true, [26079] = true, [26102] = true, [26108] = true, [26115] = true, [26195] = true, [26196] = true, [26197] = true,
        [26198] = true, [26222] = true, [26258] = true, [26259] = true, [26332] = true, [26382] = true, [26552] = true, [26637] = true, [26641] = true, [27177] = true, [27553] = true, [27565] = true,
        [27619] = true, [27620] = true, [27792] = true, [27808] = true, [27814] = true, [27868] = true, [27880] = true, [28127] = true, [28160] = true, [28314] = true, [28315] = true, [28323] = true,
        [28335] = true, [28374] = true, [28450] = true, [28522] = true, [28618] = true, [28619] = true, [28620] = true, [28621] = true, [28622] = true, [28782] = true, [28786] = true, [28991] = true,
        [29111] = true, [29484] = true, [29685] = true, [29825] = true, [29826] = true, [30001] = true, [30112] = true, [31248] = true, [31362] = true, [31365] = true, [31366] = true, [258096] = true,
        [367476] = true, [367701] = true, [367728] = true, [367741] = true, [367888] = true, [367928] = true, [368329] = true, [368332] = true, [368708] = true, [369077] = true, [370308] = true, [370436] = true,
        [370863] = true, [370904] = true, [372376] = true, [400009] = true, [404275] = true, [407501] = true, [407546] = true, [407822] = true, [409495] = true, [412570] = true, [412790] = true, [423631] = true,
        [425226] = true, [425235] = true, [425294] = true, [425891] = true, [426604] = true, [427719] = true, [428739] = true, [429147] = true, [429167] = true, [429357] = true, [429687] = true, [429688] = true,
        [432222] = true, [432439] = true, [432467] = true, [433354] = true, [434869] = true, [435195] = true, [435896] = true, [435897] = true, [436027] = true, [436059] = true, [436100] = true, [436473] = true,
        [436534] = true, [436537] = true, [436818] = true, [436828] = true, [436831] = true, [437324] = true, [437532] = true, [437764] = true, [437915] = true, [437933] = true, [437987] = true, [438721] = true,
        [440488] = true, [440574] = true, [440656] = true, [440720] = true, [441453] = true, [441642] = true, [441785] = true, [443848] = true, [443990] = true, [444522] = true, [444892] = true, [445187] = true,
        [445498] = true, [445716] = true, [445940] = true, [446296] = true, [446299] = true, [446354] = true, [446373] = true, [446391] = true, [446593] = true, [446631] = true, [446639] = true, [446707] = true,
        [446728] = true, [446731] = true, [446733] = true, [447397] = true, [447544] = true, [447555] = true, [447579] = true, [447589] = true, [447590] = true, [448572] = true, [448828] = true, [449203] = true,
        [449879] = true, [449907] = true, [450005] = true, [450600] = true, [450662] = true, [452857] = true, [455991] = true, [456010] = true, [457569] = true, [458407] = true, [459164] = true, [459280] = true,
        [459499] = true, [459837] = true, [459845] = true, [460084] = true, [460086] = true, [460119] = true, [460403] = true, [460727] = true, [460742] = true, [460756] = true, [460767] = true, [461087] = true,
        [461110] = true, [461121] = true, [461125] = true, [461155] = true, [461163] = true, [461862] = true, [462058] = true, [462259] = true, [462395] = true, [462577] = true, [462586] = true, [462937] = true,
        [463011] = true, [463013] = true, [464650] = true, [465003] = true, [465352] = true, [466270] = true, [466272] = true, [467367] = true, [467449] = true, [467840] = true, [468012] = true, [468078] = true,
        [468591] = true, [469010] = true, [469065] = true, [469146] = true, [469155] = true, [469166] = true, [469182] = true, [469227] = true, [470009] = true, [470017] = true, [470108] = true, [473525] = true,
        [474268] = true, [474400] = true, [1213342] = true, [1213356] = true, [1213362] = true, [1213462] = true, [1213924] = true, [1213996] = true, [1214002] = true, [1214028] = true, [1214205] = true, [1214223] = true,
        [1215737] = true, [1215744] = true, [1215752] = true, [1216141] = true, [1217333] = true, [1217952] = true, [1218038] = true, [1218089] = true, [1219090] = true, [1219682] = true, [1220410] = true, [1220533] = true,
        [1220680] = true, [1220845] = true, [1220914] = true, [1220928] = true, [1220930] = true, [1221420] = true, [1221453] = true, [1221571] = true, [1222578] = true, [1222581] = true, [1223037] = true, [1224315] = true,
        [1225924] = true, [1225972] = true, [1227358] = true, [1227435] = true, [1227739] = true, [1227820] = true, [1227879] = true, [1228295] = true, [1228304] = true, [1229007] = true, [1229508] = true, [1229730] = true,
        [1229756] = true, [1229760] = true, [1230086] = true, [1230276] = true, [1230283] = true, [1230512] = true, [1230576] = true, [1230908] = true, [1230927] = true, [1231087] = true, [1231157] = true, [1231215] = true,
        [1231280] = true, [1231431] = true, [1231582] = true, [1231585] = true, [1231602] = true, [1231616] = true, [1231777] = true, [1231845] = true, [1231885] = true, [1231906] = true, [1232013] = true, [1232312] = true,
        [1232637] = true, [1232697] = true, [1232702] = true, [1232842] = true, [1233831] = true, [1233884] = true, [1234823] = true, [1234825] = true, [1234842] = true, [1235538] = true, [1235570] = true, [1237317] = true,
        [1238096] = true, [1238289] = true, [1238311] = true, [1239173] = true, [1239456] = true, [1240688] = true, [1240869] = true, [1241523] = true, [1242884] = true, [1243170] = true, [1243419] = true, [1244416] = true,
        [1245154] = true, [1245883] = true, [1246456] = true, [1249834] = true, [1249950] = true, [1250313] = true, [1250419] = true, [1253200] = true, [1253317] = true, [1257055] = true, [1258429] = true, [1259338] = true,
        [1262943] = true, [1263356] = true, [1264437] = true, [1265054] = true, [1265055] = true, [1265056] = true, [1265057] = true, [1265058] = true, [1265416] = true, [1265843] = true, [1265878] = true, [1265880] = true,
        [1265881] = true, [1265883] = true, [1265981] = true, [1267199] = true, [1269161] = true, [1269192] = true, [1269216] = true, [1269268] = true, [1269272] = true, [1269278] = true, [1269330] = true, [1269334] = true,
        [1269337] = true, [1269433] = true, [1269557] = true, [1269585] = true, [1269767] = true, [1269877] = true, [1270031] = true, [1270498] = true, [1270585] = true, [1270648] = true, [1270942] = true, [1270943] = true,
        [1270944] = true, [1271000] = true, [1271044] = true, [1271102] = true, [1271632] = true, [1272794] = true, [1272804] = true, [1277331] = true, [1277332] = true, [1277333] = true, [1277334] = true, [1277335] = true,
        [1277455] = true, [1277851] = true, [1278060] = true, [1278061] = true, [1280004] = true, [1280044] = true, [1280481] = true, [1282693] = true, [1284381] = true, [1284384] = true, [1284450] = true, [1285903] = true,
        [1287735] = true, [1287872] = true, [1288387] = true, [1288447] = true, [1288961] = true, [1289143] = true, [1289434] = true, [1289941] = true, [1290013] = true, [1290041] = true, [1290043] = true, [1290732] = true,
        [1291806] = true, [1292252] = true, [1292648] = true, [1293306] = true, [1293308] = true, [1293483] = true, [1293682] = true, [1293889] = true, [1294340] = true, [1294343] = true, [1294353] = true, [1294620] = true,
        [1294626] = true, [1294660] = true, [1296564] = true, [1296664] = true, [1297068] = true, [1297109] = true, [1297589] = true, [1297748] = true, [1299094] = true, [1299440] = true, [1299443] = true, [1300211] = true,
        [1300241] = true, [1300493] = true, [1300496] = true, [1300754] = true, [1300784] = true, [1301167] = true, [1301683] = true, [1302357] = true, [1302500] = true, [1302715] = true, [1302717] = true, [1302874] = true,
        [1302937] = true, [1303136] = true, [1303598] = true, [1306224] = true, [1306620] = true, [1307520] = true, [1308177] = true, [1309719] = true, [1309823] = true, [1310189] = true, [1310438] = true, [1312052] = true,
        [1312340] = true, [1315286] = true, [1315448] = true, [1315557] = true, [1315972] = true, [1317450] = true, [1317472] = true, [1317591] = true, [1318110] = true, [1318178] = true,
    },
    debuffs = {
        { key = "mortalStrike", group = "Warrior", label = "Mortal Strike", icon = 132355, spell = 9347, ids = {
            [9347] = true, [12294] = true, [13737] = true, [15708] = true, [16856] = true, [17547] = true, [19643] = true, [21551] = true, [21552] = true, [21553] = true, [24573] = true, [27580] = true,
        } },
        { key = "hamstring", group = "Warrior", label = "Hamstring", icon = 132316, spell = 1715, ids = {
            [1715] = true, [7372] = true, [7373] = true, [9080] = true, [26141] = true, [26211] = true, [27584] = true, [1236177] = true,
        } },
        { key = "piercingHowl", group = "Warrior", label = "Piercing Howl", icon = 132117, spell = 10576, ids = {
            [10576] = true, [12323] = true, [23600] = true,
        } },
        { key = "judgementOfJustice", group = "Paladin", label = "Judgement of Justice", icon = 135971, spell = 20184, ids = {
            [20184] = true, [25945] = true,
        } },
        { key = "concussiveShot", group = "Hunter", label = "Concussive Shot", icon = 135860, spell = 5116, ids = {
            [5116] = true, [17174] = true, [22914] = true, [27634] = true, [1236191] = true,
        } },
        { key = "wingClip", group = "Hunter", label = "Wing Clip", icon = 132309, spell = 2974, ids = {
            [2974] = true, [14267] = true, [14268] = true, [27633] = true, [1310180] = true,
        } },
        { key = "viperSting", group = "Hunter", label = "Viper Sting", icon = 132157, spell = 3034, ids = {
            [3034] = true, [14279] = true, [14280] = true,
        } },
        { key = "scorpidSting", group = "Hunter", label = "Scorpid Sting", icon = 132169, spell = 3043, ids = {
            [3043] = true, [18545] = true,
        } },
        { key = "huntersMark", group = "Hunter", label = "Hunter's Mark", icon = 132212, spell = 1130, ids = {
            [1130] = true, [14323] = true, [14324] = true, [14325] = true, [1213268] = true,
        } },
        { key = "woundPoison", group = "Rogue", label = "Wound Poison", icon = 134197, spell = 13218, ids = {
            [13218] = true, [13222] = true, [13223] = true, [13224] = true,
        } },
        { key = "cripplingPoison", group = "Rogue", label = "Crippling Poison", icon = 132274, spell = 3409, ids = {
            [3409] = true, [11201] = true, [25809] = true,
        } },
        { key = "mindNumbingPoison", group = "Rogue", label = "Mind-numbing Poison", icon = 136066, spell = 5760, ids = {
            [5760] = true, [25810] = true,
        } },
        { key = "shadowWordPain", group = "Priest", label = "Shadow Word: Pain", icon = 136207, spell = 589, ids = {
            [589] = true, [594] = true, [970] = true, [992] = true, [2767] = true, [10892] = true, [10893] = true, [10894] = true, [11639] = true, [14032] = true, [15654] = true, [17146] = true,
            [19776] = true, [23268] = true, [23952] = true, [24212] = true, [27605] = true, [450646] = true,
        } },
        { key = "mindFlay", group = "Priest", label = "Mind Flay", icon = 136208, spell = 15407, ids = {
            [15407] = true, [16568] = true, [17165] = true, [17311] = true, [17312] = true, [17313] = true, [17314] = true, [18807] = true, [22919] = true, [23953] = true, [26044] = true, [26143] = true,
            [28310] = true, [29407] = true, [368292] = true, [368315] = true, [412526] = true, [474204] = true, [474268] = true, [1215740] = true,
        } },
        { key = "frostShock", group = "Shaman", label = "Frost Shock", icon = 135849, spell = 8056, ids = {
            [8056] = true, [8058] = true, [10472] = true, [10473] = true, [12548] = true, [15089] = true, [15499] = true, [19133] = true, [21030] = true, [21401] = true, [22582] = true, [23115] = true,
            [1248001] = true,
        } },
        { key = "earthbind", group = "Shaman", label = "Earthbind", icon = 136102, spell = 3600, ids = {
            [3600] = true,
        } },
        { key = "frostbolt", group = "Mage", label = "Frostbolt", icon = 135846, spell = 116, ids = {
            [116] = true, [205] = true, [837] = true, [7322] = true, [8406] = true, [8407] = true, [8408] = true, [9672] = true, [10179] = true, [10180] = true, [10181] = true, [11538] = true,
            [12675] = true, [13322] = true, [13439] = true, [15043] = true, [15497] = true, [15530] = true, [16249] = true, [16799] = true, [17503] = true, [20297] = true, [20792] = true, [20806] = true,
            [20819] = true, [20822] = true, [21369] = true, [23102] = true, [23412] = true, [24942] = true, [25304] = true, [28478] = true, [28479] = true, [350025] = true, [406680] = true, [420526] = true,
            [1213276] = true, [1220854] = true, [1244970] = true, [1248148] = true, [1293790] = true, [1298416] = true, [1303226] = true,
        } },
        { key = "coneOfCold", group = "Mage", label = "Cone of Cold", icon = 135852, spell = 120, ids = {
            [120] = true, [8492] = true, [10159] = true, [10160] = true, [10161] = true, [12557] = true, [12611] = true, [15244] = true, [20828] = true, [22746] = true, [30095] = true,
        } },
        { key = "curseOfTongues", group = "Warlock", label = "Curse of Tongues", icon = 136140, spell = 1714, ids = {
            [1714] = true, [11719] = true, [12889] = true, [13338] = true, [15470] = true, [25195] = true, [402794] = true, [444046] = true,
        } },
        { key = "curseOfExhaustion", group = "Warlock", label = "Curse of Exhaustion", icon = 136162, spell = 18223, ids = {
            [18223] = true,
        } },
        { key = "corruption", group = "Warlock", label = "Corruption", icon = 136118, spell = 172, ids = {
            [172] = true, [6222] = true, [6223] = true, [7648] = true, [11671] = true, [11672] = true, [13530] = true, [16402] = true, [17510] = true, [18088] = true, [18376] = true, [18656] = true,
            [21068] = true, [23642] = true, [25311] = true, [28829] = true, [1213450] = true, [1223963] = true,
        } },
        { key = "faerieFire", group = "Druid", label = "Faerie Fire", icon = 136033, spell = 770, ids = {
            [770] = true, [778] = true, [6950] = true, [9749] = true, [9907] = true, [13424] = true, [13752] = true, [16498] = true, [20656] = true, [21670] = true, [1288561] = true, [1289452] = true,
        } },
    },
}
