-- TownTravel.lua: boats and zeppelins on the town map, by world map, generated by Tools/build/travel.py.
local ns = _G.NaowhForever

ns.TownTravel = {
    [1411] = {
        { 50.8, 13.3, "H", "Zeppelin to Grom'gol", 1434, "Zeppelin to Undercity", 1420 },
    },
    [1413] = {
        { 63.8, 38.8, "AH", "Boat to Booty Bay", 1434 },
    },
    [1420] = {
        { 61.2, 58.9, "H", "Zeppelin to Orgrimmar", 1411, "Zeppelin to Grom'gol", 1434 },
    },
    [1434] = {
        { 25.7, 73.1, "AH", "Boat to Ratchet", 1413 },
        { 31.4, 29.8, "H", "Zeppelin to Orgrimmar", 1411, "Zeppelin to Undercity", 1420 },
    },
    [1437] = {
        { 4.5, 56.7, "A", "Boat to Auberdine", 1439 },
        { 4.7, 63.8, "A", "Boat to Theramore", 1445 },
    },
    [1438] = {
        { 54.8, 97.2, "A", "Boat to Auberdine", 1439 },
    },
    [1439] = {
        { 32.3, 44.1, "A", "Boat to Menethil Harbor", 1437 },
        { 33.3, 39.8, "A", "Boat to Rut'theran Village", 1438 },
    },
    [1444] = {
        { 31, 39.5, "A", "Boat to the Feralas coast", 1444 },
        { 43.1, 42.8, "A", "Boat to Feathermoon Stronghold", 1444 },
    },
    [1445] = {
        { 71.7, 56.7, "A", "Boat to Menethil Harbor", 1437 },
    },
}
