-- Features.lua: every feature's on/off switch and its default, by settings store.
local ns = _G.NaowhForever

ns.FEATURE_BADGES = 0
ns.BADGES_LIVE = 1

local function Missing(_, key)
    error("NaowhForever: no feature switch named " .. tostring(key), 2)
end

local STRICT = { __index = Missing }

ns.FEATURES = {
    qol = {
        enabled = true,
        deathRelease = true,
        stealthReminder = false,
        coTank = true,
        deleteConfirm = false,
        lootConfirm = false,
        questAccept = true,
        questTurnIn = true,
        questGossip = true,
        questRewardPicks = true,
        questShare = true,
        gossipAuto = false,
        groupButtons = false,
        combatTimer = false,
        cursorCooldown = false,
        combatLogger = false,
        globalCopy = false,
        badgeChat = true,
        badgeCard = true,
        badgeTooltip = true,
        badgeBanner = false,
        tooltipDisplay = true,
        spellEfficiency = false,
        slashCommands = false,
        lootFeed = true,
        hideLootWindow = false,
        fastLoot = true,
        ahPrices = true,
        ahTooltip = true,
        altCounts = false,
        mailAlts = false,
        mailQuickAttach = false,
        mailExpiry = false,
        xpTicker = true,
        groupXP = false,
        healerMana = false,
        playerHistory = false,
        naowhScore = true,
        characterPanel = true,
        characterPanelSlotMarks = true,
        inspectPanel = true,
        groupInspect = false,
        groupInspectShare = true,
        xpBar = true,
        autoRepair = true,
        sellJunk = true,
        restock = true,
        foodBar = false,
        bagSpace = false,
        scrapMarker = false,
        townMap = true,
        mapUnexplored = true,
        zoneLevels = false,
        mapSkyborne = false,
        mapSize = false,
        gearSets = true,
        gearBarVisible = true,
        trinketBar = false,
        bis = true,
        bisLootAlert = true,
        blessings = true,
        durability = false,
        talentPoints = false,
        buffThanks = false,
        combatAlert = true,
        hideErrors = false,
        hideTutorials = false,
        hideScreenshot = false,
        skipCinematics = false,
        hideAlerts = false,
        hideEventToasts = false,
        hideZoneText = false,
        hideBagBar = false,
        cursorClip = false,
        crosshair = false,
        petTracker = false,
        equipReminder = true,
        autoEmote = false,
        chatZones = false,
        mouseRing = false,
        gcdTracker = false,
        focusCastBar = false,
        trainerPopup = true,
        flightTimer = true,
        quizCamp = true,
        aimTrainer = true,
        waypoints = true,
    },
    topBar = {
        enabled = true,
        showClock = false,
        showSystem = false,
    },
    journal = {
        enabled = true,
        mapPanel = true,
        mapFactions = false,
        mapEntrances = false,
    },
    statWeights = {
        enabled = false,
    },
    training = {
        enabled = true,
        levelUpToast = true,
        trainerPanel = true,
    },
    discovery = {
        enabled = false,
        tracker = false,
        mapPins = false,
        nearbySound = false,
        bagTracker = false,
        bagMapPins = false,
    },
    completo = {
        enabled = false,
        mapPins = false,
        rareAlert = false,
        rarePins = false,
    },
    professions = {
        enabled = true,
        recipeFinder = false,
        rankAlert = false,
        bagReagents = false,
        bankReagents = false,
        vendorMaterials = false,
        craftOrders = false,
        craftTimer = false,
        shoppingList = false,
        trainFavorites = false,
        searchFavoritesAH = false,
        gatherReminder = false,
        ahSearch = false,
        ahShiftClick = false,
        craftProfit = false,
        craftProfitList = false,
        buyMaterials = false,
        buyVendor = false,
    },
    macros = {
        enabled = true,
        health = true,
        mana = true,
        food = true,
        bandage = true,
        trinket1 = true,
        trinket2 = true,
        focus = true,
        acceptPopup = true,
    },
    actionBars = {
        enabled = true,
    },
    auraBuffs = {
        enabled = true,
        raidBuffs = false,
        campfire = true,
        campNearbyAlert = true,
        lowHealth = true,
    },
    threatMeter = {
        enabled = true,
        focusEnabled = false,
        warnSound = false,
    },
    pvp = {
        enabled = false,
        auras = true,
        buffs = true,
        cc = true,
        debuffs = false,
        focus = true,
        flagButton = false,
    },
    swingTimer = {
        enabled = true,
        queueHighlight = true,
        sealColors = true,
        swingWindow = true,
        autoShotWindow = false,
        castClip = false,
        targetSwing = false,
    },
    account = {
        gameMenuButton = true,
        rxpThemes = false,
    },
}

for _, switches in pairs(ns.FEATURES) do setmetatable(switches, STRICT) end
setmetatable(ns.FEATURES, STRICT)
