-- Settings.lua: the QoL settings store (ns.QoLSettings) and its defaults, read by the core and the modules.
local ns = _G.NaowhForever

local UI = ns.UI
local F = ns.FEATURES.qol

local S = UI.ModuleSettings("qol", {
    enabled = F.enabled,
    stealthReminder = F.stealthReminder,
    reminderInGroup = false, reminderHideResting = true,
    stealthShowStealthed = true, stealthDruid = "cat",
    stealthText = "STEALTH", stealthColor = { r = 0, g = 1, b = 0 }, stealthClassColor = false,
    warningText = "RESTEALTH", warningColor = { r = 1, g = 0, b = 0 }, warningClassColor = false,
    stealthFont = "", stealthFontSize = 22, stealthOutline = "OUTLINE", stealthBackground = "none",
    coTank = F.coTank, coTankName = true, coTankClassColor = true, coTankDebuffs = false,
    coTankWidth = 180, coTankHeight = 30,
    coTankColor = { r = 0, g = 0.8, b = 0.2 }, coTankBgAlpha = 0.6,
    coTankNameClassColor = false, coTankNameColor = { r = 1, g = 1, b = 1 },
    coTankNameLength = 0, coTankFont = "", coTankFontSize = 12, coTankOutline = "OUTLINE", coTankTexture = "",
    coTankAnchor = "UIParent", coTankX = 0, coTankY = 0,
    coTankDebuffFilter = "important", coTankDebuffCap = 3, coTankDebuffSize = 22,
    coTankDebuffSpacing = 2, coTankDebuffPosition = "top", coTankDebuffGrow = "CENTER",
    coTankDebuffX = 0, coTankDebuffY = 3,
    coTankDebuffDuration = true, coTankDebuffDurationSize = 10,
    coTankDebuffStacks = true, coTankDebuffStackSize = 10, coTankDebuffTooltips = false,

    deleteConfirm = F.deleteConfirm, lootConfirm = F.lootConfirm,
    questAccept = F.questAccept, questTurnIn = F.questTurnIn, questGossip = F.questGossip, questRewardPicks = F.questRewardPicks,
    questSkipModifier = "ALT", questModifierMode = "SKIP",
    gossipAuto = F.gossipAuto, gossipModifier = "ALT", gossipModifierMode = "SKIP",
    groupButtons = F.groupButtons, groupButtonsLayout = "stacked", groupButtonsWidth = 90, groupButtonsHeight = 24,
    groupButtonsFont = "", groupButtonsFontSize = 12, groupButtonsOutline = "NONE", groupButtonsBackground = "card",
    questShare = F.questShare,
    combatTimer = F.combatTimer, combatTimerInstanceOnly = false, combatTimerChat = true,
    combatTimerSticky = false, combatTimerHidePrefix = false, combatTimerBackground = "none",
    combatTimerColor = { r = 1, g = 1, b = 1 }, combatTimerClassColor = false,
    combatTimerFont = "", combatTimerFontSize = 32, combatTimerOutline = "OUTLINE",
    cursorCooldown = F.cursorCooldown, cursorCooldownSize = 29, cursorCooldownTime = 0.75,
    globalCopy = F.globalCopy, copyTooltipIds = true, copyModifier = "CTRL-SHIFT", copyKey = "C", copyShortcutSynced = false,
    badgeChat = F.badgeChat, badgeCard = F.badgeCard, badgeTooltip = F.badgeTooltip,
    badgeBanner = F.badgeBanner, badgeBannerSkipGuild = true,
    tooltipDisplay = F.tooltipDisplay, tooltipSpellID = true, tooltipNPCID = true, tooltipItemID = true,
    tooltipRestricted = "hide", tooltipCopy = true, tooltipModifier = "CTRL-SHIFT", tooltipKey = "C",
    tooltipCopyFormat = "url", tooltipCopyHint = false,
    spellEfficiency = F.spellEfficiency, spellEfficiencyPerMana = true, spellEfficiencyPerSecond = true,
    spellEfficiencyPerManaSecond = false, spellEfficiencyStyle = "long", spellEfficiencyDecimals = 2,
    spellEfficiencyColor = { r = 0x4d / 255, g = 0xb5 / 255, b = 0xf5 / 255 }, spellEfficiencyBonus = true,
    spellEfficiencyShow = "all",
    slashCommands = F.slashCommands,
    lootFeed = F.lootFeed, lootFeedMoney = true, lootFeedXP = false, lootFeedQuality = 1,
    lootFeedQuest = true, lootFeedRep = false,
    lootFeedCount = 6, lootFeedFade = 5, lootFeedStyle = "dark", lootFeedGlow = false,
    lootFeedValue = true, lootFeedBank = true, lootFeedPrice = "vendor", lootFeedGPH = false,
    hideLootWindow = F.hideLootWindow, fastLoot = F.fastLoot,
    lootFeedWidth = 340, lootFeedHeight = 36, lootFeedSpacing = -1, lootFeedGrowth = "up",
    lootFeedFont = "", lootFeedFontSize = 11, lootFeedOutline = "OUTLINE",
    lootFeedPos = { point = "CENTER", relPoint = "CENTER", x = -508, y = 322 },
    alertsPos = { point = "CENTER", relPoint = "CENTER", x = -519, y = 167 },
    ahPrices = F.ahPrices, ahTooltip = F.ahTooltip,
    altCounts = F.altCounts, mailAlts = F.mailAlts, mailQuickAttach = F.mailQuickAttach, mailExpiry = F.mailExpiry,
    xpTicker = F.xpTicker, xpTickerLevel = true, xpTickerElapsed = true,
    xpTickerHideResting = true, xpTickerFont = "", xpTickerFontSize = 24, xpTickerOutline = "",
    xpTickerSplits = true, xpTickerHistoryCount = 10, xpTickerBackground = "card",
    xpTickerPlayed = true, xpTickerPace = false, xpTickerSplitPlayed = true,
    xpTickerPos = { point = "CENTER", relPoint = "CENTER", x = -197, y = -322 },
    groupXP = F.groupXP, groupXPShowSelf = true, groupXPWidth = 260,
    groupXPFont = "", groupXPFontSize = 12, groupXPOutline = "OUTLINE", groupXPTexture = "", groupXPBgAlpha = 0.85,
    healerMana = F.healerMana, healerManaWhere = "instance", healerManaShowSelf = true, healerManaDrinking = true,
    healerManaWidth = 160, healerManaFont = "", healerManaFontSize = 12, healerManaOutline = "OUTLINE",
    healerManaBackground = "card",
    playerHistory = F.playerHistory, playerHistoryChats = true, playerHistoryDays = 90, playerNotesTooltip = true,
    naowhScore = F.naowhScore, naowhScoreShare = true, naowhScoreTooltip = true, naowhScoreScan = true, naowhScoreNearby = true,
    naowhScoreCompare = "both",
    characterPanel = F.characterPanel,
    characterPanelSlotMarks = F.characterPanelSlotMarks, characterPanelLevels = true, characterPanelMarks = true,
    characterPanelEnchants = true, characterPanelScore = true, characterPanelBadge = true, characterPanelStats = "spec",
    characterPanelTookOver = false, characterPanelAsked = false,
    inspectPanel = F.inspectPanel, inspectPanelScore = true, inspectPanelBadge = true, inspectPanelShareBis = true,
    inspectPanelTookOver = false, inspectPanelAsked = false,
    groupInspect = F.groupInspect, groupInspectShare = F.groupInspectShare, groupInspectSort = "score", groupInspectView = "gear",
    groupInspectAlpha = 1,
    xpBar = F.xpBar, xpBarLeftText = "level", xpBarCenterText = "xp", xpBarRightText = "percent",
    xpBarTopLeft = "played", xpBarTopRight = "none", xpBarBottomLeft = "leveling",
    xpBarBottom = "none", xpBarBottomRight = "xphour", xpBarTop = "none", xpBarLeft = "none",
    xpBarRight = "none", xpBarIncomplete = false, xpBarMaxLevel = false,
    xpBarResetOnReload = false, xpBarWidth = 520, xpBarHeight = 26,
    xpBarFont = "", xpBarFontSize = 13, xpBarOutline = "OUTLINE", xpBarTexture = "", xpBarBgAlpha = 0.85,
    xpBarPos = { point = "CENTER", relPoint = "CENTER", x = 0, y = 480 },
    autoRepair = F.autoRepair, sellJunk = F.sellJunk,
    restock = F.restock, restockReagents = true, restockAmmo = true, restockAmmoTarget = 1000,
    restockFood = true, restockFoodBelow = 10, restockFoodMinLevel = 0, restockFoodMaxLevel = 60, restockVendor = true, restockBagsBelow = 4,
    restockBuy = false,
    restockFont = "", restockFontSize = 16, restockOutline = "OUTLINE", restockBackground = "none",
    foodBar = F.foodBar, foodBarSize = 36,
    foodBarShowCount = true, foodBarFont = "", foodBarFontSize = 12, foodBarTextColor = { r = 0.94, g = 0.95, b = 0.95 },
    foodBarTextPoint = "BOTTOMRIGHT", foodBarTextOutside = false, foodBarTextX = 0, foodBarTextY = 0,
    foodBarKeybinds = false, foodBarKeyFont = "", foodBarKeySize = 10, foodBarKeyColor = { r = 0.85, g = 0.85, b = 0.85 },
    foodBarKeyPoint = "TOPRIGHT", foodBarKeyOutside = false, foodBarKeyX = 0, foodBarKeyY = 0,
    foodBarAnchor = "UIParent", foodBarAnchorPoint = "CENTER", foodBarAnchorRelPoint = "CENTER",
    foodBarX = 0, foodBarY = 0,
    consumableBar = F.consumableBar, consumableBarItems = {}, consumableBarItemFlags = {},
    consumableBarSize = 36, consumableBarSpacing = 4, consumableBarGrow = "RIGHT", consumableBarPerRow = 12,
    consumableBarCooldown = true, consumableBarTooltip = true, consumableBarHideEmpty = false,
    consumableBarHideCombat = false, consumableBarBackground = false, consumableBarBgAlpha = 0.6,
    consumableBarAskNew = false, consumableBarDeclined = {}, consumableBarSkip = {}, consumableBarWindowAlpha = 1,
    consumableBarShowCount = true, consumableBarFont = "", consumableBarFontSize = 14,
    consumableBarTextColor = { r = 1, g = 1, b = 1 }, consumableBarTextPoint = "BOTTOMRIGHT",
    consumableBarTextOutside = false, consumableBarTextX = 0, consumableBarTextY = 0,
    consumableBarKeybinds = false, consumableBarKeyFont = "", consumableBarKeySize = 10,
    consumableBarKeyColor = { r = 0.85, g = 0.85, b = 0.85 }, consumableBarKeyPoint = "TOPRIGHT",
    consumableBarKeyOutside = false, consumableBarKeyX = 0, consumableBarKeyY = 0,
    consumableBarAnchor = "UIParent", consumableBarAnchorPoint = "CENTER", consumableBarAnchorRelPoint = "CENTER",
    consumableBarX = 0, consumableBarY = 0,
    bagSpace = F.bagSpace, bagSpaceCount = 4, bagSpaceSize = 36, bagSpaceGrow = "RIGHT", bagSpaceReverse = false,
    bagSpaceMaxQuality = 2, bagSpaceJunkFirst = false, bagSpaceAuction = true,
    bagSpaceProtect = true, bagSpaceFreeBelow = 0, bagSpaceHideCombat = true,
    bagSpaceOnFull = true, bagSpaceShowFree = true, bagSpaceStack = true, bagSpaceOldFirst = false,
    bagSpaceTipVendor = true, bagSpaceTipAuction = true, bagSpaceTipDelete = true, bagSpaceTipIgnore = true,
    bagSpacePrices = true, bagSpaceBackground = "card",
    bagSpaceFont = "", bagSpaceFontSize = 12, bagSpaceOutline = "",
    scrapMarker = F.scrapMarker, scrapMarkerVendor = "sell", scrapMarkerScope = "account", scrapMarkerShow = true,
    scrapMarkerProtect = true, scrapRuleWear = false, scrapRuleOld = false, scrapRuleLevels = 10,
    townCapitalsOnly = true, townSpiritHealers = true, townZoneLinks = true,
    townMap = F.townMap, townClass = true, townProfession = true, townFlight = true, townInn = true,
    townBank = true, townStable = false, townRepair = true, townSupplies = true,
    townVendors = false, townMail = true, townPinSize = 16, townMinimap = true, townMinimapSpirit = true,
    townTravel = false,
    mapUnexplored = F.mapUnexplored, mapUnexploredDark = 0.5,
    zoneLevels = F.zoneLevels,
    mapSkyborne = F.mapSkyborne, mapSkyborneSize = 20,
    mapSize = F.mapSize, mapSizePercent = 100, mapSizePos = false,
    gearSets = F.gearSets, gearBarVisible = F.gearBarVisible, trinketBar = F.trinketBar, trinketSize = 36, trinketSpacing = 4, gearBarSize = 32, gearMounted = "", gearResting = "",
    gearWindowAlpha = 1, gearBarSpacing = 4, gearBarShow = "always",
    gearPos = { point = "CENTER", relPoint = "CENTER", x = -403, y = -379 },
    bis = F.bis, bisTooltip = true, bisBagMarks = true, bisLootAlert = F.bisLootAlert, bisWindowAlpha = 1,
    bisAlertFor = "all", bisAlertChat = true, bisAlertBadge = true, bisToast = true,
    bisDropSound = "game:raidwarning", bisYoursSound = "game:epicloot",
    bisToastScale = 1, bisToastTime = 6, bisToastAlpha = 0.95, bisToastGlow = true, bisToastStar = "icon",
    bisToastBorder = "rank", bisToastEvent = true, bisToastRank = true, bisToastSlot = true,
    bisToastSource = false, bisToastGain = true, bisToastFont = "", bisToastFontSize = 13, bisToastOutline = "NONE",
    bisToastPos = { point = "CENTER", relPoint = "CENTER", x = -9, y = 393 },
    blessings = F.blessings, blessSpacing = 6, blessGroupSpacing = 6, blessTimerSize = 14, blessShowLabels = true, blessBarSize = 30, blessTimers = true, blessShowAura = true,
    blessShowFury = false, blessWindowAlpha = 1, blessFont = "", blessOutline = "OUTLINE", blessThemeColors = false,
    blessLabelStyle = "name",
    blessLayout = "horizontal",

    durability = F.durability, durabilityBelow = 14, durabilityFont = "",
    durabilityFontSize = 22, durabilityOutline = "OUTLINE", durabilityBackground = "none", durabilityTheme = false,
    talentPoints = F.talentPoints, talentPointsFont = "",
    talentPointsFontSize = 22, talentPointsOutline = "OUTLINE", talentPointsBackground = "none",
    talentPointsTheme = false,
    buffThanks = F.buffThanks, buffThanksCooldown = 10, buffThanksGroup = false, buffThanksEmote = false,
    buffThanksText = "Thanks for the {buff}, fellow traveler!\nMuch appreciated, {name}, thanks for the {buff}!",
    buffThanksPerBuff = false,
    buffThanksIntellect = "Thanks for the {buff}! I feel smarter already.\nThanks for the {buff}, {name}, my brain thanks you!\nIQ is rising, thank you for the {buff}, {name}!",
    buffThanksStamina = "Thanks for the {buff}! Feeling tougher already.\nThanks for the {buff}, {name}, I will put that health to good use!\nThanks for the {buff}, {name}, this will keep me safe!",
    buffThanksSpirit = "Thanks for the {buff}, {name}, my mana thanks you!\nSpirits be with you as well, {name}!",
    buffThanksShadow = "Thanks for the {buff}, {name}! The shadows cannot touch me now.\nShadows begone! Thank you, {name}!",
    buffThanksWild = "Thanks for the {buff}! Nature thanks you too.\nThanks for the {buff}, {name}, feeling wild!\nThanks for the {buff}, {name}, I am one with nature now!",
    buffThanksThorns = "Thanks for the {buff}, {name}! Anything that hits me will regret it.\nThanks for the {buff}, {name}! They will think twice before attacking.",
    buffThanksBlessing = "Thanks for the {buff}, {name}! The Light be with you.\nThanks for the blessing, {name}!\nWell met, {name}! Righteousness follows thanks to your {buff}.",
    combatAlert = F.combatAlert,
    combatEnterText = "+Combat", combatEnterColor = { r = 0, g = 1, b = 0 },
    combatEnterClassColor = false,
    combatLeaveText = "-Combat", combatLeaveColor = { r = 1, g = 0, b = 0 },
    combatLeaveClassColor = false,
    combatAlertFont = "", combatAlertFontSize = 32, combatAlertOutline = "OUTLINE", combatAlertBackground = "none",
    combatAlertPos = { point = "CENTER", relPoint = "CENTER", x = 0, y = 151 },
    combatEnterAudio = "none", combatEnterSound = "voice:combat", combatEnterSpeech = "Combat",
    combatLeaveAudio = "none", combatLeaveSound = "voice:safe", combatLeaveSpeech = "Safe",
    combatEnterVoice = "", combatEnterVolume = 50, combatEnterRate = 0,
    combatLeaveVoice = "", combatLeaveVolume = 50, combatLeaveRate = 0,

    hideErrors = F.hideErrors, hideTutorials = F.hideTutorials, hideScreenshot = F.hideScreenshot,
    skipCinematics = F.skipCinematics,
    hideAlerts = F.hideAlerts, hideEventToasts = F.hideEventToasts, hideZoneText = F.hideZoneText,
    hideBagBar = F.hideBagBar,
    cursorClip = F.cursorClip,
    crosshair = F.crosshair, crossSize = 20, crossThickness = 2, crossGap = 6,
    crossColor = { r = 0, g = 1, b = 0 }, crossClassColor = false, crossOpacity = 0.8,
    crossX = 0, crossY = 0, crossCombatOnly = false, crossHideMounted = false,
    crossTop = true, crossRight = true, crossBottom = true, crossLeft = true,
    crossDot = false, crossDotSize = 2,
    crossOutline = true, crossOutlineWeight = 1, crossOutlineColor = { r = 0, g = 0, b = 0 },
    crossCircle = false, crossCircleSize = 30, crossCircleColor = { r = 0, g = 1, b = 0 },
    crossMelee = false, crossMeleeColor = { r = 1, g = 0, b = 0 }, crossMeleeBorder = true,
    crossMeleeArms = false, crossMeleeDot = false, crossMeleeCircle = false,
    crossMeleeSound = false, crossMeleeSoundKey = "none", crossMeleeSoundInterval = 3,
    crossMeleeSpell = 0,

    petTracker = F.petTracker, petPassive = true, petLowHealth = false, petLowHealthBelow = 25,
    petInstanceOnly = false, petCombatOnly = false, petHideMounted = true, petShowIcon = true,
    petColor = { r = 1, g = 0, b = 0 }, petClassColor = false, petFont = "", petFontSize = 20,
    petOutline = "OUTLINE", petBackground = "none",
    petMissingText = "Pet Missing", petPassiveText = "Pet Passive", petLowHealthText = "Pet Low HP",
    equipReminder = F.equipReminder, equipOnInstance = true, equipOnReadyCheck = true, equipAutoHide = 10,
    equipIconSize = 40, equipEnchants = true, equipEnchantRules = {},
    chatZones = F.chatZones, chatZonesLevel = true, chatZonesClassColour = true, chatZonesFinder = true, chatZonesWhere = true, chatZonesMaxAge = 15, chatZonesAsk = true, chatZonesShare = false,

    mouseRing = F.mouseRing, mouseShape = "ring.tga", mouseSize = 48,
    mouseColor = { r = 1, g = 0.66, b = 0 }, mouseClassColor = false,
    mouseShowOOC = true, mouseOpacityCombat = 1, mouseOpacityOOC = 1,
    mouseHideOnClick = false, mouseHideAfk = false,
    mouseBorder = false, mouseBorderColor = { r = 1, g = 1, b = 1 }, mouseBorderClassColor = false,
    mouseBorderWeight = 2,
    mouseDot = false, mouseDotSize = 6, mouseDotColor = { r = 1, g = 1, b = 1 },
    mouseDotClassColor = false,
    mouseFadeIdle = false, mouseFadeDelay = 2, mouseFadeOpacity = 0,
    mouseGCD = true, mouseHideBackground = false, mouseGCDColor = { r = 0.004, g = 0.56, b = 0.91 },
    mouseGCDClassColor = false, mouseReadyColor = { r = 0, g = 0.8, b = 0.3 }, mouseReadyMatch = false,
    mouseGCDAlpha = 1, mouseCastSwipe = true, mouseCastColor = { r = 0.004, g = 0.56, b = 0.91 },
    mouseCastClassColor = false, mouseSwipeDelay = 0.08,
    mouseTrail = false, mouseTrailShape = "glow", mouseTrailColor = { r = 1, g = 1, b = 1 },
    mouseTrailClassColor = false, mouseTrailSparkle = false, mouseTrailLength = 20,
    mouseTrailDuration = 2, mouseTrailSize = 24, mouseTrailBrightness = 0.8,
    mouseMelee = false, mouseMeleeBorder = true, mouseMeleeRing = false,
    mouseMeleeSound = false, mouseMeleeSoundKey = "none", mouseMeleeSoundInterval = 3,

    gcdTracker = F.gcdTracker, gcdDuration = 5, gcdIconSize = 32, gcdSpacing = 4, gcdDirection = "RIGHT",
    gcdFadeStart = 0.5, gcdStack = true, gcdCombatOnly = false,
    gcdWorld = true, gcdDungeon = true, gcdRaid = true, gcdPvP = true,
    gcdBlocklist = "6603, 75", gcdTimelineColor = { r = 0.01, g = 0.56, b = 0.91 },
    gcdTimelineHeight = 4, gcdDowntime = false, gcdTexture = "",
    focusCastBar = F.focusCastBar, focusWidth = 250, focusHeight = 24,
    focusBgColor = { r = 0.12, g = 0.12, b = 0.12 }, focusBgAlpha = 0.8,
    focusReadyColor = { r = 0.01, g = 0.56, b = 0.91 }, focusReadyClassColor = false,
    focusCooldownColor = { r = 0.5, g = 0.5, b = 0.5 },
    focusColorNonInt = true, focusNonIntColor = { r = 0.8, g = 0.2, b = 0.2 },
    focusInterruptedColor = { r = 0.51, g = 0.51, b = 0.51 },
    focusIcon = true, focusIconSide = "LEFT", focusSpellName = true, focusNameLength = 0,
    focusTarget = true, focusTime = true, focusShield = true,
    focusTick = true, focusTickColor = { r = 1, g = 1, b = 1 }, focusTickClassColor = false,
    focusFont = "", focusFontSize = 12, focusOutline = "OUTLINE", focusTexture = "", focusThemeColors = false,
    focusTextColor = { r = 1, g = 1, b = 1 }, focusTextClassColor = false,
    focusHideFriendly = false, focusHideNonInt = false, focusHideOnCooldown = false,
    focusFadeTime = 0.75, focusInterrupter = false,
    focusCastBarPos = { point = "CENTER", relPoint = "CENTER", x = 5, y = 71 },
    focusAudio = "none", focusSound = "none", focusSpeech = "Interrupt",
    focusVoice = "", focusVolume = 50, focusRate = 0,

    trainerPopup = F.trainerPopup, trainerGlow = true, trainerRanks = true,
    trainerPos = { point = "TOP", relPoint = "TOP", x = -274, y = -77 },

    flightTimer = F.flightTimer, flightTimerScale = 1, flightTimerAlpha = 1, flightEarlyLanding = true, flightTimerMapTime = false,
    flightGame = "aim", quizCamp = F.quizCamp,
    quizPos = { point = "TOP", relPoint = "TOP", x = 0, y = -127 },
    flightTimerFont = "", flightTimerOutline = "NONE", flightTimerTexture = "",
    aimTrainer = F.aimTrainer, aimMode = "hexakill", aimPulse = true, aimSound = true,
    aimSoundKey = "game:click", aimShare = true,
    waypoints = F.waypoints, waypointShape = "hex", waypointScale = 1, waypointCard = true,
    waypointTime = true, waypointBeam = true, waypointFadeNear = 40, waypointEdge = true,
    waypointNav = true, waypointSound = "none", waypointHideGame = true,
})
ns.QoLSettings = S
