-------------------------------------------------------------------------------
--  Data/Formula.lua -- the Naowh Score's constants, which Score.lua reads. Generated by
--  Tools/fit_naowh_score.py: do not edit by hand.
--
--  Fitted to WoW Forever build 1.60.1.70205's own item table (wago.tools): 6,960 items with
--  stats, item levels 5 to 100. Per item the fit explains 97% of the stat budget's
--  spread (median error 4.2%). The daily watch refits it for each new build and
--  rewrites this file only when a slot moves 0.02 or a quality's worth at item level
--  60 moves 0.5.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

local Score = {}
ns.NaowhScore = Score

-- How much of an item's stats each slot carries, by inventory slot (chest = 1). Trinkets keep
-- most of their power in effects no stat shows: their 0.7 is a judgement call, not fitted.
Score.SLOTS = {
    [1] = 1.01, [2] = 0.54, [3] = 0.76, [5] = 1, [6] = 0.75, [7] = 1.01, [8] = 0.75, [9] = 0.56,
    [10] = 0.75, [11] = 0.54, [12] = 0.54, [13] = 0.7, [14] = 0.7, [15] = 0.55, [16] = 0.41,
    [17] = 0.55, [18] = 0.31,
}
-- An item of each quality counts as an epic of level x SCALE + SHIFT: grey, white, green,
-- blue, epic, legendary, artifact, heirloom (the last three as epic, at their own level).
Score.SCALE = { [0] = 0.39, [1] = 0.59, [2] = 0.65, [3] = 0.8, [4] = 1, [5] = 1, [6] = 1, [7] = 1 }
Score.SHIFT = { [0] = -3, [1] = -4.5, [2] = -5, [3] = -2.1, [4] = 0, [5] = 0, [6] = 0, [7] = 0 }
