-------------------------------------------------------------------------------
--  NaowhForever_QoL.lua -- the QoL module's settings (ns.QoLSettings) and their defaults. Each
--  feature declares its own card next to its code; also ns.DisbandGroup, for On-Screen Buttons.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever
local UI = ns.UI

local S = UI.ModuleSettings("qol", {
    enabled = true,
    deathRelease = false, deathReleaseHold = 1,
    stealthReminder = false, formReminder = false,
    reminderInGroup = false, reminderHideResting = true,
    stealthShowStealthed = true, stealthDruid = "cat",
    stealthText = "STEALTH", stealthColor = { r = 0, g = 1, b = 0 }, stealthClassColor = false,
    warningText = "RESTEALTH", warningColor = { r = 1, g = 0, b = 0 }, warningClassColor = false,
    stealthFont = "", stealthFontSize = 22,
    formDruid = "none", formShadowform = false, formCombatOnly = false, formInstanceOnly = false,
    formText = "", formColor = { r = 1, g = 0.4, b = 0 }, formClassColor = false,
    formFont = "", formFontSize = 22,
    formSound = false, formSoundKey = "none", formSoundInterval = 3,
    coTank = false, coTankName = true, coTankClassColor = true, coTankDebuffs = true,
    coTankWidth = 180, coTankHeight = 30,
    coTankColor = { r = 0, g = 0.8, b = 0.2 }, coTankBgAlpha = 0.6,
    coTankNameClassColor = false, coTankNameColor = { r = 1, g = 1, b = 1 },
    coTankNameLength = 0, coTankFont = "", coTankFontSize = 12,
    coTankAnchor = "UIParent", coTankX = 0, coTankY = 0,
    coTankDebuffFilter = "important", coTankDebuffCap = 3, coTankDebuffSize = 22,
    coTankDebuffSpacing = 2, coTankDebuffPosition = "top", coTankDebuffGrow = "CENTER",
    coTankDebuffX = 0, coTankDebuffY = 3,
    coTankDebuffDuration = true, coTankDebuffDurationSize = 10,
    coTankDebuffStacks = true, coTankDebuffStackSize = 10, coTankDebuffTooltips = false,

    deleteConfirm = false, lootConfirm = false, enchantReplace = false,
    questAccept = false, questTurnIn = false, questGossip = false, questRewardPicks = true,
    questSkipModifier = "ALT",
    groupButtons = false, groupButtonsLayout = "stacked",
    questShare = false,
    combatTimer = false, combatTimerInstanceOnly = false, combatTimerChat = true,
    combatTimerSticky = false, combatTimerHidePrefix = false, combatTimerBackground = false,
    combatTimerColor = { r = 1, g = 1, b = 1 }, combatTimerClassColor = false,
    combatTimerFont = "", combatTimerFontSize = 32,
    combatLogger = false, combatLogRaids = "ask", combatLogDungeons = "never",
    combatLogStopOnLeave = true, combatLogChat = false, combatLogAclPrompt = true,
    globalCopy = false, copyTooltipIds = true, copyModifier = "CTRL", copyKey = "C", copyShortcutSynced = false,
    -- Supporter badges. On by default so everyone sees them, except the group banner, which
    -- Naowh asked to start off.
    badgeChat = true, badgeCard = true, badgeTooltip = true,
    badgeBanner = false, badgeBannerSkipGuild = true,
    tooltipDisplay = true, tooltipSpellID = true, tooltipNPCID = true, tooltipItemID = true,
    tooltipRestricted = "hide", tooltipCopy = true, tooltipModifier = "CTRL-SHIFT", tooltipKey = "C",
    tooltipCopyFormat = "url", tooltipCopyHint = false,
    slashCommands = false,
    lootFeed = true, lootFeedMoney = true, lootFeedXP = false, lootFeedQuality = 1,
    lootFeedQuest = true, lootFeedRep = false,
    lootFeedCount = 6, lootFeedFade = 5, lootFeedStyle = "dark", lootFeedGlow = false,
    lootFeedValue = true, lootFeedBank = true, lootFeedPrice = "vendor", lootFeedGPH = false,
    hideLootWindow = false, fastLoot = false,
    lootFeedWidth = 340, lootFeedHeight = 36, lootFeedSpacing = -1, lootFeedGrowth = "up",
    lootFeedFont = "", lootFeedFontSize = 13,
    ahPrices = true, ahTooltip = true,
    altCounts = false, mailAlts = false, mailQuickAttach = false, mailExpiry = false,
    xpTicker = true, xpTickerLevel = true, xpTickerElapsed = true,
    xpTickerHideResting = false, xpTickerFont = "", xpTickerFontSize = 24, xpTickerOutline = false,
    xpTickerSplits = true, xpTickerHistoryCount = 10, xpTickerBackground = "card",
    xpTickerPlayed = true, xpTickerPace = false, xpTickerSplitPlayed = true,
    groupXP = false, groupXPShowSelf = true, groupXPWidth = 260,
    naowhScore = true, naowhScoreTooltip = true, naowhScoreScan = true, naowhScoreNearby = true,
    naowhScoreCompare = "both",
    characterPanel = true,
    -- On by default, an exception to off by default: marks on the game's own panel, no restyle.
    characterPanelSlotMarks = true, characterPanelLevels = true, characterPanelMarks = true,
    characterPanelEnchants = true, characterPanelScore = true, characterPanelBadge = true, characterPanelStats = "spec",
    characterPanelTookOver = false, characterPanelAsked = false,
    xpBar = false, xpBarLeftText = "level", xpBarCenterText = "xp", xpBarRightText = "percent",
    xpBarTopLeft = "played", xpBarTopRight = "none", xpBarBottomLeft = "leveling",
    xpBarBottom = "none", xpBarBottomRight = "xphour", xpBarTop = "none", xpBarLeft = "none",
    xpBarRight = "none", xpBarIncomplete = false, xpBarMaxLevel = false,
    xpBarResetOnReload = false, xpBarWidth = 520, xpBarHeight = 26,
    autoRepair = false, sellJunk = false,
    restock = true, restockReagents = true, restockAmmo = true, restockAmmoTarget = 1000,
    restockFood = true, restockFoodBelow = 10, restockFoodMinLevel = 0, restockFoodMaxLevel = 60, restockVendor = true, restockBagsBelow = 4,
    restockBuy = false,
    bagSpace = false, bagSpaceCount = 4, bagSpaceSize = 36, bagSpaceGrow = "RIGHT",
    bagSpaceMaxQuality = 2, bagSpaceJunkFirst = false, bagSpaceAuction = true,
    bagSpaceProtect = true, bagSpaceFreeBelow = 0, bagSpaceHideCombat = true,
    bagSpaceOnFull = true, bagSpaceShowFree = true, bagSpaceStack = true, bagSpaceOldFirst = false,
    bagSpaceTipVendor = true, bagSpaceTipAuction = true, bagSpaceTipDelete = true, bagSpaceTipIgnore = true,
    bagSpacePrices = true, bagSpaceBackground = "card",
    scrapMarker = false, scrapMarkerVendor = "sell", scrapMarkerScope = "account", scrapMarkerShow = true,
    scrapMarkerProtect = true, scrapRuleWear = false, scrapRuleOld = false, scrapRuleLevels = 10,
    townCapitalsOnly = true, townSpiritHealers = true, townZoneLinks = true,
    townMap = true, townClass = true, townProfession = true, townFlight = true, townInn = true,
    townBank = true, townStable = false, townRepair = true, townSupplies = true,
    townVendors = false, townMail = false, townPinSize = 16, townMinimap = false, townTravel = false,
    mapUnexplored = false, mapUnexploredDark = 0.5,
    gearSets = true, gearBarVisible = true, trinketBar = false, trinketSize = 36, trinketSpacing = 4, gearBarSize = 32, gearMounted = "", gearResting = "",
    gearWindowAlpha = 1,
    bis = true, bisTooltip = true, bisBagMarks = true, bisBagLevels = true, bisLootAlert = true, bisWindowAlpha = 1,
    -- Drop Alert: which picks, what it does, and its on-screen alert (BiS/View/Toast.lua).
    bisAlertFor = "all", bisAlertChat = true, bisAlertBadge = true, bisToast = true,
    bisDropSound = "game:raidwarning", bisYoursSound = "game:epicloot",
    bisToastScale = 1, bisToastTime = 6, bisToastAlpha = 0.95, bisToastGlow = true, bisToastStar = "icon",
    bisToastBorder = "rank", bisToastEvent = true, bisToastRank = true, bisToastSlot = true,
    bisToastSource = false, bisToastGain = true,
    blessings = true, blessSpacing = 6, blessGroupSpacing = 6, blessTimerSize = 14, blessShowLabels = true, blessBarSize = 30, blessTimers = true, blessShowAura = true,
    blessShowFury = false, blessWindowAlpha = 1,

    durability = true, durabilityBelow = 25, durabilityFont = "",
    talentPoints = false, talentPointsFont = "",
    combatAlert = false,
    combatEnterText = "+Combat", combatEnterColor = { r = 0, g = 1, b = 0 },
    combatEnterClassColor = false,
    combatLeaveText = "-Combat", combatLeaveColor = { r = 1, g = 0, b = 0 },
    combatLeaveClassColor = false,
    combatAlertFont = "", combatAlertFontSize = 32,
    combatEnterAudio = "none", combatEnterSound = "voice:combat", combatEnterSpeech = "Combat",
    combatLeaveAudio = "none", combatLeaveSound = "voice:safe", combatLeaveSpeech = "Safe",
    combatEnterVoice = "", combatEnterVolume = 50, combatEnterRate = 0,
    combatLeaveVoice = "", combatLeaveVolume = 50, combatLeaveRate = 0,

    hideErrors = false, hideTutorials = false, hideScreenshot = false,
    skipCinematics = false,
    hideAlerts = false, hideEventToasts = false, hideZoneText = false,
    cursorClip = false,
    crosshair = false, crossSize = 20, crossThickness = 2, crossGap = 6,
    crossColor = { r = 0, g = 1, b = 0 }, crossClassColor = false, crossOpacity = 0.8,
    crossX = 0, crossY = 0, crossCombatOnly = false, crossHideMounted = false,
    crossTop = true, crossRight = true, crossBottom = true, crossLeft = true,
    crossDot = false, crossDotSize = 2,
    crossOutline = true, crossOutlineWeight = 1, crossOutlineColor = { r = 0, g = 0, b = 0 },
    crossCircle = false, crossCircleSize = 30, crossCircleColor = { r = 0, g = 1, b = 0 },
    crossMelee = false, crossMeleeColor = { r = 1, g = 0, b = 0 }, crossMeleeBorder = true,
    crossMeleeArms = false, crossMeleeDot = false, crossMeleeCircle = false,
    crossMeleeSound = false, crossMeleeSoundKey = "none", crossMeleeSoundInterval = 3,
    crossMeleeSpell = 0,
    fps = false, localMS = false, worldMS = false,

    petTracker = false, petPassive = true, petLowHealth = false, petLowHealthBelow = 25,
    petInstanceOnly = false, petCombatOnly = false, petHideMounted = true, petShowIcon = true,
    petColor = { r = 1, g = 0, b = 0 }, petClassColor = false, petFont = "", petFontSize = 20,
    petMissingText = "Pet Missing", petPassiveText = "Pet Passive", petLowHealthText = "Pet Low HP",
    equipReminder = false, equipOnInstance = true, equipOnReadyCheck = true, equipAutoHide = 10,
    equipIconSize = 40, equipEnchants = false, equipEnchantRules = {},
    autoEmote = false, autoEmoteCooldown = 2, autoEmoteList = "698: prepares a ritual of summoning",

    mouseRing = false, mouseShape = "ring.tga", mouseSize = 48,
    mouseColor = { r = 1, g = 0.66, b = 0 }, mouseClassColor = false,
    mouseShowOOC = true, mouseOpacityCombat = 1, mouseOpacityOOC = 1,
    mouseHideOnClick = false, mouseHideAfk = false,
    mouseBorder = false, mouseBorderColor = { r = 1, g = 1, b = 1 }, mouseBorderClassColor = false,
    mouseBorderWeight = 2,
    mouseDot = false, mouseDotSize = 6, mouseDotColor = { r = 1, g = 1, b = 1 },
    mouseDotClassColor = false,
    mouseFadeIdle = false, mouseFadeDelay = 2, mouseFadeOpacity = 0,
    mouseGCD = true, mouseHideBackground = false, mouseGCDColor = { r = 0.004, g = 0.56, b = 0.91 },
    mouseGCDClassColor = false, mouseReadyColor = { r = 0, g = 0.8, b = 0.3 }, mouseReadyMatch = false,
    mouseGCDAlpha = 1, mouseCastSwipe = true, mouseCastColor = { r = 0.004, g = 0.56, b = 0.91 },
    mouseCastClassColor = false, mouseSwipeDelay = 0.08,
    mouseTrail = false, mouseTrailShape = "glow", mouseTrailColor = { r = 1, g = 1, b = 1 },
    mouseTrailClassColor = false, mouseTrailSparkle = false, mouseTrailLength = 20,
    mouseTrailDuration = 2, mouseTrailSize = 24, mouseTrailBrightness = 0.8,
    mouseMelee = false, mouseMeleeBorder = true, mouseMeleeRing = false,
    mouseMeleeSound = false, mouseMeleeSoundKey = "none", mouseMeleeSoundInterval = 3,

    gcdTracker = false, gcdDuration = 5, gcdIconSize = 32, gcdSpacing = 4, gcdDirection = "RIGHT",
    gcdFadeStart = 0.5, gcdStack = true, gcdCombatOnly = false,
    gcdWorld = true, gcdDungeon = true, gcdRaid = true, gcdPvP = true,
    gcdBlocklist = "6603, 75", gcdTimelineColor = { r = 0.01, g = 0.56, b = 0.91 },
    gcdTimelineHeight = 4, gcdDowntime = false,
    focusCastBar = false, focusWidth = 250, focusHeight = 24,
    focusBgColor = { r = 0.12, g = 0.12, b = 0.12 }, focusBgAlpha = 0.8,
    focusReadyColor = { r = 0.01, g = 0.56, b = 0.91 }, focusReadyClassColor = false,
    focusCooldownColor = { r = 0.5, g = 0.5, b = 0.5 },
    focusColorNonInt = true, focusNonIntColor = { r = 0.8, g = 0.2, b = 0.2 },
    focusInterruptedColor = { r = 0.51, g = 0.51, b = 0.51 },
    focusIcon = true, focusIconSide = "LEFT", focusSpellName = true, focusNameLength = 0,
    focusTarget = true, focusTime = true, focusShield = true,
    focusTick = true, focusTickColor = { r = 1, g = 1, b = 1 }, focusTickClassColor = false,
    focusFont = "", focusFontSize = 12,
    focusTextColor = { r = 1, g = 1, b = 1 }, focusTextClassColor = false,
    focusHideFriendly = false, focusHideNonInt = false, focusHideOnCooldown = false,
    focusFadeTime = 0.75, focusInterrupter = false,
    focusAudio = "none", focusSound = "none", focusSpeech = "Interrupt",
    focusVoice = "", focusVolume = 50, focusRate = 0,

    trainerPopup = true, trainerGlow = true, trainerRanks = true,

    flightTimer = true, flightTimerScale = 1, flightEarlyLanding = false, flightGame = "aim", quizCamp = true,
    aimTrainer = true, aimMode = "hexakill", aimPulse = true, aimSound = true,
    aimSoundKey = "game:click", aimShare = true,
})
ns.QoLSettings = S

function ns.DisbandGroup()
    if not IsInGroup() then ns.Print("You are not in a group."); return end
    if not UnitIsGroupLeader("player") then ns.Print("Only the group leader can disband the group."); return end
    ns.Confirm("Remove everyone from your group?", function()
        if InCombatLockdown() then
            ns.Print("The group can be disbanded once the fight is over.")
            return
        end
        for _, unit in ipairs(IsInRaid() and { "raid" } or { "party" }) do
            for i = GetNumGroupMembers(), 1, -1 do
                local u = unit .. i
                if UnitExists(u) and not UnitIsUnit(u, "player") then C_PartyInfo.UninviteUnit(GetUnitName(u, true)) end
            end
        end
    end)
end
