-- NaowhForever_QuizData.lua: the quiz questions; the first answer is the right one.
local ns = _G.NaowhForever

ns.QUIZ_QUESTIONS = {
    { q = "Which city is the capital of the dwarves?", a = { "Ironforge", "Stormwind", "Darnassus", "Gnomeregan" } },
    { q = "Which city is the capital of the orcs?", a = { "Orgrimmar", "Thunder Bluff", "Undercity", "Stonard" } },
    { q = "Which city is the capital of the tauren?", a = { "Thunder Bluff", "Orgrimmar", "Undercity", "Sen'jin Village" } },
    { q = "Which city is the capital of the night elves?", a = { "Darnassus", "Auberdine", "Astranaar", "Nighthaven" } },
    { q = "The Undercity lies beneath the ruins of which capital city?", a = { "Lordaeron", "Stratholme", "Dalaran", "Gilneas" } },
    { q = "Which gnome capital was lost to an invasion of troggs?", a = { "Gnomeregan", "Kharanos", "Thelsamar", "Shadowforge City" } },
    { q = "In which zone do human characters begin their journey?", a = { "Elwynn Forest", "Westfall", "Dun Morogh", "Redridge Mountains" } },
    { q = "In which zone do night elf characters begin?", a = { "Teldrassil", "Darkshore", "Ashenvale", "Moonglade" } },
    { q = "In which zone do Forsaken characters begin?", a = { "Tirisfal Glades", "Silverpine Forest", "Hillsbrad Foothills", "Duskwood" } },
    { q = "Orcs and trolls begin their adventures in which zone?", a = { "Durotar", "The Barrens", "Mulgore", "Stonetalon Mountains" } },
    { q = "Dwarves and gnomes begin their adventures in which zone?", a = { "Dun Morogh", "Loch Modan", "Wetlands", "Alterac Mountains" } },
    { q = "Who leads the Defias Brotherhood in the Deadmines?", a = { "Edwin VanCleef", "Mr. Smite", "Captain Greenskin", "Gilnid" } },
    { q = "The Deadmines entrance is hidden in which Westfall town?", a = { "Moonbrook", "Sentinel Hill", "Goldshire", "Lakeshire" } },
    { q = "Which dungeon is a prison inside Stormwind City?", a = { "The Stockade", "The Deadmines", "Blackfathom Deeps", "Razorfen Kraul" } },
    { q = "Which dungeon lies beneath Orgrimmar?", a = { "Ragefire Chasm", "Wailing Caverns", "Razorfen Downs", "Maraudon" } },
    { q = "Shadowfang Keep is found in which zone?", a = { "Silverpine Forest", "Tirisfal Glades", "Duskwood", "Alterac Mountains" } },
    { q = "Which mage brought the worgen to Shadowfang Keep?", a = { "Archmage Arugal", "Archmage Antonidas", "Kel'Thuzad", "Khadgar" } },
    { q = "Which dungeon in Tirisfal Glades is held by the Scarlet Crusade?", a = { "Scarlet Monastery", "Shadowfang Keep", "Scholomance", "Razorfen Kraul" } },
    { q = "Which Scarlet Monastery boss yells 'Blades of Light!'?", a = { "Herod", "Arcanist Doan", "Houndmaster Loksey", "Bloodmage Thalnos" } },
    { q = "Zul'Farrak is found in which zone?", a = { "Tanaris", "Stranglethorn Vale", "Feralas", "Un'Goro Crater" } },
    { q = "Scholomance is found on which island?", a = { "Caer Darrow", "Tol Barad", "Kul Tiras", "Crestfall" } },
    { q = "Which boss can drop the Deathcharger's Reins mount?", a = { "Baron Rivendare", "Darkmaster Gandling", "General Drakkisath", "Emperor Thaurissan" } },
    { q = "Who rules the Dark Iron dwarves in Blackrock Depths?", a = { "Emperor Dagran Thaurissan", "Magni Bronzebeard", "Lord Incendius", "General Angerforge" } },
    { q = "Which orc warchief in Blackrock Spire rides the dragon Gyth?", a = { "Rend Blackhand", "Overlord Wyrmthalak", "War Master Voone", "Gizrul the Slavener" } },
    { q = "Which raid is home to Ragnaros the Firelord?", a = { "Molten Core", "Blackwing Lair", "Onyxia's Lair", "Zul'Gurub" } },
    { q = "Who must be defeated in the Molten Core before Ragnaros is summoned?", a = { "Majordomo Executus", "Golemagg", "Sulfuron Harbinger", "Lucifron" } },
    { q = "Which two Molten Core bosses drop the Thunderfury bindings?", a = { "Garr and Baron Geddon", "Lucifron and Magmadar", "Gehennas and Shazzrah", "Golemagg and Sulfuron" } },
    { q = "Complete the name: Thunderfury, Blessed Blade of the...", a = { "Windseeker", "Firelord", "Stormcaller", "Tempest" } },
    { q = "Ragnaros says he was awakened too soon by whom?", a = { "Executus", "Nefarius", "Thaurissan", "Garr" } },
    { q = "Which boss yells 'BY FIRE BE PURGED!'?", a = { "Ragnaros", "Nefarian", "Onyxia", "Baron Geddon" } },
    { q = "Onyxia's Lair is found in which zone?", a = { "Dustwallow Marsh", "Burning Steppes", "Swamp of Sorrows", "Badlands" } },
    { q = "Lady Katrana Prestor of Stormwind is secretly which dragon?", a = { "Onyxia", "Sinestra", "Ysera", "Alexstrasza" } },
    { q = "Onyxia and Nefarian are the children of which dragon?", a = { "Deathwing", "Alexstrasza", "Malygos", "Nozdormu" } },
    { q = "Nefarian is the final boss of which raid?", a = { "Blackwing Lair", "Molten Core", "Upper Blackrock Spire", "Onyxia's Lair" } },
    { q = "Which corrupted red dragon in Blackwing Lair empowers the raid before the fight?", a = { "Vaelastrasz", "Chromaggus", "Ebonroc", "Flamegor" } },
    { q = "Hakkar the Soulflayer is the final boss of which raid?", a = { "Zul'Gurub", "Zul'Farrak", "Ruins of Ahn'Qiraj", "Temple of Ahn'Qiraj" } },
    { q = "The gates of Ahn'Qiraj are found in which zone?", a = { "Silithus", "Tanaris", "Un'Goro Crater", "Feralas" } },
    { q = "What did a player bang to open the gates of Ahn'Qiraj?", a = { "The Scarab Gong", "The Bronze Bell", "The Silithid Drum", "The Qiraji Horn" } },
    { q = "Which Old God waits at the end of the Temple of Ahn'Qiraj?", a = { "C'Thun", "Yogg-Saron", "N'Zoth", "Y'Shaarj" } },
    { q = "Who is the master of Naxxramas in the original game?", a = { "Kel'Thuzad", "Arthas", "Baron Rivendare", "Darkmaster Gandling" } },
    { q = "Which blue dragon is a world boss in Azshara?", a = { "Azuregos", "Sapphiron", "Kalecgos", "Malygos" } },
    { q = "Which dragon is one of the four corrupted green dragons of the Emerald Dream?", a = { "Ysondre", "Azuregos", "Vaelastrasz", "Sapphiron" } },
    { q = "What was Deathwing's name before his corruption?", a = { "Neltharion", "Nozdormu", "Nefarian", "Galakrond" } },
    { q = "Who is the Warchief of the Horde in the original game?", a = { "Thrall", "Cairne Bloodhoof", "Vol'jin", "Grom Hellscream" } },
    { q = "Who leads the tauren from Thunder Bluff in the original game?", a = { "Cairne Bloodhoof", "Baine Bloodhoof", "Hamuul Runetotem", "Magatha Grimtotem" } },
    { q = "Who leads the Forsaken from the Undercity?", a = { "Sylvanas Windrunner", "Varimathras", "Putress", "Alleria Windrunner" } },
    { q = "Who is the King of Ironforge in the original game?", a = { "Magni Bronzebeard", "Muradin Bronzebeard", "Brann Bronzebeard", "Falstad Wildhammer" } },
    { q = "Who is the High Priestess of Elune who leads the night elves?", a = { "Tyrande Whisperwind", "Maiev Shadowsong", "Shandris Feathermoon", "Jaina Proudmoore" } },
    { q = "Who rules Theramore Isle?", a = { "Jaina Proudmoore", "Tyrande Whisperwind", "Bolvar Fordragon", "Lady Katrana Prestor" } },
    { q = "Which boy king sits on Stormwind's throne in the original game?", a = { "Anduin Wrynn", "Varian Wrynn", "Llane Wrynn", "Arthas Menethil" } },
    { q = "The Horde's Durotar is named after which orc?", a = { "Durotan", "Doomhammer", "Drek'Thar", "Draka" } },
    { q = "Thrall was born into which orc clan?", a = { "Frostwolf", "Warsong", "Blackrock", "Dragonmaw" } },
    { q = "Which hammer does Thrall carry?", a = { "Doomhammer", "Gorehowl", "Sulfuras", "Ashbringer" } },
    { q = "Which pit lord did Grom Hellscream slay?", a = { "Mannoroth", "Magtheridon", "Azgalor", "Kazzak" } },
    { q = "What is the name of the orc homeworld?", a = { "Draenor", "Argus", "Azeroth", "Xoroth" } },
    { q = "Which prince of Lordaeron took up the runeblade Frostmourne?", a = { "Arthas Menethil", "Kael'thas Sunstrider", "Anduin Wrynn", "Varian Wrynn" } },
    { q = "Which paladin trained Prince Arthas?", a = { "Uther the Lightbringer", "Tirion Fordring", "Turalyon", "Alexandros Mograine" } },
    { q = "Which orc shaman's spirit became the Lich King?", a = { "Ner'zhul", "Gul'dan", "Kilrogg", "Zuluhed" } },
    { q = "The Ashbringer was first wielded by which paladin?", a = { "Alexandros Mograine", "Tirion Fordring", "Uther the Lightbringer", "Saidan Dathrohan" } },
    { q = "Who was the twin brother of Illidan Stormrage?", a = { "Malfurion Stormrage", "Fandral Staghelm", "Cenarius", "Xavius" } },
    { q = "Which goddess do the night elves worship?", a = { "Elune", "The Earth Mother", "Eonar", "Aman'Thul" } },
    { q = "What great whirlpool formed when the Well of Eternity imploded?", a = { "The Maelstrom", "The Great Sea", "The Twisting Nether", "The Emerald Dream" } },
    { q = "Who is the dark titan who leads the Burning Legion?", a = { "Sargeras", "Archimonde", "Kil'jaeden", "Mannoroth" } },
    { q = "Which order of mages rules Dalaran?", a = { "The Kirin Tor", "The Council of Tirisfal", "The Scarlet Crusade", "The Argent Dawn" } },
    { q = "Who was Medivh's apprentice?", a = { "Khadgar", "Antonidas", "Rhonin", "Kel'Thuzad" } },
    { q = "Which dwarf clan rides gryphons out of Aerie Peak?", a = { "Wildhammer", "Bronzebeard", "Dark Iron", "Frostborn" } },
    { q = "Which race lives in Timbermaw Hold?", a = { "Furbolgs", "Satyrs", "Centaur", "Gnolls" } },
    { q = "Which faction sits at Light's Hope Chapel fighting the Scourge?", a = { "Argent Dawn", "Scarlet Crusade", "Cenarion Circle", "Brood of Nozdormu" } },
    { q = "Booty Bay, Gadgetzan, Ratchet and Everlook belong to which goblin cartel?", a = { "Steamwheedle Cartel", "Venture Company", "Bilgewater Cartel", "Blackwater Raiders" } },
    { q = "Which pirates harass Booty Bay?", a = { "Bloodsail Buccaneers", "Defias Brotherhood", "Southsea Freebooters", "Blackwater Raiders" } },
    { q = "Booty Bay is found in which zone?", a = { "Stranglethorn Vale", "Tanaris", "The Barrens", "Swamp of Sorrows" } },
    { q = "The Crossroads is found in which zone?", a = { "The Barrens", "Durotar", "Mulgore", "Ashenvale" } },
    { q = "Which zone is famous for its devilsaurs?", a = { "Un'Goro Crater", "Stranglethorn Vale", "Feralas", "Silithus" } },
    { q = "Which zone holds the Dark Portal in the original game?", a = { "Blasted Lands", "Swamp of Sorrows", "Burning Steppes", "Badlands" } },
    { q = "What is the name of Thrall's hall in Orgrimmar?", a = { "Grommash Hold", "Hall of Legends", "Valley of Honor", "Blackrock Keep" } },
    { q = "What lies at the center of Ironforge?", a = { "The Great Forge", "The Mystic Ward", "The Hall of Explorers", "The Military Ward" } },
    { q = "Which train connects Stormwind and Ironforge?", a = { "The Deeprun Tram", "The Ironforge Express", "The Gnomish Rail", "The Stonewrought Line" } },
    { q = "Horde zeppelins from Orgrimmar fly to Tirisfal Glades and where else?", a = { "Grom'gol Base Camp", "Booty Bay", "Ratchet", "Kargath" } },
    { q = "Night elf flight masters offer rides on which creature?", a = { "Hippogryphs", "Gryphons", "Wind riders", "Bats" } },
    { q = "Which racial mount do trolls ride?", a = { "Raptors", "Wolves", "Kodos", "Tigers" } },
    { q = "At what level could players first ride a mount in the original game?", a = { "40", "30", "20", "50" } },
    { q = "What is the level cap of the original game?", a = { "60", "50", "70", "65" } },
    { q = "At what level did characters get their first talent point in the original game?", a = { "10", "5", "15", "20" } },
    { q = "How many silver make one gold?", a = { "100", "10", "1000", "50" } },
    { q = "In the original game, shamans were only available to which faction?", a = { "Horde", "Alliance", "Both factions", "Neither faction" } },
    { q = "Which Alliance race could be a paladin in the original game?", a = { "Dwarf", "Gnome", "Night Elf", "None of them" } },
    { q = "Which Horde race could be a druid in the original game?", a = { "Tauren", "Troll", "Orc", "Undead" } },
    { q = "Which of these classes could a gnome play in the original game?", a = { "Warlock", "Priest", "Hunter", "Paladin" } },
    { q = "Which racial ability belongs to the Forsaken?", a = { "Will of the Forsaken", "Stoneform", "War Stomp", "Shadowmeld" } },
    { q = "Which racial ability belongs to the tauren?", a = { "War Stomp", "Berserking", "Blood Fury", "Escape Artist" } },
    { q = "Which demon is the first a warlock learns to summon?", a = { "Imp", "Voidwalker", "Succubus", "Felhunter" } },
    { q = "Which epic mount can warlocks summon?", a = { "Dreadsteed", "Charger", "Deathcharger", "Nightmare" } },
    { q = "Which class collects Soul Shards?", a = { "Warlock", "Priest", "Mage", "Shaman" } },
    { q = "Which spell returns a shaman to their Hearthstone location?", a = { "Astral Recall", "Ghost Wolf", "Far Sight", "Reincarnation" } },
    { q = "Warriors learn Defensive Stance, Berserker Stance and which other stance?", a = { "Battle Stance", "Arms Stance", "Fury Stance", "Guardian Stance" } },
    { q = "What does a mage's basic Polymorph turn the target into?", a = { "A sheep", "A frog", "A chicken", "A rabbit" } },
    { q = "Which set is the warrior Tier 2 set?", a = { "Battlegear of Wrath", "Battlegear of Might", "Dreadnaught's Battlegear", "Battlegear of Valor" } },
    { q = "Which profession crafts the Arcanite Reaper?", a = { "Blacksmithing", "Engineering", "Leatherworking", "Enchanting" } },
    { q = "Which profession transmutes Arcanite Bars?", a = { "Alchemy", "Blacksmithing", "Mining", "Enchanting" } },
    { q = "Engineers choose between Goblin and which other specialization?", a = { "Gnomish", "Dwarven", "Titan", "Mechano" } },
    { q = "Which profession turns cloth into bandages?", a = { "First Aid", "Tailoring", "Alchemy", "Cooking" } },
    { q = "What is the highest-level ore in the original game?", a = { "Thorium", "Mithril", "Truesilver", "Dark Iron" } },
    { q = "Which rare herb does every original-game flask need?", a = { "Black Lotus", "Dreamfoil", "Mountain Silversage", "Plaguebloom" } },
    { q = "Which famous fisherman can be found in Dustwallow Marsh?", a = { "Nat Pagle", "Hemet Nesingwary", "Old Man Heming", "Kah Mistrunner" } },
    { q = "Which hunter runs the big game hunting camp in Stranglethorn Vale?", a = { "Hemet Nesingwary", "Nat Pagle", "Baron Revilgaz", "Krazek" } },
    { q = "Who runs the Darkmoon Faire?", a = { "Silas Darkmoon", "Sayge", "Flik", "Lhara" } },
    { q = "Turning in Onyxia's head grants which world buff?", a = { "Rallying Cry of the Dragonslayer", "Warchief's Blessing", "Spirit of Zandalar", "Songflower Serenade" } },
    { q = "Who is the Horde general in Alterac Valley?", a = { "Drek'Thar", "Vanndar Stormpike", "Rexxar", "Nazgrel" } },
    { q = "What is the objective of Warsong Gulch?", a = { "Capture the enemy flag", "Hold five bases", "Kill the enemy general", "Destroy the enemy gates" } },
    { q = "What is the highest Horde PvP rank in the original game?", a = { "High Warlord", "Warlord", "Grand Marshal", "Overlord" } },
    { q = "Which town's world PvP rivalry with Southshore is legendary?", a = { "Tarren Mill", "Hammerfall", "Brill", "The Sepulcher" } },
    { q = "What kind of creature is Hogger?", a = { "A gnoll", "A kobold", "A murloc", "A worgen" } },
    { q = "In which zone does Hogger terrorize new players?", a = { "Elwynn Forest", "Westfall", "Duskwood", "Redridge Mountains" } },
    { q = "Which creatures warn you 'You no take candle!'?", a = { "Kobolds", "Gnolls", "Troggs", "Murlocs" } },
    { q = "Which creature is famous for its gurgling 'Mrglglglgl' cry?", a = { "Murloc", "Naga", "Makrura", "Kobold" } },
    { q = "Which Deadmines boss is a murloc cook?", a = { "Cookie", "Gilnid", "Sneed", "Rhahk'Zor" } },
    { q = "Which abomination famously stomps into Darkshire?", a = { "Stitches", "Patchwerk", "Gluth", "Ramstein" } },
    { q = "What is Mankrik asking players to find?", a = { "His wife", "His son", "His axe", "His wolf" } },
    { q = "'Where is Mankrik's wife?' echoed endlessly in which zone's chat?", a = { "The Barrens", "Durotar", "Stranglethorn Vale", "Ashenvale" } },
    { q = "Barrens chat was famous for jokes about which action star?", a = { "Chuck Norris", "Arnold Schwarzenegger", "Jackie Chan", "Bruce Willis" } },
    { q = "In which dungeon did Leeroy Jenkins make his famous charge?", a = { "Upper Blackrock Spire", "Molten Core", "Stratholme", "Zul'Gurub" } },
    { q = "What class was Leeroy Jenkins?", a = { "Paladin", "Warrior", "Rogue", "Hunter" } },
    { q = "What was the name of Leeroy Jenkins' guild?", a = { "PALS FOR LIFE", "Nihilum", "Death and Taxes", "Elitist Jerks" } },
    { q = "What did Leeroy's group get swarmed by?", a = { "Dragon whelps", "Spiders", "Murlocs", "Skeletons" } },
    { q = "What did Leeroy say he had, after the wipe?", a = { "Chicken", "Pizza", "The loot", "A soulstone" } },
    { q = "What survival chance did the group work out before Leeroy ran in?", a = { "32.33, repeating", "50-50", "12.5 percent", "0.01 percent" } },
    { q = "What did Leeroy shout as he ran in?", a = { "His own name", "For the Alliance!", "Charge!", "Pull!" } },
    { q = "In the famous Onyxia wipe audio, what does the raid leader demand?", a = { "More DOTs", "More healing", "More threat", "More mana" } },
    { q = "Which Onyxia wipe line follows 'Many whelps!'?", a = { "Handle it!", "Run away!", "Kill them!", "Stack up!" } },
    { q = "How much DKP was docked in the famous Onyxia wipe audio?", a = { "50 DKP", "10 DKP", "100 DKP", "500 DKP" } },
    { q = "Which Onyxia ability is infamous for wiping raids?", a = { "Deep Breath", "Tail Sweep", "Wing Buffet", "Fireball" } },
    { q = "The Corrupted Blood plague escaped from which raid?", a = { "Zul'Gurub", "Molten Core", "Naxxramas", "Blackwing Lair" } },
    { q = "The Corrupted Blood plague mostly escaped the raid on what?", a = { "Hunter pets", "Mailed letters", "Flying mounts", "Guild banners" } },
    { q = "Doing /chicken at a chicken enough times can start which quest?", a = { "CLUCK!", "Chicken Run", "Egg Hunt", "Poultry Problems" } },
    { q = "Which race's peons answer with 'Zug zug'?", a = { "Orcs", "Trolls", "Tauren", "Goblins" } },
    { q = "What does the orcish cry 'Lok'tar ogar' mean?", a = { "Victory or death", "Blood and thunder", "For the Horde", "Strength and honor" } },
    { q = "Which famous villain warns 'You are not prepared!'?", a = { "Illidan Stormrage", "Arthas Menethil", "Kel'Thuzad", "Ragnaros" } },
    { q = "What do night elves turn into when they die?", a = { "A wisp", "A ghost owl", "A spirit wolf", "A shade" } },
    { q = "What debuff comes with taking the spirit healer's resurrection?", a = { "Resurrection Sickness", "Weakened Soul", "Forbearance", "Recently Bandaged" } },
    { q = "What is a 'corpse run'?", a = { "Running back to your body", "A timed raid clear", "Fleeing a fight to live", "A speed-leveling route" } },
    { q = "What does 'OOM' mean in group chat?", a = { "Out of mana", "Out of mobs", "Only one more", "Out of money" } },
    { q = "What does 'LFM' mean in chat?", a = { "Looking for more", "Leaving for maintenance", "Loot for me", "Last free mount" } },
    { q = "What does 'LFG' mean in chat?", a = { "Looking for group", "Loot for guild", "Leveling fast guide", "Last flight gone" } },
    { q = "What does 'WTS' mean in trade chat?", a = { "Want to sell", "Want to swap", "Where to start", "Wait the stack" } },
    { q = "What does 'DKP' stand for?", a = { "Dragon Kill Points", "Damage Kill Points", "Dungeon Key Pass", "Dwarf King Points" } },
    { q = "What does 'DoT' stand for?", a = { "Damage over time", "Death on target", "Duration of taunt", "Damage on tank" } },
    { q = "What does 'HoT' stand for?", a = { "Heal over time", "Hit on target", "Hold on tank", "Health of team" } },
    { q = "What does 'AFK' mean?", a = { "Away from keyboard", "Always fight kobolds", "Ask for kills", "Auto-follow key" } },
    { q = "What does 'BRB' mean?", a = { "Be right back", "Bring right buffs", "Big raid boss", "Bank run break" } },
    { q = "What does 'inc' warn the group about?", a = { "Enemies incoming", "Income from loot", "An incomplete quest", "A slow internet link" } },
    { q = "What does 'LoS' mean to a healer?", a = { "Line of sight", "Loss of spirit", "Lots of shields", "Lord of shadows" } },
    { q = "What does 'CC' mean in a dungeon?", a = { "Crowd control", "Critical chance", "Combat call", "Cloth caster" } },
    { q = "What does 'aggro' mean?", a = { "A mob's hostile attention", "A rogue's opener", "A raid's loot rules", "A grumpy guild leader" } },
    { q = "What is a 'ninja looter'?", a = { "Someone who steals loot", "A rogue who loots in stealth", "A fast vendor seller", "The raid's loot master" } },
    { q = "What does it mean when a group 'wipes'?", a = { "Everyone died", "The boss was one-shot", "The loot was all trash", "The group disbanded" } },
    { q = "What is a 'gank'?", a = { "Killing a far weaker player", "A fair duel", "Sharing a quest mob", "A guild recruitment post" } },
    { q = "What is a 'twink'?", a = { "A low-level alt in top gear", "A level 60 in quest gear", "A pet with no talents", "A mage who only uses frost" } },
    { q = "What does it mean to 'pull' in a dungeon?", a = { "Start a fight with mobs", "Leave the group", "Skip a boss", "Give out loot" } },
    { q = "What does 'GG' mean at the end of a match?", a = { "Good game", "Great gear", "Go ganking", "Group gone" } },
}
