-------------------------------------------------------------------------------
--  NaowhForever_TownMailboxes.lua -- mailboxes on the town map, by world map, from
--  Wowhead Forever. Generated by Tools/build_mailboxes.py; do not edit by hand.
--
--  [uiMapID] = { { x, y, "mail", name, title, class, factions }, ... }, as NaowhForever_TownData.lua
--  lists its NPCs. x and y are map percentages; every mailbox serves both factions.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.TownMailboxes = {
    [1411] = {
        { 51.8, 42, "mail", "Mailbox", "", nil, "AH" },
    },
    [1412] = {
        { 33.7, 21.9, "mail", "Mailbox", "", nil, "AH" },
        { 46.2, 63.5, "mail", "Mailbox", "", nil, "AH" },
        { 47, 60.3, "mail", "Mailbox", "", nil, "AH" },
    },
    [1413] = {
        { 45.1, 58.7, "mail", "Mailbox", "", nil, "AH" },
        { 52, 30.4, "mail", "Mailbox", "", nil, "AH" },
        { 62.2, 39.2, "mail", "Mailbox", "", nil, "AH" },
    },
    [1416] = {
        { 12.8, 52.5, "mail", "Mailbox", "", nil, "AH" },
        { 14.1, 68.2, "mail", "Mailbox", "", nil, "AH" },
        { 17.9, 71.4, "mail", "Mailbox", "", nil, "AH" },
        { 18.3, 64.7, "mail", "Mailbox", "", nil, "AH" },
        { 18.5, 61.6, "mail", "Mailbox", "", nil, "AH" },
        { 19.2, 73.9, "mail", "Mailbox", "", nil, "AH" },
    },
    [1417] = {
        { 73.8, 33.1, "mail", "Mailbox", "", nil, "AH" },
    },
    [1418] = {
        { 4, 47.4, "mail", "Mailbox", "", nil, "AH" },
    },
    [1419] = {
        { 64, 19.3, "mail", "Mailbox", "", nil, "AH" },
    },
    [1420] = {
        { 61.5, 53, "mail", "Mailbox", "", nil, "AH" },
    },
    [1421] = {
        { 43.4, 41.5, "mail", "Mailbox", "", nil, "AH" },
    },
    [1423] = {
        { 71.3, 49, "mail", "Mailbox", "", nil, "AH" },
        { 80.9, 58.5, "mail", "Mailbox", "", nil, "AH" },
    },
    [1424] = {
        { 50.4, 58.6, "mail", "Mailbox", "", nil, "AH" },
        { 62.5, 19.7, "mail", "Mailbox", "", nil, "AH" },
    },
    [1425] = {
        { 14.1, 45.7, "mail", "Mailbox", "", nil, "AH" },
        { 78.9, 80.4, "mail", "Mailbox", "", nil, "AH" },
    },
    [1426] = {
        { 47, 52.5, "mail", "Mailbox", "", nil, "AH" },
    },
    [1429] = {
        { 43, 65.5, "mail", "Mailbox", "", nil, "AH" },
    },
    [1431] = {
        { 73.8, 46.1, "mail", "Mailbox", "", nil, "AH" },
    },
    [1432] = {
        { 34.9, 47.6, "mail", "Mailbox", "", nil, "AH" },
    },
    [1433] = {
        { 21.5, 46.5, "mail", "Mailbox", "", nil, "AH" },
        { 26.4, 46.5, "mail", "Mailbox", "", nil, "AH" },
    },
    [1434] = {
        { 26.9, 76.9, "mail", "Mailbox", "", nil, "AH" },
        { 32.5, 28.7, "mail", "Mailbox", "", nil, "AH" },
    },
    [1435] = {
        { 45.5, 54.9, "mail", "Mailbox", "", nil, "AH" },
    },
    [1436] = {
        { 53, 53.4, "mail", "Mailbox", "", nil, "AH" },
    },
    [1437] = {
        { 10.8, 59.8, "mail", "Mailbox", "", nil, "AH" },
    },
    [1438] = {
        { 56.1, 58.4, "mail", "Mailbox", "", nil, "AH" },
    },
    [1439] = {
        { 37.3, 43.8, "mail", "Mailbox", "", nil, "AH" },
    },
    [1440] = {
        { 36.3, 50.3, "mail", "Mailbox", "", nil, "AH" },
        { 73.6, 61, "mail", "Mailbox", "", nil, "AH" },
    },
    [1441] = {
        { 45.8, 51, "mail", "Mailbox", "", nil, "AH" },
    },
    [1442] = {
        { 36, 7.4, "mail", "Mailbox", "", nil, "AH" },
        { 48, 61, "mail", "Mailbox", "", nil, "AH" },
    },
    [1443] = {
        { 24.8, 68.9, "mail", "Mailbox", "", nil, "AH" },
        { 65.4, 6.9, "mail", "Mailbox", "", nil, "AH" },
    },
    [1444] = {
        { 31.2, 43.8, "mail", "Mailbox", "", nil, "AH" },
        { 74.9, 44, "mail", "Mailbox", "", nil, "AH" },
    },
    [1445] = {
        { 66, 45.4, "mail", "Mailbox", "", nil, "AH" },
    },
    [1446] = {
        { 52.3, 27.8, "mail", "Mailbox", "", nil, "AH" },
    },
    [1451] = {
        { 51.6, 38, "mail", "Mailbox", "", nil, "AH" },
    },
    [1452] = {
        { 61.2, 38.6, "mail", "Mailbox", "", nil, "AH" },
    },
    [1453] = {
        { 22.2, 57.5, "mail", "Mailbox", "", nil, "AH" },
        { 30.3, 49.5, "mail", "Mailbox", "", nil, "AH" },
        { 36.8, 68.8, "mail", "Mailbox", "", nil, "AH" },
        { 39.9, 84.3, "mail", "Mailbox", "", nil, "AH" },
        { 40.8, 62.5, "mail", "Mailbox", "", nil, "AH" },
        { 45.6, 54.5, "mail", "Mailbox", "", nil, "AH" },
        { 50.1, 88.1, "mail", "Mailbox", "", nil, "AH" },
        { 50.8, 71.1, "mail", "Mailbox", "", nil, "AH" },
        { 54.5, 66.5, "mail", "Mailbox", "", nil, "AH" },
        { 54.6, 63, "mail", "Mailbox", "", nil, "AH" },
        { 54.9, 57.4, "mail", "Mailbox", "", nil, "AH" },
        { 57.4, 72.1, "mail", "Mailbox", "", nil, "AH" },
        { 61, 50.4, "mail", "Mailbox", "", nil, "AH" },
        { 61.5, 44.1, "mail", "Mailbox", "", nil, "AH" },
        { 61.9, 72.8, "mail", "Mailbox", "", nil, "AH" },
        { 64.5, 37.5, "mail", "Mailbox", "", nil, "AH" },
        { 66.6, 64.5, "mail", "Mailbox", "", nil, "AH" },
        { 67.4, 50.2, "mail", "Mailbox", "", nil, "AH" },
        { 70.9, 40.4, "mail", "Mailbox", "", nil, "AH" },
        { 72.4, 69.2, "mail", "Mailbox", "", nil, "AH" },
        { 72.5, 48.5, "mail", "Mailbox", "", nil, "AH" },
        { 74.5, 55.6, "mail", "Mailbox", "", nil, "AH" },
        { 75.9, 64.1, "mail", "Mailbox", "", nil, "AH" },
    },
    [1454] = {
        { 38.3, 74.6, "mail", "Mailbox", "", nil, "AH" },
        { 45.2, 54.4, "mail", "Mailbox", "", nil, "AH" },
        { 48.4, 37.3, "mail", "Mailbox", "", nil, "AH" },
        { 50.2, 70.8, "mail", "Mailbox", "", nil, "AH" },
        { 51.6, 46.7, "mail", "Mailbox", "", nil, "AH" },
        { 51.7, 59.1, "mail", "Mailbox", "", nil, "AH" },
        { 53.4, 65.6, "mail", "Mailbox", "", nil, "AH" },
        { 60.5, 55.4, "mail", "Mailbox", "", nil, "AH" },
        { 62.3, 40.3, "mail", "Mailbox", "", nil, "AH" },
        { 81.2, 21.4, "mail", "Mailbox", "", nil, "AH" },
    },
    [1455] = {
        { 21.2, 52.7, "mail", "Mailbox", "", nil, "AH" },
        { 33, 65, "mail", "Mailbox", "", nil, "AH" },
        { 70.9, 72.2, "mail", "Mailbox", "", nil, "AH" },
        { 72.2, 49.2, "mail", "Mailbox", "", nil, "AH" },
    },
    [1456] = {
        { 45, 59.4, "mail", "Mailbox", "", nil, "AH" },
    },
    [1457] = {
        { 41.6, 42.1, "mail", "Mailbox", "", nil, "AH" },
    },
    [1458] = {
        { 62.2, 51.7, "mail", "Mailbox", "", nil, "AH" },
        { 62.4, 36.3, "mail", "Mailbox", "", nil, "AH" },
        { 68.4, 50.6, "mail", "Mailbox", "", nil, "AH" },
        { 68.5, 37.7, "mail", "Mailbox", "", nil, "AH" },
        { 71.5, 62, "mail", "Mailbox", "", nil, "AH" },
    },
    [2482] = {
        { 69.3, 47.5, "mail", "Mailbox", "", nil, "AH" },
        { 70.8, 49.8, "mail", "Mailbox", "", nil, "AH" },
    },
    [2521] = {
        { 43.4, 44.1, "mail", "Mailbox", "", nil, "AH" },
        { 58.2, 76.4, "mail", "Mailbox", "", nil, "AH" },
        { 62.2, 73.6, "mail", "Mailbox", "", nil, "AH" },
    },
    [2548] = {
        { 58.8, 45.4, "mail", "Mailbox", "", nil, "AH" },
        { 64.5, 83.5, "mail", "Mailbox", "", nil, "AH" },
        { 78.6, 53.8, "mail", "Mailbox", "", nil, "AH" },
    },
}
