-------------------------------------------------------------------------------
--  NaowhForever_ZoneExits.lua -- the roads out of each zone, as clickable arrows on the town
--  map, from the game's map art for build 1.60.1.70205. Generated by Tools/build_zone_exits.py;
--  do not edit by hand.
--
--  [uiMapID] = { { x, y, rotation, the uiMapID it leads to }, ... }. x and y are map
--  percentages, rotation is in radians, anticlockwise from pointing up.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.ZoneExits = {
    [1411] = {
        { 34.3, 41.9, 1.50, 1413 },   -- The Barrens
        { 45.5, 9.5, 0.00, 1454 },   -- Orgrimmar
    },
    [1412] = {
        { 71.2, 61.8, -1.32, 1413 },   -- The Barrens
    },
    [1413] = {
        { 33.3, 29.4, 1.91, 1442 },   -- Stonetalon Mountains
        { 39.0, 58.6, 1.55, 1412 },   -- Mulgore
        { 44.0, 96.3, 2.92, 1441 },   -- Thousand Needles
        { 48.5, 3.0, 0.05, 1440 },   -- Ashenvale
        { 52.9, 79.7, -1.63, 1445 },   -- Dustwallow Marsh
        { 63.4, 19.0, -1.61, 1411 },   -- Durotar
    },
    [1416] = {
        { 23.0, 93.0, -3.14, 1424 },   -- Hillsbrad Foothills
        { 48.9, 97.1, 2.71, 1424 },   -- Hillsbrad Foothills
        { 80.0, 22.5, -0.05, 1422 },   -- Western Plaguelands
    },
    [1417] = {
        { 13.7, 47.5, 2.32, 1424 },   -- Hillsbrad Foothills
        { 45.0, 90.7, -3.10, 1437 },   -- Wetlands
        { 76.7, 23.2, -0.48, 1425 },   -- The Hinterlands
    },
    [1418] = {
        { 48.0, 5.7, -0.02, 1432 },   -- Loch Modan
    },
    [1419] = {
        { 52.5, 5.7, 0.12, 1435 },   -- Swamp of Sorrows
    },
    [1420] = {
        { 53.8, 80.4, 3.01, 1421 },   -- Silverpine Forest
        { 61.0, 71.0, 3.14, 1458 },   -- Undercity
        { 87.0, 69.2, -1.46, 1422 },   -- Western Plaguelands
    },
    [1421] = {
        { 56.7, 6.6, 0.20, 1420 },   -- Tirisfal Glades
        { 68.9, 78.4, -1.38, 1424 },   -- Hillsbrad Foothills
    },
    [1422] = {
        { 16.4, 56.8, 1.52, 1420 },   -- Tirisfal Glades
        { 41.7, 99.9, 1.20, 1416 },   -- Alterac Mountains
        { 68.3, 87.3, 3.00, 1425 },   -- The Hinterlands
        { 75.8, 52.4, -1.25, 1423 },   -- Eastern Plaguelands
    },
    [1423] = {
        { -0.0, 65.3, -3.01, 1422 },   -- Western Plaguelands
    },
    [1424] = {
        { 3.4, 44.2, 1.37, 1421 },   -- Silverpine Forest
        { 28.5, 28.0, 0.09, 1416 },   -- Alterac Mountains
        { 51.5, 30.8, 0.20, 1416 },   -- Alterac Mountains
        { 88.1, 31.0, -0.07, 1425 },   -- The Hinterlands
        { 90.2, 55.4, -2.38, 1417 },   -- Arathi Highlands
    },
    [1425] = {
        { 6.5, 63.2, -2.98, 1424 },   -- Hillsbrad Foothills
        { 24.2, 26.8, -0.19, 1422 },   -- Western Plaguelands
        { 54.6, 82.2, 1.99, 1417 },   -- Arathi Highlands
    },
    [1426] = {
        { 53.5, 35.0, 0.00, 1455 },   -- Ironforge
        { 86.7, 45.0, -0.86, 1432 },   -- Loch Modan
    },
    [1427] = {
        { 40.6, 99.6, 1.56, 1428 },   -- Burning Steppes
    },
    [1428] = {
        { 35.0, 24.4, -0.45, 1427 },   -- Searing Gorge
        { 77.2, 83.7, 2.92, 1433 },   -- Redridge Mountains
    },
    [1429] = {
        { 15.8, 81.2, 1.83, 1436 },   -- Westfall
        { 32.0, 50.0, 0.79, 1453 },   -- Stormwind City
        { 63.9, 91.4, 2.86, 1431 },   -- Duskwood
        { 96.3, 71.3, -1.09, 1433 },   -- Redridge Mountains
    },
    [1430] = {
        { 30.4, 35.1, 1.49, 1431 },   -- Duskwood
        { 60.5, 40.1, -1.41, 1435 },   -- Swamp of Sorrows
    },
    [1431] = {
        { 8.3, 62.9, 1.64, 1436 },   -- Westfall
        { 45.2, 91.6, -2.95, 1434 },   -- Stranglethorn Vale
        { 72.9, 15.1, -0.05, 1429 },   -- Elwynn Forest
        { 90.8, 46.1, -1.64, 1430 },   -- Deadwind Pass
    },
    [1432] = {
        { 20.0, 60.3, 0.03, 1426 },   -- Dun Morogh
        { 25.0, 6.6, 0.02, 1437 },   -- Wetlands
        { 45.5, 96.6, 2.83, 1418 },   -- Badlands
    },
    [1433] = {
        { 5.6, 91.1, -2.92, 1429 },   -- Elwynn Forest
        { 42.0, 4.0, -3.14, 1428 },   -- Burning Steppes
    },
    [1434] = {
        { 40.7, 0.1, -1.61, 1431 },   -- Duskwood
    },
    [1435] = {
        { 2.5, 56.6, 1.13, 1430 },   -- Deadwind Pass
        { 32.8, 78.5, 2.67, 1419 },   -- Blasted Lands
    },
    [1436] = {
        { 63.4, 21.3, -1.10, 1429 },   -- Elwynn Forest
        { 68.1, 61.2, -1.19, 1431 },   -- Duskwood
    },
    [1437] = {
        { 50.9, 8.8, 0.09, 1417 },   -- Arathi Highlands
        { 56.8, 78.9, 2.94, 1432 },   -- Loch Modan
    },
    [1438] = {
        { 31.0, 53.0, 1.57, 1457 },   -- Darnassus
    },
    [1439] = {
        { 42.6, 97.3, -2.66, 1440 },   -- Ashenvale
    },
    [1440] = {
        { 25.0, 12.7, 0.45, 1439 },   -- Darkshore
        { 41.3, 75.9, 2.89, 1442 },   -- Stonetalon Mountains
        { 55.5, 25.7, 0.30, 1448 },   -- Felwood
        { 68.0, 90.3, 3.14, 1413 },   -- The Barrens
        { 96.2, 48.5, -1.78, 1447 },   -- Azshara
    },
    [1441] = {
        { 9.0, 25.7, 1.81, 1444 },   -- Feralas
        { 31.4, 35.0, -3.14, 1413 },   -- The Barrens
        { 76.0, 95.5, -3.07, 1446 },   -- Tanaris
    },
    [1442] = {
        { 30.3, 82.6, -2.73, 1443 },   -- Desolace
        { 80.7, 36.1, -0.58, 1440 },   -- Ashenvale
        { 86.2, 92.3, -0.90, 1413 },   -- The Barrens
    },
    [1443] = {
        { 46.2, 96.2, -2.39, 1444 },   -- Feralas
        { 61.2, 3.2, -0.71, 1442 },   -- Stonetalon Mountains
    },
    [1444] = {
        { 45.4, 2.3, -0.77, 1443 },   -- Desolace
        { 90.2, 51.7, -3.01, 1441 },   -- Thousand Needles
    },
    [1445] = {
        { 26.9, 46.3, 1.37, 1413 },   -- The Barrens
    },
    [1446] = {
        { 23.3, 56.0, 1.59, 1449 },   -- Un'Goro Crater
        { 51.1, 17.9, 0.16, 1441 },   -- Thousand Needles
    },
    [1447] = {
        { 6.4, 73.5, 1.68, 1440 },   -- Ashenvale
    },
    [1448] = {
        { 58.9, 96.2, -2.37, 1440 },   -- Ashenvale
        { 69.0, 7.9, -1.61, 1452 },   -- Winterspring
    },
    [1449] = {
        { 21.3, 18.7, 0.96, 1451 },   -- Silithus
        { 61.8, 95.8, -3.06, 1446 },   -- Tanaris
    },
    [1451] = {
        { 77.8, 16.0, 0.51, 1449 },   -- Un'Goro Crater
    },
    [1452] = {
        { 27.7, 31.5, 0.31, 1448 },   -- Felwood
    },
}
