-- NaowhForever_QoL.lua: the QoL settings store (ns.QoLSettings) and its defaults, and ns.DisbandGroup.
local ns = _G.NaowhForever

local UI = ns.UI
local F = ns.FEATURES.qol

local TEXT_NO_GROUP = "You are not in a group."
local TEXT_NOT_LEADER = "Only the group leader can disband the group."
local TEXT_DISBAND = "Remove everyone from your group?"
local TEXT_IN_COMBAT = "The group can be disbanded once the fight is over."

local S = UI.ModuleSettings("qol", {
    enabled = F.enabled,
    deathRelease = F.deathRelease, deathReleaseHold = 1,
    stealthReminder = F.stealthReminder, formReminder = F.formReminder,
    reminderInGroup = false, reminderHideResting = true,
    stealthShowStealthed = true, stealthDruid = "cat",
    stealthText = "STEALTH", stealthColor = { r = 0, g = 1, b = 0 }, stealthClassColor = false,
    warningText = "RESTEALTH", warningColor = { r = 1, g = 0, b = 0 }, warningClassColor = false,
    stealthFont = "", stealthFontSize = 22, stealthOutline = "OUTLINE", stealthBackground = "none",
    formDruid = "none", formShadowform = false, formCombatOnly = false, formInstanceOnly = false,
    formText = "", formColor = { r = 1, g = 0.4, b = 0 }, formClassColor = false,
    formFont = "", formFontSize = 22, formOutline = "OUTLINE", formBackground = "none",
    formSound = false, formSoundKey = "none", formSoundInterval = 3,
    coTank = F.coTank, coTankName = true, coTankClassColor = true, coTankDebuffs = false,
    coTankWidth = 180, coTankHeight = 30,
    coTankColor = { r = 0, g = 0.8, b = 0.2 }, coTankBgAlpha = 0.6,
    coTankNameClassColor = false, coTankNameColor = { r = 1, g = 1, b = 1 },
    coTankNameLength = 0, coTankFont = "", coTankFontSize = 12, coTankOutline = "OUTLINE", coTankTexture = "",
    coTankAnchor = "UIParent", coTankX = 0, coTankY = 0,
    coTankDebuffFilter = "important", coTankDebuffCap = 3, coTankDebuffSize = 22,
    coTankDebuffSpacing = 2, coTankDebuffPosition = "top", coTankDebuffGrow = "CENTER",
    coTankDebuffX = 0, coTankDebuffY = 3,
    coTankDebuffDuration = true, coTankDebuffDurationSize = 10,
    coTankDebuffStacks = true, coTankDebuffStackSize = 10, coTankDebuffTooltips = false,

    deleteConfirm = F.deleteConfirm, lootConfirm = F.lootConfirm, enchantReplace = false,
    questAccept = F.questAccept, questTurnIn = F.questTurnIn, questGossip = F.questGossip, questRewardPicks = F.questRewardPicks,
    questSkipModifier = "ALT",
    groupButtons = F.groupButtons, groupButtonsLayout = "stacked", groupButtonsWidth = 90, groupButtonsHeight = 24,
    groupButtonsFont = "", groupButtonsFontSize = 12, groupButtonsOutline = "NONE", groupButtonsBackground = "card",
    questShare = F.questShare,
    combatTimer = F.combatTimer, combatTimerInstanceOnly = false, combatTimerChat = true,
    combatTimerSticky = false, combatTimerHidePrefix = false, combatTimerBackground = "none",
    combatTimerColor = { r = 1, g = 1, b = 1 }, combatTimerClassColor = false,
    combatTimerFont = "", combatTimerFontSize = 32, combatTimerOutline = "OUTLINE",
    cursorCooldown = F.cursorCooldown, cursorCooldownSize = 29, cursorCooldownTime = 0.75,
    combatLogger = F.combatLogger, combatLogRaids = "ask", combatLogDungeons = "never",
    combatLogStopOnLeave = true, combatLogChat = false, combatLogAclPrompt = true,
    globalCopy = F.globalCopy, copyTooltipIds = true, copyModifier = "CTRL-SHIFT", copyKey = "C", copyShortcutSynced = false,
    badgeChat = F.badgeChat, badgeCard = F.badgeCard, badgeTooltip = F.badgeTooltip,
    badgeBanner = F.badgeBanner, badgeBannerSkipGuild = true,
    tooltipDisplay = F.tooltipDisplay, tooltipSpellID = true, tooltipNPCID = true, tooltipItemID = true,
    tooltipRestricted = "hide", tooltipCopy = true, tooltipModifier = "CTRL-SHIFT", tooltipKey = "C",
    tooltipCopyFormat = "url", tooltipCopyHint = false,
    slashCommands = F.slashCommands,
    lootFeed = F.lootFeed, lootFeedMoney = true, lootFeedXP = false, lootFeedQuality = 1,
    lootFeedQuest = true, lootFeedRep = false,
    lootFeedCount = 6, lootFeedFade = 5, lootFeedStyle = "dark", lootFeedGlow = false,
    lootFeedValue = true, lootFeedBank = true, lootFeedPrice = "vendor", lootFeedGPH = false,
    hideLootWindow = F.hideLootWindow, fastLoot = F.fastLoot,
    lootFeedWidth = 340, lootFeedHeight = 36, lootFeedSpacing = -1, lootFeedGrowth = "up",
    lootFeedFont = "", lootFeedFontSize = 11, lootFeedOutline = "OUTLINE",
    lootFeedPos = { point = "CENTER", relPoint = "CENTER", x = -508, y = 322 },
    alertsPos = { point = "CENTER", relPoint = "CENTER", x = -519, y = 167 },
    ahPrices = F.ahPrices, ahTooltip = F.ahTooltip,
    altCounts = F.altCounts, mailAlts = F.mailAlts, mailQuickAttach = F.mailQuickAttach, mailExpiry = F.mailExpiry,
    xpTicker = F.xpTicker, xpTickerLevel = true, xpTickerElapsed = true,
    xpTickerHideResting = true, xpTickerFont = "", xpTickerFontSize = 24, xpTickerOutline = "",
    xpTickerSplits = true, xpTickerHistoryCount = 10, xpTickerBackground = "card",
    xpTickerPlayed = true, xpTickerPace = false, xpTickerSplitPlayed = true,
    xpTickerPos = { point = "CENTER", relPoint = "CENTER", x = -197, y = -322 },
    groupXP = F.groupXP, groupXPShowSelf = true, groupXPWidth = 260,
    groupXPFont = "", groupXPFontSize = 12, groupXPOutline = "OUTLINE", groupXPTexture = "", groupXPBgAlpha = 0.85,
    healerMana = F.healerMana, healerManaWhere = "instance", healerManaShowSelf = true, healerManaDrinking = true,
    healerManaWidth = 160, healerManaFont = "", healerManaFontSize = 12, healerManaOutline = "OUTLINE",
    healerManaBackground = "card",
    playerHistory = F.playerHistory, playerHistoryChats = true, playerHistoryDays = 90, playerNotesTooltip = true,
    naowhScore = F.naowhScore, naowhScoreTooltip = true, naowhScoreScan = true, naowhScoreNearby = true,
    naowhScoreCompare = "both",
    characterPanel = F.characterPanel,
    characterPanelSlotMarks = F.characterPanelSlotMarks, characterPanelLevels = true, characterPanelMarks = true,
    characterPanelEnchants = true, characterPanelScore = true, characterPanelBadge = true, characterPanelStats = "spec",
    characterPanelTookOver = false, characterPanelAsked = false,
    inspectPanel = F.inspectPanel, inspectPanelScore = true, inspectPanelBadge = true, inspectPanelShareBis = true,
    inspectPanelTookOver = false, inspectPanelAsked = false,
    groupInspect = F.groupInspect, groupInspectShare = F.groupInspectShare, groupInspectSort = "score", groupInspectView = "gear",
    groupInspectAlpha = 1,
    xpBar = F.xpBar, xpBarLeftText = "level", xpBarCenterText = "xp", xpBarRightText = "percent",
    xpBarTopLeft = "played", xpBarTopRight = "none", xpBarBottomLeft = "leveling",
    xpBarBottom = "none", xpBarBottomRight = "xphour", xpBarTop = "none", xpBarLeft = "none",
    xpBarRight = "none", xpBarIncomplete = false, xpBarMaxLevel = false,
    xpBarResetOnReload = false, xpBarWidth = 520, xpBarHeight = 26,
    xpBarFont = "", xpBarFontSize = 13, xpBarOutline = "OUTLINE", xpBarTexture = "", xpBarBgAlpha = 0.85,
    xpBarPos = { point = "CENTER", relPoint = "CENTER", x = 0, y = 480 },
    autoRepair = F.autoRepair, sellJunk = F.sellJunk,
    restock = F.restock, restockReagents = true, restockAmmo = true, restockAmmoTarget = 1000,
    restockFood = true, restockFoodBelow = 10, restockFoodMinLevel = 0, restockFoodMaxLevel = 60, restockVendor = true, restockBagsBelow = 4,
    restockBuy = false,
    restockFont = "", restockFontSize = 16, restockOutline = "OUTLINE", restockBackground = "none",
    foodBar = F.foodBar, foodBarSize = 36,
    bagSpace = F.bagSpace, bagSpaceCount = 4, bagSpaceSize = 36, bagSpaceGrow = "RIGHT",
    bagSpaceMaxQuality = 2, bagSpaceJunkFirst = false, bagSpaceAuction = true,
    bagSpaceProtect = true, bagSpaceFreeBelow = 0, bagSpaceHideCombat = true,
    bagSpaceOnFull = true, bagSpaceShowFree = true, bagSpaceStack = true, bagSpaceOldFirst = false,
    bagSpaceTipVendor = true, bagSpaceTipAuction = true, bagSpaceTipDelete = true, bagSpaceTipIgnore = true,
    bagSpacePrices = true, bagSpaceBackground = "card",
    bagSpaceFont = "", bagSpaceFontSize = 12, bagSpaceOutline = "",
    scrapMarker = F.scrapMarker, scrapMarkerVendor = "sell", scrapMarkerScope = "account", scrapMarkerShow = true,
    scrapMarkerProtect = true, scrapRuleWear = false, scrapRuleOld = false, scrapRuleLevels = 10,
    townCapitalsOnly = true, townSpiritHealers = true, townZoneLinks = true,
    townMap = F.townMap, townClass = true, townProfession = true, townFlight = true, townInn = true,
    townBank = true, townStable = false, townRepair = true, townSupplies = true,
    townVendors = false, townMail = true, townPinSize = 16, townMinimap = true, townTravel = false,
    mapUnexplored = F.mapUnexplored, mapUnexploredDark = 0.5,
    mapSkyborne = F.mapSkyborne, mapSkyborneSize = 20,
    gearSets = F.gearSets, gearBarVisible = F.gearBarVisible, trinketBar = F.trinketBar, trinketSize = 36, trinketSpacing = 4, gearBarSize = 32, gearMounted = "", gearResting = "",
    gearWindowAlpha = 1, gearBarSpacing = 4, gearBarShow = "always",
    gearPos = { point = "CENTER", relPoint = "CENTER", x = -403, y = -379 },
    bis = F.bis, bisTooltip = true, bisBagMarks = true, bisBagLevels = true, bisLootAlert = F.bisLootAlert, bisWindowAlpha = 1,
    bisAlertFor = "all", bisAlertChat = true, bisAlertBadge = true, bisToast = true,
    bisDropSound = "game:raidwarning", bisYoursSound = "game:epicloot",
    bisToastScale = 1, bisToastTime = 6, bisToastAlpha = 0.95, bisToastGlow = true, bisToastStar = "icon",
    bisToastBorder = "rank", bisToastEvent = true, bisToastRank = true, bisToastSlot = true,
    bisToastSource = false, bisToastGain = true, bisToastFont = "", bisToastFontSize = 13, bisToastOutline = "NONE",
    bisToastPos = { point = "CENTER", relPoint = "CENTER", x = -9, y = 393 },
    blessings = F.blessings, blessSpacing = 6, blessGroupSpacing = 6, blessTimerSize = 14, blessShowLabels = true, blessBarSize = 30, blessTimers = true, blessShowAura = true,
    blessShowFury = false, blessWindowAlpha = 1, blessFont = "", blessOutline = "OUTLINE", blessThemeColors = false,
    blessLabelStyle = "name",
    blessLayout = "horizontal",

    durability = F.durability, durabilityBelow = 14, durabilityFont = "",
    durabilityFontSize = 22, durabilityOutline = "OUTLINE", durabilityBackground = "none", durabilityTheme = false,
    talentPoints = F.talentPoints, talentPointsFont = "",
    talentPointsFontSize = 22, talentPointsOutline = "OUTLINE", talentPointsBackground = "none",
    talentPointsTheme = false,
    buffThanks = F.buffThanks, buffThanksCooldown = 10, buffThanksGroup = false, buffThanksEmote = false,
    buffThanksText = "Thanks for the {buff}, fellow traveler!\nMuch appreciated, {name}, thanks for the {buff}!",
    buffThanksEmoteText = "thanks a kind stranger for the {buff}.\nappreciates the {buff}, it will be put to good use.",
    buffThanksPerBuff = false,
    buffThanksIntellect = "Thanks for the {buff}! I feel smarter already.\nThanks for the {buff}, {name}, my brain thanks you!\nIQ is rising, thank you for the {buff}, {name}!",
    buffThanksStamina = "Thanks for the {buff}! Feeling tougher already.\nThanks for the {buff}, {name}, I will put that health to good use!\nThanks for the {buff}, {name}, this will keep me safe!",
    buffThanksSpirit = "Thanks for the {buff}, {name}, my mana thanks you!\nSpirits be with you as well, {name}!",
    buffThanksShadow = "Thanks for the {buff}, {name}! The shadows cannot touch me now.\nShadows begone! Thank you, {name}!",
    buffThanksWild = "Thanks for the {buff}! Nature thanks you too.\nThanks for the {buff}, {name}, feeling wild!\nThanks for the {buff}, {name}, I am one with nature now!",
    buffThanksThorns = "Thanks for the {buff}, {name}! Anything that hits me will regret it.\nThanks for the {buff}, {name}! They will think twice before attacking.",
    buffThanksBlessing = "Thanks for the {buff}, {name}! The Light be with you.\nThanks for the blessing, {name}!\nWell met, {name}! Righteousness follows thanks to your {buff}.",
    combatAlert = F.combatAlert,
    combatEnterText = "+Combat", combatEnterColor = { r = 0, g = 1, b = 0 },
    combatEnterClassColor = false,
    combatLeaveText = "-Combat", combatLeaveColor = { r = 1, g = 0, b = 0 },
    combatLeaveClassColor = false,
    combatAlertFont = "", combatAlertFontSize = 32, combatAlertOutline = "OUTLINE", combatAlertBackground = "none",
    combatAlertPos = { point = "CENTER", relPoint = "CENTER", x = 0, y = 151 },
    combatEnterAudio = "none", combatEnterSound = "voice:combat", combatEnterSpeech = "Combat",
    combatLeaveAudio = "none", combatLeaveSound = "voice:safe", combatLeaveSpeech = "Safe",
    combatEnterVoice = "", combatEnterVolume = 50, combatEnterRate = 0,
    combatLeaveVoice = "", combatLeaveVolume = 50, combatLeaveRate = 0,

    hideErrors = F.hideErrors, hideTutorials = F.hideTutorials, hideScreenshot = F.hideScreenshot,
    skipCinematics = F.skipCinematics,
    hideAlerts = F.hideAlerts, hideEventToasts = F.hideEventToasts, hideZoneText = F.hideZoneText,
    cursorClip = F.cursorClip,
    crosshair = F.crosshair, crossSize = 20, crossThickness = 2, crossGap = 6,
    crossColor = { r = 0, g = 1, b = 0 }, crossClassColor = false, crossOpacity = 0.8,
    crossX = 0, crossY = 0, crossCombatOnly = false, crossHideMounted = false,
    crossTop = true, crossRight = true, crossBottom = true, crossLeft = true,
    crossDot = false, crossDotSize = 2,
    crossOutline = true, crossOutlineWeight = 1, crossOutlineColor = { r = 0, g = 0, b = 0 },
    crossCircle = false, crossCircleSize = 30, crossCircleColor = { r = 0, g = 1, b = 0 },
    crossMelee = false, crossMeleeColor = { r = 1, g = 0, b = 0 }, crossMeleeBorder = true,
    crossMeleeArms = false, crossMeleeDot = false, crossMeleeCircle = false,
    crossMeleeSound = false, crossMeleeSoundKey = "none", crossMeleeSoundInterval = 3,
    crossMeleeSpell = 0,

    petTracker = F.petTracker, petPassive = true, petLowHealth = false, petLowHealthBelow = 25,
    petInstanceOnly = false, petCombatOnly = false, petHideMounted = true, petShowIcon = true,
    petColor = { r = 1, g = 0, b = 0 }, petClassColor = false, petFont = "", petFontSize = 20,
    petOutline = "OUTLINE", petBackground = "none",
    petMissingText = "Pet Missing", petPassiveText = "Pet Passive", petLowHealthText = "Pet Low HP",
    equipReminder = F.equipReminder, equipOnInstance = true, equipOnReadyCheck = true, equipAutoHide = 10,
    equipIconSize = 40, equipEnchants = true, equipEnchantRules = {},
    autoEmote = F.autoEmote, autoEmoteCooldown = 2, autoEmoteList = "698: prepares a ritual of summoning",
    chatZones = F.chatZones, chatZonesLevel = true, chatZonesClassColour = true, chatZonesFinder = true, chatZonesWhere = true, chatZonesMaxAge = 15, chatZonesAsk = true, chatZonesShare = false,

    mouseRing = F.mouseRing, mouseShape = "ring.tga", mouseSize = 48,
    mouseColor = { r = 1, g = 0.66, b = 0 }, mouseClassColor = false,
    mouseShowOOC = true, mouseOpacityCombat = 1, mouseOpacityOOC = 1,
    mouseHideOnClick = false, mouseHideAfk = false,
    mouseBorder = false, mouseBorderColor = { r = 1, g = 1, b = 1 }, mouseBorderClassColor = false,
    mouseBorderWeight = 2,
    mouseDot = false, mouseDotSize = 6, mouseDotColor = { r = 1, g = 1, b = 1 },
    mouseDotClassColor = false,
    mouseFadeIdle = false, mouseFadeDelay = 2, mouseFadeOpacity = 0,
    mouseGCD = true, mouseHideBackground = false, mouseGCDColor = { r = 0.004, g = 0.56, b = 0.91 },
    mouseGCDClassColor = false, mouseReadyColor = { r = 0, g = 0.8, b = 0.3 }, mouseReadyMatch = false,
    mouseGCDAlpha = 1, mouseCastSwipe = true, mouseCastColor = { r = 0.004, g = 0.56, b = 0.91 },
    mouseCastClassColor = false, mouseSwipeDelay = 0.08,
    mouseTrail = false, mouseTrailShape = "glow", mouseTrailColor = { r = 1, g = 1, b = 1 },
    mouseTrailClassColor = false, mouseTrailSparkle = false, mouseTrailLength = 20,
    mouseTrailDuration = 2, mouseTrailSize = 24, mouseTrailBrightness = 0.8,
    mouseMelee = false, mouseMeleeBorder = true, mouseMeleeRing = false,
    mouseMeleeSound = false, mouseMeleeSoundKey = "none", mouseMeleeSoundInterval = 3,

    gcdTracker = F.gcdTracker, gcdDuration = 5, gcdIconSize = 32, gcdSpacing = 4, gcdDirection = "RIGHT",
    gcdFadeStart = 0.5, gcdStack = true, gcdCombatOnly = false,
    gcdWorld = true, gcdDungeon = true, gcdRaid = true, gcdPvP = true,
    gcdBlocklist = "6603, 75", gcdTimelineColor = { r = 0.01, g = 0.56, b = 0.91 },
    gcdTimelineHeight = 4, gcdDowntime = false, gcdTexture = "",
    focusCastBar = F.focusCastBar, focusWidth = 250, focusHeight = 24,
    focusBgColor = { r = 0.12, g = 0.12, b = 0.12 }, focusBgAlpha = 0.8,
    focusReadyColor = { r = 0.01, g = 0.56, b = 0.91 }, focusReadyClassColor = false,
    focusCooldownColor = { r = 0.5, g = 0.5, b = 0.5 },
    focusColorNonInt = true, focusNonIntColor = { r = 0.8, g = 0.2, b = 0.2 },
    focusInterruptedColor = { r = 0.51, g = 0.51, b = 0.51 },
    focusIcon = true, focusIconSide = "LEFT", focusSpellName = true, focusNameLength = 0,
    focusTarget = true, focusTime = true, focusShield = true,
    focusTick = true, focusTickColor = { r = 1, g = 1, b = 1 }, focusTickClassColor = false,
    focusFont = "", focusFontSize = 12, focusOutline = "OUTLINE", focusTexture = "", focusThemeColors = false,
    focusTextColor = { r = 1, g = 1, b = 1 }, focusTextClassColor = false,
    focusHideFriendly = false, focusHideNonInt = false, focusHideOnCooldown = false,
    focusFadeTime = 0.75, focusInterrupter = false,
    focusCastBarPos = { point = "CENTER", relPoint = "CENTER", x = 5, y = 71 },
    focusAudio = "none", focusSound = "none", focusSpeech = "Interrupt",
    focusVoice = "", focusVolume = 50, focusRate = 0,

    trainerPopup = F.trainerPopup, trainerGlow = true, trainerRanks = true,
    trainerPos = { point = "TOP", relPoint = "TOP", x = -274, y = -77 },

    flightTimer = F.flightTimer, flightTimerScale = 1, flightTimerAlpha = 1, flightEarlyLanding = true, flightTimerMapTime = false,
    flightGame = "aim", quizCamp = F.quizCamp,
    quizPos = { point = "TOP", relPoint = "TOP", x = 0, y = -127 },
    flightTimerFont = "", flightTimerOutline = "NONE", flightTimerTexture = "",
    aimTrainer = F.aimTrainer, aimMode = "hexakill", aimPulse = true, aimSound = true,
    aimSoundKey = "game:click", aimShare = true,
    waypoints = F.waypoints, waypointShape = "hex", waypointScale = 1, waypointCard = true,
    waypointTime = true, waypointBeam = true, waypointFadeNear = 40, waypointEdge = true,
    waypointNav = true, waypointSound = "none", waypointHideGame = true,
})
ns.QoLSettings = S

local function Disband()
    if InCombatLockdown() then
        ns.Print(TEXT_IN_COMBAT)
        return
    end
    local prefix = IsInRaid() and "raid" or "party"
    for i = GetNumGroupMembers(), 1, -1 do
        local unit = prefix .. i
        if UnitExists(unit) and not UnitIsUnit(unit, "player") then C_PartyInfo.UninviteUnit(GetUnitName(unit, true)) end
    end
end

function ns.DisbandGroup()
    if not IsInGroup() then ns.Print(TEXT_NO_GROUP); return end
    if not UnitIsGroupLeader("player") then ns.Print(TEXT_NOT_LEADER); return end
    ns.Confirm(TEXT_DISBAND, Disband)
end
