-------------------------------------------------------------------------------
--  NaowhForever_TownTravel.lua -- boats and zeppelins on the town map, by world map, from the
--  game's tables for build 1.60.1.70205. Generated by Tools/build_travel.py; do not edit by hand.
--
--  [uiMapID] = { { x, y, label, the uiMapID it takes you to, factions }, ... }. x and y are
--  map percentages.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.TownTravel = {
    [1411] = {
        { 50.5, 12.7, "Zeppelin to Grom'gol", 1434, "H" },
        { 51, 13.9, "Zeppelin to Undercity", 1420, "H" },
    },
    [1413] = {
        { 63.8, 38.8, "Boat to Booty Bay", 1434, "AH" },
    },
    [1420] = {
        { 60.6, 58.9, "Zeppelin to Orgrimmar", 1411, "H" },
        { 61.9, 58.9, "Zeppelin to Grom'gol", 1434, "H" },
    },
    [1434] = {
        { 25.7, 73.1, "Boat to Ratchet", 1413, "AH" },
        { 31.2, 30.4, "Zeppelin to Orgrimmar", 1411, "H" },
        { 31.5, 29.1, "Zeppelin to Undercity", 1420, "H" },
    },
    [1437] = {
        { 4.5, 56.7, "Boat to Auberdine", 1439, "A" },
        { 4.7, 63.8, "Boat to Theramore", 1445, "A" },
    },
    [1438] = {
        { 54.8, 97.2, "Boat to Auberdine", 1439, "A" },
    },
    [1439] = {
        { 32.3, 44.1, "Boat to Menethil Harbor", 1437, "A" },
        { 33.3, 39.8, "Boat to Rut'theran Village", 1438, "A" },
    },
    [1444] = {
        { 31, 39.5, "Boat to the Feralas coast", 1444, "A" },
        { 43.1, 42.8, "Boat to Feathermoon Stronghold", 1444, "A" },
    },
    [1445] = {
        { 71.7, 56.7, "Boat to Menethil Harbor", 1437, "A" },
    },
}
