-------------------------------------------------------------------------------
--  NaowhForever_ZoneExits.lua -- the roads out of each zone, as clickable arrows on the town
--  map: Wowhead Forever's zone grid on the game's maps for build 1.60.1.70205. Generated by
--  Tools/build_zone_exits.py; do not edit by hand.
--
--  [uiMapID] = { { x, y, rotation, the uiMapID it leads to }, ... }. x and y are map
--  percentages, rotation is in radians, anticlockwise from pointing up.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.ZoneExits = {
    [1411] = {
        { 35.8, 42.5, 1.57, 1413 },   -- The Barrens
        { 45.5, 9.5, 0.00, 1454 },   -- Orgrimmar
    },
    [1412] = {
        { 39.9, 13.3, -1.14, 1442 },   -- Stonetalon Mountains
        { 63.5, 62.3, -1.43, 1413 },   -- The Barrens
    },
    [1413] = {
        { 35.7, 28.8, 1.33, 1442 },   -- Stonetalon Mountains
        { 42.7, 58.9, 1.63, 1412 },   -- Mulgore
        { 44.9, 89.2, 2.68, 1441 },   -- Thousand Needles
        { 48.8, 6.5, 0.20, 1440 },   -- Ashenvale
        { 49.5, 80.1, -1.39, 1445 },   -- Dustwallow Marsh
        { 61.5, 18.9, -1.60, 1411 },   -- Durotar
    },
    [1416] = {
        { 20.8, 89.7, -2.20, 1424 },   -- Hillsbrad Foothills
        { 48.9, 88.8, -3.10, 1424 },   -- Hillsbrad Foothills
        { 84.9, 30.6, 0.62, 1422 },   -- Western Plaguelands
    },
    [1417] = {
        { 15.2, 46.6, 1.30, 1424 },   -- Hillsbrad Foothills
        { 46.2, 89.8, -2.58, 1437 },   -- Wetlands
        { 77.2, 21.8, -1.06, 1425 },   -- The Hinterlands
    },
    [1418] = {
        { 48.0, 9.0, -0.00, 1432 },   -- Loch Modan
    },
    [1419] = {
        { 53.0, 6.8, -0.00, 1435 },   -- Swamp of Sorrows
    },
    [1420] = {
        { 57.5, 76.3, 2.16, 1421 },   -- Silverpine Forest
        { 61.0, 71.0, 3.14, 1458 },   -- Undercity
        { 83.2, 70.0, -1.57, 1422 },   -- Western Plaguelands
    },
    [1421] = {
        { 57.0, 4.8, -0.00, 1420 },   -- Tirisfal Glades
        { 66.3, 78.4, -1.82, 1424 },   -- Hillsbrad Foothills
    },
    [1422] = {
        { 30.0, 57.0, 1.57, 1420 },   -- Tirisfal Glades
        { 48.2, 90.5, 2.17, 1416 },   -- Alterac Mountains
        { 73.3, 59.0, -0.47, 1423 },   -- Eastern Plaguelands
    },
    [1423] = {
        { 9.5, 61.0, 1.57, 1422 },   -- Western Plaguelands
    },
    [1424] = {
        { 13.9, 49.2, 1.24, 1421 },   -- Silverpine Forest
        { 29.2, 29.8, 0.86, 1416 },   -- Alterac Mountains
        { 51.7, 30.6, 0.01, 1416 },   -- Alterac Mountains
        { 85.2, 48.8, -2.15, 1417 },   -- Arathi Highlands
        { 89.6, 29.8, -0.83, 1425 },   -- The Hinterlands
    },
    [1425] = {
        { 7.5, 60.7, 1.69, 1424 },   -- Hillsbrad Foothills
        { 23.0, 28.8, -0.96, 1423 },   -- Eastern Plaguelands
        { 56.6, 80.6, 2.09, 1417 },   -- Arathi Highlands
    },
    [1426] = {
        { 53.5, 35.0, 0.00, 1455 },   -- Ironforge
        { 87.0, 48.9, -1.82, 1432 },   -- Loch Modan
    },
    [1427] = {
        { 45.0, 85.0, 3.14, 1428 },   -- Burning Steppes
    },
    [1428] = {
        { 36.2, 21.3, -0.00, 1427 },   -- Searing Gorge
        { 78.0, 81.5, 3.14, 1433 },   -- Redridge Mountains
    },
    [1429] = {
        { 20.9, 79.4, 1.85, 1436 },   -- Westfall
        { 32.0, 50.0, 0.79, 1453 },   -- Stormwind City
        { 66.3, 84.1, 2.58, 1431 },   -- Duskwood
        { 92.5, 72.0, -1.57, 1433 },   -- Redridge Mountains
    },
    [1430] = {
        { 33.8, 35.0, 1.57, 1431 },   -- Duskwood
        { 58.5, 40.0, -1.57, 1435 },   -- Swamp of Sorrows
    },
    [1431] = {
        { 9.0, 63.0, 1.57, 1436 },   -- Westfall
        { 44.7, 85.6, -2.92, 1434 },   -- Stranglethorn Vale
        { 73.0, 16.2, -0.00, 1429 },   -- Elwynn Forest
        { 89.8, 46.0, -1.57, 1430 },   -- Deadwind Pass
    },
    [1432] = {
        { 20.8, 61.7, 1.03, 1426 },   -- Dun Morogh
        { 25.0, 6.8, -0.00, 1437 },   -- Wetlands
        { 38.6, 92.3, -1.90, 1418 },   -- Badlands
    },
    [1433] = {
        { 2.5, 88.9, 1.61, 1429 },   -- Elwynn Forest
        { 42.0, 8.8, -0.00, 1428 },   -- Burning Steppes
        { 43.7, 8.8, -1.45, 2548 },   -- Riverglades
        { 70.3, 18.9, -0.87, 2548 },   -- Riverglades
    },
    [1434] = {
        { 40.7, 5.5, -0.06, 1431 },   -- Duskwood
    },
    [1435] = {
        { 6.5, 57.0, 1.57, 1430 },   -- Deadwind Pass
        { 33.0, 66.0, 3.14, 1419 },   -- Blasted Lands
    },
    [1436] = {
        { 62.9, 22.1, -1.18, 1429 },   -- Elwynn Forest
        { 66.5, 62.0, -1.57, 1431 },   -- Duskwood
    },
    [1437] = {
        { 51.3, 10.2, 0.20, 1417 },   -- Arathi Highlands
        { 55.5, 85.4, 3.14, 1432 },   -- Loch Modan
    },
    [1438] = {
        { 31.0, 53.0, 1.57, 1457 },   -- Darnassus
    },
    [1439] = {
        { 43.6, 93.8, 3.10, 1440 },   -- Ashenvale
    },
    [1440] = {
        { 27.1, 15.9, -0.34, 1439 },   -- Darkshore
        { 42.0, 73.2, 3.14, 1442 },   -- Stonetalon Mountains
        { 56.0, 31.2, 0.01, 1448 },   -- Felwood
        { 67.7, 84.5, -2.93, 1413 },   -- The Barrens
        { 93.9, 47.1, -1.98, 1447 },   -- Azshara
    },
    [1441] = {
        { 8.6, 26.8, 0.83, 1444 },   -- Feralas
        { 32.0, 21.4, -0.64, 1413 },   -- The Barrens
        { 76.0, 95.2, 3.14, 1446 },   -- Tanaris
    },
    [1442] = {
        { 29.3, 76.1, 2.91, 1443 },   -- Desolace
        { 69.5, 96.5, 1.78, 1412 },   -- Mulgore
        { 81.3, 37.7, -0.00, 1440 },   -- Ashenvale
        { 83.4, 91.6, -2.00, 1413 },   -- The Barrens
    },
    [1443] = {
        { 45.7, 93.8, -2.94, 1444 },   -- Feralas
        { 56.9, 88.6, -1.74, 2652 },   -- Shen'dralas
        { 61.0, 4.0, -0.00, 1442 },   -- Stonetalon Mountains
        { 65.9, 78.6, 2.56, 2652 },   -- Shen'dralas
    },
    [1444] = {
        { 45.3, 4.5, 0.17, 1443 },   -- Desolace
        { 87.8, 49.6, -1.75, 1441 },   -- Thousand Needles
    },
    [1445] = {
        { 30.0, 46.8, 1.64, 1413 },   -- The Barrens
    },
    [1446] = {
        { 25.5, 56.2, 0.54, 1449 },   -- Un'Goro Crater
        { 51.0, 23.2, -0.00, 1441 },   -- Thousand Needles
    },
    [1447] = {
        { 11.2, 76.0, 1.25, 1440 },   -- Ashenvale
    },
    [1448] = {
        { 55.1, 90.8, 3.14, 1440 },   -- Ashenvale
        { 65.2, 8.0, -1.57, 1452 },   -- Winterspring
    },
    [1449] = {
        { 27.8, 20.0, 1.57, 1451 },   -- Silithus
        { 65.5, 95.5, -2.43, 1446 },   -- Tanaris
    },
    [1451] = {
        { 83.7, 21.6, -1.57, 1449 },   -- Un'Goro Crater
    },
    [1452] = {
        { 28.2, 36.1, 1.57, 1448 },   -- Felwood
    },
    [2548] = {
        { 17.5, 69.1, 1.53, 1433 },   -- Redridge Mountains
        { 28.1, 70.8, 2.92, 1433 },   -- Redridge Mountains
    },
    [2652] = {
        { 22.2, 23.0, 1.57, 1443 },   -- Desolace
        { 34.0, 6.7, -0.74, 1443 },   -- Desolace
    },
}
