-- NaowhForever_TownSpiritHealers.lua: spirit healers on the town map, by world map, generated by Tools/build_spirit_healers.py.
local ns = _G.NaowhForever

ns.TownSpiritHealers = {
    [1411] = {
        { 44.2, 69.4, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 47, 17.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 53.6, 44.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 57.6, 73.2, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1412] = {
        { 42.6, 78, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 45.8, 59.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 46.4, 55.4, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1413] = {
        { 45.2, 61, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 50.8, 32.4, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 60.2, 39.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1417] = {
        { 48.8, 55.4, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1418] = {
        { 8.2, 55.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 57, 24.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1419] = {
        { 51, 12.2, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1420] = {
        { 17.6, 67.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 31.2, 64.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 56.2, 49.4, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 79, 40.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 82, 69.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1421] = {
        { 44.2, 41.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1422] = {
        { 45.6, 85.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 65.6, 74.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1423] = {
        { 38.2, 70.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 39, 92.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 47.2, 44.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 70.4, 54.4, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 80, 64.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 96.4, 91.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1424] = {
        { 51.6, 52.4, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 63.6, 19.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1425] = {
        { 16.8, 44.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 60.6, 38.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 62, 26.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 72.6, 68, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1426] = {
        { 29.6, 69.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 47, 55, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 54.2, 39, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1427] = {
        { 35.6, 22.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1428] = {
        { 63.2, 23.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1429] = {
        { 39.4, 60.4, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 49.6, 43.2, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 83.4, 69.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1430] = {
        { 40, 75.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1431] = {
        { 20, 49.4, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 44.8, 67.2, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 47.8, 45.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 75, 59, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1432] = {
        { 32.4, 46.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1433] = {
        { 15.8, 56.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 20.8, 56.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1434] = {
        { 30, 73, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 38.4, 8.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1435] = {
        { 50.2, 62.2, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1436] = {
        { 51.6, 49.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1437] = {
        { 11.6, 43.4, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 49.4, 41.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1438] = {
        { 56.2, 63.2, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 58.8, 42.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1439] = {
        { 41.8, 36.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 43.6, 92.2, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1440] = {
        { 17.8, 11, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 22.2, 28.2, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 40.2, 53, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 51.6, 63.2, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 80.6, 58, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 84.2, 56.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 93.2, 42.2, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1441] = {
        { 30.6, 23.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 69.2, 53.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1442] = {
        { 57.6, 62, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1443] = {
        { 50.2, 62.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1444] = {
        { 31.6, 48, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 44, 7.4, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 50.4, 13.4, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 54.8, 47.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 73, 44.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1445] = {
        { 39.6, 30.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 63.6, 43, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1446] = {
        { 54, 28.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1447] = {
        { 14.4, 78.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 54.2, 71.4, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 70.4, 15.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1448] = {
        { 49.4, 30.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 56.2, 86.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1449] = {
        { 80, 49.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1450] = {
        { 62, 69.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1451] = {
        { 28, 87.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 47, 38.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 80.6, 19.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1452] = {
        { 61.2, 34.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1456] = {
        { 56.6, 17.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1457] = {
        { 77, 27, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [1458] = {
        { 67.8, 14.2, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [2482] = {
        { 9.6, 47, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 81.2, 40.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 85.6, 68.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [2521] = {
        { 40.2, 63.8, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 41, 22.4, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 55, 68.2, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 55.4, 45, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 68.6, 50.2, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
    [2548] = {
        { 60.8, 45.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 62, 83.6, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
        { 76, 54.4, "spirit", "Spirit Healer", "Graveyard", nil, "AH" },
    },
}
