-- TownMailboxes.lua: mailboxes on the town map, by world map, generated by Tools/build_mailboxes.py.
local ns = _G.NaowhForever

ns.TownMailboxes = {
    [1411] = {
        { 51.9, 42.1, "mail", "Mailbox", "", nil, "AH" },
    },
    [1412] = {
        { 33.7, 21.9, "mail", "Mailbox", "", nil, "AH" },
        { 46.2, 63.5, "mail", "Mailbox", "", nil, "AH" },
        { 47, 60.3, "mail", "Mailbox", "", nil, "AH" },
    },
    [1413] = {
        { 45.1, 58.7, "mail", "Mailbox", "", nil, "AH" },
        { 52, 30.5, "mail", "Mailbox", "", nil, "AH" },
        { 62.2, 39.2, "mail", "Mailbox", "", nil, "AH" },
    },
    [1416] = {
        { 12.8, 52.5, "mail", "Mailbox", "", nil, "AH" },
        { 14.8, 69.2, "mail", "Mailbox", "", nil, "AH" },
        { 18.1, 64.5, "mail", "Mailbox", "", nil, "AH" },
        { 18.1, 71.5, "mail", "Mailbox", "", nil, "AH" },
        { 18.6, 61.5, "mail", "Mailbox", "", nil, "AH" },
        { 19.2, 73.9, "mail", "Mailbox", "", nil, "AH" },
    },
    [1417] = {
        { 73.8, 33.1, "mail", "Mailbox", "", nil, "AH" },
    },
    [1418] = {
        { 3.9, 47.5, "mail", "Mailbox", "", nil, "AH" },
    },
    [1419] = {
        { 64.1, 19.3, "mail", "Mailbox", "", nil, "AH" },
    },
    [1420] = {
        { 61.5, 53.1, "mail", "Mailbox", "", nil, "AH" },
    },
    [1421] = {
        { 43.4, 41.5, "mail", "Mailbox", "", nil, "AH" },
    },
    [1423] = {
        { 71.3, 49, "mail", "Mailbox", "", nil, "AH" },
        { 80.9, 58.6, "mail", "Mailbox", "", nil, "AH" },
    },
    [1424] = {
        { 50.4, 58.6, "mail", "Mailbox", "", nil, "AH" },
        { 62.5, 19.7, "mail", "Mailbox", "", nil, "AH" },
    },
    [1425] = {
        { 14.1, 45.7, "mail", "Mailbox", "", nil, "AH" },
        { 78.9, 80.4, "mail", "Mailbox", "", nil, "AH" },
    },
    [1426] = {
        { 47, 52.5, "mail", "Mailbox", "", nil, "AH" },
    },
    [1429] = {
        { 42.9, 65.4, "mail", "Mailbox", "", nil, "AH" },
    },
    [1431] = {
        { 73.8, 46.2, "mail", "Mailbox", "", nil, "AH" },
    },
    [1432] = {
        { 34.8, 47.7, "mail", "Mailbox", "", nil, "AH" },
    },
    [1433] = {
        { 21.5, 46.6, "mail", "Mailbox", "", nil, "AH" },
        { 26.5, 46.6, "mail", "Mailbox", "", nil, "AH" },
    },
    [1434] = {
        { 26.8, 76.5, "mail", "Mailbox", "", nil, "AH" },
        { 32.5, 28.7, "mail", "Mailbox", "", nil, "AH" },
    },
    [1435] = {
        { 45.5, 55, "mail", "Mailbox", "", nil, "AH" },
    },
    [1436] = {
        { 53, 53.5, "mail", "Mailbox", "", nil, "AH" },
    },
    [1437] = {
        { 10.8, 59.7, "mail", "Mailbox", "", nil, "AH" },
    },
    [1438] = {
        { 56.1, 58.4, "mail", "Mailbox", "", nil, "AH" },
    },
    [1439] = {
        { 37.3, 43.8, "mail", "Mailbox", "", nil, "AH" },
    },
    [1440] = {
        { 36.3, 50.3, "mail", "Mailbox", "", nil, "AH" },
        { 73.6, 61, "mail", "Mailbox", "", nil, "AH" },
    },
    [1441] = {
        { 45.9, 51, "mail", "Mailbox", "", nil, "AH" },
    },
    [1442] = {
        { 36, 7.3, "mail", "Mailbox", "", nil, "AH" },
        { 48, 61.1, "mail", "Mailbox", "", nil, "AH" },
    },
    [1443] = {
        { 24.8, 68.8, "mail", "Mailbox", "", nil, "AH" },
        { 65.4, 6.9, "mail", "Mailbox", "", nil, "AH" },
    },
    [1444] = {
        { 31.2, 43.8, "mail", "Mailbox", "", nil, "AH" },
        { 74.9, 44, "mail", "Mailbox", "", nil, "AH" },
    },
    [1445] = {
        { 66, 45.4, "mail", "Mailbox", "", nil, "AH" },
    },
    [1446] = {
        { 52.3, 27.8, "mail", "Mailbox", "", nil, "AH" },
    },
    [1451] = {
        { 51.7, 37.9, "mail", "Mailbox", "", nil, "AH" },
    },
    [1452] = {
        { 61.3, 38.6, "mail", "Mailbox", "", nil, "AH" },
    },
    [1453] = {
        { 22.2, 57.6, "mail", "Mailbox", "", nil, "AH" },
        { 30.1, 49.6, "mail", "Mailbox", "", nil, "AH" },
        { 37, 68.8, "mail", "Mailbox", "", nil, "AH" },
        { 40, 84.2, "mail", "Mailbox", "", nil, "AH" },
        { 40.8, 62.6, "mail", "Mailbox", "", nil, "AH" },
        { 45.6, 54.6, "mail", "Mailbox", "", nil, "AH" },
        { 50, 87.6, "mail", "Mailbox", "", nil, "AH" },
        { 50.7, 71.3, "mail", "Mailbox", "", nil, "AH" },
        { 54.5, 66.5, "mail", "Mailbox", "", nil, "AH" },
        { 54.9, 57.4, "mail", "Mailbox", "", nil, "AH" },
        { 54.9, 63.2, "mail", "Mailbox", "", nil, "AH" },
        { 57.4, 72.2, "mail", "Mailbox", "", nil, "AH" },
        { 61, 50.6, "mail", "Mailbox", "", nil, "AH" },
        { 61.5, 44.1, "mail", "Mailbox", "", nil, "AH" },
        { 62.3, 73.4, "mail", "Mailbox", "", nil, "AH" },
        { 64.6, 37.5, "mail", "Mailbox", "", nil, "AH" },
        { 66.7, 64.3, "mail", "Mailbox", "", nil, "AH" },
        { 67.6, 50.1, "mail", "Mailbox", "", nil, "AH" },
        { 71, 40.5, "mail", "Mailbox", "", nil, "AH" },
        { 72.3, 69.3, "mail", "Mailbox", "", nil, "AH" },
        { 72.5, 48.3, "mail", "Mailbox", "", nil, "AH" },
        { 74.3, 55.7, "mail", "Mailbox", "", nil, "AH" },
        { 75.9, 64.1, "mail", "Mailbox", "", nil, "AH" },
    },
    [1454] = {
        { 38.5, 74.5, "mail", "Mailbox", "", nil, "AH" },
        { 45.2, 54.5, "mail", "Mailbox", "", nil, "AH" },
        { 48.2, 37.4, "mail", "Mailbox", "", nil, "AH" },
        { 50.4, 70.8, "mail", "Mailbox", "", nil, "AH" },
        { 51.4, 59, "mail", "Mailbox", "", nil, "AH" },
        { 51.9, 46.4, "mail", "Mailbox", "", nil, "AH" },
        { 53.3, 65.5, "mail", "Mailbox", "", nil, "AH" },
        { 60.4, 55.6, "mail", "Mailbox", "", nil, "AH" },
        { 62.2, 40.4, "mail", "Mailbox", "", nil, "AH" },
        { 81.2, 21.6, "mail", "Mailbox", "", nil, "AH" },
    },
    [1455] = {
        { 21.1, 52.9, "mail", "Mailbox", "", nil, "AH" },
        { 32.9, 64.9, "mail", "Mailbox", "", nil, "AH" },
        { 70.9, 72.3, "mail", "Mailbox", "", nil, "AH" },
        { 72, 49.4, "mail", "Mailbox", "", nil, "AH" },
    },
    [1456] = {
        { 45, 59.2, "mail", "Mailbox", "", nil, "AH" },
    },
    [1457] = {
        { 41.6, 42.2, "mail", "Mailbox", "", nil, "AH" },
    },
    [1458] = {
        { 62.2, 52.4, "mail", "Mailbox", "", nil, "AH" },
        { 62.8, 36.5, "mail", "Mailbox", "", nil, "AH" },
        { 67.9, 38.4, "mail", "Mailbox", "", nil, "AH" },
        { 69.5, 50.4, "mail", "Mailbox", "", nil, "AH" },
        { 71.7, 62.3, "mail", "Mailbox", "", nil, "AH" },
    },
    [2482] = {
        { 69.3, 47.7, "mail", "Mailbox", "", nil, "AH" },
        { 70.8, 49.8, "mail", "Mailbox", "", nil, "AH" },
    },
    [2521] = {
        { 43.3, 44.1, "mail", "Mailbox", "", nil, "AH" },
        { 58.3, 76.3, "mail", "Mailbox", "", nil, "AH" },
        { 62.2, 73.6, "mail", "Mailbox", "", nil, "AH" },
    },
    [2548] = {
        { 58.8, 45.5, "mail", "Mailbox", "", nil, "AH" },
        { 64.5, 83.6, "mail", "Mailbox", "", nil, "AH" },
        { 78.6, 53.8, "mail", "Mailbox", "", nil, "AH" },
    },
}
