-- Build.lua: the WoW Forever build the Journal's game data is read from, generated by Tools/build/factions.py.
local ns = _G.NaowhForever

ns.Journal.DATA_BUILD = "1.60.1.70338"
ns.Journal.DATA_DATE = "10 Oct 2026"
