-- Style.lua: the house look every module shares (ns.Shared.Style): colors, icons and sizes.
local Shared = _G.NaowhForever.Shared

local PI = 3.141592653589793
local OPACITY_MIN, PERCENT_MAX, PERCENT_STEP = 40, 100, 5
local MEDIA = "Interface\\AddOns\\NaowhForever\\Core\\Media\\"

Shared.Style = {
    BORDER_RGB = { r = 0, g = 0, b = 0 },
    BACKDROP_ALPHA = 0.97,
    HUD_SHADOW_RGB = { r = 0, g = 0, b = 0 },
    HUD_SHADOW_ALPHA = 0.8,
    HUD_SHADOW_X = 1,
    HUD_SHADOW_Y = -1,
    HUD_CARD_ALPHA = 0.85,
    HUD_SOFT_ALPHA = 0.7,
    HUD_SOFT_FADE = 32,
    HUD_SOFT_INSET = 12,
    HUD_SOFT_SHADOW_ALPHA = 1,
    HUD_BARE_SHADOW_ALPHA = 1,
    HUD_BARE_SHADOW_X = 1,
    HUD_BARE_SHADOW_Y = -1,
    SHADOW_ALPHA = 0.4,
    SHADOW_SIZE = 48,
    CLASSIC_GOLD_RGB = { r = 0xd4 / 255, g = 0xaf / 255, b = 0x37 / 255 },
    CLASSIC_BRONZE_RGB = { r = 0x5e / 255, g = 0x4a / 255, b = 0x1c / 255 },
    CLASSIC_TRIM_BODY = 3,
    CLASSIC_GEM = 12,
    CLASSIC_GEM_EDGE = 2,
    CLASSIC_PLATE_H = 30,
    CLASSIC_PLATE_BODY = 2,
    CLASSIC_PLATE_PAD = 34,
    CLASSIC_PLATE_SIZE = 16,
    CLASSIC_TITLE_RGB = { r = 0xf4 / 255, g = 0xcf / 255, b = 0x63 / 255 },
    CLASSIC_PLATE_GEM = 7,
    CLASSIC_PLATE_GEM_GAP = 12,
    -- The game's panel button (UIPanelButtonTemplate): its art, the caps' width, and the template's own crops.
    CLASSIC_BUTTON_ART = {
        up = "Interface\\Buttons\\UI-Panel-Button-Up",
        down = "Interface\\Buttons\\UI-Panel-Button-Down",
        disabled = "Interface\\Buttons\\UI-Panel-Button-Disabled",
        highlight = "Interface\\Buttons\\UI-Panel-Button-Highlight",
    },
    CLASSIC_BUTTON_CAP = 12,
    CLASSIC_BUTTON_COORDS = {
        left = { 0, 0.09375, 0, 0.6875 }, middle = { 0.09375, 0.53125, 0, 0.6875 },
        right = { 0.53125, 0.625, 0, 0.6875 }, glow = { 0, 0.625, 0, 0.6875 },
    },
    CLASSIC_DISABLED_ALPHA = 0.5,
    CLASSIC_BEVEL_RGB = { r = 0x6b / 255, g = 0x62 / 255, b = 0x52 / 255 },
    CLASSIC_FILL_RGB = { { r = 0xc7 / 255, g = 0x9a / 255, b = 0x3a / 255 }, { r = 0x6e / 255, g = 0x50 / 255, b = 0x19 / 255 } },
    CLASSIC_KNOB_EDGE = 2,
    CLASSIC_CHECK = "Interface\\Buttons\\UI-CheckBox-Check",
    CLASSIC_CHECK_SCALE = 1.3,
    CLASSIC_TAB_RGB = { { r = 0x3d / 255, g = 0x2d / 255, b = 0x19 / 255 }, { r = 0x1a / 255, g = 0x12 / 255, b = 0x0a / 255 } },
    CLASSIC_PICK_RGB = { r = 0x46 / 255, g = 0x78 / 255, b = 0xd2 / 255 },
    CLASSIC_PICK_ALPHA = 0.6,
    CLASSIC_PICK_FADE = 0.1,
    CLASSIC_PICK_LINE_RGB = { r = 0x96 / 255, g = 0xbe / 255, b = 0xff / 255 },
    CLASSIC_PICK_LINE_ALPHA = 0.4,
    CLASSIC_SECTION_GEM = 7,
    CLASSIC_SECTION_GEM_GAP = 8,
    CLASSIC_TIP_RGB = { r = 0x02 / 255, g = 0x02 / 255, b = 0x12 / 255 },
    CLASSIC_TIP_ALPHA = 0.94,
    CLASSIC_TIP_EDGE_RGB = { r = 0x9a / 255, g = 0x9a / 255, b = 0xb0 / 255 },
    CLASSIC_PATTERN = "Interface\\FrameGeneral\\UIFrameNeutralBackground",
    CLASSIC_PATTERN_SHADE = 0.7,
    CLASSIC_PATTERN_ALPHA = 0.6,
    CLASSIC_HEADING_STEP = 1,
    CLASSIC_HEADING_SHADOW = 1,
    CLASSIC_ICON_PATH = "Interface\\Icons\\",
    CLASSIC_ICON_CROP = 0.07,
    CLASSIC_ICONS = {
        checklist = "INV_Misc_Note_01", map = "INV_Misc_Book_09", trophy = "INV_Chest_Plate16",
        notes = "INV_Misc_Book_11", compass = "INV_Misc_Map_01", shield = "INV_Shield_06",
        spark = "Spell_Holy_FistOfJustice", hammer = "Trade_BlackSmithing", pen = "INV_Scroll_03",
        grid = "INV_Misc_Gear_02", aura = "Spell_Holy_WordFortitude", bars = "Ability_Warrior_RallyingCry",
        group = "Spell_Shadow_EvilEye", swords = "Ability_DualWield", infinity = "Ability_MeleeDamage",
        settings = "INV_Misc_Gear_01", person = "INV_Misc_Head_Human_01", heart = "Spell_Holy_Heal",
        friends = "INV_Letter_01", guild = "INV_Shirt_GuildTabard_01", hearth = "INV_Misc_Rune_01",
        NaowhForeverJournal = "INV_Misc_Book_09", NaowhForeverBiS = "INV_Chest_Plate16",
        NaowhForeverGroup = "Spell_Shadow_EvilEye", NaowhForeverTraining = "INV_Misc_Book_11",
        NaowhForeverDiscovery = "INV_Misc_Map_01",
    },
    CLASSIC_HIGHLIGHT = "Interface\\Buttons\\ButtonHilight-Square",
    FOREVER_GOLD_RGB = { r = 1, g = 0xd1 / 255, b = 0 },
    FOREVER_CHECK_RGB = { r = 1, g = 0xd3 / 255, b = 0x4a / 255 },
    FOREVER_LIGHT_RGB = { r = 0xf2 / 255, g = 0xe6 / 255, b = 0xc8 / 255 },
    FOREVER_SUMMARY_RGB = { r = 0xe6 / 255, g = 0xd6 / 255, b = 0xb0 / 255 },
    FOREVER_DISABLED_TEXT_RGB = { r = 0.5, g = 0.5, b = 0.5 },
    FOREVER_VALUE_RGB = { r = 1, g = 1, b = 1 },
    FOREVER_TAB_ON_RGB = { r = 1, g = 0xf4 / 255, b = 0xd0 / 255 },
    FOREVER_MUTED_RGB = { r = 0x9a / 255, g = 0x8f / 255, b = 0x7a / 255 },
    FOREVER_BRONZE_RGB = { r = 0xc9 / 255, g = 0xa2 / 255, b = 0x5a / 255 },
    FOREVER_BRONZE_DARK_RGB = { r = 0x6e / 255, g = 0x51 / 255, b = 0x26 / 255 },
    FOREVER_BRONZE_DEEP_RGB = { r = 0x5a / 255, g = 0x40 / 255, b = 0x19 / 255 },
    FOREVER_PICK_RIM_RGB = { r = 0xd8 / 255, g = 0xb0 / 255, b = 0x64 / 255 },
    FOREVER_PILL_RIM_RGB = { r = 0x7a / 255, g = 0x5f / 255, b = 0x33 / 255 },
    FOREVER_BAR_RIM_RGB = { r = 0x6b / 255, g = 0x52 / 255, b = 0x30 / 255 },
    FOREVER_FIELD_RIM_RGB = { r = 0x6b / 255, g = 0x5a / 255, b = 0x40 / 255 },
    FOREVER_SEARCH_RIM_RGB = { r = 0x5a / 255, g = 0x52 / 255, b = 0x46 / 255 },
    FOREVER_CHECK_RIM_RGB = { r = 0x7a / 255, g = 0x6a / 255, b = 0x4e / 255 },
    FOREVER_INSET_RIM_RGB = { r = 0x4a / 255, g = 0x3a / 255, b = 0x22 / 255 },
    FOREVER_SWATCH_RIM_RGB = { r = 0x8a / 255, g = 0x6a / 255, b = 0x35 / 255 },
    FOREVER_TAB_RIM_RGB = { r = 0x5a / 255, g = 0x44 / 255, b = 0x22 / 255 },
    FOREVER_INSET_RGB = { r = 0x11 / 255, g = 0x10 / 255, b = 0x0e / 255 },
    FOREVER_FIELD_RGB = { r = 0x0a / 255, g = 0x09 / 255, b = 0x08 / 255 },
    FOREVER_SIDE_RGB = { r = 0x14 / 255, g = 0x12 / 255, b = 0x10 / 255 },
    FOREVER_PORTRAIT_RGB = { r = 0x06 / 255, g = 0x17 / 255, b = 0x26 / 255 },
    FOREVER_PORTRAIT_GLOW_RGB = { r = 0x2a / 255, g = 0x8f / 255, b = 0xc4 / 255 },
    FOREVER_BAND_RGB = { { r = 0x1e / 255, g = 0x1b / 255, b = 0x17 / 255 }, { r = 0x0f / 255, g = 0x0d / 255, b = 0x0b / 255 } },
    FOREVER_TITLE_BAR_RGB = { { r = 0x26 / 255, g = 0x22 / 255, b = 0x1d / 255 }, { r = 0x15 / 255, g = 0x13 / 255, b = 0x0f / 255 } },
    FOREVER_RED_RGB = { { r = 0xa8 / 255, g = 0x14 / 255, b = 0x0c / 255 }, { r = 0x4e / 255, g = 0x05 / 255, b = 0x02 / 255 } },
    FOREVER_RED_HOVER_RGB = { { r = 0xc8 / 255, g = 0x24 / 255, b = 0x16 / 255 }, { r = 0x62 / 255, g = 0x0a / 255, b = 0x05 / 255 } },
    FOREVER_RED_DISABLED_RGB = { { r = 0x4a / 255, g = 0x46 / 255, b = 0x42 / 255 }, { r = 0x24 / 255, g = 0x22 / 255, b = 0x20 / 255 } },
    FOREVER_PLATE_RGB = { { r = 0x8a / 255, g = 0x6a / 255, b = 0x2c / 255 }, { r = 0x3e / 255, g = 0x2c / 255, b = 0x0e / 255 } },
    FOREVER_FIELD_FILL_RGB = { { r = 0x24 / 255, g = 0x21 / 255, b = 0x1d / 255 }, { r = 0x16 / 255, g = 0x14 / 255, b = 0x12 / 255 } },
    FOREVER_TAB_RGB = { { r = 0x2a / 255, g = 0x26 / 255, b = 0x22 / 255 }, { r = 0x1a / 255, g = 0x18 / 255, b = 0x15 / 255 } },
    FOREVER_TAB_ACTIVE_RGB = { { r = 0xa3 / 255, g = 0x7b / 255, b = 0x2c / 255 }, { r = 0x4a / 255, g = 0x34 / 255, b = 0x10 / 255 } },
    FOREVER_BAR_RGB = { { r = 0x4a / 255, g = 0x3a / 255, b = 0x26 / 255 }, { r = 0x2c / 255, g = 0x22 / 255, b = 0x16 / 255 } },
    FOREVER_BAR_OPEN_RGB = { { r = 0x58 / 255, g = 0x45 / 255, b = 0x2a / 255 }, { r = 0x34 / 255, g = 0x28 / 255, b = 0x18 / 255 } },
    FOREVER_NAV_RGB = { { r = 0x1c / 255, g = 0x19 / 255, b = 0x16 / 255 }, { r = 0x16 / 255, g = 0x14 / 255, b = 0x11 / 255 } },
    FOREVER_NAV_PICK_RGB = { { r = 0x7a / 255, g = 0x5a / 255, b = 0x1c / 255 }, { r = 0x33 / 255, g = 0x24 / 255, b = 0x0b / 255 } },
    FOREVER_PILL_RGB = { { r = 0x2b / 255, g = 0x27 / 255, b = 0x22 / 255 }, { r = 0x1b / 255, g = 0x18 / 255, b = 0x15 / 255 } },
    FOREVER_CLOSE_RGB = { { r = 0xb8 / 255, g = 0x1a / 255, b = 0x10 / 255 }, { r = 0x5a / 255, g = 0x05 / 255, b = 0x03 / 255 } },
    FOREVER_TIP_RGB = { { r = 0, g = 0, b = 0 }, { r = 0.23, g = 0.19, b = 0 } },
    FOREVER_FRAME_LAYOUT = "PortraitFrameTemplate",
    FOREVER_FRAME_ATLASES = { "UI-Frame-PortraitMetal-CornerTopLeft", "UI-Frame-Metal-CornerTopRight",
        "UI-Frame-Metal-CornerBottomLeft", "UI-Frame-Metal-CornerBottomRight", "_UI-Frame-Metal-EdgeTop",
        "_UI-Frame-Metal-EdgeBottom", "!UI-Frame-Metal-EdgeLeft", "!UI-Frame-Metal-EdgeRight" },
    FOREVER_BARE_LAYOUT = "ButtonFrameTemplateNoPortrait",
    FOREVER_BARE_ATLASES = { "UI-Frame-Metal-CornerTopLeft", "UI-Frame-Metal-CornerTopRight",
        "UI-Frame-Metal-CornerBottomLeft", "UI-Frame-Metal-CornerBottomRight", "_UI-Frame-Metal-EdgeTop",
        "_UI-Frame-Metal-EdgeBottom", "!UI-Frame-Metal-EdgeLeft", "!UI-Frame-Metal-EdgeRight" },
    FOREVER_SELECTION_KIT = { highlight = "editmode-actionbar-highlight", selected = "editmode-actionbar-selected" },
    FOREVER_SELECTION_PIECES = { corner = "%s-NineSlice-Corner", top = "_%s-NineSlice-EdgeTop",
        bottom = "_%s-NineSlice-EdgeBottom", left = "!%s-NineSlice-EdgeLeft", right = "!%s-NineSlice-EdgeRight",
        center = "%s-NineSlice-Center" },
    FOREVER_SELECTION_OUT = 8,
    FOREVER_SELECTION_GLOW_ALPHA = 0.4,
    FOREVER_SELECTION_ALPHA = 0.3,
    FOREVER_SELECTION_RGB = { r = 0x2e / 255, g = 0x7d / 255, b = 0xf0 / 255 },
    FOREVER_SELECTION_EDGE_RGB = { r = 0x8c / 255, g = 0xc8 / 255, b = 1 },
    FOREVER_SELECTED_RGB = { r = 1, g = 0xc8 / 255, b = 0x1e / 255 },
    FOREVER_SELECTED_EDGE_RGB = { r = 1, g = 0xe6 / 255, b = 0x5a / 255 },
    FOREVER_GUIDE_RGB = { r = 0xf2 / 255, g = 0xe6 / 255, b = 0xc8 / 255 },
    FOREVER_GUIDE_ALPHA = 0.55,
    FOREVER_INSET_LAYOUT = "InsetFrameTemplate",
    FOREVER_INSET_ATLASES = { "UI-Frame-InnerTopLeft", "UI-Frame-InnerTopRight", "UI-Frame-InnerBotLeftCorner",
        "UI-Frame-InnerBotRight", "_UI-Frame-InnerTopTile", "_UI-Frame-InnerBotTile", "!UI-Frame-InnerLeftTile",
        "!UI-Frame-InnerRightTile" },
    FOREVER_CLOSE_ATLAS = { normal = "RedButton-Exit", pushed = "RedButton-exit-pressed",
        highlight = "RedButton-Highlight", disabled = "RedButton-Exit-Disabled" },
    FOREVER_TAB_ATLAS = { left = "uiframe-tab-left", middle = "_uiframe-tab-center", right = "uiframe-tab-right" },
    FOREVER_ACTIVE_TAB_ATLAS = { left = "uiframe-activetab-left", middle = "_uiframe-activetab-center",
        right = "uiframe-activetab-right" },
    FOREVER_SIDE_TAB_ATLAS = { normal = "common-sidetab", selected = "common-sidetab-selected",
        hover = "common-sidetab-hover", mask = "common-sidetab-mask" },
    FOREVER_SEARCH_ATLAS = { left = "common-search-border-left", middle = "common-search-border-middle",
        right = "common-search-border-right", icon = "common-search-magnifyingglass" },
    FOREVER_PILL_ATLAS = "UI-Character-Info-Title",
    FOREVER_BAND_ATLAS = "UI-Character-Info-Line-Bounce",
    FOREVER_BAR_ATLAS = "common-button-list-collapseExpand",
    FOREVER_PLUS_ATLAS = "common-button-list-plus",
    FOREVER_MINUS_ATLAS = "common-button-list-minus",
    FOREVER_DROPDOWN_ATLAS = "common-dropdown-a-button",
    FOREVER_RED_BUTTON_ATLAS = { left = "128-RedButton-Left", center = "_128-RedButton-Center",
        right = "128-RedButton-Right", highlight = "128-RedButton-Highlight" },
    FOREVER_RED_BUTTON_STATES = { "", "-Pressed", "-Disabled" },
    FOREVER_ROCK = "Interface\\FrameGeneral\\UI-Background-Rock",
    FOREVER_ROCK_SHADE = 0.55,
    FOREVER_ROCK_ALPHA = 0.5,
    FOREVER_CHECK = "Interface\\Buttons\\UI-CheckBox-Check",
    FOREVER_CHECK_DISABLED = "Interface\\Buttons\\UI-CheckBox-Check-Disabled",
    FOREVER_CHECK_DIM_ALPHA = 0.55,
    FOREVER_CHECKBOX = { up = "Interface\\Buttons\\UI-CheckBox-Up", down = "Interface\\Buttons\\UI-CheckBox-Down",
        highlight = "Interface\\Buttons\\UI-CheckBox-Highlight" },
    FOREVER_KNOB = "Interface\\Buttons\\UI-SliderBar-Button-Horizontal",
    FOREVER_HIGHLIGHT = "Interface\\QuestFrame\\UI-QuestLogTitleHighlight",
    FOREVER_TIP_ARROW = "Interface\\TalentFrame\\TalentFrame-Parts",
    FOREVER_TIP_ARROW_COORDS = { 0.78515625, 0.9921875, 0.546875, 0.58789063 },
    FOREVER_SIDE = 2,
    FOREVER_TITLE_H = 21,
    FOREVER_TITLE_SIZE = 12,
    FOREVER_TITLE_Y = 5,
    FOREVER_TITLE_LEFT = 58,
    FOREVER_TITLE_RIGHT = 24,
    FOREVER_CHROME_LEVEL = 15,
    FOREVER_PORTRAIT = 62,
    FOREVER_TAB_PAD = 14,
    FOREVER_TAB_GAP = 2,
    FOREVER_PORTRAIT_X = -5,
    FOREVER_PORTRAIT_Y = 7,
    FOREVER_PORTRAIT_RING = 6,
    FOREVER_PORTRAIT_LEVEL = 5,
    FOREVER_PORTRAIT_ROOM = 64,
    FOREVER_MASK_IN = 2,
    FOREVER_MASK_DROP = 4,
    FOREVER_CLOSE = 24,
    FOREVER_CLOSE_X = -2,
    FOREVER_CLOSE_Y = 1,
    FOREVER_CLOSE_GLYPH = 12,
    FOREVER_BAND_ALPHA = 0.035,
    FOREVER_GLOW_ALPHA = 0.55,
    FOREVER_HIGHLIGHT_ALPHA = 0.4,
    FOREVER_CHECK_SIZE = 22,
    FOREVER_CHECK_DRAWN = 16,
    FOREVER_LEAF_SHADE = 0.7,
    FOREVER_LIGHT_ALPHA = 0.05,
    FOREVER_LIGHT_SUBLEVEL = -5,
    FOREVER_CHECK_SCALE = 1.4,
    FOREVER_KNOB_SCALE = 2,
    FOREVER_ARROW_BUTTON = 18,
    FOREVER_ARROW_GLYPH = 10,
    FOREVER_TOP_TAB_SHARE = 0.75,
    FOREVER_TOP_TAB_CROP = 0.25,
    FOREVER_TAB_LEFT_X = -3,
    FOREVER_TAB_RIGHT_X = 7,
    FOREVER_ACTIVE_LEFT_X = -1,
    FOREVER_ACTIVE_RIGHT_X = 8,
    FOREVER_SEARCH_CAP = 8,
    FOREVER_SEARCH_CAP_X = -5,
    FOREVER_PILL_DIAMOND = 9,
    FOREVER_PILL_INSET = 10,
    FOREVER_PILL_PAD = 4,
    FOREVER_SIGN = 16,
    FOREVER_SIGN_RIGHT = 16,
    FOREVER_SIGN_SIZE = 18,
    FOREVER_BAR_GAP = 2,
    FOREVER_CARD_BAR_H = 28,
    FOREVER_CARD_GAP = 5,
    FOREVER_BODY_GAP = 4,
    FOREVER_BAND_H = 56,
    FOREVER_RAIL = 4,
    FOREVER_RAIL_EDGE = 1,
    FOREVER_SCROLL_ARROW = 12,
    FOREVER_SCROLL_ARROW_GAP = 2,
    FOREVER_PILL_W = 240,
    FOREVER_SIDE_TAB = 44,
    FOREVER_SIDE_TAB_TRIM = 5,
    FOREVER_SIDE_TAB_ICON = 28,
    FOREVER_SIDE_TAB_TOP = 70,
    FOREVER_SIDE_TAB_GAP = 4,
    FOREVER_TIP_EDGE = 2,
    FOREVER_TIP_ARROW_W = 30,
    FOREVER_TIP_ARROW_H = 12,
    RED_CODE = "|cfff87171",
    RED_RGB = { r = 0.97, g = 0.44, b = 0.44 },
    WARN_CODE = "|cfffb923c",
    WARN_RGB = { r = 0xfb / 255, g = 0x92 / 255, b = 0x3c / 255 },
    GOLD_CODE = "|cffe6cc80",
    TIP_RGB = { r = 0.9, g = 0.8, b = 0.5 },
    BIS_CODE = "|cffff8000",
    BIS_RGB = { r = 1, g = 0.5, b = 0 },
    SECOND_CODE = "|cffc7ccdb",
    SECOND_RGB = { r = 0xc7 / 255, g = 0xcc / 255, b = 0xdb / 255 },
    LOOK_CODE = "|cff66d9ef",
    LOOK_RGB = { r = 0x66 / 255, g = 0xd9 / 255, b = 0xef / 255 },
    UPGRADE_CODE = "|cff1eff00",
    HAVE_RGB = { r = 0.3, g = 0.82, b = 0.48 },
    FOREVER_CODE = "|cffeed69e",
    FOREVER_RGB = { r = 0xee / 255, g = 0xd6 / 255, b = 0x9e / 255 },
    CARRIED_RGB = { r = 1, g = 0.82, b = 0 },
    TIME_OK_RGB = { r = 0.29, g = 0.87, b = 0.5 },
    TIME_LOW_RGB = { r = 0.98, g = 0.8, b = 0.08 },
    TIME_OUT_RGB = { r = 0.97, g = 0.27, b = 0.27 },
    PICKED_RGB = { r = 1, g = 0.82, b = 0 },
    TIP_TITLE_RGB = { r = 1, g = 1, b = 1 },
    GUIDE_RGB = { r = 0xf2 / 255, g = 0xa3 / 255, b = 0x3a / 255 },

    ARROW = MEDIA .. "chevron",
    UP = MEDIA .. "chevron_up",
    HANGER = MEDIA .. "hanger",
    STAR = MEDIA .. "star",
    UPGRADE_ATLAS = "bags-greenarrow",
    SCRAP_ATLAS = "bags-icon-scrappable",
    SCRAP_RATIO = 32 / 36,
    CLOCK_ATLAS = "auctionhouse-icon-clock",
    QUEST_ATLAS = "smallquestbang",
    PIN = MEDIA .. "pin",
    GEM = MEDIA .. "waypoint_diamond",
    CHAIN = MEDIA .. "chain",
    INFO = MEDIA .. "info",
    LOGO = MEDIA .. "LogoAddon",
    LOGO_SMALL = MEDIA .. "LogoSmall",
    BAG = MEDIA .. "bag",
    CROSS = MEDIA .. "cross",
    PLUS = MEDIA .. "plus",
    FUNNEL = MEDIA .. "funnel",
    TICK = MEDIA .. "check",
    OPACITY = MEDIA .. "opacity",
    WAND = MEDIA .. "wand",
    SCALES = MEDIA .. "scales",
    FOREVER = MEDIA .. "infinity",
    FOREVER_ICON = MEDIA .. "infinity_outlined",
    ELBOW = MEDIA .. "elbow",
    IMPORT = MEDIA .. "import",
    EXPORT = MEDIA .. "export",
    ROUND = MEDIA .. "circle_mask",
    RING = MEDIA .. "circle_ring",
    LIST_SHOWN = MEDIA .. "sidebar_shown",
    LIST_HIDDEN = MEDIA .. "sidebar_hidden",
    SEARCH = MEDIA .. "Navigation\\search.tga",
    PLAY = MEDIA .. "play",
    PAUSE = MEDIA .. "pause",
    RESET = MEDIA .. "reset",
    EYE = MEDIA .. "eye",
    EYE_OFF = MEDIA .. "eye_off",
    LOCK = MEDIA .. "lock",
    ALIGN_LEFT = MEDIA .. "align_left",
    ALIGN_HCENTER = MEDIA .. "align_hcenter",
    ALIGN_RIGHT = MEDIA .. "align_right",
    ALIGN_TOP = MEDIA .. "align_top",
    ALIGN_VCENTER = MEDIA .. "align_vcenter",
    ALIGN_BOTTOM = MEDIA .. "align_bottom",
    ALIGN_ACROSS = MEDIA .. "align_across",
    ALIGN_DOWN = MEDIA .. "align_down",
    SOFT_SHADE = MEDIA .. "soft_shade",
    CHECK = "Interface\\RaidFrame\\ReadyCheck-Ready",
    WHITE = "Interface\\Buttons\\WHITE8X8",
    CLASS_ICONS = "Interface\\Glues\\CharacterCreate\\UI-CharacterCreate-Classes",
    CLASS_CROP = 0.02,
    ICON_CROP = 0.08,
    ICON_CROP_HIGH = 0.92,
    PLACE_DOT = " \194\183 ",

    TEXT_SIZE = 12,
    SMALL_SIZE = 11,
    GAP = 6,
    INDENT = 20,
    SECTION_H = 28,
    SECTION_TIGHT_H = 20,
    SECTION_SPACE = 8,
    NOTE_PAD = 6,
    ACTION = 16,
    STRIPE = 0.025,
    HOVER = 0.05,

    CARD_FILL = 0.025,
    CARD_PAD = 10,
    CARD_GAP = 10,
    CARD_BOTTOM = 6,
    CARD_MIN_W = 310,
    MAX_COLUMNS = 3,
    CARD_HEADER_H = 38,
    CARD_NAME_SIZE = 15,

    ICON = 30,
    ITEM_H = 40,

    WINDOW_FOOTER = 20,
    WINDOW_HEADER = 52,
    WINDOW_PAD = 12,
    WINDOW_CARD_FILL = 0.035,
    WINDOW_CARD_EDGE = 0.7,
    CONTENT_INSET = 22,
    SCROLLBAR = 16,
    SEARCH_H = 24,
    TAB_SIZE = 12,
    TAB_H = 26,
    TAB_LINE = 2,
    TAB_FILL = 0.16,
    TAB_GAP = 6,
    LOGO_SIZE = 32,
    BAR_ICON = 18,
    BAR_GAP = 12,
    SLIDER_W = 90,
    SLIDER_H = 4,
    KNOB = 12,
    KNOB_GLOW = 22,
    OPACITY_MIN = OPACITY_MIN,
    OPACITY_MAX = PERCENT_MAX,
    OPACITY_STEP = PERCENT_STEP,
    OPACITY_RANGE = { OPACITY_MIN, PERCENT_MAX, PERCENT_STEP },
    ALPHA_RANGE = { 0, PERCENT_MAX, PERCENT_STEP },
    PERCENT_SCALE = 0.01,
    SCALE_RANGE = { 50, 150, PERCENT_STEP },
    PIN_SIZE_RANGE = { 12, 32, 1 },
    HUD_TEXT_RANGE = { 8, 24, 1 },
    STAGE_MARGIN = 16,
    STAGE_NOTE_Y = 10,
    STAGE_NOTE_SIZE = 11,
    PANEL_W = 380,
    PANEL_PAD = 10,
    PANEL_HEADER = 30,
    PANEL_BUTTONS = 34,
    PANEL_INSET = 4,
    CLOSE_SIZE = 20,
    CLOSE_IN = 6,

    TRACKER_W = 320,
    TRACKER_SLOT = 24,
    TRACKER_BAR_RGB = { r = 0x14 / 255, g = 0x16 / 255, b = 0x19 / 255 },
    TRACKER_GAP = 6,
    TRACKER_SCROLL = 20,
    CLOSE_ROOM = 34,
    ROW_LEFT = 6,
    WAYPOINT_SLOT = 20,
    ROW_TOP = 6,
    ROW_LINE_GAP = 3,
    ROW_BOTTOM = 8,
    ROW_RIGHT = 10,
    ROW_HOVER = 0.04,
    ROW_DIVIDER = 0.6,
    ROW_TICK = 16,
    OPEN_TURN = -PI / 2,
}
