-- Style.lua: the house look every module shares (ns.Shared.Style): colors, icons and sizes.
local Shared = _G.NaowhForever.Shared

local PI = 3.141592653589793
local OPACITY_MIN, PERCENT_MAX, PERCENT_STEP = 40, 100, 5
local MEDIA = "Interface\\AddOns\\NaowhForever\\Core\\Media\\"

Shared.Style = {
    BORDER_RGB = { r = 0, g = 0, b = 0 },
    BACKDROP_ALPHA = 0.97,
    HUD_SHADOW_RGB = { r = 0, g = 0, b = 0 },
    HUD_SHADOW_ALPHA = 0.8,
    HUD_SHADOW_X = 1,
    HUD_SHADOW_Y = -1,
    HUD_CARD_ALPHA = 0.85,
    HUD_SOFT_ALPHA = 0.7,
    HUD_SOFT_FADE = 32,
    HUD_SOFT_INSET = 12,
    HUD_SOFT_SHADOW_ALPHA = 1,
    HUD_BARE_SHADOW_ALPHA = 1,
    HUD_BARE_SHADOW_X = 1,
    HUD_BARE_SHADOW_Y = -1,
    SHADOW_ALPHA = 0.4,
    SHADOW_SIZE = 48,
    CLASSIC_GOLD_RGB = { r = 0xd4 / 255, g = 0xaf / 255, b = 0x37 / 255 },
    CLASSIC_BRONZE_RGB = { r = 0x5e / 255, g = 0x4a / 255, b = 0x1c / 255 },
    CLASSIC_TRIM_BODY = 3,
    CLASSIC_GEM = 12,
    CLASSIC_GEM_EDGE = 2,
    CLASSIC_PLATE_H = 30,
    CLASSIC_PLATE_BODY = 2,
    CLASSIC_PLATE_PAD = 34,
    CLASSIC_PLATE_SIZE = 16,
    CLASSIC_TITLE_RGB = { r = 0xf4 / 255, g = 0xcf / 255, b = 0x63 / 255 },
    CLASSIC_PLATE_GEM = 7,
    CLASSIC_PLATE_GEM_GAP = 12,
    CLASSIC_BUTTON_RGB = {
        rest  = { { r = 0xb4 / 255, g = 0x2a / 255, b = 0x1d / 255 }, { r = 0x5a / 255, g = 0x0b / 255, b = 0x06 / 255 } },
        hover = { { r = 0xd2 / 255, g = 0x3a / 255, b = 0x2a / 255 }, { r = 0x82 / 255, g = 0x14 / 255, b = 0x0b / 255 } },
        down  = { { r = 0x4e / 255, g = 0x09 / 255, b = 0x06 / 255 }, { r = 0x8a / 255, g = 0x16 / 255, b = 0x0d / 255 } },
    },
    CLASSIC_RIM_LIT_RGB = { r = 0xff / 255, g = 0xe2 / 255, b = 0x8a / 255 },
    CLASSIC_BUTTON_SHINE = 0.1,
    CLASSIC_BEVEL_RGB = { r = 0x6b / 255, g = 0x62 / 255, b = 0x52 / 255 },
    CLASSIC_FILL_RGB = { { r = 0xc7 / 255, g = 0x9a / 255, b = 0x3a / 255 }, { r = 0x6e / 255, g = 0x50 / 255, b = 0x19 / 255 } },
    CLASSIC_KNOB_EDGE = 2,
    CLASSIC_CHECK = "Interface\\Buttons\\UI-CheckBox-Check",
    CLASSIC_CHECK_SCALE = 1.3,
    CLASSIC_TAB_RGB = { { r = 0x3d / 255, g = 0x2d / 255, b = 0x19 / 255 }, { r = 0x1a / 255, g = 0x12 / 255, b = 0x0a / 255 } },
    CLASSIC_PICK_RGB = { r = 0x46 / 255, g = 0x78 / 255, b = 0xd2 / 255 },
    CLASSIC_PICK_ALPHA = 0.6,
    CLASSIC_PICK_FADE = 0.1,
    CLASSIC_PICK_LINE_RGB = { r = 0x96 / 255, g = 0xbe / 255, b = 0xff / 255 },
    CLASSIC_PICK_LINE_ALPHA = 0.4,
    CLASSIC_SECTION_GEM = 7,
    CLASSIC_SECTION_GEM_GAP = 8,
    CLASSIC_TIP_RGB = { r = 0x02 / 255, g = 0x02 / 255, b = 0x12 / 255 },
    CLASSIC_TIP_ALPHA = 0.94,
    CLASSIC_TIP_EDGE_RGB = { r = 0x9a / 255, g = 0x9a / 255, b = 0xb0 / 255 },
    CLASSIC_PATTERN = "Interface\\FrameGeneral\\UI-Background-Rock",
    CLASSIC_PATTERN_SHADE = 0.6,
    CLASSIC_PATTERN_ALPHA = 0.55,
    CLASSIC_HEADING_STEP = 1,
    CLASSIC_HEADING_SHADOW = 1,
    CLASSIC_ICON_PATH = "Interface\\Icons\\",
    CLASSIC_ICON_CROP = 0.07,
    CLASSIC_ICONS = {
        checklist = "INV_Misc_Note_01", map = "INV_Misc_Book_09", trophy = "INV_Chest_Plate16",
        notes = "INV_Misc_Book_11", compass = "INV_Misc_Map_01", shield = "INV_Shield_06",
        spark = "Spell_Holy_FistOfJustice", hammer = "Trade_BlackSmithing", pen = "INV_Scroll_03",
        grid = "INV_Misc_Gear_02", aura = "Spell_Holy_WordFortitude", bars = "Ability_Warrior_DefensiveStance",
        group = "Ability_Warrior_RallyingCry", swords = "Ability_DualWield", infinity = "Ability_MeleeDamage",
        settings = "INV_Misc_Gear_01", person = "INV_Misc_Head_Human_01", heart = "Spell_Holy_Heal",
        friends = "INV_Letter_01", guild = "INV_Shirt_GuildTabard_01", hearth = "INV_Misc_Rune_01",
        NaowhForeverJournal = "INV_Misc_Book_09", NaowhForeverBiS = "INV_Chest_Plate16",
        NaowhForeverGroup = "Ability_Warrior_RallyingCry", NaowhForeverTraining = "INV_Misc_Book_11",
        NaowhForeverDiscovery = "INV_Misc_Map_01",
    },
    CLASSIC_HIGHLIGHT = "Interface\\Buttons\\ButtonHilight-Square",
    RED_CODE = "|cfff87171",
    RED_RGB = { r = 0.97, g = 0.44, b = 0.44 },
    WARN_CODE = "|cfffb923c",
    WARN_RGB = { r = 0xfb / 255, g = 0x92 / 255, b = 0x3c / 255 },
    GOLD_CODE = "|cffe6cc80",
    TIP_RGB = { r = 0.9, g = 0.8, b = 0.5 },
    BIS_CODE = "|cffff8000",
    BIS_RGB = { r = 1, g = 0.5, b = 0 },
    SECOND_CODE = "|cffc7ccdb",
    SECOND_RGB = { r = 0xc7 / 255, g = 0xcc / 255, b = 0xdb / 255 },
    LOOK_CODE = "|cff66d9ef",
    LOOK_RGB = { r = 0x66 / 255, g = 0xd9 / 255, b = 0xef / 255 },
    UPGRADE_CODE = "|cff1eff00",
    HAVE_RGB = { r = 0.3, g = 0.82, b = 0.48 },
    FOREVER_CODE = "|cffeed69e",
    FOREVER_RGB = { r = 0xee / 255, g = 0xd6 / 255, b = 0x9e / 255 },
    CARRIED_RGB = { r = 1, g = 0.82, b = 0 },
    TIME_OK_RGB = { r = 0.29, g = 0.87, b = 0.5 },
    TIME_LOW_RGB = { r = 0.98, g = 0.8, b = 0.08 },
    TIME_OUT_RGB = { r = 0.97, g = 0.27, b = 0.27 },
    PICKED_RGB = { r = 1, g = 0.82, b = 0 },
    TIP_TITLE_RGB = { r = 1, g = 1, b = 1 },
    GUIDE_RGB = { r = 0xf2 / 255, g = 0xa3 / 255, b = 0x3a / 255 },

    ARROW = MEDIA .. "chevron",
    UP = MEDIA .. "chevron_up",
    HANGER = MEDIA .. "hanger",
    STAR = MEDIA .. "star",
    UPGRADE_ATLAS = "bags-greenarrow",
    SCRAP_ATLAS = "bags-icon-scrappable",
    SCRAP_RATIO = 32 / 36,
    CLOCK_ATLAS = "auctionhouse-icon-clock",
    QUEST_ATLAS = "smallquestbang",
    PIN = MEDIA .. "pin",
    GEM = MEDIA .. "waypoint_diamond",
    CHAIN = MEDIA .. "chain",
    INFO = MEDIA .. "info",
    LOGO = MEDIA .. "LogoAddon",
    LOGO_SMALL = MEDIA .. "LogoSmall",
    BAG = MEDIA .. "bag",
    CROSS = MEDIA .. "cross",
    PLUS = MEDIA .. "plus",
    FUNNEL = MEDIA .. "funnel",
    TICK = MEDIA .. "check",
    OPACITY = MEDIA .. "opacity",
    WAND = MEDIA .. "wand",
    SCALES = MEDIA .. "scales",
    FOREVER = MEDIA .. "infinity",
    FOREVER_ICON = MEDIA .. "infinity_outlined",
    ELBOW = MEDIA .. "elbow",
    IMPORT = MEDIA .. "import",
    EXPORT = MEDIA .. "export",
    ROUND = MEDIA .. "circle_mask",
    LIST_SHOWN = MEDIA .. "sidebar_shown",
    LIST_HIDDEN = MEDIA .. "sidebar_hidden",
    SEARCH = MEDIA .. "Navigation\\search.tga",
    PLAY = MEDIA .. "play",
    PAUSE = MEDIA .. "pause",
    RESET = MEDIA .. "reset",
    EYE = MEDIA .. "eye",
    EYE_OFF = MEDIA .. "eye_off",
    LOCK = MEDIA .. "lock",
    ALIGN_LEFT = MEDIA .. "align_left",
    ALIGN_HCENTER = MEDIA .. "align_hcenter",
    ALIGN_RIGHT = MEDIA .. "align_right",
    ALIGN_TOP = MEDIA .. "align_top",
    ALIGN_VCENTER = MEDIA .. "align_vcenter",
    ALIGN_BOTTOM = MEDIA .. "align_bottom",
    ALIGN_ACROSS = MEDIA .. "align_across",
    ALIGN_DOWN = MEDIA .. "align_down",
    SOFT_SHADE = MEDIA .. "soft_shade",
    CHECK = "Interface\\RaidFrame\\ReadyCheck-Ready",
    WHITE = "Interface\\Buttons\\WHITE8X8",
    CLASS_ICONS = "Interface\\Glues\\CharacterCreate\\UI-CharacterCreate-Classes",
    CLASS_CROP = 0.02,
    ICON_CROP = 0.08,
    ICON_CROP_HIGH = 0.92,
    PLACE_DOT = " \194\183 ",

    TEXT_SIZE = 12,
    SMALL_SIZE = 11,
    GAP = 6,
    INDENT = 20,
    SECTION_H = 28,
    SECTION_TIGHT_H = 20,
    SECTION_SPACE = 8,
    NOTE_PAD = 6,
    ACTION = 16,
    STRIPE = 0.025,
    HOVER = 0.05,

    CARD_FILL = 0.025,
    CARD_PAD = 10,
    CARD_GAP = 10,
    CARD_BOTTOM = 6,
    CARD_MIN_W = 310,
    MAX_COLUMNS = 3,
    CARD_HEADER_H = 38,
    CARD_NAME_SIZE = 15,

    ICON = 30,
    ITEM_H = 40,

    WINDOW_FOOTER = 20,
    WINDOW_HEADER = 52,
    WINDOW_PAD = 12,
    WINDOW_CARD_FILL = 0.035,
    WINDOW_CARD_EDGE = 0.7,
    CONTENT_INSET = 22,
    SCROLLBAR = 16,
    SEARCH_H = 24,
    TAB_SIZE = 12,
    TAB_H = 26,
    TAB_LINE = 2,
    TAB_FILL = 0.16,
    TAB_GAP = 6,
    LOGO_SIZE = 32,
    BAR_ICON = 18,
    BAR_GAP = 12,
    SLIDER_W = 90,
    SLIDER_H = 4,
    KNOB = 12,
    KNOB_GLOW = 22,
    OPACITY_MIN = OPACITY_MIN,
    OPACITY_MAX = PERCENT_MAX,
    OPACITY_STEP = PERCENT_STEP,
    OPACITY_RANGE = { OPACITY_MIN, PERCENT_MAX, PERCENT_STEP },
    ALPHA_RANGE = { 0, PERCENT_MAX, PERCENT_STEP },
    PERCENT_SCALE = 0.01,
    SCALE_RANGE = { 50, 150, PERCENT_STEP },
    PIN_SIZE_RANGE = { 12, 32, 1 },
    HUD_TEXT_RANGE = { 8, 24, 1 },
    STAGE_MARGIN = 16,
    STAGE_NOTE_Y = 10,
    STAGE_NOTE_SIZE = 11,
    PANEL_W = 380,
    PANEL_PAD = 10,
    PANEL_HEADER = 30,
    PANEL_BUTTONS = 34,
    PANEL_INSET = 4,
    CLOSE_SIZE = 20,
    CLOSE_IN = 6,

    TRACKER_W = 320,
    TRACKER_SLOT = 24,
    TRACKER_BAR_RGB = { r = 0x14 / 255, g = 0x16 / 255, b = 0x19 / 255 },
    TRACKER_GAP = 6,
    TRACKER_SCROLL = 20,
    CLOSE_ROOM = 34,
    ROW_LEFT = 6,
    WAYPOINT_SLOT = 20,
    ROW_TOP = 6,
    ROW_LINE_GAP = 3,
    ROW_BOTTOM = 8,
    ROW_RIGHT = 10,
    ROW_HOVER = 0.04,
    ROW_DIVIDER = 0.6,
    ROW_TICK = 16,
    OPEN_TURN = -PI / 2,
}
