"""Each Dungeon Journal boss's abilities, from the Abilities tab of its Wowhead Forever NPC
page, written to DungeonJournal/Data/Abilities.lua as spell IDs keyed by NPC ID. Only the IDs:
the game gives each one's name, icon and description when the Journal shows it.

The bosses are read from DungeonJournal/Data/Dungeons (their npc = ...); pages are kept in
Tools/abilities_cache.json, so a run only fetches bosses not seen yet. --refresh fetches all.

Usage: py Tools/build_abilities.py [--refresh]
"""
import json
import os
import re
import sys
import urllib.error

import wowhead

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DUNGEONS = os.path.join(ROOT, "DungeonJournal", "Data", "Dungeons")
OUT = os.path.join(ROOT, "DungeonJournal", "Data", "Abilities.lua")
CACHE = os.path.join(ROOT, "Tools", "abilities_cache.json")

# One ability in the listview's data: its ID and name, in the order Wowhead lists them.
ABILITY = re.compile(r'"displayName":"((?:[^"\\]|\\.)*)","id":(\d+)')

HEADER = """-------------------------------------------------------------------------------
--  Data/Abilities.lua -- each boss's abilities, as the spell IDs on the Abilities tab of its
--  Wowhead Forever NPC page, keyed by its NPC ID. Generated by Tools/build_abilities.py; do
--  not edit by hand. The game gives each one's name, icon and description.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.Abilities = {
"""


def bosses():
    """(dungeon file, npc, name) for every boss with an NPC ID, in load order of the files."""
    found = []
    for file in sorted(os.listdir(DUNGEONS)):
        with open(os.path.join(DUNGEONS, file), encoding="utf-8") as f:
            text = f.read()
        dungeon = re.search(r'name = "([^"]+)"', text).group(1)
        for npc, name in re.findall(r'\{ npc = (\d+), name = "((?:[^"\\]|\\.)*)"', text):
            found.append((dungeon, int(npc), name))
    return found


def abilities(page):
    """The (spell ID, name) pairs on a page's Abilities tab, or [] with none."""
    start = page.find("id: 'abilities'")
    if start < 0:
        return []
    data = page.find("data:", start)
    end = page.find("});", data)
    return [(int(spell), name) for name, spell in ABILITY.findall(page[data:end])]


def main():
    refresh = "--refresh" in sys.argv
    cache = {}
    if os.path.exists(CACHE) and not refresh:
        with open(CACHE, encoding="utf-8") as f:
            cache = json.load(f)
    lines, dungeon_was = [], None
    for dungeon, npc, name in bosses():
        key = str(npc)
        if key not in cache:
            print(f"  {name} ({npc})", file=sys.stderr)
            try:
                cache[key] = abilities(wowhead.fetch(f"{wowhead.WOWHEAD}/npc={npc}"))
            except urllib.error.HTTPError as e:
                # No page for it on Wowhead Forever: none listed.
                if e.code != 404:
                    raise
                print("    no page", file=sys.stderr)
                cache[key] = []
            with open(CACHE, "w", encoding="utf-8", newline="\n") as f:
                json.dump(cache, f, indent=1, sort_keys=True)
        spells = cache[key]
        if not spells:
            continue
        if dungeon != dungeon_was:
            lines.append(f"    -- {dungeon}")
            dungeon_was = dungeon
        ids = ", ".join(str(spell) for spell, _ in spells)
        names = ", ".join(n for _, n in spells)
        lines.append(f"    [{npc}] = {{ {ids} }},  -- {name}: {names}")
    text = HEADER + "\n".join(lines) + "\n}\n"
    # The addon's files are ASCII with CRLF line ends.
    text = text.encode("ascii", "replace").decode("ascii")
    with open(OUT, "w", encoding="ascii", newline="\r\n") as f:
        f.write(text)
    print(f"{len(lines)} lines to {os.path.relpath(OUT, ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
