"""What is new in WoW Forever: the items, quests and NPCs Wowhead's Forever database marks as
new (not in the original game), for the addon's Forever mark (Shared/Data/Forever.lua).

Wowhead lists a thousand rows a page at most, so each kind is read by ID range, a range
split in two whenever it comes back full, and only "new" rows are kept (not "updated" or
"unchanged"). Only the IDs the addon's own data mentions are written, so the file stays
small. Answers are cached in Tools/forever_new.json; pass --refresh to read Wowhead again.

Run from the repo root: python Tools/build_forever_new.py [--refresh]
"""
import glob
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
from wowhead import WOWHEAD, fetch  # noqa: E402

ROOT = os.path.join(os.path.dirname(__file__), "..")
CACHE = os.path.join(os.path.dirname(__file__), "forever_new.json")
OUT = os.path.join(ROOT, "Shared", "Data", "Forever.lua")
# Wowhead shows a thousand rows at most, a few of them without a status: a page this full may
# have more past it, so its range is split.
FULL = 900

# Each kind: its list page, its listview, the filter on ID, the highest ID to read, and the
# addon's files that mention it.
KINDS = {
    "items": {"page": "items", "filter": 151, "top": 400000, "files": [
        "NaowhForever_DungeonJournal/Data/Items.lua", "NaowhForever_DungeonJournal/Data/Dungeons/*.lua",
        "NaowhForever_DungeonJournal/Data/FactionItems.lua", "NaowhForever_DungeonJournal/Data/Factions/*.lua",
        "NaowhForever_DungeonJournal/Data/BiSQuests.lua", "NaowhForever_DungeonJournal/Data/Quests.lua", "NaowhForever_BiS/BiS/Data/*.lua"]},
    "quests": {"page": "quests", "filter": 30, "top": 200000, "files": [
        "NaowhForever_DungeonJournal/Data/Quests.lua", "NaowhForever_DungeonJournal/Data/QuestChains.lua",
        "NaowhForever_DungeonJournal/Data/BiSQuests.lua"]},
    "npcs": {"page": "npcs", "filter": 37, "top": 400000, "files": ["NaowhForever_DungeonJournal/Data/Dungeons/*.lua"]},
}

# A row of a listview, items' (JavaScript) or the others' (JSON): its ID, then its status,
# with no other row's ID in between.
ROW = re.compile(r'"id":(\d+),(?:(?!"id":\d).)*?"envChange":\{"status":"(\w+)"', re.S)


def rows(page, name):
    start = max(page.find(f"id: '{name}'"), page.find(f'"id":"{name}"'))
    data = page.rfind("var listview" + name, 0, start) if start >= 0 else -1
    if data < 0:   # the data inline, after the listview's id
        data = start
    end = page.find("</script>", data)
    return [(int(i), status) for i, status in ROW.findall(page[data:end])] if data >= 0 else []


def read(kind, low, high, found):
    spec = KINDS[kind]
    f = spec["filter"]
    page = fetch(f"{WOWHEAD}/{spec['page']}?filter={f}:{f};2:4;{low}:{high}")
    # Only the rows in the range: past the IDs Wowhead's filter takes (a quest's stops at
    # 100000), it ignores the filter and lists its usual first page instead.
    got = [(i, status) for i, status in rows(page, spec["page"]) if low <= i <= high]
    if len(got) >= FULL and high > low:
        mid = (low + high) // 2
        read(kind, low, mid, found)
        read(kind, mid + 1, high, found)
        return
    print(f"  {kind} {low}-{high}: {len(got)}, {sum(1 for _, s in got if s == 'new')} new", file=sys.stderr)
    found.extend(i for i, status in got if status == "new")


def mentioned(patterns):
    ids = set()
    for pattern in patterns:
        for path in glob.glob(os.path.join(ROOT, pattern)):
            with open(path, encoding="utf-8") as fh:
                ids.update(int(n) for n in re.findall(r"\b\d{2,6}\b", fh.read()))
    return ids


def lua_set(ids):
    lines, line = [], "       "
    for i in sorted(ids):
        part = f" [{i}] = true,"
        if len(line) + len(part) > 100:
            lines.append(line)
            line = "       "
        line += part
    if line.strip():
        lines.append(line)
    return "\n".join(lines)


def main():
    cache = {}
    if os.path.exists(CACHE) and "--refresh" not in sys.argv:
        with open(CACHE, encoding="utf-8") as fh:
            cache = json.load(fh)
    for kind, spec in KINDS.items():
        if kind not in cache:
            found = []
            read(kind, 1, spec["top"], found)
            cache[kind] = sorted(set(found))
            with open(CACHE, "w", encoding="utf-8") as fh:
                json.dump(cache, fh, indent=1)
    out = ["-------------------------------------------------------------------------------",
           "--  Data/Forever.lua -- what is new in WoW Forever, by ID: the items, quests and NPCs",
           "--  Wowhead's Forever database marks as new (not in the original game), for the Forever mark",
           "--  (Shared/Parts.lua). Only the IDs the addon's own data mentions. Generated by",
           "--  Tools/build_forever_new.py; do not edit by hand.",
           "-------------------------------------------------------------------------------",
           "local ns = _G.NaowhForever", "", "ns.Shared.ForeverNew = {"]
    for kind, spec in KINDS.items():
        keep = set(cache[kind]) & mentioned(spec["files"])
        print(f"{kind}: {len(cache[kind])} new in Forever, {len(keep)} of them in the addon's data")
        out += [f"    {kind} = {{", lua_set(keep), "    },"]
    out.append("}")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="ascii", newline="\r\n") as fh:
        fh.write("\n".join(out) + "\n")
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
