"""Build the town map's mailboxes from Wowhead Forever.

Wowhead's mailbox list (wowhead.com/forever/objects/mailboxes) names every mailbox object; each
object's own page has where it stands, as map percentages by world map ID (g_mapperData), the
same IDs and units as the town map's NPCs. Wowhead lists one mailbox several times, under
more than one object or spawn, up to a couple of percent apart: points that chain within SAME
of each other are one mailbox, pinned at its most central point, one Wowhead has (an average
of a stretched group could fall between two mailboxes).

Wowhead's answers are kept in Tools/mailbox_cache.json; delete it to ask again.

Writes QoL/NaowhForever_TownMailboxes.lua.

Usage: python Tools/build_mailboxes.py
"""
import json
import re

from wowhead import WOWHEAD, fetch
from build_journal import ROOT, TOOLS, header, write

OUT = ROOT / "QoL" / "NaowhForever_TownMailboxes.lua"
CACHE = TOOLS / "mailbox_cache.json"
SAME = 2.5   # map percent: points chained closer than this are one mailbox


def mailbox_ids():
    page = fetch(f"{WOWHEAD}/objects/mailboxes")
    return sorted({int(i) for i in re.findall(r'"id":(\d+),"location":\[[^\]]*\],"name":"', page)})


def positions(object_id, kind="object"):
    """{ map ID: [[x, y], ...] } from the object's (or NPC's) page."""
    page = fetch(f"{WOWHEAD}/{kind}={object_id}")
    m = re.search(r"g_mapperData = (\{.*?\});", page)
    found = {}
    for floors in (json.loads(m.group(1)) if m else {}).values():
        for floor in floors:
            found.setdefault(str(floor["uiMapId"]), []).extend(floor["coords"])
    return found


def central(points):
    """The point with the least distance to the rest."""
    return min(points, key=lambda p: sum((p[0] - q[0]) ** 2 + (p[1] - q[1]) ** 2 for q in points))


def merge(found):
    """{ map ID: [(x, y), ...] } from positions() answers, the points that chain within SAME of
    each other as one, at its most central point."""
    groups_by_map = {}
    for spots in found:
        for map_id, coords in spots.items():
            groups = groups_by_map.setdefault(int(map_id), [])
            for x, y in coords:
                near = [g for g in groups if any((x - gx) ** 2 + (y - gy) ** 2 < SAME ** 2 for gx, gy in g)]
                merged = [(x, y)]
                for g in near:
                    merged += g
                    groups.remove(g)
                groups.append(merged)
    return {map_id: [central(g) for g in groups] for map_id, groups in groups_by_map.items()}


def main():
    cache = json.loads(CACHE.read_text(encoding="utf-8")) if CACHE.exists() else {}
    for object_id in mailbox_ids():
        if str(object_id) not in cache:
            print(f"object {object_id}")
            cache[str(object_id)] = positions(object_id)
            CACHE.write_text(json.dumps(cache, indent=1, sort_keys=True) + "\n", encoding="utf-8")
    by_map = merge(cache.values())
    lines = header(
        "NaowhForever_TownMailboxes.lua -- mailboxes on the town map, by world map, from",
        "Wowhead Forever. Generated by Tools/build_mailboxes.py; do not edit by hand.",
        "",
        "[uiMapID] = { { x, y, \"mail\", name, title, class, factions }, ... }, as NaowhForever_TownData.lua",
        "lists its NPCs. x and y are map percentages; every mailbox serves both factions.",
    )
    lines.append("ns.TownMailboxes = {")
    total = 0
    for map_id in sorted(by_map):
        lines.append(f"    [{map_id}] = {{")
        for x, y in sorted(by_map[map_id]):
            lines.append(f'        {{ {x:g}, {y:g}, "mail", "Mailbox", "", nil, "AH" }},')
            total += 1
        lines.append("    },")
    lines.append("}")
    write(OUT, lines)
    print(f"{total} mailboxes on {len(by_map)} maps -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
