"""What a boss's page in the Dungeon Journal shows of each boss beyond its loot, from its
Wowhead Forever NPC page:

- its abilities, from the page's Abilities tab, to NaowhForever_DungeonJournal/Data/Abilities.lua as spell
  IDs keyed by NPC ID, each name once (the first Wowhead lists). Only the IDs: the game gives
  each one's name, icon and description.
- its level, classification (Elite, Rare...), creature type and title ("Ragefire
  Chieftain"), to NaowhForever_DungeonJournal/Data/BossInfo.lua, for the page's header.

The bosses are read from NaowhForever_DungeonJournal/Data/Dungeons (their npc = ...); what each page gives
is kept in Tools/abilities_cache.json, so a run only fetches bosses not seen yet (or seen
before the cache kept the header's facts). --refresh fetches all; --offline fetches nothing
and writes what the cache has (a boss not fetched yet is left out until the next run).

Usage: py Tools/build_abilities.py [--refresh]
"""
import json
import os
import re
import sys
import urllib.error

import wowhead

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DUNGEONS = os.path.join(ROOT, "NaowhForever_DungeonJournal", "Data", "Dungeons")
OUT = os.path.join(ROOT, "NaowhForever_DungeonJournal", "Data", "Abilities.lua")
INFO_OUT = os.path.join(ROOT, "NaowhForever_DungeonJournal", "Data", "BossInfo.lua")
CACHE = os.path.join(ROOT, "Tools", "abilities_cache.json")

# One ability in the listview's data: its ID and name, in the order Wowhead lists them.
ABILITY = re.compile(r'"displayName":"((?:[^"\\]|\\.)*)","id":(\d+)')

# Abilities.lua: each boss's abilities, as the spell IDs on the Abilities tab of its Wowhead
# Forever NPC page, keyed by its NPC ID. The game gives each one's name, icon and description.
HEADER = """-- Abilities.lua: each boss's abilities as spell IDs, generated by Tools/build_abilities.py.
local ns = _G.NaowhForever

ns.Journal.Abilities = {
"""


# BossInfo.lua: each boss as its Wowhead Forever NPC page has it, for the header of its page in
# the Dungeon Journal: { lowest level, highest level (-1: ??), classification (0 normal, 1 elite,
# 2 rare elite, 3 boss, 4 rare), creature type (Wowhead's number: 7 is Humanoid), its title or
# nil }, keyed by NPC ID.
INFO_HEADER = """-- BossInfo.lua: each boss's level, kind and title, generated by Tools/build_abilities.py.
local ns = _G.NaowhForever

ns.Journal.BossInfo = {
"""

# The NPC's own record on its page: level, classification, type, its title.
NPC = re.compile(r"g_npcs\[(\d+)\], (\{.*?\})\);")


def npc_facts(page, npc):
    """{minlevel, maxlevel, classification, type, tag} from the page, or None."""
    for found, body in NPC.findall(page):
        if int(found) != npc:
            continue
        try:
            data = json.JSONDecoder().raw_decode(body)[0]
        except ValueError:
            return None
        return {k: data.get(k) for k in ("minlevel", "maxlevel", "classification", "type", "tag")}
    return None


def lua_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def bosses():
    """(dungeon file, npc, name) for every boss with an NPC ID, in load order of the files."""
    found = []
    for file in sorted(os.listdir(DUNGEONS)):
        with open(os.path.join(DUNGEONS, file), encoding="utf-8") as f:
            text = f.read()
        dungeon = re.search(r'name = "([^"]+)"', text).group(1)
        for npc, name in re.findall(r'\{ npc = (\d+), name = "((?:[^"\\]|\\.)*)"', text):
            found.append((dungeon, int(npc), name))
    return found


def abilities(page):
    """The (spell ID, name) pairs on a page's Abilities tab, or [] with none."""
    start = page.find("id: 'abilities'")
    if start < 0:
        return []
    data = page.find("data:", start)
    end = page.find("});", data)
    return [(int(spell), name) for name, spell in ABILITY.findall(page[data:end])]


def unique_by_name(spells):
    """The (spell ID, name) pairs with each name once: the first of each, in Wowhead's order."""
    seen, out = set(), []
    for spell, name in spells:
        if name not in seen:
            seen.add(name)
            out.append((spell, name))
    return out


def main():
    refresh = "--refresh" in sys.argv
    cache = {}
    if os.path.exists(CACHE) and not refresh:
        with open(CACHE, encoding="utf-8") as f:
            cache = json.load(f)
    offline = "--offline" in sys.argv
    lines, info_lines = [], []
    for dungeon, npc, name in bosses():
        key = str(npc)
        entry = cache.get(key)
        # An entry from before the cache kept the header's facts is a bare list: fetched again,
        # or offline, its abilities kept and its header left for the next run.
        if not isinstance(entry, dict) and offline:
            entry = {"abilities": entry if isinstance(entry, list) else [], "npc": None}
        elif not isinstance(entry, dict):
            print(f"  {name} ({npc})", file=sys.stderr)
            try:
                page = wowhead.fetch(f"{wowhead.WOWHEAD}/npc={npc}")
                entry = {"abilities": abilities(page), "npc": npc_facts(page, npc)}
            except urllib.error.HTTPError as e:
                # No page for it on Wowhead Forever: nothing listed.
                if e.code != 404:
                    raise
                print("    no page", file=sys.stderr)
                entry = {"abilities": [], "npc": None}
            cache[key] = entry
            with open(CACHE, "w", encoding="utf-8", newline="\n") as f:
                json.dump(cache, f, indent=1, sort_keys=True)
        spells, facts = unique_by_name(entry["abilities"]), entry["npc"]
        if facts:
            high = facts["maxlevel"]
            high = -1 if high is None or high >= 9999 else high
            low = facts["minlevel"] if facts["minlevel"] is not None else high
            low = -1 if low >= 9999 else low
            tag = lua_string(facts["tag"]) if facts.get("tag") else "nil"
            info_lines.append(f"    [{npc}] = {{ {low}, {high}, {facts['classification'] or 0}, "
                              f"{facts['type'] or 0}, {tag} }},")
        if not spells:
            continue
        ids = ", ".join(str(spell) for spell, _ in spells)
        lines.append(f"    [{npc}] = {{ {ids} }},")
    for path, header, body in ((OUT, HEADER, lines), (INFO_OUT, INFO_HEADER, info_lines)):
        text = header + "\n".join(body) + "\n}\n"
        # The addon's files are ASCII with CRLF line ends.
        text = text.encode("ascii", "replace").decode("ascii")
        with open(path, "w", encoding="ascii", newline="\r\n") as f:
            f.write(text)
        print(f"{len(body)} lines to {os.path.relpath(path, ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
