"""Build the town map's spirit healers from Wowhead Forever.

Forever's C_DeathInfo.GetGraveyardsForMap returns nothing while you are alive, so the town map
cannot ask the game. Every graveyard's healer is the one Spirit Healer NPC, whose Wowhead page
has where each one stands (g_mapperData), as the mailboxes' pages do; spawns a step apart are
one healer, merged as Tools/build_mailboxes.py does.

Writes QoL/NaowhForever_TownSpiritHealers.lua.

Usage: python Tools/build_spirit_healers.py
"""
from build_journal import ROOT, header, write
from build_mailboxes import merge, positions

OUT = ROOT / "QoL" / "NaowhForever_TownSpiritHealers.lua"
SPIRIT_HEALER = 6491   # the NPC


def main():
    by_map = merge([positions(SPIRIT_HEALER, "npc")])
    lines = header(
        "NaowhForever_TownSpiritHealers.lua -- spirit healers on the town map, by world map,",
        "from Wowhead Forever. Generated by Tools/build_spirit_healers.py; do not edit by hand.",
        "",
        "[uiMapID] = { { x, y, \"spirit\", name, title, class, factions }, ... }, as",
        "NaowhForever_TownData.lua lists its NPCs. x and y are map percentages.",
    )
    lines.append("ns.TownSpiritHealers = {")
    total = 0
    for map_id in sorted(by_map):
        lines.append(f"    [{map_id}] = {{")
        for x, y in sorted(by_map[map_id]):
            lines.append(f'        {{ {x:g}, {y:g}, "spirit", "Spirit Healer", "Graveyard", nil, "AH" }},')
            total += 1
        lines.append("    },")
    lines.append("}")
    write(OUT, lines)
    print(f"{total} spirit healers on {len(by_map)} maps -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
