"""Which dungeon quests need which boss, for a boss's page in the Dungeon Journal: a quest
needs a boss when the objective on its Wowhead Forever page (or an item or NPC it asks for)
names the boss, or links the boss's NPC. Written to DungeonJournal/Data/BossQuests.lua as
quest IDs (Data/Quests.lua's) keyed by NPC ID. The rest of a quest's chain (its steps)
counts too: the quest is listed for a boss any step needs.

The quests are read from DungeonJournal/Data/Quests.lua, the bosses from
DungeonJournal/Data/Dungeons; pages are kept in Tools/quest_objectives_cache.json, so a run
only fetches quests not seen yet. --refresh fetches all.

Usage: py Tools/build_boss_quests.py [--refresh]
"""
import html
import json
import os
import re
import sys
import urllib.error

import wowhead

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
QUESTS = os.path.join(ROOT, "DungeonJournal", "Data", "Quests.lua")
DUNGEONS = os.path.join(ROOT, "DungeonJournal", "Data", "Dungeons")
OUT = os.path.join(ROOT, "DungeonJournal", "Data", "BossQuests.lua")
CACHE = os.path.join(ROOT, "Tools", "quest_objectives_cache.json")

HEADER = """-------------------------------------------------------------------------------
--  Data/BossQuests.lua -- the dungeon quests that need each boss (its kill, or something it
--  drops), as quest IDs from Data/Quests.lua keyed by the boss's NPC ID. Matched by the
--  boss's name in the quest's objective on Wowhead Forever. Generated by
--  Tools/build_boss_quests.py; do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.BossQuests = {
"""


def dungeon_quests():
    """{dungeon name: [(quest ID, quest name, [step IDs])]} from Data/Quests.lua."""
    with open(QUESTS, encoding="utf-8") as f:
        text = f.read()
    out = {}
    blocks = re.split(r'\n    \{ name = "', text)[1:]
    for block in blocks:
        name = block[:block.index('"')]
        quests = []
        # A quest starts on its own line; its steps may run onto the lines after it.
        entries = re.split(r"\n        \{ (?=\d)", block)[1:]
        for entry in entries:
            qid = int(re.match(r"\d+", entry).group(0))
            qname = re.match(r'\d+, "((?:[^"\\]|\\.)*)"', entry).group(1)
            steps = []
            m = re.search(r"steps = \{(.*?)\}\s*,?\s*(?:next|lead|alt|\}|$)", entry, re.S)
            if m:
                steps = [int(s) for s in re.findall(r"\d+", m.group(1))]
            quests.append((qid, qname, steps))
        out[name] = quests
    return out


def dungeon_maps():
    """{dungeon name: instance map ID} from Data/Quests.lua; the wings of one instance share it."""
    with open(QUESTS, encoding="utf-8") as f:
        text = f.read()
    return {name: int(m) for name, m in re.findall(r'\n    \{ name = "([^"]+)", map = (\d+)', text)}


def kin_bosses(dungeon, bosses, maps):
    """The bosses a dungeon's quests can need: every wing of its instance, else its own."""
    m = maps.get(dungeon)
    kin = [d for d in bosses if m is not None and maps.get(d) == m] or [dungeon]
    return [boss for d in kin for boss in bosses.get(d, [])]


def dungeon_bosses():
    """{dungeon name: [(npc, boss name)]} from Data/Dungeons."""
    out = {}
    for file in sorted(os.listdir(DUNGEONS)):
        with open(os.path.join(DUNGEONS, file), encoding="utf-8") as f:
            text = f.read()
        dungeon = re.search(r'name = "([^"]+)"', text).group(1)
        out[dungeon] = [(int(n), name) for n, name in re.findall(r'\{ npc = (\d+), name = "((?:[^"\\]|\\.)*)"', text)]
    return out


def objective(page):
    """A quest page's objective and what it asks for, as plain text, and the NPC IDs linked
    in what it asks for."""
    start = page.find('<h1 class="heading-size-1">')
    if start < 0:
        return "", []
    end = page.find('<script type="application/json" id="data.mapper', start)
    if end < 0:
        end = page.find('<h2 class="heading-size-3">', start)
    part = page[start:end if end > 0 else start + 6000]
    part = part[part.find("</h1>") + 5:]
    npcs = [int(n) for n in re.findall(r"/forever/npc=(\d+)", part.split('<table class="icon-list">', 1)[-1])
            ] if '<table class="icon-list">' in part else []
    text = html.unescape(re.sub(r"<[^>]+>", " ", part))
    return re.sub(r"\s+", " ", text).strip(), npcs


TITLES = {"Lord", "Lady", "Prince", "Princess", "Archmage", "General", "Captain", "Overlord",
          "Highlord", "Warchief", "Baron", "Mekgineer", "Doctor", "Archivist", "Houndmaster",
          "Pyroguard", "Commander", "Inquisitor", "High", "Twilight", "Mother"}


def short_name(name, text):
    """A quest often names a boss without its title ("the Gems of Cobrahn" for Lord
    Cobrahn): its last word, capitalised and whole, counts when every word before it is a
    title. Not for a family name (Lord Alexei Barov) or a plain word (Spawn of Hakkar)."""
    words = name.split()
    if len(words) < 2 or not all(w in TITLES for w in words[:-1]):
        return False
    last = words[-1]
    return len(last) >= 5 and re.search(r"\b" + re.escape(last) + r"\b", text) is not None


def fetch(cache, qid):
    key = str(qid)
    if key not in cache:
        print(f"  quest {qid}", file=sys.stderr)
        try:
            text, npcs = objective(wowhead.fetch(f"{wowhead.WOWHEAD}/quest={qid}"))
        except urllib.error.HTTPError as e:
            if e.code != 404:
                raise
            text, npcs = "", []
        cache[key] = {"text": text, "npcs": npcs}
        with open(CACHE, "w", encoding="utf-8", newline="\n") as f:
            json.dump(cache, f, indent=1, sort_keys=True)
    return cache[key]


def main():
    cache = {}
    if os.path.exists(CACHE) and "--refresh" not in sys.argv:
        with open(CACHE, encoding="utf-8") as f:
            cache = json.load(f)
    bosses = dungeon_bosses()
    maps = dungeon_maps()
    found = {}   # npc -> [(quest ID, quest name)]
    for dungeon, quests in dungeon_quests().items():
        here = kin_bosses(dungeon, bosses, maps)
        if not here:
            print(f"  no bosses for {dungeon}", file=sys.stderr)
            continue
        for qid, qname, steps in quests:
            pages = [fetch(cache, i) for i in [qid] + steps]
            text = " ".join(p["text"] for p in pages)
            lower = text.lower()
            npcs = {n for p in pages for n in p["npcs"]}
            for npc, name in here:
                if (npc in npcs or name.lower() in lower or short_name(name, text))                         and (qid, qname) not in found.get(npc, []):
                    found.setdefault(npc, []).append((qid, qname))
    lines = []
    for dungeon, here in bosses.items():
        listed = [(npc, name) for npc, name in here if npc in found]
        if not listed:
            continue
        lines.append(f"    -- {dungeon}")
        for npc, name in listed:
            ids = ", ".join(str(q) for q, _ in found[npc])
            names = "; ".join(n for _, n in found[npc])
            lines.append(f"    [{npc}] = {{ {ids} }},  -- {name}: {names}")
    text = HEADER + "\n".join(lines) + "\n}\n"
    text = text.encode("ascii", "replace").decode("ascii")
    with open(OUT, "w", encoding="ascii", newline="\r\n") as f:
        f.write(text)
    print(f"{len(found)} bosses with quests to {os.path.relpath(OUT, ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
