-- Writes Core/NaowhForever_Starter.lua, the setup a new install starts from, out of a profile
-- string from Export Profile (NFPROFILE1:), saved to a file. Takes every module's settings and
-- positions, the Macros settings and the look; Smart Reminders is left out. Run from the repo
-- root with the libraries in Libs/:
--   lua5.1 Tools/build_starter.lua profile.txt
local source = assert(arg[1], "usage: lua5.1 Tools/build_starter.lua <file with the profile string>")
local OUT = "Core/NaowhForever_Starter.lua"
-- Smart Reminders' own settings, and the Custom Reminders that run on its triggers.
local LEFT_OUT = { tankReminder = true, customReminders = true }

strmatch = string.match
dofile("Libs/LibStub/LibStub.lua")
dofile("Libs/LibDeflate/LibDeflate.lua")
dofile("Libs/LibSerialize/LibSerialize.lua")
local ns = { UI = {}, PlainText = function(s) return s end, ValidPackData = function(d) return type(d) == "table" end }
local env = setmetatable({ _G = { NaowhForever = ns }, date = os.date }, { __index = _G })
ns.Shared = { Decode = dofile("Tools/regression/load_decode.lua")(env) }
local chunk = assert(loadfile("Core/NaowhForever_ProfileShare.lua"))
setfenv(chunk, env)
chunk()

local f = assert(io.open(source, "rb"))
local payload, why = ns.DecodeProfile(f:read("*a"))
f:close()
assert(payload, "not a profile string: " .. tostring(why))
local parts = payload.parts

-- Taken into the account by the import's own checks, which this does not repeat.
for _, part in ipairs({ "library", "builds", "bisLists" }) do
    assert(parts[part] == nil, "the string carries " .. part .. ", which this does not take yet")
end
assert(not (parts.macros and parts.macros.classMacros), "the string carries class macros, which this does not take yet")

local profile, account = {}, {}
for key, values in pairs(parts.settings or {}) do
    if not LEFT_OUT[key] then profile[key] = values end
end
if parts.macros and parts.macros.module then profile.macros = parts.macros.module end
for key, value in pairs(parts.look or {}) do account[key] = value end

local function Key(k)
    if type(k) == "string" and k:match("^[%a_][%w_]*$") then return k end
    if type(k) == "string" then return "[" .. ("%q"):format(k) .. "]" end
    return "[" .. tostring(k) .. "]"
end

local function Value(v)
    if type(v) == "string" then
        -- ASCII only in the source: anything else as a decimal escape.
        return (("%q"):format(v):gsub("\\\n", "\\n"):gsub("[\128-\255]", function(c)
            return ("\\%d"):format(c:byte())
        end))
    end
    if type(v) == "number" then
        local short = ("%.14g"):format(v)
        return tonumber(short) == v and short or ("%.17g"):format(v)
    end
    return tostring(v)
end

local function Sorted(t)
    local keys = {}
    for k in pairs(t) do keys[#keys + 1] = k end
    table.sort(keys, function(a, b)
        if type(a) == type(b) then return a < b end
        return type(a) == "number"
    end)
    return keys
end

local lines = {}
local function Emit(t, indent)
    for _, k in ipairs(Sorted(t)) do
        local v = t[k]
        if type(v) == "table" then
            if next(v) == nil then
                lines[#lines + 1] = ("%s%s = {},"):format(indent, Key(k))
            else
                lines[#lines + 1] = ("%s%s = {"):format(indent, Key(k))
                Emit(v, indent .. "    ")
                lines[#lines + 1] = indent .. "},"
            end
        else
            lines[#lines + 1] = ("%s%s = %s,"):format(indent, Key(k), Value(v))
        end
    end
end

lines[#lines + 1] = "-------------------------------------------------------------------------------"
lines[#lines + 1] = "--  NaowhForever_Starter.lua -- the setup a new install starts from: its Default profile"
lines[#lines + 1] = "--  and the account's look. Generated by Tools/build_starter.lua from a profile string;"
lines[#lines + 1] = "--  do not edit by hand."
lines[#lines + 1] = ("--  Source: %s by %s, %s."):format(tostring(payload.name), tostring(payload.author), tostring(payload.made))
lines[#lines + 1] = "-------------------------------------------------------------------------------"
lines[#lines + 1] = "local ns = _G.NaowhForever"
lines[#lines + 1] = ""
lines[#lines + 1] = "ns.STARTER = {"
lines[#lines + 1] = "    profile = {"
Emit(profile, "        ")
lines[#lines + 1] = "    },"
lines[#lines + 1] = "    account = {"
Emit(account, "        ")
lines[#lines + 1] = "    },"
lines[#lines + 1] = "}"

local out = assert(io.open(OUT, "wb"))
out:write(table.concat(lines, "\r\n"), "\r\n")
out:close()
print(("%s: %d modules, %d look settings"):format(OUT, #Sorted(profile), #Sorted(account)))
