"""Build the world map's unexplored areas from the game's own tables (Tools/wago.py).

Each zone map has one piece of art (UiMapXMapArt: uiMapID -> UiMapArtID), and the art an
overlay for every area you can explore (WorldMapOverlay: its size and offset on the art, in
the art's pixels), cut into tiles (WorldMapOverlayTile: one texture per row and column, all
on layer 0 for Forever's maps). The game only gives addons the areas you have explored
(C_MapExplorationInfo.GetExploredMapTextures), so the rest are read from here and drawn
greyed out. An overlay with no tiles has nothing to draw and is left out.

Writes QoL/NaowhForever_MapOverlays.lua. Run it again when wago.BUILD moves on to a new build.

Usage: python Tools/build_map_overlays.py [--build 1.60.1.70205]
"""
import argparse
import math
import sys

import wago
from build_journal import ROOT, header, write

OUT = ROOT / "QoL" / "NaowhForever_MapOverlays.lua"
TILE = 256   # the art layers' tile size: every overlay's tile count matches it
COLUMNS = {
    "UiMapXMapArt": ("UiMapID", "UiMapArtID", "PhaseID"),
    "WorldMapOverlay": ("ID", "UiMapArtID", "TextureWidth", "TextureHeight", "OffsetX", "OffsetY"),
    "WorldMapOverlayTile": ("WorldMapOverlayID", "RowIndex", "ColIndex", "LayerIndex", "FileDataID"),
}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--build", default=wago.BUILD)
    build = parser.parse_args().build

    tables = {name: wago.table(name, build) for name in COLUMNS}
    for name, columns in COLUMNS.items():
        rows = tables[name]
        if not rows or any(column not in rows[0] for column in columns):
            sys.exit(f"wago.tools cannot read {name} for {build} yet")

    maps_by_art = {}
    for row in tables["UiMapXMapArt"]:
        if row["PhaseID"] == "0":
            maps_by_art.setdefault(row["UiMapArtID"], []).append(int(row["UiMapID"]))

    tiles = {}
    for row in tables["WorldMapOverlayTile"]:
        if row["LayerIndex"] == "0":
            tiles.setdefault(row["WorldMapOverlayID"], []).append(row)

    by_map = {}
    for row in tables["WorldMapOverlay"]:
        overlay_tiles = tiles.get(row["ID"])
        if not overlay_tiles or row["UiMapArtID"] not in maps_by_art:
            continue
        width, height = int(row["TextureWidth"]), int(row["TextureHeight"])
        if len(overlay_tiles) != math.ceil(width / TILE) * math.ceil(height / TILE):
            sys.exit(f"overlay {row['ID']} has {len(overlay_tiles)} tiles for {width}x{height}")
        overlay_tiles.sort(key=lambda t: (int(t["RowIndex"]), int(t["ColIndex"])))
        overlay = [width, height, int(row["OffsetX"]), int(row["OffsetY"])]
        overlay += [int(t["FileDataID"]) for t in overlay_tiles]
        for map_id in maps_by_art[row["UiMapArtID"]]:
            by_map.setdefault(map_id, []).append(overlay)

    lines = header(
        "NaowhForever_MapOverlays.lua -- every explorable area of each zone map, from the",
        f"game's tables for build {build}. Generated by Tools/build_map_overlays.py; do not",
        "edit by hand.",
        "",
        "[uiMapID] = { { width, height, offsetX, offsetY, fileDataID, ... }, ... }: the area's",
        "size and place on the map art in its pixels, then its 256px tiles row by row.",
    )
    lines.append("ns.MapOverlays = {")
    total = 0
    for map_id in sorted(by_map):
        lines.append(f"    [{map_id}] = {{")
        for overlay in sorted(by_map[map_id]):
            lines.append("        { " + ", ".join(str(n) for n in overlay) + " },")
            total += 1
        lines.append("    },")
    lines.append("}")
    write(OUT, lines)
    print(f"{total} areas on {len(by_map)} maps -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
