-- Writes Core/NaowhForever_Starter.lua, the setup a new install starts from, out of a Naowh
-- Forever SavedVariables file. Takes what Export Profile shares (every module's settings and
-- positions, the Macros settings, the Library, talent builds, BiS lists and the look) from
-- the Default profile, and leaves Smart Reminders out.
--   lua5.1 Tools/build_starter.lua "<WTF>/Account/<account>/SavedVariables/NaowhForever.lua"
local source = assert(arg[1], "usage: lua5.1 Tools/build_starter.lua <SavedVariables/NaowhForever.lua>")
local OUT = "Core/NaowhForever_Starter.lua"
local PROFILE = "Default"
-- Smart Reminders' own settings, and the Custom Reminders that run on its triggers.
local LEFT_OUT = { tankReminder = true, customReminders = true }
local LOOK = { "themePreset", "themeColors", "uiFont", "windowScale" }

dofile(source)
local db = assert(NaowhForeverDB, "no NaowhForeverDB in " .. source)
local root = assert(db.profiles and db.profiles[PROFILE], "no " .. PROFILE .. " profile")
local account = db.account or {}
local known = account.moduleDefaults or {}

local profile = {}
for key, values in pairs(root) do
    if (known[key] or key == "macros") and not LEFT_OUT[key] and type(values) == "table" then
        profile[key] = values
    end
end

local shared = {}
if type(account.libraryMacros) == "table" then
    local library = {}
    for class, list in pairs(account.libraryMacros) do
        local own = {}
        -- A pack macro's Library copy is the pack curator's, as in the export.
        for _, m in ipairs(list) do if not m.pack then own[#own + 1] = m end end
        if #own > 0 then library[class] = own end
    end
    if next(library) then shared.libraryMacros = library end
end
shared.trainingBuilds = account.trainingBuilds
shared.bisLists = account.bisLists
for _, key in ipairs(LOOK) do shared[key] = account[key] end

local function Key(k)
    if type(k) == "string" and k:match("^[%a_][%w_]*$") then return k end
    if type(k) == "string" then return "[" .. ("%q"):format(k) .. "]" end
    return "[" .. tostring(k) .. "]"
end

local function Value(v)
    if type(v) == "string" then
        -- ASCII only in the source: anything else as a decimal escape.
        return (("%q"):format(v):gsub("\\\n", "\\n"):gsub("[\128-\255]", function(c)
            return ("\\%d"):format(c:byte())
        end))
    end
    if type(v) == "number" then
        local short = ("%.14g"):format(v)
        return tonumber(short) == v and short or ("%.17g"):format(v)
    end
    return tostring(v)
end

local function Sorted(t)
    local keys = {}
    for k in pairs(t) do keys[#keys + 1] = k end
    table.sort(keys, function(a, b)
        if type(a) == type(b) then return a < b end
        return type(a) == "number"
    end)
    return keys
end

local lines = {}
local function Emit(t, indent)
    for _, k in ipairs(Sorted(t)) do
        local v = t[k]
        if type(v) == "table" then
            if next(v) == nil then
                lines[#lines + 1] = ("%s%s = {},"):format(indent, Key(k))
            else
                lines[#lines + 1] = ("%s%s = {"):format(indent, Key(k))
                Emit(v, indent .. "    ")
                lines[#lines + 1] = indent .. "},"
            end
        elseif type(v) ~= "function" and type(v) ~= "userdata" then
            lines[#lines + 1] = ("%s%s = %s,"):format(indent, Key(k), Value(v))
        end
    end
end

lines[#lines + 1] = "-------------------------------------------------------------------------------"
lines[#lines + 1] = "--  NaowhForever_Starter.lua -- the setup a new install starts from: its Default profile"
lines[#lines + 1] = "--  and the account's shared parts. Generated by Tools/build_starter.lua from a"
lines[#lines + 1] = "--  SavedVariables file; do not edit by hand."
lines[#lines + 1] = "-------------------------------------------------------------------------------"
lines[#lines + 1] = "local ns = _G.NaowhForever"
lines[#lines + 1] = ""
lines[#lines + 1] = "ns.STARTER = {"
lines[#lines + 1] = "    profile = {"
Emit(profile, "        ")
lines[#lines + 1] = "    },"
lines[#lines + 1] = "    account = {"
Emit(shared, "        ")
lines[#lines + 1] = "    },"
lines[#lines + 1] = "}"

local out = assert(io.open(OUT, "wb"))
out:write(table.concat(lines, "\r\n"), "\r\n")
out:close()
print(("%s: %d modules, %d account parts"):format(OUT, #Sorted(profile), #Sorted(shared)))
