return {
["training"] = {
},
["discovery"] = {
["enabled"] = true,
["bagMapPinSize"] = 16,
["mapPinSize"] = 16,
["bagMapPins"] = true,
["mapPins"] = false,
},
["actionBars"] = {
},
["journal"] = {
["usableOnly"] = false,
},
["swingTimer"] = {
["sealColors"] = false,
["swingPos"] = {
["y"] = -196.1290307496515,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 0,
},
["swingWindow"] = false,
["queueHighlight"] = false,
["showMH"] = false,
},
["professions"] = {
["craftProfit"] = true,
["craftProfitList"] = true,
["vendorMaterials"] = true,
["searchFavoritesAH"] = true,
["rankAlert"] = true,
["buyMaterials"] = true,
["ahShiftClick"] = true,
["bagReagents"] = true,
["ahSearch"] = true,
["bankReagents"] = true,
["gatherIconSize"] = 46,
["recipeFinder"] = true,
["gatherReminder"] = true,
["shoppingList"] = true,
["craftTimer"] = true,
},
["threatMeter"] = {
["enabled"] = false,
["threatPos"] = {
["y"] = -433.9999894909563,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 802.9999805558477,
},
["visibilityMerged"] = true,
["visibility"] = "threat",
["showHeader"] = false,
},
["qol"] = {
["groupInspectShare"] = false,
["bisBagMarks"] = false,
["townMap"] = false,
["xpBar"] = false,
["mapUnexplored"] = false,
["lootFeed"] = false,
["naowhScore"] = false,
["characterPanelAsked"] = true,
["flightGame"] = "quiz",
["bagSpaceAuction"] = false,
["xpBarPos"] = {
["y"] = 449.9999891035262,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 0,
},
["inspectPanelShareBis"] = false,
["bagSpaceFontSize"] = 15,
["alertsPos"] = {
["y"] = 240.9999941643329,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 0,
},
["characterPanelSlotMarks"] = false,
["characterPanelTookOver"] = true,
["xpTicker"] = false,
["talentPoints"] = true,
["trinketSize"] = 42,
["focusCastBarPos"] = {
["y"] = 173.1899628257156,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 0,
},
["blessShowFury"] = true,
["lootFeedWidth"] = 280,
["coTank"] = false,
["scrapMarker"] = false,
["gcdTrackerPos"] = {
["y"] = -461.0752652711105,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 0,
},
["gearBarSize"] = 42,
["autoRepair"] = false,
["bisToastPos"] = {
["y"] = 277.5627218796237,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 0,
},
["bagSpacePos"] = {
["y"] = -332.6164848970697,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 734.050173565947,
},
["copyKey"] = "C",
["restockAmmoTarget"] = 200,
["bagSpaceOutline"] = "OUTLINE",
["trinketBar"] = false,
["townMail"] = false,
["inspectPanelTookOver"] = true,
["blessPos"] = {
["y"] = 0,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -519.5698884771468,
},
["gearBarVisible"] = false,
["copyModifier"] = "CTRL-SHIFT",
["durabilityBelow"] = 20,
["scrapMarkerVendor"] = "ask",
["mailAlts"] = true,
["copyShortcutSynced"] = true,
["bisBagLevels"] = false,
["bagSpace"] = false,
["restockAmmo"] = false,
["restock"] = false,
["townSupplies"] = false,
["deathRelease"] = false,
["gearPos"] = {
["y"] = -188.1003569762739,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -721.4336862077822,
},
["questGossip"] = false,
["blessBarSize"] = 42,
["mailQuickAttach"] = true,
["lootFeedPos"] = {
["y"] = -167.9999959319831,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -368.9999910648915,
},
["questShare"] = false,
["groupInspect"] = true,
["bagSpaceHideCombat"] = false,
["mapUnexploredDark"] = 0.5,
["bagSpaceBackground"] = "none",
["questAccept"] = false,
["restockBagsBelow"] = 10,
["equipReminder"] = false,
["combatAlert"] = false,
["foodBar"] = false,
["tooltipCopy"] = false,
["tooltipDisplay"] = false,
["bagSpaceIgnore"] = {
},
["copyTooltipIds"] = false,
["inspectPanelAsked"] = true,
["waypoints"] = false,
["questTurnIn"] = false,
["quizCamp"] = false,
["flightGameMigrated"] = true,
["restockReagents"] = false,
["slashList"] = {
{
["enabled"] = true,
["frame"] = "CooldownViewerSettings",
["name"] = "cdm",
},
{
["enabled"] = true,
["frame"] = "EditModeManagerFrame",
["name"] = "em",
},
{
["enabled"] = true,
["frame"] = "QuickKeybindFrame",
["name"] = "kb",
},
},
["playerHistory"] = false,
["scrapMarkerScope"] = "char",
["townStable"] = true,
["townTravel"] = true,
["trinketPos"] = {
["y"] = -137.6344075436151,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -721.4336862077822,
},
["xpTickerPos"] = {
["y"] = 525.3046554581308,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -979.4982003520605,
},
["questRewardPicks"] = false,
["characterPanel"] = false,
["inspectPanel"] = false,
},
["unlockMode"] = {
["anchoredTo"] = {
["Loot Feed"] = {
["target"] = "Alerts",
["x"] = -659.3190307617188,
["side"] = "RIGHT",
["y"] = -456.7619781494141,
},
},
["hidden"] = {
},
["locked"] = {
},
},
["auraBuffs"] = {
["buffsPos"] = {
["y"] = 332.6164848970697,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 0,
},
["campIconSize"] = 100,
["onlyIfCarried"] = true,
["campfire"] = false,
["campPos"] = {
["y"] = 792.5447998046875,
["relPoint"] = "BOTTOMLEFT",
["point"] = "CENTER",
["x"] = 198.4229125976563,
},
["lowHealth"] = false,
["lowHealthPos"] = {
["y"] = -188.999995423481,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 0,
},
["iconSize"] = 48,
["raidBuffs"] = false,
["campAlertScale"] = 1.8,
},
["tankReminder"] = {
["enabled"] = false,
},
["statWeights"] = {
["enabled"] = false,
},
["macros"] = {
["focusMark"] = false,
["focusAnnounce"] = false,
["bandage"] = false,
["food"] = false,
["mana"] = false,
["health"] = false,
["focus"] = false,
["trinket1"] = false,
["trinket2"] = false,
["acceptPopup"] = false,
},
["topBar"] = {
["showClock"] = false,
["layoutMigrated"] = true,
["tooltipScale"] = 100,
["use24h"] = true,
["hideInCombat"] = false,
["layout"] = {
["left"] = {
"ldb:NaowhForeverJournal",
"ldb:NaowhForeverBiS",
},
["right"] = {
"ldb:NaowhForeverTraining",
"ldb:NaowhForeverDiscovery",
},
},
["showSystem"] = false,
},
}
