"""Daily badge sync for .github/workflows/badges.yml. From the repo root:

    python Tools/sync_badges.py [--url URL] [--from FILE]

Writes Badges/BadgesPatrons.lua from naowh.gg's list of active Legendary patrons
(https://naowh.gg/api/forever/badges, or a saved copy with --from): each region's character
GUIDs, with the month their pledge started. Patrons add their characters' codes (/nf badges id)
on naowh.gg/forever/account; naowh.gg keeps a lapsed patron's codes, so they come back on a
re-sub, and lists only the active ones here. Every entry is checked before the file is written,
the output is sorted so an unchanged list writes an unchanged file, and the file keeps its CRLF
line endings. Prints "changed" or "unchanged".
"""

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path

URL = "https://naowh.gg/api/forever/badges"
OUT = Path("Badges/BadgesPatrons.lua")
GUID = re.compile(r"^Player-\d+-[0-9A-F]{8}$")
MONTH = re.compile(r"^\d{4}-(0[1-9]|1[0-2])$")

# The file's one-line header (the house style allows no other comment): the active Legendary
# patrons, by region and character GUID, with the month their pledge started. The next sync
# overwrites it, so it is never edited by hand.
HEADER = """-- BadgesPatrons.lua: the Legendary patrons' badges, generated by Tools/sync_badges.py.
local ns = _G.NaowhForever
"""


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": "NaowhForever badge sync"})
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def validated(data):
    patrons = data.get("patrons") if isinstance(data, dict) else None
    if not isinstance(patrons, dict):
        raise ValueError('expected {"patrons": {region: {guid: {since}}}}')
    out = {}
    for region, characters in patrons.items():
        if not re.fullmatch(r"[1-9]\d{0,2}", str(region)) or not isinstance(characters, dict):
            raise ValueError(f"bad region {region!r}")
        for guid, entry in characters.items():
            since = entry.get("since") if isinstance(entry, dict) else None
            if not GUID.match(guid) or not isinstance(entry, dict) or (since is not None and not MONTH.match(str(since))):
                raise ValueError(f"bad entry {region}:{guid} {entry!r}")
            out.setdefault(int(region), {})[guid] = since
    return out


def render(patrons):
    lines = [HEADER, "ns.BADGE_PATRONS = {"]
    for region in sorted(patrons):
        lines.append(f"    [{region}] = {{")
        for guid in sorted(patrons[region]):
            since = patrons[region][guid]
            value = f'{{ since = "{since}" }}' if since else "{}"
            lines.append(f'        ["{guid}"] = {value},')
        lines.append("    },")
    lines.append("}")
    return "\r\n".join("\n".join(lines).split("\n")) + "\r\n"


def main():
    parser = argparse.ArgumentParser(description="Write the Legendary patron badge list.")
    parser.add_argument("--url", default=URL)
    parser.add_argument("--from", dest="source", type=Path, help="a saved JSON response")
    args = parser.parse_args()
    data = json.loads(args.source.read_text(encoding="utf-8")) if args.source else fetch(args.url)
    text = render(validated(data))
    if OUT.read_bytes() == text.encode("ascii"):
        print("unchanged")
        return 0
    OUT.write_bytes(text.encode("ascii"))
    print("changed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
