-------------------------------------------------------------------------------
--  Data/Abilities.lua -- each boss's abilities, as the spell IDs on the Abilities tab of its
--  Wowhead Forever NPC page, keyed by its NPC ID. Generated by Tools/build_abilities.py; do
--  not edit by hand. The game gives each one's name, icon and description.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.Abilities = {
    -- Blackfathom Deeps
    [4887] = { 5568 },  -- Ghamoo-ra: Trample
    [4831] = { 246, 865, 6660, 8435 },  -- Lady Sarevess: Slow, Frost Nova, Shoot, Forked Lightning
    [6243] = { 6533, 7165 },  -- Gelihast: Net, Battle Stance
    [12902] = { 12167, 12550 },  -- Lorgus Jett: Lightning Bolt, Lightning Shield
    [12876] = { 15043, 15531 },  -- Baron Aquanis: Frostbolt, Frost Nova
    [4832] = { 8399 },  -- Twilight Lord Kelris: Sleep
    [4830] = { 8433, 1604, 5101, 13496, 15571 },  -- Old Serra'kis: Leech Pulse, Dazed, Dazed, Dazed, Dazed
    [4829] = { 3490, 3815 },  -- Aku'mai: Frenzied Rage, Poison Cloud
    -- Blackrock Depths
    [9018] = { 12040, 13704, 14032, 14033 },  -- High Interrogator Gerstahn: Shadow Shield, Psychic Scream, Shadow Word: Pain, Mana Burn
    [9025] = { 6524, 13728, 13729 },  -- Lord Roccor: Ground Tremor, Earth Shock, Flame Shock
    [9319] = { 13730, 15615, 21049 },  -- Houndmaster Grebmar: Demoralizing Shout, Pummel, Bloodlust
    [9031] = { 8994, 12493, 13787, 15470, 15471, 15472 },  -- Anub'shiah: Banish, Curse of Weakness, Demon Armor, Curse of Tongues, Enveloping Web, Shadow Bolt
    [9029] = { 7121, 14331, 15245 },  -- Eviscerator: Anti-Magic Shield, Vicious Rend, Shadow Bolt Volley
    [9027] = { 13736, 15708, 21049 },  -- Gorosh the Dervish: Whirlwind, Mortal Strike, Bloodlust
    [9028] = { 6524, 8269, 15579 },  -- Grizzle: Ground Tremor, Enrage, Cleave
    [9032] = { 15475 },  -- Hedrum the Creeper: Baneful Poison
    [9030] = { 13323, 13747, 15254, 15453 },  -- Ok'thor the Breaker: Polymorph, Slow, Arcane Bolt, Arcane Explosion
    [9024] = { 15038, 15041, 15095, 15616 },  -- Pyromancer Loregrain: Scorching Totem, Fire Ward, Molten Blast, Flame Shock
    [9017] = { 13899, 13900, 14099, 26977 },  -- Lord Incendius: Fire Storm, Fiery Burst, Mighty Blow, Curse of the Elemental Lord
    [9041] = { 6136, 12544, 12674, 12675, 15044 },  -- Warder Stilgiss: Chilled, Frost Armor, Frost Nova, Frostbolt, Frost Ward
    [9042] = { 15042 },  -- Verek: Curse of Blood
    [9056] = { 8258, 11978, 13953, 15346, 15493 },  -- Fineous Darkvire: Devotion Aura, Kick, Holy Strike, Seal of Reckoning, Holy Light
    [9016] = { 13895, 23379 },  -- Bael'Gar: Summon Spawn of Bael'Gar, Magma Splash
    [9033] = { 15572 },  -- General Angerforge: Sunder Armor
    [8983] = { 15305, 15507, 15605 },  -- Golem Lord Argelmach: Chain Lightning, Lightning Shield, Shock
    [9537] = { 9573, 14872 },  -- Hurley Blackbreath: Flame Breath, Drunken Rage
    [9502] = { 14099, 15285, 15588 },  -- Phalanx: Mighty Blow, Fireball Volley, Thunderclap
    [9543] = { 9080, 12540 },  -- Ribbly Screwspigot: Hamstring, Gouge
    [9499] = { 8994, 12739, 12742, 13338, 13787 },  -- Plugger Spazzring: Banish, Shadow Bolt, Immolate, Curse of Tongues, Demon Armor
    [9156] = { 14744 },  -- Ambassador Flamelash: Burning Spirit
    [9938] = { 15593, 15668 },  -- Magmus: War Stomp, Fiery Burst
    [9019] = { 15636, 17492 },  -- Emperor Dagran Thaurissan: Avatar of Flame, Hand of Thaurissan
    [8923] = { 403233 },  -- Panzor the Invincible: Meathook
    [8929] = { 8362, 15537, 15586, 15587, 15654 },  -- Princess Moira Bronzebeard: Renew, Shadow Bolt, Heal, Mind Blast, Shadow Word: Pain
    -- The Deadmines
    [644] = { 6304 },  -- Rhahk'Zor: Rhahk'Zor Slam
    [642] = { 3603, 5141, 7399 },  -- Sneed's Shredder: Distracting Pain, Eject Sneed, Terrify
    [643] = { 6713 },  -- Sneed: Disarm
    [1763] = { 5213 },  -- Gilnid: Molten Metal
    [646] = { 3391, 6264, 6432, 6435 },  -- Mr. Smite: Thrash, Nimble Reflexes, Smite Stomp, Smite Slam
    [647] = { 5208, 5532 },  -- Captain Greenskin: Poisoned Harpoon, Cleave
    [639] = { 3391, 5200 },  -- Edwin VanCleef: Thrash, VanCleef's Allies
    [645] = { 5174, 6306 },  -- Cookie: Cookie's Cooking, Acid Splash
    -- Dire Maul
    [14354] = { 14145, 15228, 22424, 22735 },  -- Pusillin: Fire Blast, Fireball, Blast Wave, Spirit of Runn Tum
    [11490] = { 22478 },  -- Zevrim Thornhoof: Intense Pain
    [13280] = { 22420 },  -- Hydrospawn: Submersion
    [14327] = { 12742, 13338, 16247, 17228, 22709, 22710 },  -- Lethtendris: Immolate, Curse of Tongues, Curse of Thorns, Shadow Bolt Volley, Void Bolt, Enlarge
    [11492] = { 22662, 22689 },  -- Alzzin the Wildshaper: Wither, Mangle
    [16097] = { 12024, 14443, 22907, 25164, 27636, 27637, 27639 },  -- Isalien: Net, Multi-Shot, Shoot, Vengeance, Starshards, Regrowth, Call Pet
    [11489] = { 5568, 22916, 22924, 22994 },  -- Tendris Warpwood: Trample, Uppercut, Grasping Vines, Entangle
    [11488] = { 14301, 20735, 22908, 22910, 22914, 22915 },  -- Illyanna Ravenoak: Immolation Trap Effect, Multi-Shot, Volley, Immolation Trap, Concussive Shot, Improved Concussive Shot
    [11487] = { 7645, 17146, 17287, 22917, 22919 },  -- Magister Kalendris: Dominate Mind, Shadow Word: Pain, Mind Blast, Shadowform, Mind Flay
    [11496] = { 5568, 8269, 16128, 22899, 22950 },  -- Immol'thar: Trample, Enrage, Infected Bite, Eye of Immol'thar, Portal of Immol'thar
    [11486] = { 3391, 15589, 20537, 22920, 22995 },  -- Prince Tortheldrin: Thrash, Whirlwind, Counterspell, Arcane Blast, Summon
    [11467] = { 12540, 15581, 15582, 21060 },  -- Tsu'zee: Gouge, Sinister Strike, Backstab, Blind
    [14506] = { 17146, 18670, 20989, 23224 },  -- Lord Hel'nurath: Shadow Word: Pain, Knock Away, Sleep, Veil of Shadow
    [14690] = { 6136, 14907, 15245 },  -- Revanchion: Chilled, Frost Nova, Shadow Bolt Volley
    [14326] = { 22818 },  -- Guard Mol'dar: Mol'dar's Moxie
    [14322] = { 8269, 15577, 16740, 22833, 22835 },  -- Stomper Kreeg: Enrage, Whirlwind, War Stomp, Booze Spit, Drunken Rage
    [14321] = { 22817 },  -- Guard Fengus: Fengus' Ferocity
    [14323] = { 22820 },  -- Guard Slip'kik: Slip'kik's Savvy
    [14325] = { 8599, 19134, 22857, 22859, 22860, 29544 },  -- Captain Kromcrush: Enrage, Intimidating Shout, Retaliation, Mortal Cleave, Call Reavers, Intimidating Shout
    [11501] = { 15572 },  -- King Gordok: Sunder Armor
    [14324] = { 15531 },  -- Cho'Rush the Observer: Frost Nova
    -- Excavation Site: Wetlands
    [260322] = { 3604, 16495, 1316382 },  -- Saltspine: Tendon Rip, Fatal Bite, Dust Storm
    [260325] = { 13445, 14100, 1284435 },  -- Shadetooth: Rend, Terrifying Roar, Enrage
    [260808] = { 9616, 1316480 },  -- Highland Horror: Wild Regeneration, Entangling Roots
    [260326] = { 8078, 8374, 10101, 11876, 1284450 },  -- Relic Guardian: Thunderclap, Arcing Smash, Knock Away, War Stomp, Stasis
    -- Gnomeregan
    [7079] = { 1604, 5101, 13496, 15571 },  -- Viscous Fallout: Dazed, Dazed, Dazed, Dazed
    [6235] = { 11082, 11084, 11085 },  -- Electrocutioner 6000: Megavolt, Shock, Chain Bolt
    [6229] = { 5568, 8374, 10887 },  -- Crowd Pummeler 9-60: Trample, Arcing Smash, Crowd Pummel
    [7800] = { 10101, 11130, 11518, 11521, 11524, 11526, 11527, 11798 },  -- Mekgineer Thermaplugg: Knock Away, Knock Away, Activate Bomb 01, Activate Bomb 02, Activate Bomb 04, Activate Bomb 05, Activate Bomb 06, Activate Bomb 03B
    [6228] = { 184, 2601, 9053, 10870, 15228, 22425 },  -- Dark Iron Ambassador: Fire Shield II, Fire Shield III, Fireball, Summon Burning Servant, Fireball, Fireball Volley
    [6231] = { 10852, 10855, 10858, 10860 },  -- Techbot: Battle Net, Lag, Summon Dupe Bug, Patch
    -- The Hall of Thanes
    [261306] = { 13860, 1292602 },  -- Faldrim Anvilmar: Mind Blast, Anvilmar's Curse
    [261316] = { 11970, 1293228 },  -- Magmatus: Fire Nova, Combust
    [261311] = { 11130, 21055, 22911 },  -- Plunder: Knock Away, Crush Armor, Charge
    [261319] = { 11977, 19134, 25710, 29544 },  -- Durgen Dirgehammer: Rend, Intimidating Shout, Heroic Strike, Intimidating Shout
    -- Lower Blackrock Spire
    [9196] = { 8269, 10101 },  -- Highlord Omokk: Enrage, Knock Away
    [9236] = { 16098 },  -- Shadow Hunter Vosh'gajin: Curse of Blood
    [9237] = { 3391, 10966, 15615, 15618, 15708, 15754, 16075 },  -- War Master Voone: Thrash, Uppercut, Pummel, Snap Kick, Mortal Strike, Cleave, Throw Axe
    [10596] = { 16103, 16104, 16468 },  -- Mother Smolderweb: Summon Spire Spiderling, Crystallize, Mother's Milk
    [10584] = { 15580, 16508, 16509 },  -- Urok Doomhowl: Strike, Intimidating Roar, Rend
    [9736] = { 15504, 15609, 16496, 16497 },  -- Quartermaster Zigris: Drink Healing Potion, Hooked Net, Shoot, Stun Bomb
    [10268] = { 8269, 16128, 16495 },  -- Gizrul the Slavener: Enrage, Infected Bite, Fatal Bite
    [10220] = { 3391, 13738 },  -- Halycon: Thrash, Rend
    [9568] = { 12887, 15663, 16244 },  -- Overlord Wyrmthalak: Sweeping Slam, Cleave, Demoralizing Shout
    [9219] = { 403233, 1604, 5101, 13496, 15571 },  -- Spirestone Butcher: Meathook, Dazed, Dazed, Dazed, Dazed
    [9218] = { 403233 },  -- Spirestone Battle Lord: Meathook
    [9217] = { 8365, 13323, 15230, 16170, 403233 },  -- Spirestone Lord Magus: Enlarge, Polymorph, Arcane Bolt, Bloodlust, Meathook
    [9596] = { 403233 },  -- Bannok Grimaxe: Meathook
    [10376] = { 16416 },  -- Crystal Fang: Summon Spire Spiderling
    [9718] = { 403233 },  -- Ghok Bashguud: Meathook
    [10263] = { 15548, 15580, 16046, 16074 },  -- Burning Felguard: Thunderclap, Strike, Blast Wave, Burning Felguard Spawn
    [16080] = { 15605, 20989, 22271, 27527, 27530, 27532, 27543, 27545, 27546, 27551, 27553, 27554, 27555, 27556, 27557, 27564, 27567, 27737 },  -- Mor Grayhoof: Shock, Sleep, Arcane Explosion, Healing Touch, Hurricane, Rejuvenation, Bear Form, Cat Form, Faerie Dragon Form, Demoralizing Roar, Maul, Swipe, Shred, Rake, Ferocious Bite, Reflection, Chain Lightning, Moonfire
    -- Maraudon
    [13282] = { 21687 },  -- Noxxion: Toxic Volley
    [12258] = { 11427, 15976 },  -- Razorlash: Cleave, Puncture
    [12236] = { 7964, 16100, 21390, 21655 },  -- Lord Vyletongue: Smoke Bomb, Shoot, Multi-Shot, Blink
    [12225] = { 12747, 21793, 21807, 21968 },  -- Celebras the Cursed: Entangling Roots, Twisted Tranquility, Wrath, Corrupt Forces of Nature
    [12203] = { 5568, 18670, 21727, 21808 },  -- Landslide: Trample, Knock Away, Summon Player, Summon Shardlings
    [13601] = { 9143, 16100, 21833, 29419 },  -- Tinkerer Gizlock: Bomb, Shoot, Goblin Dragon Gun, Flash Bomb
    [13596] = { 15976, 16495 },  -- Rotgrip: Puncture, Fatal Bite
    [12201] = { 3391, 21832, 21869, 21909, 22592 },  -- Princess Theradras: Thrash, Boulder, Repulsive Gaze, Dust Field, Knockdown
    [12237] = { 13446, 15593 },  -- Meshlok the Harvester: Strike, War Stomp
    -- Onyxia's Lair
    [10184] = { 15847, 17086, 18351, 18392, 18435, 18500, 18564, 18576, 18584, 18596, 18609, 18617, 19633, 19983, 20019, 20279, 20311, 21131, 22191, 22195, 22199, 22200, 22201, 22202 },  -- Onyxia: Tail Sweep, Breath, Breath, Fireball, Flame Breath, Wing Buffet, Breath, Breath, Breath, Breath, Breath, Breath, Knock Away, Cleave, Engulfing Flames, Summon Player, Summon Player, Breath, Heated Ground, Heated Ground, Heated Ground, Heated Ground, Heated Ground, Heated Ground
    -- Ragefire Chasm
    [11517] = { 5532 },  -- Oggleflint: Cleave
    [11520] = { 11970, 18072 },  -- Taragaman the Hungerer: Fire Nova, Uppercut
    [11518] = { 18267, 20800 },  -- Jergosh the Invoker: Curse of Weakness, Immolate
    [11519] = { 744, 14873 },  -- Bazzalan: Poison, Sinister Strike
    -- Razorfen Downs
    [7355] = { 12255 },  -- Tuten'kash: Curse of Tuten'kash
    [7357] = { 12466, 12470 },  -- Mordresh Fire Eye: Fireball, Fire Nova
    [8567] = { 12627, 12795 },  -- Glutton: Disease Cloud, Enrage
    [7358] = { 6136, 12642, 13009, 15530, 15531 },  -- Amnennar the Coldbringer: Chilled, Summon Frost Spectres, Amnennar's Wrath, Frostbolt, Frost Nova
    [7354] = { 7645, 11639, 12039, 12471 },  -- Ragglesnout: Dominate Mind, Shadow Word: Pain, Heal, Shadow Bolt
    [7356] = { 11442, 12946 },  -- Plaguemaw the Rotting: Withered Touch, Putrid Stench
    [14686] = { 16838, 17105, 22743, 429688 },  -- Lady Falther'ess: Banshee Shriek, Banshee Curse, Ribbon of Souls, Dominate Mind
    -- Razorfen Kraul
    [4424] = { 6192, 8286, 14900 },  -- Aggem Thorncurse: Battle Shout, Summon Boar Spirit, Chain Heal
    [4428] = { 9613, 14515 },  -- Death Speaker Jargba: Shadow Bolt, Dominate Mind
    [4420] = { 7165, 9128, 15548 },  -- Overlord Ramtusk: Battle Stance, Battle Shout, Thunderclap
    [4422] = { 8260, 8269, 8285, 8359, 8555 },  -- Agathelos the Raging: Rushing Charge, Enrage, Rampage, Left for Dead, Left for Dead
    [4421] = { 6077, 8292, 8358, 8361 },  -- Charlga Razorflank: Renew, Chain Bolt, Mana Spike, Purity
    [4425] = { 14920, 17260, 23147, 23148, 24577, 24578 },  -- Blind Hunter: Growl, Bite, Dive, Dive, Demoralizing Screech, Demoralizing Screech
    [4842] = { 2484, 8270, 9532 },  -- Earthcaller Halmgar: Earthbind Totem, Summon Earth Rumbler, Lightning Bolt
    [4438] = { 8148, 8259 },  -- Razorfen Spearhide: Thorns Aura, Whirling Barrage
    [6168] = { 8270, 9532 },  -- Roogug: Summon Earth Rumbler, Lightning Bolt
    -- Ruins of Lordaeron
    [250483] = { 3358 },  -- Witherfang: Leech Poison
    [250660] = { 5568, 17307 },  -- The Baron: Trample, Knockout
    [256035] = { 3358 },  -- Viktor the Vile: Leech Poison
    [250631] = { 6136, 14907, 1266011 },  -- The Abandoned: Chilled, Frost Nova, Life Drain
    [256097] = { 14099, 1301635 },  -- Bjork: Mighty Blow, Anti-Magic Shield
    [250657] = { 13376, 18399 },  -- Rath'mael: Fire Shield, Flamestrike
    -- Scarlet Monastery
    [3983] = { 2767, 9034 },  -- Interrogator Vishas: Shadow Word: Pain, Immolate
    [4543] = { 8053, 8814, 9613, 12470 },  -- Bloodmage Thalnos: Flame Shock, Flame Spike, Shadow Bolt, Fire Nova
    [6490] = { 5137, 7399, 9373 },  -- Azshir the Sleepless: Call of the Grave, Terrify, Soul Siphon
    [6488] = { 7366, 15496, 403233 },  -- Fallen Champion: Berserker Stance, Cleave, Meathook
    [6489] = { 3815, 21007 },  -- Ironspine: Poison Cloud, Curse of Weakness
    [14693] = { 15531, 17165, 22643, 28873, 403233 },  -- Scorn: Frost Nova, Mind Flay, Frostbolt Volley, Lich Slap, Meathook
    [3974] = { 6192, 6742 },  -- Houndmaster Loksey: Battle Shout, Bloodlust
    [6487] = { 8988, 9433, 9435, 9438, 13323 },  -- Arcanist Doan: Silence, Arcane Explosion, Detonation, Arcane Bubble, Polymorph
    [3975] = { 8260, 8269, 8989, 22540 },  -- Herod: Rushing Charge, Enrage, Whirlwind, Cleave
    [4542] = { 8282, 8399, 11647, 12039, 12096, 15090 },  -- High Inquisitor Fairbanks: Curse of Blood, Sleep, Power Word: Shield, Heal, Fear, Dispel Magic
    [3976] = { 1020, 5589, 8990, 9257, 14518, 25771 },  -- Scarlet Commander Mograine: Divine Shield, Hammer of Justice, Retribution Aura, Lay on Hands, Crusader Strike, Forbearance
    [3977] = { 9232, 9256, 9481, 12039, 14515, 22187 },  -- High Inquisitor Whitemane: Scarlet Resurrection, Deep Sleep, Holy Smite, Heal, Dominate Mind, Power Word: Shield
    -- Scholomance
    [10506] = { 6016, 8379, 12882, 12889, 14515, 16467, 17228, 18144 },  -- Kirtonos the Herald: Pierce Armor, Disarm, Wing Flap, Curse of Tongues, Dominate Mind, Kirtonos Transform, Shadow Bolt Volley, Swoop
    [10503] = { 16098 },  -- Jandice Barov: Curse of Blood
    [11622] = { 16727 },  -- Rattlegore: War Stomp
    [10433] = { 17697 },  -- Marduk Blackpool: Defiling Aura
    [10432] = { 16046, 18399 },  -- Vectus: Blast Wave, Flamestrike
    [10508] = { 8398, 11130, 12096, 18099, 18100, 18101, 18763 },  -- Ras Frostwhisper: Frostbolt Volley, Knock Away, Fear, Chill Nova, Frost Armor, Chilled, Freeze
    [10505] = { 8362, 13747, 15586, 17831, 17843, 18376 },  -- Instructor Malicia: Renew, Slow, Heal, Call of the Grave, Flash Heal, Corruption
    [11261] = { 8269, 16509, 18103 },  -- Doctor Theolen Krastinov: Enrage, Rend, Backhand
    [10901] = { 8245 },  -- Lorekeeper Polkelt: Corrosive Acid
    [10507] = { 15550, 15584, 17963, 18670 },  -- The Ravenian: Trample, Cleave, Sundering Cleave, Knock Away
    [10504] = { 15570, 17467, 17820 },  -- Lord Alexei Barov: Immolate, Unholy Aura, Veil of Shadow
    [10502] = { 12528, 12542, 14515, 17289, 18671 },  -- Lady Illucia Barov: Silence, Fear, Dominate Mind, Shadow Shock, Curse of Agony
    [1853] = { 12040, 17950, 18702 },  -- Darkmaster Gandling: Shadow Shield, Shadow Portal, Curse of the Darkmaster
    [14695] = { 7964, 11972, 16496, 21390, 403233 },  -- Lord Blackwood: Smoke Bomb, Shield Bash, Shoot, Multi-Shot, Meathook
    [16118] = { 8269, 17228, 27687, 27688, 27689, 27695 },  -- Kormok: Enrage, Shadow Bolt Volley, Summon Bone Minions, Bone Shield, Bloodlust, Summon Bone Mages
    [14516] = { 15754, 17393, 22644, 23261, 429688 },  -- Death Knight Darkreaver: Cleave, Shadow Bolt, Blood Leech, Summon Darkreaver's Fallen Charger, Dominate Mind
    -- Shadowfang Keep
    [3914] = { 7295 },  -- Rethilgore: Soul Drain
    [3887] = { 7068 },  -- Baron Silverlaine: Veil of Shadow
    [4278] = { 642, 1026, 5588, 25771 },  -- Commander Springvale: Divine Shield, Holy Light, Hammer of Justice, Forbearance
    [4279] = { 7481, 7483, 7484 },  -- Odo the Blindwatcher: Howling Rage, Howling Rage, Howling Rage
    [4274] = { 7125 },  -- Fenrus the Devourer: Toxic Saliva
    [3927] = { 7487, 7488, 7489 },  -- Wolf Master Nandos: Call Bleak Worg, Call Slavering Worg, Call Lupine Horror
    [4275] = { 6547, 7588, 7621, 7803, 13797 },  -- Archmage Arugal: Rend, Void Bolt, Arugal's Curse, Thundershock, Immolation Trap Effect
    [3872] = { 5532, 7165, 9080 },  -- Deathsworn Captain: Cleave, Battle Stance, Hamstring
    [3864] = { 7139 },  -- Fel Steed: Fel Stomp
    [14682] = { 8269, 16508, 17745, 403233 },  -- Sever: Enrage, Intimidating Roar, Diseased Spit, Meathook
    [4627] = { 7154 },  -- Arugal's Voidwalker: Dark Offering
    -- The Stockade
    [1696] = { 3391, 8599 },  -- Targorr the Dread: Thrash, Enrage
    [1666] = { 3419, 7164, 8242 },  -- Kam Deepfury: Improved Blocking, Defensive Stance, Shield Slam
    [1717] = { 421, 6742 },  -- Hamhock: Chain Lightning, Bloodlust
    [1716] = { 7964, 9128 },  -- Bazil Thredd: Smoke Bomb, Battle Shout
    [1663] = { 7165, 11976, 19134, 29544 },  -- Dextren Ward: Battle Stance, Strike, Intimidating Shout, Intimidating Shout
    [1720] = { 1604, 5101, 13496, 15571 },  -- Bruegal Ironknuckle: Dazed, Dazed, Dazed, Dazed
    -- Stratholme
    [10808] = { 8599, 17470 },  -- Timmy the Cruel: Enrage, Ravenous Claw
    [10516] = { 6136, 14907 },  -- The Unforgiven: Chilled, Frost Nova
    [10558] = { 14443, 16100, 16244, 16798 },  -- Hearthsinger Forresten: Multi-Shot, Shoot, Demoralizing Shout, Enchanting Lullaby
    [10997] = { 10101, 15615, 16496, 17279 },  -- Cannon Master Willey: Knock Away, Pummel, Shoot, Summon Crimson Rifleman
    [10811] = { 17274, 17293, 17366 },  -- Archivist Galford: Pyroblast, Burning Winds, Fire Nova
    [10393] = { 6136, 12544, 15230, 15499, 16799 },  -- Skul: Chilled, Frost Armor, Arcane Bolt, Frost Shock, Frostbolt
    [10809] = { 14331 },  -- Stonespine: Vicious Rend
    [11143] = { 12741 },  -- Postmaster Malown: Curse of Weakness
    [10812] = { 12098, 13704, 17281, 17284, 17286, 17287, 17399, 17405, 18647 },  -- Grand Crusader Dathrohan: Sleep, Psychic Scream, Crusader Strike, Holy Strike, Crusader's Hammer, Mind Blast, Shadow Shock, Domination, Banish
    [14684] = { 8398, 12096, 15244, 16799, 403233 },  -- Balzaphon: Frostbolt Volley, Fear, Cone of Cold, Frostbolt, Meathook
    [10435] = { 10887, 14099, 16791, 16793 },  -- Magistrate Barthilas: Crowd Pummel, Mighty Blow, Furious Anger, Draining Blow
    [10436] = { 16867 },  -- Baroness Anastari: Banshee Curse
    [10437] = { 4962, 6016, 16795, 17235 },  -- Nerub'enkan: Encasing Webs, Pierce Armor, Crypt Scarabs, Raise Undead Scarab
    [10438] = { 6136, 16869, 17238, 17243, 17503 },  -- Maleki the Pallid: Chilled, Ice Tomb, Drain Life, Drain Mana, Frostbolt
    [10439] = { 5568, 17307, 17687 },  -- Ramstein the Gorger: Trample, Knockout, Flurry
    [10440] = { 15708, 15754, 17393, 17434, 17435, 17467 },  -- Baron Rivendare: Mortal Strike, Cleave, Shadow Bolt, Shadow Bolt, Shadow Bolt, Unholy Aura
    -- Sunken Temple
    [8580] = { 6524, 12887 },  -- Atal'alarion: Ground Tremor, Sweeping Slam
    [5721] = { 12882, 12884 },  -- Dreamscythe: Wing Flap, Acid Breath
    [5720] = { 12882, 12884 },  -- Weaver: Wing Flap, Acid Breath
    [5710] = { 8376, 12468, 12480, 12492 },  -- Jammal'an the Prophet: Earthgrab Totem, Flamestrike, Hex of Jammal'an, Healing Wave
    [5711] = { 11639, 12471, 12493 },  -- Ogom the Wretched: Shadow Word: Pain, Shadow Bolt, Curse of Weakness
    [5719] = { 12882, 12884 },  -- Morphaz: Wing Flap, Acid Breath
    [5722] = { 12882, 12884 },  -- Hazzas: Wing Flap, Acid Breath
    [5709] = { 3391, 11876, 12890, 12891 },  -- Shade of Eranikus: Thrash, War Stomp, Deep Slumber, Acid Breath
    [5708] = { 12280, 17260, 23148, 25011, 403233 },  -- Spawn of Hakkar: Acid of Hakkar, Bite, Dive, Lightning Breath, Meathook
    -- Uldaman
    [6910] = { 15801, 16006 },  -- Revelosh: Lightning Bolt, Chain Lightning
    [7228] = { 8374, 10101, 11876 },  -- Ironaya: Arcing Smash, Knock Away, War Stomp
    [7023] = { 10061, 10072 },  -- Obsidian Sentinel: Summon Obsidian Shard, Splintered Obsidian
    [7206] = { 10094, 10132 },  -- Ancient Stone Keeper: Sand Storms, Sand Storms
    [7291] = { 3356, 8053, 9482, 11969 },  -- Galgann Firehammer: Flame Lash, Flame Shock, Amplify Flames, Fire Nova
    [4854] = { 6742, 8143, 8292, 9532, 11892 },  -- Grimlok: Bloodlust, Tremor Totem, Chain Bolt, Lightning Bolt, Shrink
    [2748] = { 6524, 8269, 10252, 10258 },  -- Archaedas: Ground Tremor, Enrage, Awaken Earthen Guardians, Awaken Vault Warder
    [6906] = { 14516, 15620 },  -- Baelog: Strike, Shoot
    [6907] = { 6268 },  -- Eric \"The Swift\": Rushing Charge
    [6908] = { 8242 },  -- Olaf: Shield Slam
    -- Upper Blackrock Spire
    [9816] = { 16078, 16079, 16536 },  -- Pyroguard Emberseer: Emberseer Despawn, Fire Nova, Flame Buffet
    [10264] = { 16727 },  -- Solakar Flamewreath: War Stomp
    [10899] = { 6253, 15580, 16172, 403233 },  -- Goraluk Anvilcrack: Backhand, Strike, Head Crack, Meathook
    [10339] = { 10101, 16328, 16350, 16359, 16390 },  -- Gyth: Knock Away, Summon Rend Blackhand, Freeze, Corrosive Acid Breath, Flame Breath
    [10429] = { 8269, 13736, 15708, 15754 },  -- Warchief Rend Blackhand: Enrage, Whirlwind, Mortal Strike, Cleave
    [10430] = { 14100, 15570, 16144, 16636, 16785, 16788, 20477 },  -- The Beast: Terrifying Roar, Immolate, Fire Blast, Berserker Charge, Flamebreak, Fireball, Summon Player
    [10363] = { 15588 },  -- General Drakkisath: Thunderclap
    [10509] = { 11972, 14516, 15749, 403233 },  -- Jed Runewatcher: Shield Bash, Strike, Shield Charge, Meathook
    [16042] = { 27249, 27286, 27338, 27382 },  -- Lord Valthalak: Summon Spectral Assassin, Shadow Wrath, Shadow Staff, Shadow Bolt Volley
    -- Wailing Caverns
    [3671] = { 700, 5187, 8148, 9532 },  -- Lady Anacondra: Sleep, Healing Touch, Thorns Aura, Lightning Bolt
    [3669] = { 744, 5188, 7965, 8040, 9532 },  -- Lord Cobrahn: Poison, Healing Touch, Cobrahn Serpent Form, Druid's Slumber, Lightning Bolt
    [3653] = { 14917, 14918, 17256, 17257, 17258, 26064 },  -- Kresh: Growl, Growl, Bite, Bite, Bite, Shell Shield
    [3670] = { 700, 5187, 8147, 9532 },  -- Lord Pythas: Sleep, Healing Touch, Thunderclap, Lightning Bolt
    [3674] = { 6254 },  -- Skum: Chained Bolt
    [3673] = { 700, 6778, 9532 },  -- Lord Serpentis: Sleep, Healing Touch, Lightning Bolt
    [5775] = { 8142 },  -- Verdan the Everliving: Grasping Vines
    [3654] = { 7399, 7967, 8150 },  -- Mutanus the Devourer: Terrify, Naralex's Nightmare, Thundercrack
    -- Zul'Farrak
    [8127] = { 2860, 8376, 10413, 10915, 11893, 11894, 11895, 11899 },  -- Antu'sul: Chain Lightning, Earthgrab Totem, Earth Shock, Flash Heal, Warder Despawn, Antu'sul's Minion, Healing Wave of Antu'sul, Healing Ward
    [7272] = { 8600 },  -- Theka the Martyr: Fevered Plague
    [7271] = { 11086, 12491, 12739, 15245 },  -- Witch Doctor Zum'rah: Ward of Zum'rah, Healing Wave, Shadow Bolt, Shadow Bolt Volley
    [7796] = { 8600 },  -- Nekrum Gutchewer: Fevered Plague
    [7275] = { 8362, 12039, 13704, 15537 },  -- Shadowpriest Sezz'ziz: Renew, Heal, Psychic Scream, Shadow Bolt
    [7604] = { 3639, 11972, 12170, 403233 },  -- Sergeant Bly: Improved Blocking, Shield Bash, Revenge, Meathook
    [7795] = { 11086, 12491, 12739, 15245 },  -- Hydromancer Velratha: Ward of Zum'rah, Healing Wave, Shadow Bolt, Shadow Bolt Volley
    [7273] = { 11131, 11836, 11902 },  -- Gahz'rilla: Icicle, Freeze Solid, Gahz'rilla Slam
    [7267] = { 7366, 8269, 11837, 15623 },  -- Chief Ukorz Sandscalp: Berserker Stance, Enrage, Wide Slash, Cleave
    [10082] = { 6533, 12551, 15547, 403233 },  -- Zerillis: Net, Frost Shot, Shoot, Meathook
    [10081] = { 12251, 15667 },  -- Dustwraith: Virulent Poison, Sinister Strike
}
