-------------------------------------------------------------------------------
--  Data/BossInfo.lua -- each boss as its Wowhead Forever NPC page has it, for the header of
--  its page in the Dungeon Journal: { lowest level, highest level (-1: ??), classification
--  (0 normal, 1 elite, 2 rare elite, 3 boss, 4 rare), creature type (Wowhead's number: 7 is
--  Humanoid), its title or nil }, keyed by NPC ID. Generated by Tools/build_abilities.py; do
--  not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.BossInfo = {
    -- Blackfathom Deeps
    [4887] = { 25, 25, 1, 1, nil },  -- Ghamoo-ra
    [4831] = { 25, 25, 1, 7, nil },  -- Lady Sarevess
    [6243] = { 26, 26, 1, 7, nil },  -- Gelihast
    [12902] = { 26, 26, 1, 7, nil },  -- Lorgus Jett
    [12876] = { 28, 28, 1, 4, nil },  -- Baron Aquanis
    [4832] = { 27, 27, 1, 7, nil },  -- Twilight Lord Kelris
    [4830] = { 26, 26, 1, 1, nil },  -- Old Serra'kis
    [4829] = { 28, 28, 1, 10, nil },  -- Aku'mai
    -- Blackrock Depths
    [9018] = { 52, 52, 1, 7, "Twilight's Hammer Interrogator" },  -- High Interrogator Gerstahn
    [9025] = { 51, 51, 1, 4, nil },  -- Lord Roccor
    [9319] = { 52, 52, 1, 7, nil },  -- Houndmaster Grebmar
    [9031] = { 54, 54, 1, 6, nil },  -- Anub'shiah
    [9029] = { 54, 54, 1, 7, nil },  -- Eviscerator
    [9027] = { 56, 56, 1, 7, nil },  -- Gorosh the Dervish
    [9028] = { 54, 54, 1, 7, nil },  -- Grizzle
    [9032] = { 53, 53, 1, 1, nil },  -- Hedrum the Creeper
    [9030] = { 53, 53, 1, 7, nil },  -- Ok'thor the Breaker
    [9024] = { 52, 52, 1, 7, nil },  -- Pyromancer Loregrain
    [9017] = { 55, 55, 1, 4, nil },  -- Lord Incendius
    [9041] = { 56, 56, 1, 7, nil },  -- Warder Stilgiss
    [9042] = { 55, 55, 1, 3, nil },  -- Verek
    [9056] = { 54, 54, 1, 7, "Chief Architect" },  -- Fineous Darkvire
    [9016] = { 54, 54, 1, 5, nil },  -- Bael'Gar
    [9033] = { 57, 57, 1, 7, nil },  -- General Angerforge
    [8983] = { 57, 57, 1, 7, nil },  -- Golem Lord Argelmach
    [9537] = { 55, 55, 1, 7, nil },  -- Hurley Blackbreath
    [9502] = { 55, 55, 1, 4, nil },  -- Phalanx
    [9543] = { 53, 53, 1, 7, nil },  -- Ribbly Screwspigot
    [9499] = { 55, 55, 1, 7, nil },  -- Plugger Spazzring
    [9156] = { 57, 57, 1, 7, nil },  -- Ambassador Flamelash
    [9938] = { 57, 57, 1, 5, nil },  -- Magmus
    [9019] = { 59, 59, 1, 7, nil },  -- Emperor Dagran Thaurissan
    [8923] = { 57, 57, 2, 4, nil },  -- Panzor the Invincible
    [8929] = { 58, 58, 1, 7, "Princess of Ironforge" },  -- Princess Moira Bronzebeard
    -- City of Dalaran
    [246017] = { -1, -1, 1, 4, nil },  -- Unstable Sentinel
    [246020] = { -1, -1, 1, 4, nil },  -- Shade of the Archmage
    [247032] = { -1, -1, 2, 7, nil },  -- Lyn the Ignored
    -- The Deadmines
    [644] = { 19, 19, 1, 7, "The Foreman" },  -- Rhahk'Zor
    [642] = { 20, 20, 1, 9, "Lumbermaster" },  -- Sneed's Shredder
    [643] = { 20, 20, 1, 7, "Lumbermaster" },  -- Sneed
    [1763] = { 20, 20, 1, 7, "The Smelter" },  -- Gilnid
    [646] = { 20, 20, 1, 7, "The Ship's First Mate" },  -- Mr. Smite
    [647] = { 20, 20, 1, 7, nil },  -- Captain Greenskin
    [639] = { 21, 21, 1, 7, "Defias Kingpin" },  -- Edwin VanCleef
    [645] = { 20, 20, 1, 7, "The Ship's Cook" },  -- Cookie
    [3586] = { 19, 19, 2, 7, nil },  -- Miner Johnson
    -- Dire Maul
    [14354] = { 57, 57, 1, 3, nil },  -- Pusillin
    [11490] = { 57, 57, 1, 3, nil },  -- Zevrim Thornhoof
    [13280] = { 57, 57, 1, 4, nil },  -- Hydrospawn
    [14327] = { 57, 57, 1, 7, nil },  -- Lethtendris
    [11492] = { 58, 58, 1, 3, nil },  -- Alzzin the Wildshaper
    [16097] = { -1, -1, 1, 7, nil },  -- Isalien
    [11489] = { 60, 60, 1, 4, nil },  -- Tendris Warpwood
    [11488] = { 60, 60, 1, 6, nil },  -- Illyanna Ravenoak
    [11487] = { 60, 60, 1, 6, nil },  -- Magister Kalendris
    [11496] = { 61, 61, 1, 3, nil },  -- Immol'thar
    [11486] = { 61, 61, 1, 7, nil },  -- Prince Tortheldrin
    [11467] = { 59, 59, 1, 6, nil },  -- Tsu'zee
    [14506] = { 62, 62, 1, 3, nil },  -- Lord Hel'nurath
    [14690] = { 60, 60, 1, 6, nil },  -- Revanchion
    [14326] = { 59, 59, 1, 7, nil },  -- Guard Mol'dar
    [14322] = { 59, 59, 1, 7, "The Drunk" },  -- Stomper Kreeg
    [14321] = { 58, 59, 1, 7, nil },  -- Guard Fengus
    [14323] = { 59, 59, 1, 7, nil },  -- Guard Slip'kik
    [14325] = { 61, 61, 1, 7, nil },  -- Captain Kromcrush
    [11501] = { 62, 62, 1, 7, nil },  -- King Gordok
    [14324] = { 60, 60, 1, 7, nil },  -- Cho'Rush the Observer
    -- The Drowned City
    [270882] = { -1, -1, 1, 6, "Staging Area 1" },  -- Zul'Alai
    [270883] = { -1, -1, 1, 7, "Staging Area 2" },  -- Var'Taka
    [270884] = { -1, -1, 1, 7, "Staging Area 3" },  -- Captain Dreadrise
    [270885] = { -1, -1, 1, 4, "Staging Area 4" },  -- Deathless Marrow
    [270886] = { -1, -1, 1, 7, "Staging Area 6" },  -- Min'loth the Serpent
    -- Excavation Site: Wetlands
    [260322] = { -1, -1, 1, 1, nil },  -- Saltspine
    [260325] = { -1, -1, 1, 1, nil },  -- Shadetooth
    [260808] = { 28, 28, 1, 4, nil },  -- Highland Horror
    [260326] = { -1, -1, 1, 4, nil },  -- Relic Guardian
    -- Gnomeregan
    [7361] = { 32, 32, 1, 7, nil },  -- Grubbis
    [7079] = { 30, 30, 1, 4, nil },  -- Viscous Fallout
    [6235] = { 32, 32, 1, 9, nil },  -- Electrocutioner 6000
    [6229] = { 32, 32, 1, 9, nil },  -- Crowd Pummeler 9-60
    [7800] = { 34, 34, 1, 9, nil },  -- Mekgineer Thermaplugg
    [6228] = { 33, 41, 2, 7, nil },  -- Dark Iron Ambassador
    [6231] = { 26, 26, 1, 9, nil },  -- Techbot
    -- The Hall of Thanes
    [261306] = { -1, -1, 1, 6, nil },  -- Faldrim Anvilmar
    [261316] = { -1, -1, 1, 4, nil },  -- Magmatus
    [261311] = { -1, -1, 1, 4, nil },  -- Plunder
    [261319] = { -1, -1, 1, 7, nil },  -- Durgen Dirgehammer
    -- Lower Blackrock Spire
    [9196] = { 59, 59, 1, 7, nil },  -- Highlord Omokk
    [9236] = { 58, 58, 1, 7, nil },  -- Shadow Hunter Vosh'gajin
    [9237] = { 59, 59, 1, 7, nil },  -- War Master Voone
    [10596] = { 59, 59, 1, 1, nil },  -- Mother Smolderweb
    [10584] = { 60, 60, 2, 7, nil },  -- Urok Doomhowl
    [9736] = { 59, 59, 1, 7, "Bloodaxe Legion" },  -- Quartermaster Zigris
    [10268] = { 60, 60, 1, 1, nil },  -- Gizrul the Slavener
    [10220] = { 59, 59, 1, 1, nil },  -- Halycon
    [9568] = { 60, 60, 1, 2, nil },  -- Overlord Wyrmthalak
    [9219] = { 57, 57, 2, 7, nil },  -- Spirestone Butcher
    [9218] = { 58, 58, 2, 7, nil },  -- Spirestone Battle Lord
    [9217] = { 58, 58, 2, 7, nil },  -- Spirestone Lord Magus
    [9596] = { 59, 59, 2, 7, "Firebrand Legion Champion" },  -- Bannok Grimaxe
    [10376] = { 60, 60, 2, 1, nil },  -- Crystal Fang
    [9718] = { 59, 59, 2, 7, "Bloodaxe Champion" },  -- Ghok Bashguud
    [10263] = { 56, 57, 2, 3, nil },  -- Burning Felguard
    [16080] = { 60, 60, 1, 7, nil },  -- Mor Grayhoof
    -- Maraudon
    [13282] = { 48, 48, 1, 4, nil },  -- Noxxion
    [12258] = { 48, 48, 1, 10, nil },  -- Razorlash
    [12236] = { 47, 47, 1, 3, nil },  -- Lord Vyletongue
    [12225] = { 49, 49, 1, 7, nil },  -- Celebras the Cursed
    [12203] = { 50, 50, 1, 5, nil },  -- Landslide
    [13601] = { 50, 50, 1, 7, nil },  -- Tinkerer Gizlock
    [13596] = { 50, 50, 1, 1, nil },  -- Rotgrip
    [12201] = { 51, 51, 1, 4, nil },  -- Princess Theradras
    [12237] = { 48, 48, 2, 4, nil },  -- Meshlok the Harvester
    -- Onyxia's Lair
    [10184] = { -1, -1, 3, 2, nil },  -- Onyxia
    -- Ragefire Chasm
    [11517] = { 16, 16, 1, 7, "Ragefire Chieftain" },  -- Oggleflint
    [11520] = { 16, 16, 1, 7, nil },  -- Taragaman the Hungerer
    [11518] = { 16, 16, 1, 7, nil },  -- Jergosh the Invoker
    [11519] = { 16, 16, 1, 7, nil },  -- Bazzalan
    -- Razorfen Downs
    [7355] = { 40, 40, 1, 6, nil },  -- Tuten'kash
    [7357] = { 39, 39, 1, 6, nil },  -- Mordresh Fire Eye
    [8567] = { 40, 40, 1, 6, nil },  -- Glutton
    [7358] = { 41, 41, 1, 6, nil },  -- Amnennar the Coldbringer
    [7354] = { 40, 40, 1, 7, nil },  -- Ragglesnout
    [7356] = { 40, 40, 1, 7, nil },  -- Plaguemaw the Rotting
    [14686] = { 40, 40, 1, 6, nil },  -- Lady Falther'ess
    -- Razorfen Kraul
    [4424] = { 30, 30, 1, 7, "Death's Head Prophet" },  -- Aggem Thorncurse
    [4428] = { 30, 30, 1, 7, "Death's Head Captain" },  -- Death Speaker Jargba
    [4420] = { 32, 32, 1, 7, nil },  -- Overlord Ramtusk
    [4422] = { 33, 33, 1, 1, nil },  -- Agathelos the Raging
    [4421] = { 33, 33, 1, 7, "The Crone" },  -- Charlga Razorflank
    [4425] = { 32, 32, 2, 1, nil },  -- Blind Hunter
    [4842] = { 32, 32, 2, 7, nil },  -- Earthcaller Halmgar
    [4438] = { 29, 30, 1, 7, nil },  -- Razorfen Spearhide
    [6168] = { 28, 28, 1, 7, nil },  -- Roogug
    -- Ruins of Lordaeron
    [250483] = { -1, -1, 1, 1, nil },  -- Witherfang
    [250660] = { -1, -1, 1, 6, nil },  -- The Baron
    [256035] = { -1, -1, 1, 6, nil },  -- Viktor the Vile
    [250631] = { -1, -1, 1, 6, nil },  -- The Abandoned
    [256097] = { -1, -1, 1, 6, nil },  -- Bjork
    [250657] = { -1, -1, 1, 6, nil },  -- Rath'mael
    [255699] = { -1, -1, 2, 6, nil },  -- Lordaeron Captain
    -- Scarlet Monastery - Armory
    [3975] = { 40, 40, 1, 7, "The Scarlet Champion" },  -- Herod
    -- Scarlet Monastery - Cathedral
    [4542] = { 40, 40, 1, 6, nil },  -- High Inquisitor Fairbanks
    [3976] = { 42, 42, 1, 7, nil },  -- Scarlet Commander Mograine
    [3977] = { 42, 42, 1, 7, nil },  -- High Inquisitor Whitemane
    -- Scarlet Monastery - Graveyard
    [3983] = { 32, 32, 1, 7, nil },  -- Interrogator Vishas
    [4543] = { 34, 34, 1, 6, nil },  -- Bloodmage Thalnos
    [6490] = { 33, 33, 2, 6, nil },  -- Azshir the Sleepless
    [6488] = { 33, 33, 2, 6, nil },  -- Fallen Champion
    [6489] = { 33, 33, 2, 6, nil },  -- Ironspine
    [14693] = { 34, 34, 1, 6, nil },  -- Scorn
    -- Scarlet Monastery - Library
    [3974] = { 34, 34, 1, 7, nil },  -- Houndmaster Loksey
    [6487] = { 37, 37, 1, 7, nil },  -- Arcanist Doan
    -- Scholomance
    [10506] = { 60, 60, 1, 6, nil },  -- Kirtonos the Herald
    [10503] = { 61, 61, 1, 6, nil },  -- Jandice Barov
    [11622] = { 61, 61, 1, 6, nil },  -- Rattlegore
    [10433] = { 58, 58, 1, 6, nil },  -- Marduk Blackpool
    [10432] = { 60, 60, 1, 6, nil },  -- Vectus
    [10508] = { 62, 62, 1, 6, nil },  -- Ras Frostwhisper
    [10505] = { 60, 60, 1, 7, nil },  -- Instructor Malicia
    [11261] = { 60, 60, 1, 7, "The Butcher" },  -- Doctor Theolen Krastinov
    [10901] = { 60, 60, 1, 6, nil },  -- Lorekeeper Polkelt
    [10507] = { 60, 60, 1, 6, nil },  -- The Ravenian
    [10504] = { 60, 60, 1, 6, nil },  -- Lord Alexei Barov
    [10502] = { 60, 60, 1, 6, nil },  -- Lady Illucia Barov
    [1853] = { 61, 61, 1, 7, nil },  -- Darkmaster Gandling
    [14695] = { 60, 60, 1, 6, nil },  -- Lord Blackwood
    [16118] = { 60, 60, 1, 7, nil },  -- Kormok
    [14516] = { 62, 62, 1, 6, nil },  -- Death Knight Darkreaver
    -- Shadowfang Keep
    [3914] = { 20, 20, 1, 7, "The Cell Keeper" },  -- Rethilgore
    [3886] = { 22, 22, 1, 7, nil },  -- Razorclaw the Butcher
    [3887] = { 24, 24, 1, 6, nil },  -- Baron Silverlaine
    [4278] = { 24, 24, 1, 6, nil },  -- Commander Springvale
    [4279] = { 24, 24, 1, 7, nil },  -- Odo the Blindwatcher
    [4274] = { 25, 25, 1, 1, nil },  -- Fenrus the Devourer
    [3927] = { 25, 25, 1, 7, nil },  -- Wolf Master Nandos
    [4275] = { 26, 26, 1, 7, nil },  -- Archmage Arugal
    [3872] = { 25, 25, 2, 6, nil },  -- Deathsworn Captain
    [3864] = { 19, 20, 1, 1, nil },  -- Fel Steed
    [14682] = { 25, 25, 1, 6, nil },  -- Sever
    [4627] = { 24, 25, 0, 3, nil },  -- Arugal's Voidwalker
    -- The Stockade
    [1696] = { 24, 24, 1, 7, nil },  -- Targorr the Dread
    [1666] = { 27, 27, 1, 7, nil },  -- Kam Deepfury
    [1717] = { 28, 28, 1, 7, nil },  -- Hamhock
    [1716] = { 29, 29, 1, 7, nil },  -- Bazil Thredd
    [1663] = { 26, 26, 1, 7, nil },  -- Dextren Ward
    [1720] = { 26, 26, 2, 7, nil },  -- Bruegal Ironknuckle
    -- Stratholme
    [10808] = { 58, 58, 2, 6, nil },  -- Timmy the Cruel
    [10516] = { 57, 57, 1, 6, nil },  -- The Unforgiven
    [10558] = { 57, 57, 2, 6, nil },  -- Hearthsinger Forresten
    [10997] = { 60, 60, 1, 7, nil },  -- Cannon Master Willey
    [10811] = { 60, 60, 1, 7, nil },  -- Archivist Galford
    [10813] = { -1, -1, 1, 3, nil },  -- Balnazzar
    [10393] = { 58, 58, 2, 6, nil },  -- Skul
    [10809] = { 60, 60, 2, 6, nil },  -- Stonespine
    [11143] = { 60, 60, 1, 6, nil },  -- Postmaster Malown
    [10812] = { 62, 62, 1, 7, nil },  -- Grand Crusader Dathrohan
    [14684] = { 60, 60, 1, 6, nil },  -- Balzaphon
    [10435] = { 58, 58, 1, 6, nil },  -- Magistrate Barthilas
    [10436] = { 59, 59, 1, 6, nil },  -- Baroness Anastari
    [10437] = { 60, 60, 1, 6, nil },  -- Nerub'enkan
    [10438] = { 61, 61, 1, 7, nil },  -- Maleki the Pallid
    [10439] = { 61, 61, 1, 6, nil },  -- Ramstein the Gorger
    [10440] = { 62, 62, 1, 6, nil },  -- Baron Rivendare
    -- Sunken Temple
    [8580] = { 50, 50, 1, 7, "Guardian of the Idol" },  -- Atal'alarion
    [5721] = { 53, 53, 1, 2, nil },  -- Dreamscythe
    [5720] = { 51, 51, 1, 2, nil },  -- Weaver
    [5710] = { 54, 54, 1, 7, nil },  -- Jammal'an the Prophet
    [5711] = { 53, 53, 1, 6, nil },  -- Ogom the Wretched
    [5719] = { 52, 52, 1, 2, nil },  -- Morphaz
    [5722] = { 53, 53, 1, 2, nil },  -- Hazzas
    [5709] = { 55, 55, 1, 2, nil },  -- Shade of Eranikus
    [8443] = { -1, -1, 1, 10, nil },  -- Avatar of Hakkar
    [5708] = { 50, 51, 1, 1, nil },  -- Spawn of Hakkar
    -- Uldaman
    [6910] = { 40, 40, 1, 7, nil },  -- Revelosh
    [7228] = { 40, 40, 1, 5, nil },  -- Ironaya
    [7023] = { 42, 42, 1, 9, nil },  -- Obsidian Sentinel
    [7206] = { 44, 44, 1, 4, nil },  -- Ancient Stone Keeper
    [7291] = { 45, 45, 1, 7, nil },  -- Galgann Firehammer
    [4854] = { 45, 45, 1, 7, "Stonevault Chieftain" },  -- Grimlok
    [2748] = { 47, 47, 1, 5, "Ancient Stone Watcher" },  -- Archaedas
    [6906] = { 41, 41, 1, 7, nil },  -- Baelog
    [6907] = { 40, 40, 1, 7, nil },  -- Eric \"The Swift\"
    [6908] = { 40, 40, 1, 7, nil },  -- Olaf
    -- Upper Blackrock Spire
    [9816] = { -1, -1, 3, 4, nil },  -- Pyroguard Emberseer
    [10264] = { 60, 60, 1, 2, nil },  -- Solakar Flamewreath
    [10899] = { 61, 61, 1, 7, "Blackhand Legion Armorsmith" },  -- Goraluk Anvilcrack
    [10339] = { 62, 62, 1, 2, "Rend Blackhand's Mount" },  -- Gyth
    [10429] = { -1, -1, 3, 7, nil },  -- Warchief Rend Blackhand
    [10430] = { -1, -1, 3, 1, nil },  -- The Beast
    [10363] = { -1, -1, 3, 2, nil },  -- General Drakkisath
    [10509] = { 59, 59, 2, 7, "Blackhand Legion" },  -- Jed Runewatcher
    [16042] = { -1, -1, 3, 7, nil },  -- Lord Valthalak
    -- Wailing Caverns
    [3671] = { 20, 20, 1, 7, "Fanglord" },  -- Lady Anacondra
    [3669] = { 20, 20, 1, 7, "Fanglord" },  -- Lord Cobrahn
    [3653] = { 20, 20, 1, 1, nil },  -- Kresh
    [3670] = { 21, 21, 1, 7, "Fanglord" },  -- Lord Pythas
    [3674] = { 21, 21, 1, 1, nil },  -- Skum
    [3673] = { 21, 21, 1, 7, "Fanglord" },  -- Lord Serpentis
    [5775] = { 21, 21, 1, 4, nil },  -- Verdan the Everliving
    [3654] = { 22, 22, 1, 7, nil },  -- Mutanus the Devourer
    [5912] = { 20, 20, 2, 2, nil },  -- Deviate Faerie Dragon
    -- Zul'Farrak
    [8127] = { 48, 48, 1, 7, "Overseer of Sul" },  -- Antu'sul
    [7272] = { 45, 46, 1, 6, nil },  -- Theka the Martyr
    [7271] = { 46, 46, 1, 7, nil },  -- Witch Doctor Zum'rah
    [7796] = { 45, 46, 1, 6, nil },  -- Nekrum Gutchewer
    [7275] = { 47, 47, 1, 7, nil },  -- Shadowpriest Sezz'ziz
    [7604] = { 45, 45, 1, 7, nil },  -- Sergeant Bly
    [7795] = { 46, 46, 1, 7, nil },  -- Hydromancer Velratha
    [7273] = { 46, 46, 1, 10, nil },  -- Gahz'rilla
    [7267] = { 48, 48, 1, 7, nil },  -- Chief Ukorz Sandscalp
    [10082] = { 45, 45, 2, 7, nil },  -- Zerillis
    [10081] = { 45, 45, 2, 7, nil },  -- Dustwraith
}
