-------------------------------------------------------------------------------
--  Data/BossQuests.lua -- the dungeon quests that need each boss (its kill, or something it
--  drops), as quest IDs from Data/Quests.lua keyed by the boss's NPC ID. Matched by the
--  boss's name in the quest's objective on Wowhead Forever. Generated by
--  Tools/build_boss_quests.py; do not edit by hand.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.BossQuests = {
    -- Blackfathom Deeps
    [12902] = { 6565 },  -- Lorgus Jett: Allegiance to the Old Gods
    [4832] = { 6561, 1200 },  -- Twilight Lord Kelris: Blackfathom Villainy; Blackfathom Villainy
    [4829] = { 6563 },  -- Aku'mai: The Essence of Aku'Mai
    -- Blackrock Depths
    [9017] = { 3907, 4263 },  -- Lord Incendius: Disharmony of Fire; Incendius!
    [9056] = { 3802 },  -- Fineous Darkvire: Dark Iron Legacy
    [9016] = { 4024 },  -- Bael'Gar: A Taste of Flame
    [9033] = { 4132 },  -- General Angerforge: Operation: Death to Angerforge
    [8983] = { 4063 },  -- Golem Lord Argelmach: The Rise of the Machines
    [9019] = { 4003, 4362 },  -- Emperor Dagran Thaurissan: The Royal Rescue; The Fate of the Kingdom
    [8929] = { 4003, 4362 },  -- Princess Moira Bronzebeard: The Royal Rescue; The Fate of the Kingdom
    -- The Deadmines
    [639] = { 166 },  -- Edwin VanCleef: The Defias Brotherhood
    -- Dire Maul
    [14354] = { 7441 },  -- Pusillin: Pusillin and the Elder Azj'Tordin
    [13280] = { 7463 },  -- Hydrospawn: Arcane Refreshment
    [14327] = { 7489, 7488 },  -- Lethtendris: Lethtendris's Web; Lethtendris's Web
    [11492] = { 5526 },  -- Alzzin the Wildshaper: Shards of the Felvine
    [11496] = { 7461 },  -- Immol'thar: The Madness Within
    [11486] = { 7461, 7703 },  -- Prince Tortheldrin: The Madness Within; Unfinished Gordok Business
    [14325] = { 7703 },  -- Captain Kromcrush: Unfinished Gordok Business
    -- Gnomeregan
    [7800] = { 2841, 2929 },  -- Mekgineer Thermaplugg: Rig Wars; The Grand Betrayal
    [6231] = { 2922 },  -- Techbot: Save Techbot's Brain!
    -- The Hall of Thanes
    [261306] = { 96395 },  -- Faldrim Anvilmar: An Ancient Grudge
    [261319] = { 96393 },  -- Durgen Dirgehammer: Old Ironforge Incursion
    -- Lower Blackrock Spire
    [9196] = { 4903, 4742 },  -- Highlord Omokk: Warlord's Command; Seal of Ascension
    [9237] = { 4903, 4742 },  -- War Master Voone: Warlord's Command; Seal of Ascension
    [10596] = { 4866 },  -- Mother Smolderweb: Mother's Milk
    [10220] = { 4724, 4701 },  -- Halycon: The Pack Mistress; Put Her Down
    [9568] = { 4903, 4742 },  -- Overlord Wyrmthalak: Warlord's Command; Seal of Ascension
    -- Maraudon
    [12201] = { 7064, 7065 },  -- Princess Theradras: Corruption of Earth and Seed; Corruption of Earth and Seed
    -- Ragefire Chasm
    [11520] = { 5761 },  -- Taragaman the Hungerer: Slaying the Beast
    [11518] = { 5728 },  -- Jergosh the Invoker: Hidden Enemies
    [11519] = { 5728 },  -- Bazzalan: Hidden Enemies
    -- Razorfen Downs
    [7358] = { 3341, 3636 },  -- Amnennar the Coldbringer: Bring the End; Bring the Light
    -- Ruins of Lordaeron
    [250483] = { 95216 },  -- Witherfang: The New Plague
    [250660] = { 97288, 95250 },  -- The Baron: Unending Torment; Abominable Creatures
    [250657] = { 92422 },  -- Rath'mael: The Wrath of Rath'mael
    -- Scarlet Monastery
    [3974] = { 1048, 1053 },  -- Houndmaster Loksey: Into The Scarlet Monastery; In the Name of the Light
    [3975] = { 1048, 1053 },  -- Herod: Into The Scarlet Monastery; In the Name of the Light
    [3976] = { 1048, 1053 },  -- Scarlet Commander Mograine: Into The Scarlet Monastery; In the Name of the Light
    [3977] = { 1048, 1053 },  -- High Inquisitor Whitemane: Into The Scarlet Monastery; In the Name of the Light
    -- Scholomance
    [10506] = { 5384 },  -- Kirtonos the Herald: Kirtonos the Herald
    [10503] = { 5515 },  -- Jandice Barov: Krastinov's Bag of Horrors
    [10432] = { 4771 },  -- Vectus: Dawn's Gambit
    [10508] = { 5466 },  -- Ras Frostwhisper: The Lich, Ras Frostwhisper
    [11261] = { 5382 },  -- Doctor Theolen Krastinov: Doctor Theolen Krastinov, the Butcher
    [14516] = { 7668 },  -- Death Knight Darkreaver: The Darkreaver Menace
    -- Shadowfang Keep
    [4275] = { 1014 },  -- Archmage Arugal: Arugal Must Die
    -- The Stockade
    [1696] = { 386 },  -- Targorr the Dread: What Comes Around...
    [1666] = { 378 },  -- Kam Deepfury: The Fury Runs Deep
    [1716] = { 391 },  -- Bazil Thredd: The Stockade Riots
    [1663] = { 377 },  -- Dextren Ward: Crime and Punishment
    -- Stratholme
    [10811] = { 5251 },  -- Archivist Galford: The Archivist
    [10813] = { 5262 },  -- Balnazzar: The Truth Comes Crashing Down
    [10439] = { 6163 },  -- Ramstein the Gorger: Ramstein
    [10440] = { 5263, 8945 },  -- Baron Rivendare: Above and Beyond; Dead Man's Plea
    -- Uldaman
    [6906] = { 2398, 2240 },  -- Baelog: The Lost Dwarves; The Hidden Chamber
    -- Upper Blackrock Spire
    [9816] = { 6821 },  -- Pyroguard Emberseer: Eye of the Emberseer
    [10899] = { 5127 },  -- Goraluk Anvilcrack: The Demon Forge
    [10429] = { 4974 },  -- Warchief Rend Blackhand: For The Horde!
    [10430] = { 5047 },  -- The Beast: Finkle Einhorn, At Your Service!
    [10363] = { 6602, 5102, 6502, 7761 },  -- General Drakkisath: Blood of the Black Dragon Champion; General Drakkisath's Demise; Drakefire Amulet; Blackhand's Command
    -- Wailing Caverns
    [3671] = { 914 },  -- Lady Anacondra: Leaders of the Fang
    [3669] = { 914 },  -- Lord Cobrahn: Leaders of the Fang
    [3670] = { 914 },  -- Lord Pythas: Leaders of the Fang
    [3673] = { 914 },  -- Lord Serpentis: Leaders of the Fang
    -- Zul'Farrak
    [7273] = { 2770 },  -- Gahz'rilla: Gahz'rilla
}
