-------------------------------------------------------------------------------
--  Data/Dungeons/BlackfathomDeeps.lua -- Blackfathom Deeps in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("BlackfathomDeeps", {
    name = "Blackfathom Deeps",
    zone = "Ashenvale", territory = "Contested",
    entrance = { map = 1440, x = 13.9, y = 14.3 },
    wings = {
        { bosses = {
            { npc = 4887, name = "Ghamoo-ra", encounters = { 2916, 2761 }, loot = { 6908, 6907, 273839 }, chance = { 57, 37, 0 } },
            { npc = 4831, name = "Lady Sarevess", encounters = { 2915, 2762 }, loot = { 11121, 888, 3078 }, chance = { 38, 38, 19 } },
            { npc = 6243, name = "Gelihast", encounters = { 2914, 2763 }, loot = { 6905, 6906, 273840 }, chance = { 47, 45, 0 } },
            { npc = 12902, name = "Lorgus Jett", encounters = { 2913, 2764 }, loot = { 273841, 273842, 273843 } },
            { npc = 12876, name = "Baron Aquanis" },
            { npc = 4832, name = "Twilight Lord Kelris", encounters = { 2911, 2766 }, loot = { 1155, 6903, 273846 }, chance = { 49, 34, 0 } },
            { npc = 4830, name = "Old Serra'kis", encounters = { 2912, 2765 }, loot = { 6901, 6902, 6904 }, chance = { 40, 33, 21 } },
            { npc = 4829, name = "Aku'mai", encounters = { 2910, 2767 }, loot = { 6911, 6910, 6909 }, chance = { 38, 37, 20 } },
            { npc = nil, name = "Trash", trash = true, loot = { 2034, 1454, 1481, 1486, 1491, 2271, 2567, 3413, 3414, 3415, 3416, 3417 }, chance = { 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
        } },
    },
})
