-------------------------------------------------------------------------------
--  Data/Dungeons/BlackrockDepths.lua -- Blackrock Depths in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("BlackrockDepths", {
    name = "Blackrock Depths",
    zone = "Blackrock Mountain", territory = "Contested",
    entrance = { map = 1427, x = 27.6, y = 72.4 },
    wings = {
        { name = "Detention Block", bosses = {
            { npc = 9018, name = "High Interrogator Gerstahn", model = 8761, encounters = { 227 }, notInGame = 4 },
            { npc = 9025, name = "Lord Roccor", model = 5781, encounters = { 228 }, notInGame = 4 },
            { npc = 9319, name = "Houndmaster Grebmar", model = 9212, encounters = { 229 }, notInGame = 4 },
        } },
        { name = "Ring of Law", bosses = {
            { npc = 9031, name = "Anub'shiah", model = 3004, notInGame = 4 },
            { npc = 9029, name = "Eviscerator", model = 523, notInGame = 4 },
            { npc = 9027, name = "Gorosh the Dervish", model = 8760, notInGame = 4 },
            { npc = 9028, name = "Grizzle", model = 7873, notInGame = 4 },
            { npc = 9032, name = "Hedrum the Creeper", model = 8271, notInGame = 4 },
            { npc = 9030, name = "Ok'thor the Breaker", model = 11538, notInGame = 4 },
        } },
        { name = "Shadowforge City", bosses = {
            { npc = 9024, name = "Pyromancer Loregrain", model = 8762, encounters = { 231 }, notInGame = 4 },
            { npc = 9017, name = "Lord Incendius", model = 1204, encounters = { 232 }, notInGame = 5 },
            { npc = 9041, name = "Warder Stilgiss", model = 9089, encounters = { 233 }, notInGame = 4 },
            { npc = 9042, name = "Verek", model = 9019, notInGame = 2 },
            { npc = 9056, name = "Fineous Darkvire", model = 8704, encounters = { 234 }, notInGame = 4 },
            { npc = 9016, name = "Bael'Gar", model = 12162, encounters = { 235 }, notInGame = 4 },
            { npc = 9033, name = "General Angerforge", model = 8756, encounters = { 236 }, notInGame = 5 },
            { npc = 8983, name = "Golem Lord Argelmach", model = 8759, encounters = { 237 }, notInGame = 4 },
            { npc = 9537, name = "Hurley Blackbreath", model = 8658, encounters = { 238 }, notInGame = 4 },
            { npc = 9502, name = "Phalanx", model = 8177, encounters = { 239 }, notInGame = 3, loot = { 227947 }, chance = { 29 } },
            { npc = 9543, name = "Ribbly Screwspigot", model = 8667, encounters = { 240 } },
            { npc = 9499, name = "Plugger Spazzring", model = 8652, encounters = { 241 }, notInGame = 2 },
            { npc = 9156, name = "Ambassador Flamelash", model = 8329, encounters = { 242 }, notInGame = 5 },
            { npc = 9938, name = "Magmus", model = 12162, encounters = { 244 }, notInGame = 4 },
            { npc = 9019, name = "Emperor Dagran Thaurissan", model = 8807, encounters = { 2790 }, notInGame = 11 },
            { npc = 8923, name = "Panzor the Invincible", model = 8270, rare = true, notInGame = 4 },
            { npc = 8929, name = "Princess Moira Bronzebeard", model = 8705, optional = true, encounters = { 2789 }, notInGame = 4 },
            { npc = nil, name = "Secret Safe", chest = 161495, notInGame = 7 },
            { npc = nil, name = "Chest of The Seven", chest = 169243, notInGame = 4 },
            { npc = nil, name = "Trash", trash = true, notInGame = 18 },
        } },
    },
})
