-------------------------------------------------------------------------------
--  Data/Dungeons/Dalaran.lua -- City of Dalaran in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Dalaran", {
    name = "City of Dalaran",
    new = true,
    zone = "Alterac Mountains", territory = "Contested",
    entrance = { map = 1416, x = 21.7, y = 68.3 },
    wings = {
        { bosses = {
            { npc = 246017, name = "Unstable Sentinel", encounters = { 3302 }, loot = { 273046 } },
            { npc = 246020, name = "Shade of the Archmage", encounters = { 3303 }, loot = { 273052 } },
            { npc = 247032, name = "Lyn the Ignored", rare = true, encounters = { 3310 } },
        } },
    },
})
