-------------------------------------------------------------------------------
--  Data/Dungeons/DireMaul.lua -- Dire Maul in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("DireMaul", {
    name = "Dire Maul",
    zone = "Feralas", territory = "Contested",
    entrance = { map = 1444, x = 61.9, y = 31.6 },
    wings = {
        { name = "East", bosses = {
            { npc = 14354, name = "Pusillin", model = 7552, encounters = { 2792 } },
            { npc = 11490, name = "Zevrim Thornhoof", model = 11335, encounters = { 343 } },
            { npc = 13280, name = "Hydrospawn", model = 5489, encounters = { 344 } },
            { npc = 14327, name = "Lethtendris", model = 14378, encounters = { 345 } },
            { npc = 11492, name = "Alzzin the Wildshaper", model = 14416, encounters = { 346 } },
            { npc = 16097, name = "Isalien", model = 16000, optional = true },
        } },
        { name = "West", bosses = {
            { npc = 11489, name = "Tendris Warpwood", model = 14383, encounters = { 350 } },
            { npc = 11488, name = "Illyanna Ravenoak", model = 11270, encounters = { 347 } },
            { npc = 11487, name = "Magister Kalendris", model = 14384, encounters = { 348 } },
            { npc = 11496, name = "Immol'thar", model = 14173, encounters = { 349 } },
            { npc = 11486, name = "Prince Tortheldrin", model = 11256, encounters = { 361 } },
            { npc = 11467, name = "Tsu'zee", model = 11250, rare = true, encounters = { 2794 } },
            { npc = 14506, name = "Lord Hel'nurath", model = 14556, optional = true, encounters = { 2793 } },
            { npc = 14690, name = "Revanchion", model = 14695, optional = true },
        } },
        { name = "North", bosses = {
            { npc = 14326, name = "Guard Mol'dar", model = 11561, encounters = { 362 } },
            { npc = 14322, name = "Stomper Kreeg", model = 11545, encounters = { 363 } },
            { npc = 14321, name = "Guard Fengus", model = 11561, encounters = { 364 } },
            { npc = 14323, name = "Guard Slip'kik", model = 11561, encounters = { 365 } },
            { npc = 14325, name = "Captain Kromcrush", model = 11564, encounters = { 366 } },
            { npc = 11501, name = "King Gordok", model = 11583, encounters = { 368 } },
            { npc = 14324, name = "Cho'Rush the Observer", model = 11537, optional = true, encounters = { 367 } },
            { npc = nil, name = "Gordok Tribute", chest = 179564 },
        } },
    },
})
