-------------------------------------------------------------------------------
--  Data/Dungeons/ExcavationSite.lua -- Excavation Site: Wetlands in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("ExcavationSite", {
    name = "Excavation Site: Wetlands",
    new = true,
    zone = "Wetlands", territory = "Contested",
    entrance = { map = 1437, x = 48.1, y = 56.5 },
    wings = {
        { bosses = {
            { npc = 260322, name = "Saltspine", model = 144209, encounters = { 3480 }, loot = { 273023, 273024, 273022 } },
            { npc = 260325, name = "Shadetooth", model = 144210, encounters = { 3481 }, loot = { 273025, 273027, 273026 } },
            { npc = 260808, name = "Highland Horror", model = 9010, encounters = { 3644 } },
            { npc = 260326, name = "Relic Guardian", model = 144224, encounters = { 3482 }, loot = { 273030, 273028, 273029 } },
        } },
    },
})
