-------------------------------------------------------------------------------
--  Data/Dungeons/Gnomeregan.lua -- Gnomeregan in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Gnomeregan", {
    name = "Gnomeregan",
    zone = "Dun Morogh", territory = "Alliance",
    entrance = { map = 1426, x = 24.0, y = 40.0 },
    wings = {
        { bosses = {
            { npc = 7361, name = "Grubbis", model = 144378, encounters = { 2768 }, loot = { 9445 }, chance = { 8 } },
            { npc = 7079, name = "Viscous Fallout", model = 5497, encounters = { 2769 }, loot = { 9454, 9452, 9453 }, chance = { 60, 20, 18 } },
            { npc = 6235, name = "Electrocutioner 6000", model = 6915, encounters = { 2770 }, loot = { 9448, 9447, 9446 }, chance = { 40, 32, 16 } },
            { npc = 6229, name = "Crowd Pummeler 9-60", model = 6774, encounters = { 2771 }, loot = { 9450, 9449 }, chance = { 65, 33 } },
            { npc = 7800, name = "Mekgineer Thermaplugg", model = 6980, encounters = { 2772 }, loot = { 9461, 9458, 9459, 9492 }, chance = { 33, 32, 18, 10 } },
            { npc = 6228, name = "Dark Iron Ambassador", model = 6669, rare = true, loot = { 9455, 9456, 9457 }, chance = { 43, 34, 20 } },
            { npc = 6231, name = "Techbot", model = 7288, optional = true },
            { npc = nil, name = "Trash", trash = true, loot = { 9485, 9486, 9487, 9488, 9490, 9491, 9508, 9509, 9510, 9489 } },
        } },
    },
})
