-------------------------------------------------------------------------------
--  Data/Dungeons/LowerBlackrockSpire.lua -- Lower Blackrock Spire in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("LowerBlackrockSpire", {
    name = "Lower Blackrock Spire",
    zone = "Blackrock Mountain", territory = "Contested",
    entrance = { map = 1427, x = 41.1, y = 95.3 },
    wings = {
        { bosses = {
            { npc = 9196, name = "Highlord Omokk", model = 11565, encounters = { 267 }, notInGame = 5, loot = { 16670 }, chance = { 16 } },
            { npc = 9236, name = "Shadow Hunter Vosh'gajin", model = 9732, encounters = { 268 }, notInGame = 5, loot = { 16712 }, chance = { 17 } },
            { npc = 9237, name = "War Master Voone", model = 9733, encounters = { 269 }, notInGame = 6, loot = { 16676 }, chance = { 19 } },
            { npc = 10596, name = "Mother Smolderweb", model = 9929, encounters = { 270 }, notInGame = 3, loot = { 16715 }, chance = { 16 } },
            { npc = 10584, name = "Urok Doomhowl", model = 11583, encounters = { 271 }, notInGame = 4 },
            { npc = 9736, name = "Quartermaster Zigris", model = 9738, encounters = { 272 }, notInGame = 2 },
            { npc = 10268, name = "Gizrul the Slavener", model = 9564, encounters = { 273 }, notInGame = 3, loot = { 16718 }, chance = { 18 } },
            { npc = 10220, name = "Halycon", model = 9567, encounters = { 274 }, notInGame = 4 },
            { npc = 9568, name = "Overlord Wyrmthalak", model = 8711, encounters = { 275 }, notInGame = 6, loot = { 16679, 13164 }, chance = { 16, 1 } },
            { npc = 9219, name = "Spirestone Butcher", model = 11574, rare = true, notInGame = 2 },
            { npc = 9218, name = "Spirestone Battle Lord", model = 11576, rare = true, notInGame = 2 },
            { npc = 9217, name = "Spirestone Lord Magus", model = 11578, rare = true, notInGame = 3 },
            { npc = 9596, name = "Bannok Grimaxe", model = 9668, rare = true, notInGame = 3 },
            { npc = 10376, name = "Crystal Fang", model = 9755, rare = true, notInGame = 3 },
            { npc = 9718, name = "Ghok Bashguud", model = 11809, rare = true, notInGame = 3 },
            { npc = 10263, name = "Burning Felguard", model = 5047, rare = true, notInGame = 2 },
            { npc = 16080, name = "Mor Grayhoof", model = 15997, optional = true, notInGame = 5 },
            { npc = nil, name = "Trash", trash = true, notInGame = 1, loot = { 16683, 16680, 16696, 16703, 16673, 16735, 16713 }, chance = { 3, 3, 3, 3, 3, 3, 3 } },
        } },
    },
})
