-------------------------------------------------------------------------------
--  Data/Dungeons/Maraudon.lua -- Maraudon in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Maraudon", {
    name = "Maraudon",
    zone = "Desolace", territory = "Contested",
    entrance = { map = 1443, x = 30.1, y = 61.9 },
    wings = {
        { bosses = {
            { npc = 13282, name = "Noxxion", model = 11172, encounters = { 422 }, notInGame = 3 },
            { npc = 12258, name = "Razorlash", model = 12389, encounters = { 423 }, notInGame = 4 },
            { npc = 12236, name = "Lord Vyletongue", model = 12334, encounters = { 424 }, notInGame = 3 },
            { npc = 12225, name = "Celebras the Cursed", model = 12350, encounters = { 425 }, notInGame = 3 },
            { npc = 12203, name = "Landslide", model = 12293, encounters = { 426 }, notInGame = 4 },
            { npc = 13601, name = "Tinkerer Gizlock", model = 7125, encounters = { 427 }, notInGame = 3 },
            { npc = 13596, name = "Rotgrip", model = 13589, encounters = { 428 }, notInGame = 3 },
            { npc = 12201, name = "Princess Theradras", model = 12292, encounters = { 429 }, notInGame = 8 },
            { npc = 12237, name = "Meshlok the Harvester", model = 9014, rare = true, notInGame = 3 },
        } },
    },
})
