-------------------------------------------------------------------------------
--  Data/Dungeons/RuinsOfLordaeron.lua -- Ruins of Lordaeron in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("RuinsOfLordaeron", {
    name = "Ruins of Lordaeron",
    new = true,
    zone = "Tirisfal Glades", territory = "Horde",
    entrance = { map = 1458, x = 71.6, y = 11.4 },
    wings = {
        { bosses = {
            { npc = 250483, name = "Witherfang", model = 144189, encounters = { 3353 }, loot = { 271201, 271203, 271202 }, chance = { 33, 30, 27 } },
            { npc = 250660, name = "The Baron", model = 144188, encounters = { 3355 }, loot = { 271206, 271204, 271205 }, chance = { 44, 28, 22 } },
            { npc = 256035, name = "Viktor the Vile", model = 139455, encounters = { 3411 }, loot = { 271212, 271211, 271218 }, chance = { 38, 31, 31 } },
            { npc = 250631, name = "The Abandoned", model = 138667, encounters = { 3357 }, loot = { 271207, 271216, 271208 }, chance = { 45, 33, 21 } },
            { npc = 256097, name = "Bjork", model = 144170, encounters = { 3412 }, loot = { 271210, 271209, 271217 }, chance = { 46, 31, 23 } },
            { npc = 250657, name = "Rath'mael", model = 144175, encounters = { 3354 }, loot = { 271213, 271214, 271215 }, chance = { 44, 33, 23 } },
            { npc = 255699, name = "Lordaeron Captain", model = 139050, rare = true, encounters = { 3408 }, loot = { 6641, 6642 } },
        } },
    },
})
