-------------------------------------------------------------------------------
--  Data/Dungeons/ScarletMonasteryCathedral.lua -- Scarlet Monastery - Cathedral in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("ScarletMonasteryCathedral", {
    name = "Scarlet Monastery - Cathedral",
    zone = "Tirisfal Glades", territory = "Horde",
    entrance = { map = 1420, x = 83.9, y = 31.6 },
    wings = {
        { bosses = {
            { npc = 4542, name = "High Inquisitor Fairbanks", model = 2605, encounters = { 449 } },
            { npc = 3976, name = "Scarlet Commander Mograine", model = 2042, loot = { 7726 }, chance = { 42 } },
            { npc = 3977, name = "High Inquisitor Whitemane", model = 2043, encounters = { 450 } },
            { npc = nil, name = "Trash", trash = true, loot = { 10330, 10329, 10333, 10331, 10328, 2262, 5756, 5819, 7727, 7728, 7729, 7730, 7752, 7753, 7754, 7759, 7761, 7786, 7787, 8225, 8226, 10332 }, chance = { 14, 2, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
        } },
    },
})
