-------------------------------------------------------------------------------
--  Data/Dungeons/ScarletMonasteryLibrary.lua -- Scarlet Monastery - Library in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("ScarletMonasteryLibrary", {
    name = "Scarlet Monastery - Library",
    zone = "Tirisfal Glades", territory = "Horde",
    entrance = { map = 1420, x = 83.9, y = 31.6 },
    wings = {
        { bosses = {
            { npc = 3974, name = "Houndmaster Loksey", model = 2040, encounters = { 446 }, loot = { 7756, 3456, 7710 }, chance = { 56, 25, 14 } },
            { npc = 6487, name = "Arcanist Doan", model = 5266, encounters = { 447 }, loot = { 7712, 7714, 7713, 7711 }, chance = { 47, 47, 47, 46 } },
            { npc = nil, name = "Trash", trash = true, loot = { 10330, 10329, 10333, 10331, 10328, 2262, 5756, 5819, 7727, 7728, 7729, 7730, 7752, 7753, 7754, 7759, 7761, 7786, 7787, 8225, 8226, 10332 }, chance = { 14, 2, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
        } },
    },
})
