-------------------------------------------------------------------------------
--  Data/Dungeons/ScarletMonasteryArmory.lua -- Scarlet Monastery - Armory in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("ScarletMonasteryArmory", {
    name = "Scarlet Monastery - Armory",
    zone = "Tirisfal Glades", territory = "Horde",
    entrance = { map = 1420, x = 83.9, y = 31.6 },
    wings = {
        { bosses = {
            { npc = 3975, name = "Herod", model = 2041, encounters = { 448 } },
            { npc = nil, name = "Trash", trash = true, loot = { 10330, 10329, 10333, 10331, 10328, 2262, 5756, 5819, 7727, 7728, 7729, 7730, 7752, 7753, 7754, 7759, 7761, 7786, 7787, 8225, 8226, 10332 }, chance = { 14, 2, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
        } },
    },
})
