-------------------------------------------------------------------------------
--  Data/Dungeons/Scholomance.lua -- Scholomance in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Scholomance", {
    name = "Scholomance",
    zone = "Western Plaguelands", territory = "Contested",
    entrance = { map = 1422, x = 70.7, y = 71.0 },
    wings = {
        { bosses = {
            { npc = 10506, name = "Kirtonos the Herald", model = 143673, encounters = { 2805 }, loot = { 16734 }, chance = { 19 } },
            { npc = 10503, name = "Jandice Barov", model = 11073, encounters = { 2804 }, loot = { 16701 }, chance = { 16 } },
            { npc = 11622, name = "Rattlegore", model = 12073, encounters = { 2811 }, loot = { 16711 }, chance = { 18 } },
            { npc = 10433, name = "Marduk Blackpool", model = 10248, encounters = { 2809 } },
            { npc = 10432, name = "Vectus", model = 2606, encounters = { 2813 } },
            { npc = 10508, name = "Ras Frostwhisper", model = 7919, encounters = { 2810 }, loot = { 16689 }, chance = { 19 } },
            { npc = 10505, name = "Instructor Malicia", model = 11069, encounters = { 2803 }, loot = { 16710 }, chance = { 4 } },
            { npc = 11261, name = "Doctor Theolen Krastinov", model = 10901, encounters = { 2802 }, loot = { 16684 }, chance = { 8 } },
            { npc = 10901, name = "Lorekeeper Polkelt", model = 11492, encounters = { 2808 }, loot = { 16705 }, chance = { 8 } },
            { npc = 10507, name = "The Ravenian", model = 10433, encounters = { 2812 }, loot = { 16716 }, chance = { 5 } },
            { npc = 10504, name = "Lord Alexei Barov", model = 11072, encounters = { 2807 }, loot = { 16722 }, chance = { 4 } },
            { npc = 10502, name = "Lady Illucia Barov", model = 11835, encounters = { 2806 } },
            { npc = 1853, name = "Darkmaster Gandling", model = 11070, encounters = { 2801 }, loot = { 16686, 16677, 16731, 16693, 16698, 16720, 16707, 16727, 16667 }, chance = { 13, 12, 12, 12, 11, 11, 11, 7, 6 } },
            { npc = 14695, name = "Lord Blackwood", model = 14699, optional = true },
            { npc = 16118, name = "Kormok", model = 16020, optional = true, encounters = { 3055 } },
            { npc = 14516, name = "Death Knight Darkreaver", model = 14591, optional = true, loot = { 18760 }, chance = { 24 } },
            { npc = nil, name = "Trash", trash = true, loot = { 16684, 16705, 16722 }, chance = { 5, 4, 3 } },
        } },
    },
})
