-------------------------------------------------------------------------------
--  Data/Dungeons/Stratholme.lua -- Stratholme in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Stratholme", {
    name = "Stratholme",
    zone = "Eastern Plaguelands", territory = "Contested",
    entrance = { map = 1423, x = 26.9, y = 11.8 },
    wings = {
        { name = "Main Gate", bosses = {
            { npc = 10808, name = "Timmy the Cruel", model = 571, encounters = { 474 } },
            { npc = 10516, name = "The Unforgiven", model = 10771, encounters = { 472 } },
            { npc = 10558, name = "Hearthsinger Forresten", model = 10482, encounters = { 473 }, loot = { 16682 }, chance = { 14 } },
            { npc = 10997, name = "Cannon Master Willey", model = 10674, encounters = { 475 }, loot = { 16708 }, chance = { 16 } },
            { npc = 10811, name = "Archivist Galford", model = 10544, encounters = { 477 }, loot = { 16692 }, chance = { 18 } },
            { npc = 10813, name = "Balnazzar", model = 10691, encounters = { 478 }, loot = { 16725 } },
            { npc = 10393, name = "Skul", model = 2606, rare = true, encounters = { 2799 } },
            { npc = 10809, name = "Stonespine", model = 7856, rare = true, encounters = { 2800 } },
            { npc = 11143, name = "Postmaster Malown", model = 10669, optional = true, encounters = { 2798 } },
            { npc = 10812, name = "Grand Crusader Dathrohan", model = 10545, optional = true },
            { npc = 14684, name = "Balzaphon", model = 7919, optional = true, loot = { 23125 } },
        } },
        { name = "Service Entrance", bosses = {
            { npc = 10435, name = "Magistrate Barthilas", model = 10433, encounters = { 482 } },
            { npc = 10436, name = "Baroness Anastari", model = 10698, encounters = { 479 }, loot = { 16704 }, chance = { 18 } },
            { npc = 10437, name = "Nerub'enkan", model = 9793, encounters = { 480 }, loot = { 16675 }, chance = { 18 } },
            { npc = 10438, name = "Maleki the Pallid", model = 10546, encounters = { 481 }, loot = { 16691 }, chance = { 18 } },
            { npc = 10439, name = "Ramstein the Gorger", model = 12818, encounters = { 483 }, loot = { 16737 }, chance = { 17 } },
            { npc = 10440, name = "Baron Rivendare", model = 10729, encounters = { 484 }, loot = { 16687, 16709, 16699, 16694, 16678, 16732, 16719, 16728, 16668 }, chance = { 11, 11, 11, 10, 10, 10, 10, 7, 6 } },
            { npc = nil, name = "Trash", trash = true, loot = { 16725, 16723, 16697 }, chance = { 14, 2, 1 } },
        } },
    },
})
