-------------------------------------------------------------------------------
--  Data/Dungeons/SunkenTemple.lua -- Sunken Temple in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("SunkenTemple", {
    name = "Sunken Temple",
    zone = "Swamp of Sorrows", territory = "Contested",
    entrance = { map = 1435, x = 69.6, y = 53.7 },
    wings = {
        { bosses = {
            { npc = 8580, name = "Atal'alarion", model = 7873, encounters = { 3582, 2814 }, notInGame = 3 },
            { npc = 5721, name = "Dreamscythe", model = 7553, encounters = { 3588, 486 }, notInGame = 3 },
            { npc = 5720, name = "Weaver", model = 6375, encounters = { 3587, 487 }, notInGame = 3 },
            { npc = 5710, name = "Jammal'an the Prophet", model = 6708, encounters = { 3589, 488 }, notInGame = 3 },
            { npc = 5711, name = "Ogom the Wretched", model = 6709, notInGame = 3 },
            { npc = 5719, name = "Morphaz", model = 7975, encounters = { 3586, 490 }, notInGame = 3 },
            { npc = 5722, name = "Hazzas", model = 9584, encounters = { 3585, 491 }, notInGame = 3 },
            { npc = 5709, name = "Shade of Eranikus", model = 7806, encounters = { 3584, 493 }, notInGame = 7 },
            { npc = 8443, name = "Avatar of Hakkar", model = 8053, encounters = { 3583, 492 }, notInGame = 1 },
            { npc = 5708, name = "Spawn of Hakkar", model = 4065, optional = true, notInGame = 2 },
            { npc = nil, name = "Trash", trash = true, notInGame = 28 },
        } },
    },
})
