-------------------------------------------------------------------------------
--  Data/Dungeons/Uldaman.lua -- Uldaman in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Uldaman", {
    name = "Uldaman",
    zone = "Badlands", territory = "Contested",
    entrance = { map = 1418, x = 44.0, y = 12.0 },
    wings = {
        { bosses = {
            { npc = 6910, name = "Revelosh", model = 5945, encounters = { 547 }, loot = { 9389, 9387, 9390, 9388 }, chance = { 23, 23, 22, 21 } },
            { npc = 7228, name = "Ironaya", model = 6089, encounters = { 549 }, loot = { 9407, 9409, 9408 }, chance = { 38, 38, 20 } },
            { npc = 7023, name = "Obsidian Sentinel", model = 5285, encounters = { 1887 }, loot = { 9384 }, chance = { 3 } },
            { npc = 7206, name = "Ancient Stone Keeper", model = 10798, encounters = { 551 }, loot = { 9410, 9411 }, chance = { 48, 47 } },
            { npc = 7291, name = "Galgann Firehammer", model = 6059, encounters = { 552 }, loot = { 11311, 9419, 11310, 9412 }, chance = { 38, 20, 20, 18 } },
            { npc = 4854, name = "Grimlok", model = 11165, encounters = { 553 }, loot = { 9415, 9414, 9416 }, chance = { 40, 30, 19 } },
            { npc = 2748, name = "Archaedas", model = 5988, encounters = { 554 }, loot = { 11118, 9413, 9418 }, chance = { 62, 14, 14 } },
            { npc = 6906, name = "Baelog", model = 5710, optional = true, loot = { 9401 }, chance = { 9 } },
            { npc = 6907, name = "Eric \"The Swift\"", optional = true, loot = { 9398, 9394 }, chance = { 80, 8 } },
            { npc = 6908, name = "Olaf", model = 5709, optional = true, loot = { 9404 }, chance = { 12 } },
            { npc = nil, name = "Trash", trash = true, loot = { 9383, 9392, 9422, 9423, 9424, 9425, 9426, 9427, 9429, 9430, 9431, 9432, 9465 } },
        } },
    },
})
