-------------------------------------------------------------------------------
--  Data/Dungeons/Uldaman.lua -- Uldaman in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("Uldaman", {
    name = "Uldaman",
    zone = "Badlands", territory = "Contested",
    entrance = { map = 1418, x = 44.0, y = 12.0 },
    wings = {
        { bosses = {
            { npc = 6910, name = "Revelosh", model = 5945, encounters = { 547 }, notInGame = 4 },
            { npc = 7228, name = "Ironaya", model = 6089, encounters = { 549 }, notInGame = 3 },
            { npc = 7023, name = "Obsidian Sentinel", model = 5285, encounters = { 1887 }, notInGame = 1 },
            { npc = 7206, name = "Ancient Stone Keeper", model = 10798, encounters = { 551 }, notInGame = 2 },
            { npc = 7291, name = "Galgann Firehammer", model = 6059, encounters = { 552 }, notInGame = 4 },
            { npc = 4854, name = "Grimlok", model = 11165, encounters = { 553 }, notInGame = 3 },
            { npc = 2748, name = "Archaedas", model = 5988, encounters = { 554 }, notInGame = 3 },
            { npc = 6906, name = "Baelog", model = 5710, optional = true, notInGame = 1 },
            { npc = 6907, name = "Eric \"The Swift\"", optional = true, notInGame = 2 },
            { npc = 6908, name = "Olaf", model = 5709, optional = true, notInGame = 1 },
            { npc = nil, name = "Trash", trash = true, notInGame = 13 },
        } },
    },
})
