-------------------------------------------------------------------------------
--  Data/Dungeons/UpperBlackrockSpire.lua -- Upper Blackrock Spire in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("UpperBlackrockSpire", {
    name = "Upper Blackrock Spire",
    zone = "Blackrock Mountain", territory = "Contested",
    entrance = { map = 1427, x = 41.1, y = 95.3 },
    wings = {
        { bosses = {
            { npc = 9816, name = "Pyroguard Emberseer", model = 143803, encounters = { 3062 }, notInGame = 4, loot = { 16672 }, chance = { 18 } },
            { npc = 10264, name = "Solakar Flamewreath", model = 9581, notInGame = 4, loot = { 16695 }, chance = { 18 } },
            { npc = 10899, name = "Goraluk Anvilcrack", model = 10222, notInGame = 4 },
            { npc = 10339, name = "Gyth", model = 9806, notInGame = 4, loot = { 16669 }, chance = { 19 } },
            { npc = 10429, name = "Warchief Rend Blackhand", model = 9778, encounters = { 3063 }, notInGame = 12, loot = { 16733 }, chance = { 20 } },
            { npc = 10430, name = "The Beast", model = 10193, encounters = { 3068 }, notInGame = 9, loot = { 16729 }, chance = { 18 } },
            { npc = 10363, name = "General Drakkisath", model = 10115, encounters = { 3069 }, notInGame = 9, loot = { 16700, 16730, 16706, 16674, 16688, 16690, 16721, 16726, 16666 }, chance = { 12, 12, 12, 11, 11, 11, 10, 7, 6 } },
            { npc = 10509, name = "Jed Runewatcher", model = 9686, rare = true, notInGame = 3 },
            { npc = 16042, name = "Lord Valthalak", model = 14308, optional = true, encounters = { 3070 }, notInGame = 8 },
            { npc = nil, name = "Trash", trash = true, notInGame = 1, loot = { 16683, 16680, 16696, 16703, 16673, 16735, 16713 }, chance = { 3, 3, 3, 3, 3, 3, 3 } },
        } },
    },
})
