-------------------------------------------------------------------------------
--  Data/Dungeons/ZulFarrak.lua -- Zul'Farrak in the Dungeon Journal.
--  Generated by Tools/build_journal.py from Tools/journal_bosses.json and Wowhead Forever;
--  do not edit by hand. Naowh's tips are in Data/Tips.lua.
-------------------------------------------------------------------------------
local ns = _G.NaowhForever

ns.Journal.AddDungeon("ZulFarrak", {
    name = "Zul'Farrak",
    zone = "Tanaris", territory = "Contested",
    entrance = { map = 1446, x = 39.6, y = 21.7 },
    wings = {
        { bosses = {
            { npc = 8127, name = "Antu'sul", model = 7353, encounters = { 595 }, notInGame = 4 },
            { npc = 7272, name = "Theka the Martyr", model = 6696, encounters = { 596 } },
            { npc = 7271, name = "Witch Doctor Zum'rah", model = 6434, encounters = { 597 }, notInGame = 2 },
            { npc = 7796, name = "Nekrum Gutchewer", model = 6690, encounters = { 598 } },
            { npc = 7275, name = "Shadowpriest Sezz'ziz", model = 6441, encounters = { 599 }, notInGame = 4 },
            { npc = 7604, name = "Sergeant Bly", model = 6433, notInGame = 1 },
            { npc = 7795, name = "Hydromancer Velratha", model = 6685, encounters = { 593 } },
            { npc = 7273, name = "Gahz'rilla", model = 7271, encounters = { 594 }, notInGame = 2 },
            { npc = 7267, name = "Chief Ukorz Sandscalp", model = 6439, encounters = { 600 }, notInGame = 5 },
            { npc = 10082, name = "Zerillis", model = 9293, rare = true, notInGame = 1 },
            { npc = 10081, name = "Dustwraith", model = 9292, rare = true, notInGame = 1 },
            { npc = nil, name = "Trash", trash = true, notInGame = 1 },
        } },
    },
})
